### ISSUE TITLE
Requiring Lz and Nz for two-dimensional grids is a bit counterintuitive

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1001]
At the moment, to solve equations on a two-dimensional grid one has to provide `Nz=1` and any `Lz` they wish. For example, giving `Lz=2e-16` works pretty well:

```julia
julia> grid = RegularCartesianGrid(size=(128, 128, 1), extent=(2π, 2π, eps(Float64)))
RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 6.283185307179586], y ∈ [0.0, 6.283185307179586], z ∈ [-2.220446049250313e-16, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (128, 128, 1)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (0.04908738521234052, 0.04908738521234052, 2.220446049250313e-16)
```

However, `Lz=0` spits out an error...
```julia
julia> grid = RegularCartesianGrid(size=(128, 128, 1), extent=(2π, 2π, 0))
ERROR: ArgumentError: Elements of extent=(6.283185307179586, 6.283185307179586, 0) must be > 0!
Stacktrace:
 [1] validate_tupled_argument at /Users/navid/Research/Oceananigans.jl/src/Grids/grid_utils.jl:306 [inlined]
 [2] validate_regular_grid_size_and_extent(::Type{T} where T, ::Tuple{Int64,Int64,Int64}, ::Tuple{Float64,Float64,Int64}, ::Tuple{Int64,Int64,Int64}, ::Nothing, ::Nothing, ::Nothing) at /Users/navid/Research/Oceananigans.jl/src/Grids/grid_utils.jl:330
 [3] RegularCartesianGrid(::Type{T} where T; size::Tuple{Int64,Int64,Int64}, x::Nothing, y::Nothing, z::Nothing, extent::Tuple{Float64,Float64,Int64}, topology::Tuple{DataType,DataType,DataType}, halo::Tuple{Int64,Int64,Int64}) at /Users/navid/Research/Oceananigans.jl/src/Grids/regular_cartesian_grid.jl:126
 [4] top-level scope at REPL[33]:1
```

Perhaps it makes sense that there should be a check and each dimension that has extent =0 and number of grid-points =1 should be treated "specially" and bypass the validation at https://github.com/CliMA/Oceananigans.jl/blob/e808a821d78949b0482b8372533e992cabb5d65f/src/Grids/grid_utils.jl#L306?

**Comment by glwagner** [comment]
I agree it's silly that users are _required_ to provide meaningless numbers. Pointless suffering...

There's some related discussion on #940 .

We should resolve #902, #940, and this issue at the same time.

I guess we need to dispatch `validate_regular_grid_size_and_extent` on the topology. Then we can correctly adjust user input depending on whether a dimension is `Flat`.

**Comment by glwagner** [comment]
Do you think we should require `size=(Nt, Nr)` for 2D grids and `size=N` for 1D grids?

**Comment by glwagner** [comment]
Hmm, I guess this type of input is the only possible way to resolve this issue, since if we required a 3-tuple for `size`, it would not make sense to require something different for `extent`.
