### ISSUE TITLE
TurbulenceClosures module needs to be cleaned up

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1002]
`Oceananigans.TurbulenceClosures` is a bit messy right now.

One big issue is that we have two implementations of `AnisotropicMinimumDissipation`. I think we should commit to `VerstappenAnisotropicMinimumDissipation`, and possibly change its name to just `AnisotropicMinimumDissipation`.

We should also probably only support one version of `Smagorinsky`. We have an implementation of the Smagorinsky model that is _apparently_ used by the UK Met Office's Large Eddy Model (LEM), aka "BLASIUS" (`blasius_smagorinsky.jl`). But we never use this model and its untested. It's no small piece of work to really test all that code. Maybe we should delete it and just keep the much more common and popular `smagorinsky_lilly.jl`? We can also delete the alias `ConstantSmagorinsky`.

Some functions should probably be shuffled around: all of the code in `closure_operators.jl` should be moved to `viscous_dissipation_operators.jl` and `diffusion_operators`. Also to be consistent we should rename `viscous_dissipation_operators.jl` to `viscosity_operators.jl` (or at the least, `viscous_friction_operators.jl`.

The functions in `closure_operators.jl` also need to be converted to finite-volume form. I think the implementation of those functions can also be simplified to accept an isotropic viscosity rather than the entire `diffusivities` object.

We should also probably wrap all of the closures in their own submodules? Or maybe not...

The implementation for tupled closures is also split into the top-level file and `closure_tuples.jl`. We should put the whole thing in `closure_tuples.jl`.

What else?

**Comment by glwagner** [comment]
@BrodiePearson do you think there are good reasons to keep `blasius_smagorinsky.jl` around? It seems in practice most people would want `AnisotropicMinimumDissipation` (and while having two LES models at least seems wise, it may not be too important what the "secondary" model is).

**Comment by BrodiePearson** [comment]
I agree that the AMD and Smagorinsky-Lilly schemes would be sufficient here, so there's not probably no reason to even test BLASIUS scheme.
