### ISSUE TITLE
A more chatty, more friendly Oceananigans

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1013]
Sometimes precompilation and model setup tasks can take a fair amount of time. This can lead to head-scratching and/or boredom while running scripts: what _is_ Oceananigans up to, anyways?

To solve this problem and make Oceananigans more friendly and more chatty, we might add some helpful `@info` messages that print at various stages in the model setup process.

Looking at the examples gives a helpful overview of model setup. Here's some things we might consider info statements for:

1. Grid creation (type, size, topology, domain)
2. Boundary conditions (type and non-default boundary conditions)
3. Model creation (grid info including size and halo regions, and maybe just `display` model properties)
4. `set!(model, ...)`?
5. `Simulation` construction (stop criteria, time-step...)
6. `run!` initialization (diagnostics, output writers)
7. `run!` completion?

**Comment by glwagner** [comment]
Should we define new log levels for this purpose? It's less committing to add "maor logging" when they can be turned off. For example we can have a `MODEL` (or `SETUP`) level, and maybe a `SIMULATION` level...

**Comment by tomchor** [comment]
(Sorry, I accidentally unpinned this issue but just re-pinned it)

**Comment by glwagner** [comment]
`Simulation` is pretty chatty now so I think we can close this.
