### ISSUE TITLE
Different advection schemes for velocities and tracers

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1015]
We should allow different advection schemes for velocities and tracers. This requires doing something similar to what we do for closures. Perhaps we can allow

```julia
model = IncompressibleModel(advection=(velocities=CenteredFourthOrder(), tracers=WENO5()))
```

We also probably want to allow different advection schemes for every tracer. We can support something like

```julia
model = IncompressibleModel(advection=(velocities=CenteredFourthOrder(), T=WENO5(), S=CenteredSecondOrder()))
```

Let's discuss whether the syntax proposed above is acceptable or if we want a different design.

PS we need to write down a list of `forbidden_tracer_names` and throw an error if they are provided. Right now these are `:u, :v, :w` and any possible property of `diffusivities`. The above design would also preclude `:velocities` and `:tracers`.

**Comment by ali-ramadhan** [comment]
I think this syntax makes a lot of sense since it's pretty close to how users can specify different turbulent diffusivity closures for each tracer.

I guess you can't have different advection schemes for u, v, w so e.g. `velocities=CenteredFourthOrder()` makes sense too.

**Comment by francispoulin** [comment]
The setup @glwagner suggests for splitting the advection schemes would work well for `IncompressibleModel`, I think.  

For `ShallowWater`, something different would need to be done.  The solution field has `uh`, `vh`, and `h`, but it would be nice to have different advection schemes for the mass transports `uh`, and `vh` than for the mass equation `h`.

**Comment by glwagner** [comment]
Superceded by #2454
