### ISSUE TITLE
Models with `Flat` dimensions still return NaN

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1023]
I think the definition of "cell volumes" needs to be dispatched on for models of dimension < 3:

https://github.com/CliMA/Oceananigans.jl/blob/6b2cea36d5782f5a73402b97f4d7476de9237c93/src/Operators/areas_and_volumes.jl#L49-L50

Since `Flat` dimensions have zero grid spacing, cell volumes in models with `Flat` dimensions are spuriously calculated to be `0`, which leads to dividing by `0` in advection operators, eg

https://github.com/CliMA/Oceananigans.jl/blob/6b2cea36d5782f5a73402b97f4d7476de9237c93/src/Advection/tracer_advection_operators.jl#L15-L19

I found this while testing the `internal_wave.jl` example for #1014 . We should have a test that models with `Flat` dimensions don't NaN. In fact, I think most or all of the dynamics tests could be converted to use `Flat`.

**Comment by ali-ramadhan** [comment]
@glwagner @francispoulin I'm closing this issue as it seems to have been resolved by #1513. Please re-open if that's not the case.
