### ISSUE TITLE
Deploy documentation through Buildkite.

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1051]
Right now it's done through Travis which is very slow. We can build and deploy docs much faster on Buildkite as Tartarus has lots of CPU resources.

**Comment by navidcy** [comment]
Why not via Github actions? (just saying..)
Do you need GPU functionality for some doc testing?

**Comment by ali-ramadhan** [comment]
Ah yeah no that's a good question.

Initially it's just because the CPUs on Buildkite (running on our machine) are more powerful than the ones on Travis so we can reduce documentation build times from 30~40 minutes down to ~20 minutes.

But we also want to run higher-resolution examples and more of them, which is where more powerful CPUs is helpful, and since we have many cores available we can hopefully run/test/build many examples in parallel (#1053).

And yeah maybe at some point we'll also have MPI (+ GPU?) examples which would have to run on more powerful machines that we can probably access through Buildkite.

**Comment by navidcy** [comment]
I guess v0.44.2 is missing from docs because this was merged after the v0.44.2 tag, correct?
