### ISSUE TITLE
Buildkite not cleaning up environments

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1055]
https://github.com/CliMA/Oceananigans.jl/blob/0908bbdf8f1eed491043d7a9bf1a230c934be7a7/.buildkite/pipeline.yml#L207-L224

does not actually delete the `.julia` depots which can build up and cause future builds to run out of space. I think Buildkite or Linux is limiting the amount of space Buildkite can take up in `/var/lib/buildkite-agent/`.

It's just executing `rm -rf`: https://buildkite.com/clima/oceananigans/builds/205

Potential victim builds:
https://buildkite.com/clima/oceananigans/builds/209
https://buildkite.com/clima/oceananigans/builds/210

I removed the old depots on Tartarus but @glwagner you might have to clean up Sverdrup.

**Comment by glwagner** [comment]
At least its not `rm -rf /*`

**Comment by glwagner** [comment]
The `yml` looks fine to me --- do you see an issue?

**Comment by ali-ramadhan** [comment]
No but it's not doing the right thing. Might require some debugging or trial and error. I can try some stuff. I'll try to regularly clean up `/var/lib/buildkite-agent/` until this is resolved.
