### ISSUE TITLE
Use `-O1` or even `-O0` to reduce compile time for faster testing?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1076]
This significantly reduced the time to first plot for Plots.jl: https://github.com/JuliaPlots/Plots.jl/pull/2544

I guess the idea is we don't care about performance when running our tests. Most of the time is spent compiling so if we can reduce compile time (at the cost of having sub-optimal code) then our tests will run faster.

**Comment by glwagner** [comment]
What is the default?

**Comment by glwagner** [comment]
Seems like a no brainer...

**Comment by ali-ramadhan** [comment]
Ah default is `-O2`. Not mentioned in `man julia` but is mentioned here: https://docs.julialang.org/en/v1/manual/getting-started/#man-getting-started

**Comment by ali-ramadhan** [comment]
Out of curiosity I tried it out on `using Oceananigans`:

```
$ julia --project
julia> @time using Oceananigans
 21.000003 seconds (22.10 M allocations: 1.263 GiB, 2.42% gc time)
```

```
$julia -O0 --project
julia> @time using Oceananigans
 16.059612 seconds (22.10 M allocations: 1.263 GiB, 3.29% gc time)

julia> @time using Oceananigans
  1.131695 seconds (1.59 M allocations: 79.577 MiB, 9.74% gc time)

julia> @time using Oceananigans
  0.000122 seconds (222 allocations: 13.969 KiB)

julia> @time using Oceananigans
  0.000128 seconds (222 allocations: 13.969 KiB)
```

Looks like we have some function invalidations on the second `using Oceananigans` as well.
