### ISSUE TITLE
The all-knowing `TimeStepWizard`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1087]
It isn't really a wizard if your simulation still blows up due to fast inertial waves (or acoustic waves in #1079). Would be neat if it also knew which time step to take to keep the simulation stable against more sources of numerical instabilities.

Right now only advective and diffusive CFL are considered: https://github.com/CliMA/Oceananigans.jl/blob/71cd9533b05d8a4efbc948ae924c513b25201319/src/Simulations/time_step_wizard.jl#L33-L36

**Comment by glwagner** [comment]
The only difficulty is that such imposed time-scales are not restrictive _unless_ there are dynamics that acquire the time-scales. 

For example, in a 2D doubly-bounded model, there are no inertial waves even when coriolis is included. This is why I left this consideration to the user through the `max_Δt` property (also useful for user-imposed limitations through forcing and bcs).

The opposite problem occurs in strongly stratified scenarios, where waves exist with frequencies much greater than `f`. Then a coriolis limiter isn't all that helpful.

But I agree though that it would be pretty nice to automate this somehow and it would be super easy just to put a kwarg in `TimeStepWizard` for Coriolis-related-timestep-limiting. I wonder if we should do a little science; ie do some testing to understand when and why the Coriolis time-scale is a limiting factor, and perhaps provide some feature that help users keep their simulations happily running.

**Comment by glwagner** [comment]
Ah yes. What if we develop a _term-specific_ utility?

I think what we want is a utility that diagnoses a maximum time-step from each term. Imagine

```julia
wizard = TimeStepWizard(magic = (advection=1.0, closure=0.5, coriolis=1/10), ...)
```

well, maybe there's a better kwarg name than `magic`. But something like that: we give the wizard a list of terms to check for any time-step limitations and use the assigned multipliers to limit the next time-step appropriately.

**Comment by glwagner** [comment]
> It isn't really a wizard

There's room in this world for not-very-powerful wizards

**Comment by ali-ramadhan** [comment]
Ah a term-specific utility looks like it would be neat! I guess considering only advection by default would consider most cases.

**Comment by glwagner** [comment]
Im closing this because `advection` is the most important time-scale that _varies_ in a simulation. Other time-step limitations are fixed by model physics, so users can ensure those restrictions aren't violated by setting `min_Δt`.
