### ISSUE TITLE
Benchmarking fully loaded simulations

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1089]
We should add a benchmark for a fully loaded model, e.g. WENO-5 + RK3 + multiple passive tracers + TEOS-10(?) + output writing + time averaging + ...

With #1088 we can serialize such a `BenchmarkGroup` to disk and compare with results from `benchmark_static_ocean.jl` to automatically generate tables of slowdown values for barebones simulation -> fully loaded simulation.

**Comment by glwagner** [comment]
How about benchmarking the examples?

We should have a fully-loaded example too.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
