### ISSUE TITLE
Do we need a discourse / zulip / Google group / mailing list / other kind of public forum or chat service?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1098]
There's a growing number of users of Oceananigans, and we want share knowledge, share ideas, chat, science together, and maybe even work together. Currently the only way for users to ask questions is by posting an issue to github like this one. 

But the issue tracker is _supposedly_ supposed to be used for issues related to the source code and code development. Other questions like:

* Why is my code slow?
* How do I implement my science idea?
* What does Oceananigans _mean_?
* Why is @navidcy so passionate about documentation?

don't have a place to be asked except for, perhaps, emailing developers and other normal humans directly. But unfortunately private emails are not accessible to all, and thus knowledge is lost or not disseminated.

We do now have a channel on the julia slack:

https://julialang.slack.com/archives/C01D24C0CAH

which may, or may not, suffice for now.

**Comment by navidcy** [comment]
:) I don't really know myself... I'll let others throw ideas on this

**Comment by glwagner** [comment]
For now we are going to use the julia slack:

https://julialang.slack.com/archives/C01D24C0CAH

we can reconsider a different application in the future.
