### ISSUE TITLE
When multithreading use 4 times more threads for FFTW

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1113]
Super easy fix. Suggested by @vchuravy.

Should rerun multithreading benchmarks after this.

**Comment by glwagner** [comment]
See also 

https://github.com/JuliaMath/FFTW.jl/pull/105

and

https://github.com/JuliaMath/FFTW.jl/pull/151

**Comment by milankl** [comment]
The `FFTW.set_num_threads` is a global FFTW configuration that ideally shouldn't be set to avoid affecting other packages that are loaded in the same session also depended on FFTW see https://github.com/SpeedyWeather/SpeedyWeather.jl/issues/919. PR #4958 fixes that
