### ISSUE TITLE
Plotting recipes

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1115]
Would be neat if we could add plotting recipes for fields: https://docs.juliaplots.org/latest/recipes/

I guess Plots.jl makes the most sense for 2D plots? Could even do nice things with subplots for things like `plot(model.velocities)` or even `plot(model)`.

3D plotting recipes with Makie.jl would be even cooler! https://makie.juliaplots.org/stable/recipes.html

Could add some interactive tools that you slide through the 3D volume and look at slices.

**Comment by glwagner** [comment]
> Could add some interactive tools that you slide through the 3D volume and look at slices.

Now THAT is a feature for AD 50349.

**Comment by francispoulin** [comment]
Maybe it would be nice to plot 1D slices in each direction of the mask?

For the z direction, for example, I wonder if something like this might work?  I have not tried this out yet but just getting it started.

```
using Plots
using Oceananigans.Grids: xnodes 

@inline (g::GaussianMask{:z})(x, y, z) = exp(-(z - g.center)^2 / (2 * g.width^2))

z_mask = GaussianMask{:z}(center=-grid.Lz, width=grid.Lz/10)

plot(z, z_mask)
```

**Comment by navidcy** [comment]
Closing this since we moved to Makie for plots in examples.
