### ISSUE TITLE
Define `minimum` and `maximum` for `Field`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1117]
Would be nice as it's a common operation to do. Maybe some other operations too. Might want to consider not overloading `mean(::Field)` as people might expect it to return a scalar instead of an `AveragedField`.

cc @whitleyv

**Comment by ali-ramadhan** [comment]
This would actually be good to work on since a `minimum`, `mean`, etc. that works seamlessly for CPU and GPU would reduce a lot of headaches and accidental CUDA scalar operations.

**Comment by glwagner** [comment]
I think this is easy right? Just

```julia
Statistics.minimum(f::Field) = minimum(interior(f))
```

or even better

```julia
reductions = (:maximum, :minimum, :std, ...)

for r in reductions
    @eval begin
        Statistics.$r(f::Field) = $r(interior(f))
    end
end
```

or something.

**Comment by francispoulin** [comment]
This looks good to me.  I wonde whether we would want to use this in the time stepping wizard to compute the maximum velocities?

**Comment by ali-ramadhan** [comment]
Unfortunately I don't think it's that simple:

```julia
julia> model.tracers.T
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64,3,CuArray{Float64,3}}, size: (130, 130, 3)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=128, Ny=128, Nz=1)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)

julia> minimum(interior(model.tracers.T))
ERROR: scalar getindex is disallowed
```

**Comment by ali-ramadhan** [comment]
Ah never mind we just need `interiorparent` instead of `interior`:

```julia
julia> CUDA.allowscalar(false)

julia> minimum(interiorparent(model.tracers.T))
0.0
```

In this case, I think CUDA.jl knows what to do for non-contiguous `CuArray` views, but not for `non-contiguous `OffsetArray{CuArray}` views.
