### ISSUE TITLE
Incorrect warning about simulations running forever in Simulation constructor

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1124]
I get a warning:

```julia
julia> simulation = Simulation(model, Δt=0.1, iteration_interval=100,
                               progress=sim -> @info("Model iteration: $(sim.model.clock.iteration)"))
┌ Warning: This simulation will run forever as stop iteration = stop time = wall time limit = Inf.
└ @ Oceananigans.Simulations ~/Research/Oceananigans.jl/src/Simulations/simulation.jl:63
```

 @glwagner  you mentioned that this is bogus warning... Should we fix it before this PR? Otherwise the warning will appear in the documentation.

_Originally posted by @navidcy in https://github.com/CliMA/Oceananigans.jl/pull/1123#discussion_r515339534_

**Comment by glwagner** [comment]
In particular, this warning is inaccurate when users intend to add custom stopping criteria as is done in #1123 .

This is still a useful error, but it should be moved inside `run!(simulation)` (with appropriate checks to ensure that the warning is correct, ie, that no additional stop critieria are specified).

**Comment by glwagner** [comment]
Might be best just to resolve this when `Simulation` is redesigned a la #1138

**Comment by navidcy** [comment]
Is this still outstanding @glwagner?

**Comment by glwagner** [comment]
It's not. We have a tradeoff. Either we decide to keep the warning to help poor unsuspecting users that don't realize they need stop criteria, and live with the annoying warning for cases where we set stopping criteria _after_ the constructor, or we remove the warning.

**Comment by glwagner** [comment]
Probably should just live with the warning and close the issue.

**Comment by navidcy** [comment]
Live with the warning.
