### ISSUE TITLE
Derivatives and interpolation of ComputedFields is incorrect on boundaries

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1130]
Derivative and interpolation operations for `ComputedField`s are not correct across boundaries, because `ComputedField`s do not have boundary conditions and thus their halo regions do not get filled. As an illustration:

```julia
julia> using Oceananigans, Oceananigans.Fields, Oceananigans.Grids, Oceananigans.AbstractOperations
[ Info: Oceananigans will use 8 threads

julia> grid = RegularCartesianGrid(size=(1, 1, 2), extent=(1, 1, 2))
RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-2.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (1, 1, 2)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (1.0, 1.0, 1.0)

julia> c = CellField(CPU(), grid)
Field located at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 4)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=2)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)

julia> two_c = ComputedField(2 * c)
ComputedField located at (Cell, Cell, Cell) of BinaryOperation at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 4)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=2)
├── operand: BinaryOperation at (Cell, Cell, Cell)
└── status: time=0.0

julia> dz_two_c = ComputedField(∂z(two_c))
ComputedField located at (Cell, Cell, Face) of Derivative at (Cell, Cell, Face)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 5)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=2)
├── operand: Derivative at (Cell, Cell, Face)
└── status: time=0.0

julia> set!(c, (x, y, z) -> rand())
1×1×2 view(OffsetArray(::Array{Float64,3}, 0:2, 0:2, 0:3), 1:1, 1:1, 1:2) with eltype Float64:
[:, :, 1] =
 0.8753467111937931

[:, :, 2] =
 0.649695162761919

julia> compute!(dz_two_c)

julia> two_c.data[1, 1, :]
4-element OffsetArray(::Array{Float64,1}, 0:3) with eltype Float64 with indices 0:3:
 0.0
 1.7506934223875863
 1.299390325523838
 0.0

julia> interior(dz_two_c)
1×1×3 view(OffsetArray(::Array{Float64,3}, 0:2, 0:2, 0:4), 1:1, 1:1, 1:3) with eltype Float64:
[:, :, 1] =
 1.7506934223875863

[:, :, 2] =
 -0.45130309686374837

[:, :, 3] =
 -1.299390325523838
```

The values of `dz_two_c` at the top and bottom boundary simply reflect the interior values of `two_c`. This is not what's expected: the vertical derivative of `2 * c` across boundaries actually depends on the boundary conditions imposed on `c`.

This is a tricky issue to resolve. I'm not sure we can determine correct halo region values for computed fields in general.

However, we can allow `ComputedField`s to have boundary conditions, like `Field`s currently do. In this case, users may specify boundary conditions on `ComputedField`s and we can reuse existing defaults if boundary conditions are not specified (or we can use `boundary_conditions = nothing` as a default). At the very least, this will ensure that `ComputedField`s are correct across periodic boundaries and at best users who need correct boundary conditions imposed on `ComputedField`s can provide them.

**Comment by glwagner** [comment]
I think putting boundary conditions with a `nothing` default on `ComputedField`s makes a lot of sense. We preserve existing behavior and performance while allowing the flexibility for users to design a computation tree with intermediate steps that's correct everywhere.

**Comment by tomchor** [comment]
I think allowing boundary conditions for `ComputedField`s is a nice solution. But I also don't understand why they can't be applied automatically. If each of the fields in a `ComputedField` has its halo regions properly filled (based on their individual BCs), shouldn't the computation automatically produce results for the `ComputedField` that match the appropriate BC?

**Comment by glwagner** [comment]
I don't think that will work out of the box when the `ComputedField` requires derivatives or interpolation in the halo region. For derivatives or interpolation to work within halo regions, the fields being differentiated or interpolated would have to have larger halo regions than the `ComputedField`. Maybe I'm missing something?

**Comment by glwagner** [comment]
The problem here I think is that arbitrary derivatives or interpolation operations are not automatically well-defined in our finite volume method. The most egregious case is when fields have `Flux` boundary conditions; in that case we don't attempt to determine the gradients of those fields across boundaries at all (in principle this is _often_, but not always, inferable given completely knowledge of the PDE / turbulence closure used for the field...)

With second-order operations, we need halo regions of size 1 in order to compute second order quantities like the an isotropic diffusivity. However, to be well-defined on boundaries, higher-order derivatives would require more boundary conditions. So far we've skirted the issue (or just ignored it) by simply not allowing boundary conditions for `ComputedField`s. This has the sad consequence that `ComputedField`s cannot be trusted adjacent to boundaries; a restriction that is especially severe for flat problems in which the entire problem is adjacent to a boundary.

I think the simplest solution for now is to ask users to supply boundary conditions for their `ComputedField`s where appropriate. We could also have a discussion about how to infer boundary conditions on `ComputedField`s based on their expression tree / operand, but I'm worried this might be a hard, or even ill-posed problem.

**Comment by tomchor** [comment]
@glwagner I think I see what you mean now. It's definitely a harder problem than I anticipated. I think the ideal way would be to infer these conditions automatically, but like you said that may be a very hard problem. I don't think it's ill-posed, since you basically have all the necessary information in one way or another. So if I, a human, can arrive at the right answer with the same information, I think a program could do the same.

Second best way would be to try infer the right BCs but provide an option to manually force a certain BC. I think inferring should be relatively easy in very simple cases, no? For example, in the pseudo-code below...

```julia

... # Some code
UVelocityBoundaryConditions(grid, top = BoundaryCondition(Gradient, 0), bottom = BoundaryCondition(Gradient, 0),)
... # More code

dudz_comp = ComputedField(∂z(u))
compute!(dudz_comp)
```

This currently produces something with the wrong derivatives at the boundary, but I'd expect that it wouldn't be too hard to get this one right automatically since you basically have to do something similar to solve the Boussinesq equations. Am I wrong?

Finally, I don't oppose relying completely on the user to provide the BCs for the ComputedFields like you said. Mostly I don't know the difference in the amount of effort between these options! So maybe if this one is significantly faster to code/test than the other ones, this should be the way for now.

**Comment by glwagner** [comment]
> But I guess you mean higher order derivatives? Where, like you pointed out, you'd need more points in the halo region?

Not exactly... derivatives of too high an order may actually segfault because they'll try to access memory that doesn't exist. That's also a problem...

The problem here is that derivatives of `ComputedField` are not correct (note that your example doesn't use derivatives of `ComputedField`, it only uses derivatives of `Field`).

Here's an example:

```julia
using Oceananigans
using Oceananigans.Fields
using Oceananigans.AbstractOperations: ∂x

grid = RegularCartesianGrid(size=(3, 1, 1), extent=(2π, 1, 1), halo=(2, 2, 2)) 

model = IncompressibleModel(grid=grid)

set!(model, T = (x, y, z) -> sin(x))

T, S = model.tracers

d²T_dx² = ComputedField(∂x(∂x(T)))

dT_dx = ComputedField(∂x(T))
d²T_dx²_computed_derivative = ComputedField(∂x(dT_dx))

compute!(d²T_dx²)
compute!(d²T_dx²_computed_derivative)

@show interior(d²T_dx²)
@show interior(d²T_dx²_computed_derivative)
```

I find that

```
interior(d²T_dx²) = [-0.5922903530864669; 2.385416011097638e-16; 0.5922903530864667]
```

but

```
interior(d²T_dx²_computed_derivative) = [-0.5922903530864669; 2.385416011097638e-16; 0.19743011769548882]
```

This occurs because the second calculation uses the value of `dT_dx` at `i=4` (the right boundary) where `dT_dx[4, 1, 1]
0.0` --- despite that 

```
julia> dT_dx_op = ∂x(T)
Derivative at (Face, Center, Center)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=1, Nz=1)
│   └── domain: x ∈ [1.1842378929335e-15, 6.283185307179587], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
└── tree: 
    ∂xᶠᵃᵃ at (Face, Center, Center) via identity
    └── Field located at (Center, Center, Center)

julia> dT_dx_op[4, 1, 1]
0.8269933431326884
```

In this case, we _are_ able to evaluate `dT_dx_op` outside the interior because I used halos of size 2.

**Comment by glwagner** [comment]
We have boundary conditions for all `Field`s now.
