### ISSUE TITLE
Proposal to export the entire user interface at the top-level module

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1132]
I think it would be to good to export the entire user interface at the top-level module so it's all fully available to the user with just `using Oceananigans`.

Some thoughts:
1. Would make it much easier to set up scripts. Many times I've found that users add something to their scripts, e.g. `AveragedField` or a `NetCDFOutputWriter`, and forget to add `using Oceananigans.Fields` or `using Oceananigans.OutputWriters`. It can be hard for a user to figure out exactly which import statement they're missing without consulting the docs (this could be considered a pain point).

2. Our current approach is not consistent either. The top level `Oceananigans` module exports a lot of the user interface but not all of it, so users are expected to import submodules but the submodules themselves export way more than just the user interface including functions that are not part of the user interface (example: https://github.com/CliMA/Oceananigans.jl/blob/master/src/Fields/Fields.jl).

3. I think we should export the entire user-interface at the top-level and be mindful of not exporting too much. Everything that gets exported at the top-level requires a docstring (this would allow us to enable strict checking for exported docstrings in `makedocs`: https://github.com/CliMA/Oceananigans.jl/blob/9026438047fe3e5d4805edcebe42560268dc65fb/docs/make.jl#L150).

**Comment by glwagner** [comment]
I agree with this. I think our experience has shown that requiring submodule imports is a huge source of boilerplate.

At the same time, I think we should stop exporting names from submodules (for better internal code documentation). This will requires some refactoring.

**Comment by navidcy** [comment]
Is there any benefit of not exporting everything anyway? I just can’t think of any? Keep namespace cleaner?

**Comment by glwagner** [comment]
> Keep namespace cleaner?

Yes, I think that's the argument for limiting how much you export.

**Comment by ali-ramadhan** [comment]
> Is there any benefit of not exporting everything anyway? I just can’t think of any? Keep namespace cleaner?

I think exporting something inherently tells users it's documented, tested, and okay to use. But there are lots of internal functions that are not documented and probably shouldn't be used by users.

**Comment by navidcy** [comment]
I see you.
