### ISSUE TITLE
Every exported name requires a docstring

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1133]
This might be easier to work on if we decide to go ahead with #1132.

This would allow us to enable strict checking for exported docstrings in `makedocs`: https://github.com/CliMA/Oceananigans.jl/blob/9026438047fe3e5d4805edcebe42560268dc65fb/docs/make.jl#L150

**Comment by glwagner** [comment]
@navidcy is this still an issue?

**Comment by glwagner** [comment]
Probably should resolve #2996 first then we can look at this.

**Comment by navidcy** [comment]
This is resolved!
