### ISSUE TITLE
Exporting only long-form boundary condition constructors?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1140]
Currently the `Oceananigans` module exports

```julia
Flux, Value, Gradient, NormalFlow,
FluxBoundaryCondition, ValueBoundaryCondition, GradientBoundaryCondition,
```

so there's some redundancy (perhaps we should export one set to reduce namespace pollution) but a minor practical issue is that the `Flux` type conflicts with the popular Flux.jl package (I guess I'm the only one using them together right now but there may be more in the future?). There's also some inconsistency in exporting `NormalFlow` but not `NormalFlowBoundaryCondition`.

In deciding on what to export for the user interface (see #1132) I'm wondering what do people think about only exporting the long-name version, e.g. `FluxBoundaryCondition` instead of `Flux`.

I think this will have a few benefits:
1. Lower probability for conflicts. `Flux` is one example, but `Value` and `Gradient` are pretty generic terms so I wouldn't be surprised if they conflict with exports from other packages future users may want to work with.
2. Scripts might read more intuitively, e.g. because you say "a flux boundary condition" and not "a boundary condition of type flux".
3. If we decide to export the complete set of boundary conditions we could do it by exporting `PeriodicBoundaryCondition` without having to worry about conflicting with the `Periodic` topology.

X-Ref: #1132

**Comment by glwagner** [comment]
I'm fine with this. Also helps with #1119 .
