### ISSUE TITLE
Fill halo regions in set!(model, ...)?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1150]
Over at PR #1128, we've been investigating why the plankton concentration becomes negative, and as part of that @navidcy printed the buoyancy field prior to calling `run!`. He discovered that the halo regions were not filled. We do fill them as an initialization step in `run!` (otherwise the model would not be correct). However, it's still confusing or maybe just disheartening / stressful that the halos are not filled prior to `run!`. Yet we have all the information we need to fill halos in `set!` --- so we should probably do that.

**Comment by ali-ramadhan** [comment]
Yeah filling halo regions as part of `set!` seems like the right thing to do.

I guess we don't use `set!` for any performance critical code, but in case we do in the future might be nice to add an optional kwarg `set!(field, fill_halos=true)` in case someone wants to use `fill_halos=false` to shave 0-6 kernel launches.

**Comment by ali-ramadhan** [comment]
This is done in `update_state!` so we can close this issue I think.

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/Models/IncompressibleModels/update_incompressible_model_state.jl
