### ISSUE TITLE
NetCDF output writer should append by default if file already exists

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1160]
By default `NetCDFOutputWriter` uses `mode = "c"` which overwrites existing files.

The problem arises when using the same script to checkpoint and pickup (i.e. running the same script over and over): `mode = "c"` is fine the first run but after that you want `mode = "a"`.

Making the user explicitly select the `mode` will force the user to check if there's a checkpoint to select a mode, which will add boilerplate code like

```julia
searchdir(path, key) = filter(x -> occursin(key, x), readdir(path))
checkpoints = searchdir(base_dir, "iteration")

n_checkpoints = length(checkpoints)
checkpointed = n_checkpoints > 0 ? true : false

mode = checkpointed ? "a" : "c"
```

Would be nice if `NetCDFOutputWriter` switched to `mode = "a"` if a file exists (and print a warning).

**Comment by ali-ramadhan** [comment]
cc @qwert2266 @sandreza since this affects you guys.

**Comment by glwagner** [comment]
Wouldn't the logic above be better written

```julia
pickup = true
mode = pickup ? "a" : "c"
```

I think #1162 is a positive contribution, but best not to mislead.

**Comment by ali-ramadhan** [comment]
Ah but if you want to use `pickup=true` the first time you run the script then there won't be any NetCDF Files so `mode = "a"` will fail to append. Did I understand your suggestion correctly?

**Comment by glwagner** [comment]
Ah I see, my suggestion doesn't solve that problem.

For a script-based solution for problems like these it might be better to use `glob`:

```julia
checkpoint_files = glob("*iteration*", checkpointer.dir)
mode = length(checkpoint_files) > 0 ? "a" : "c"
```

but definitely glad to see a solution for this likely common problem in the source.
