### ISSUE TITLE
invalid assignment location

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1164]
I am going through the examples and starting with the 1D diffusion problem.

I seemed to get the following error by simply copying and pasting the commands in the docs.  

Does something need to be updated?

```
julia> IsotropicDiffusivity: ν=1.05e-06, κ=1.0
ERROR: syntax: invalid assignment location "1.05e-06" around REPL[7]:1
Stacktrace:
 [1] top-level scope at REPL[7]:1

```

**Comment by glwagner** [comment]
No worries, no need to delete the issue! If someone else has the same confusion, the issue might help them.

It does seem that we assume some familiarity with julia's Documenter (there's no explanation that gray boxes are code; white boxes are output). This might be something to mention in the getting started when we recommend the best way for users to become familiar with the code (being discussed on #1149 )

**Comment by francispoulin** [comment]
No, it's very obvious and I have read this properly many, many times.  I was just copying a pasting with too much vigour and misread.  It occurs to me that doing this in a jupyter notebook would be much better.  

I don't see that this comes with the repo by default.  Is that correct?  Do you think it would be wortwhile to have these example son notebooks so people can view them more easily without the copying and pasting, and silly mistakes that comes along with doing that?

**Comment by navidcy** [comment]
Yeap. That's easy... I can work on that 👍

**Comment by francispoulin** [comment]
I don't mean to add to your alrady busy schedule but I do think that notebooks are pretty great and easy to use.  I'm installing IJulia now, maybe something worth mentioning in the docs if you wanted to use jupyter, and am going to test it out myself.

Also, I needed to add JLD2 to run the 1D diffusion problem.  I might suggest saying explcitly you need to add this package?

**Comment by navidcy** [comment]
no worries @francispoulin
I guess something like the nbviewer button at the top, e.g., [here](https://fourierflows.github.io/GeophysicalFlowsDocumentation/dev/generated/barotropicqg_betadecay/) is what you have in mind, right?

**Comment by glwagner** [comment]
> No, it's very obvious and I have read this properly many, many times

Ah, I see what you are saying. The notebook format is nice too because you can edit / change the code.

> I might suggest saying explcitly you need to add this package?

Agree! We are actually considering adding a line at the top of the examples that downloads the packages for users.

I hadn't thought of these issues because I use a different method for runnign the examples: I use `git clone` to clone the repository, and then run `julia --project example_name.jl` from the `examples/` directory.

However, as we are discussing on #1149 we'd like to improve new users' experience here and `git clone` is probably too much to expect. We want clickable shortcuts that yield figures on your screen with minimal effort / prior julia knowledge.

**Comment by francispoulin** [comment]
@navidcy , yes, that looks great.  However, when I click on the link I don't think I can execute the commands, but maybe I was too quick to close the page.

I created a notebook for the 1D diffusion problem by basically copying and pasting what you have in the example.  My markdown is a bit rusty but luckily you had all the right syntax there already.  I was going to attach it to this message here but it seems that notebook are unsupported. It is nothing fancy but I do think that if there was an open to open the notebook and run it that would make it a bit easlier than copying and pasting.

@glwagner that sounds like a great way to run the script, which is certainly what you want to do.  Personally, when learning what a script is doing it's nice to execute it line by line to get to know the process.  After you've seen it once then you definitely want to the entire example.  Anyhow, my 2 cents worth.

**Comment by glwagner** [comment]
> Personally, when learning what a script is doing it's nice to execute it line by line to get to know the process.

That's very useful to know. The workflow you're describing is similar to what @ali-ramadhan was recommending in the discussion on #1149 . @rcmusgrave also uses a similar approach to examples, I think.

**Comment by glwagner** [comment]
@francispoulin you may be able to autogenerate a notebook using the utility

https://fredrikekre.github.io/Literate.jl/v2/outputformats/#Literate.notebook

For example, you might be able to execute this block of code from `examples/`:

```julia
using Pkg
pkg"add Literate, Plots, JLD2, Oceananigans"

Literate.notebook("one_dimensional_diffusion.jl")
```

**Comment by francispoulin** [comment]
Thanks for sharing @glwagner !

I will certainly give that a try as my copying and pasting clearly leaves something to be desired.

I tried it and I think this works great!  Such a great tool to have, and proven to be way faster, and usually more accurate than my copying and pasting.

One thing I noticed in the 2D turbulence example, you want to have a space between the second comment below and the u,v,w... otherwise it doesn't convert the comment into a nice text.

```
## To make our equations prettier, we unpack `u`, `v`, and `w` from 
## the `NamedTuple` model.velocities:
u, v, w = model.velocities

```

**Comment by francispoulin** [comment]
Similary, in internal_wave.jl, lines 36 and 37 should only have one # per line.

```
# Background fields are functions of `x, y, z, t`, and optional parameters.
# Here we have one parameter, the buoyancy frequency

```

**Comment by glwagner** [comment]
Nice catch, thanks. Sometimes double quotes are intended (because sometimes we _do_ want a code comment, rather than markdown). Here I suspect we want markdown, however, as you point out.
