### ISSUE TITLE
Reducing boilerplate in OutputWriter specification

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1171]
Building up OutputWriters can be a major source of boilerplate in "production" scripts that often involve multiple types of output (slices at different locations, different types of averages, etc). An example is:

https://github.com/glwagner/EadyTurbulence/blob/master/initial_value_problem/eady_initial_value_problem.jl

I think the point is more or less that output writers are often related to one another. For example, we typically want all our output in a single directory, and on the same schedule. I also pretty much always use `force=true` (I guess the equivalent for NetCDF is "clobber" mode).

Is there a way to reduce this boilerplate or is it a fact of Oceananigans life? Can we specify some output parameters in `Simulation` rather than in each `OutputWriter` individually? Resolving #1163 might help but I'm not sure. It does seem to make sense to coordinate the output directory through the `Simulation` rather than each output writer individually. But this also contradicts some of what was discussed on #963, such as using the keyword `filepath` rather than `prefix` and `dir`.

**Comment by ali-ramadhan** [comment]
Yeah definitely agree with output writer construction being boilerplate-y...

Taking the Eady turbulence IVP example, it seems like there are two kinds of output writers:
1. Slices (`xy_surface`, `xy_subsurface`, `xy_middepth`, `xy_bottom`, `xz`, `yz`).
2. Sets of computed fields (`horizontal_averages`, `volume_averages`).

# Saving collections of slices

For number 1, I can imagine an abstraction, perhaps a collection of output writers like `NetCDFOutputWriters`, that allows you to specify a number of slice outputs for all fields:

```julia
slices = (all           = FieldSlicer(),
          xy_surface    = FieldSlicer(k=grid.Nz),
          xy_subsurface = FieldSlicer(k=k_subsurface),
          xy_middepth   = FieldSlicer(k=round(Int, grid.Nz/2)),
          xy_bottom     = FieldSlicer(k=1),
          xz            = FieldSlicer(j=1),
          yz            = FieldSlicer(i=1)
)

simulation.output_writers[:slices] = NetCDFOutputWriters(filepath_prefix="eady_turbulence", slices=slices, ...)
```

This would save all fields in `merge(model.velocities, model.tracers)` to `eady_turbulence_all.nc`, `eady_turbulence_xy_surface.nc`, etc. with appropriate slicing. You could pass in one schedule for all slices, or a named tuple of schedules if you want different schedules for different output writers.

I think it makes sense to have a `filepath_prefix` for the collection of output writers, e.g. `NetCDFOutputWriters`, while just `filepath` for individual output writers, e.g. `NetCDFOutputWriter`.

I thought about adding this functionality to the `Simulation` constructor with kwargs like `output=:netcdf` or `output=:jld2` but felt like the number of extra kwargs would just make it messy.

# Saving collections of computed fields

For number 2, we could perhaps automate some of this to avoid boilerplate like https://github.com/glwagner/EadyTurbulence/blob/6581af1cd867d8ad69dac7ea09deb3078c505c24/initial_value_problem/eady_initial_value_problem.jl#L149-L163

Not sure if we want yet another super-constructor but one idea is to add something like `AveragedNetCDFOutputWriter`.

```julia
averages = (u=u, v=v, b=b, ζ²=ζ², b²=b², bz=∂z(b))

simulations.output_writers[:horizontal_averages] = AveragedNetCDFOutputWriter(model, averages, dims=(1, 2), ...)

simulations.output_writers[:volume_averages] = AveragedNetCDFOutputWriter(model, averages, dims=(1, 2, 3), ...)
```

**Comment by glwagner** [comment]
Ahh, very nice ideas. A convenience constructor for a collection of writers is a much better idea than the "global variable"-y solution I proposed regarding `Simulation`; we just have to invent a file naming convention that makes sense (I actually think that file name conventions are nice because it regularizes output between users, which can help with communication...)

We actually don't need separate `Averaged*` constructors if we extend the philosophy of time-averaging and add a kwarg like `spatially_averaged_dims` (maybe there's a better name, but we have to avoid confusion with time-averaging) that transforms fields into `AveragedField`s, eg

```julia
simulations.output_writers[:horizontal_averages] =
    NetCDFOutputWriter(model, output_fields, spatially_averaged_dims=(1, 2), ...)

simulations.output_writers[:volume_averages] =
    NetCDFOutputWriter(model, output_fields, spatially_averaged_dims=(1, 2, 3), ...)
```

the default `nothing` doesn't transform anything.

**Comment by glwagner** [comment]
I'm closing this because its a bit open ended, and I think there are decent user-driven solutions to this issue that don't require any special features on the Oceananigans side.
