### ISSUE TITLE
Oceananigans should complain if boundary conditions are inconsistent

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1177]
Easy to get burned by accidentally applying e.g. no-slip boundary conditions along a periodic dimension (mixing up `east` and `north`).

Oceananigans should probably print a warning or error if you apply inconsistent boundary conditions.

Definitely occurred to me multiple times (and recently encountered by @whitleyv too).

**Comment by glwagner** [comment]
I believe this is dup with #890

**Comment by glwagner** [comment]
I think error is appropriate / friendly since you most definitely want to know that your problem doesn't make sense.

**Comment by ali-ramadhan** [comment]
Ah sorry yes, it's a duplicate of #890 haha.
