### ISSUE TITLE
Stop assuming a default topology?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1178]
Seems like a leftover relic from a time when we only had 1 pressure solver for `(Periodic, Periodic, Bounded)`. 

Might be good to be explicit about the topology, but maybe we should wait until all 9 (or 27) topologies are usable?

Would be good to be explicit since it may be unclear whether adding walls should happen via boundary conditions or via a grid topology.

cc @whitleyv

**Comment by glwagner** [comment]
I support that. It's not really boilerplate if the topology is an intrinsic part of the problem.

**Comment by tomchor** [comment]
Not sure if I should open another issue for this, but I was trying to set-up a 2D topology like `(Bounded, Flat, Bounded)` but couldn't. Apparently, however, `(Flat, Bounded, Bounded)` works.

Is there a list of available topologies to choose from? The `topology` page on the docs leads me to believe that they're all implemented but (unless I'm missing something) they're not. Is that list somewhere in the docs? I couldn't find it.

Cheers!

**Comment by glwagner** [comment]
Might be best to explain that we don't recommend `Flat` right now too...

**Comment by navidcy** [comment]
@tomchor I believe that until https://github.com/CliMA/Oceananigans.jl/pull/1024 is resolved, `Flat` topologies could be problematic.

Perhaps we should resurrect https://github.com/CliMA/Oceananigans.jl/pull/1024? @ali-ramadhan, @glwagner

**Comment by glwagner** [comment]
I'm not convinced this is a good idea anymore. Defaults are useful. Thoughts?

**Comment by francispoulin** [comment]
For the inexperienced usef I think defaults are a good idea.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
