### ISSUE TITLE
Bottom boundary layer example / tutorial?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1183]
While we have a few examples / tutorials that demonstrate how Oceananigans can be used to model the ocean surface boundary layer, we have nothing comparable for a ocean bottom boundary layer / atmospheric boundary layer where the action goes down at rough / no-slip boundary. It might be nice to provide a bottom boundary layer example with a wall model appropriate for LES. There's a number of people interested in using Oceananigans to model the bottom boundary layer (cc @tomchor, @raphaelouillon)

It'd be nice to think of some way to make it fun and interesting. A few ideas are:

* Implement a wall model appropriate for rough boundaries, and atmospheric / bottom boundary layer LES
* Model sediment-turbulence interaction, perhaps with an effect on buoyancy?
* Use the TEOS10 equation of state (not used in any examples)
* Use a gravitational acceleration that's not aligned with z, once #1151 is resolved
* Drive turbulence with tides (eg perhaps reproduce @bekaiser's work in an LES setting)

Could do all at once...

Others might have better or more reasonable ideas.

**Comment by francispoulin** [comment]
Would flow over a seamount be of interest and doable?  Some models have difficulties with this problem because of what some call "gradient pressure error" so it might not be the first thing to do, but if Oceananigans could do this well, that would be most impressive.  Could also look pretty cool, but all the examples above sound great!

**Comment by navidcy** [comment]
Flow over seamount is not yet possible but it’s coming...

(See #1036)

**Comment by francispoulin** [comment]
Thanks @navidcy 

I presume this needs the immersed boundary method to be working before we can deal with non-cartesian geometries?

**Comment by glwagner** [comment]
Thats right @francispoulin !

The immersed boundary doesn't change the geometry (one its attractive features); so the geometry would remain Cartesian and regular. More or less the immersed boundary adds forcing terms to the RHS / adjusts the velocity field and pressure solver to approximate the presence of a boundary that's "immersed" within the structured grid.

Agree it would awesome to have an example of this kind when we're ready. Let's think about it in a few months or so :-D

**Comment by wenegrat** [comment]
How about doing the arrested Ekman layer problem (as in Ruan et al. 2019)?

This would require resolving #1151 and adding a wall-model. The domain setup is otherwise very simple, fixed barotropic flow and fixed uniform background stratification. Small domain in the horizontal, and Xiaozhou's results give a nice point of comparison.

**Comment by ali-ramadhan** [comment]
Ah that could be a neat validation experiment for tilted gravity and Oceananigans in general!

Just linking to Ruan et al. (2019): https://doi.org/10.1175/JPO-D-18-0079.1

**Comment by glwagner** [comment]
Wall models should be relatively simple to implement, see `eady_turbulence.jl`:

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/examples/eady_turbulence.jl#L160-L169

**Comment by glwagner** [comment]
@xiaozhou.r might be interested in implementing Ruan et al. (2019).

**Comment by xiaozhour** [comment]
Getting myself familiar with Oceananigans these days -- would be happy to help set up the run and provide previous model output from DIABLO for comparison!

**Comment by navidcy** [comment]
@tomchor, does the "tilted bottom boundary layer example" serve this purpose? Shall we close this issue?

**Comment by tomchor** [comment]
Yes!
