### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1186]
Should we move away from Travis-CI?
https://discourse.julialang.org/t/using-julia-in-github-actions/27805/5

**Comment by navidcy** [comment]
I've noticed that often times recently travis job fail without reason... Perhaps that's random coincidental event though...

**Comment by glwagner** [comment]
I don't know the technical details, but agree that Travis is frustrating...

What's the alternative and how would we switch?

**Comment by navidcy** [comment]
Word on the street mentions GitHub Actions. But I'm not sure how CPU-intensive tests could be handled.

**Comment by ali-ramadhan** [comment]
Yeah the era of free Travis is over haha. We've already run out of Travis credits so some builds have stopped running.

This is fine except for the fact that Travis currently builds our docs, so our docs won't update until we have more credits or we build and deploy docs elsewhere, e.g. from Buildkite.

@maleadt has been setting up Buildkite pipelines for JuliaGPU and CUDA.jl so we could borrow from his `pipeline.yml`: https://github.com/JuliaGPU/CUDA.jl/blob/master/.buildkite/pipeline.yml

and his Buildkite plugins:

https://github.com/JuliaCI/julia-buildkite-plugin
https://github.com/JuliaCI/julia-test-buildkite-plugin
https://github.com/JuliaCI/julia-coverage-buildkite-plugin

**Comment by ali-ramadhan** [comment]
This was resolved by #1207 and #1209.
