### ISSUE TITLE
Multithreaded FFTs on the CPU

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#119]
> Do you think that we should allow people to plan multithreaded FFTs on the CPU? There's no reason not to use multithreading if its available.
> 
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/pull/116#issuecomment-470798886_

**Comment by ali-ramadhan** [comment]
From Googling around I believe FFTW.jl is build in serial mode? I couldn't see how to make use of multi-threading or specify the number of threads.

A related performance optimization would be to consider using Intel's MKL which is usually faster on Intel machines (and might come with multi-threading out of the box).

But since we're not running large models on single-core CPUs this seems like a low priority consideration for now.

**Comment by glwagner** [comment]
I think “Nthreads” is a keyword argument in plan_fft.

**Comment by glwagner** [comment]
As far as I know the stock FFTW comes in multithreaded version. Passing
nthreads to the planner will result in a planned fft.

Could make an “fftkwargs” argument to Model. Then the user can specify
whatever arg they want to the planner via a Dict.

**Comment by ali-ramadhan** [comment]
Ah just checked and there's a `FFTW.set_num_threads(nthreads::Integer)` function. Should be easy for us to benchmark Oceananigans.jl with different `nthreads` using the benchmarking script #116.

**Comment by glwagner** [comment]
You only need to use that if you are directly calling fft. If you use
plan_fft, you have to specify nthreads to the planner.

**Comment by ali-ramadhan** [comment]
Ah I see. I couldn't find it in the FFTW.jl source but will have a closer look later. I'm sure you're right.

**Comment by glwagner** [comment]
Do ? plan_fft! at the REPL

**Comment by ali-ramadhan** [comment]
Weird, I see no mention of threads or multi-threading
```
help?> plan_fft
search: plan_fft plan_fft! plan_rfft plan_ifft plan_bfft plan_ifft! plan_bfft! plan_irfft plan_brfft

  plan_fft(A [, dims]; flags=FFTW.ESTIMATE, timelimit=Inf)

  Pre-plan an optimized FFT along given dimensions (dims) of arrays matching the shape and type of A. (The first two arguments have the same meaning as for fft.) Returns an object P which
  represents the linear operator computed by the FFT, and which contains all of the information needed to compute fft(A, dims) quickly.

  To apply P to an array A, use P * A; in general, the syntax for applying plans is much like that of matrices. (A plan can only be applied to arrays of the same size as the A for which
  the plan was created.) You can also apply a plan with a preallocated output array Â by calling mul!(Â, plan, A). (For mul!, however, the input array A must be a complex floating-point
  array like the output Â.) You can compute the inverse-transform plan by inv(P) and apply the inverse plan with P \ Â (the inverse plan is cached and reused for subsequent calls to inv or
  \), and apply the inverse plan to a pre-allocated output array A with ldiv!(A, P, Â).

  The flags argument is a bitwise-or of FFTW planner flags, defaulting to FFTW.ESTIMATE. e.g. passing FFTW.MEASURE or FFTW.PATIENT will instead spend several seconds (or more) benchmarking
  different possible FFT algorithms and picking the fastest one; see the FFTW manual for more information on planner flags. The optional timelimit argument specifies a rough upper bound on
  the allowed planning time, in seconds. Passing FFTW.MEASURE or FFTW.PATIENT may cause the input array A to be overwritten with zeros during plan creation.

  plan_fft! is the same as plan_fft but creates a plan that operates in-place on its argument (which must be an array of complex floating-point numbers). plan_ifft and so on are similar
  but produce plans that perform the equivalent of the inverse transforms ifft and so on.

help?> plan_fft!
search: plan_fft! plan_ifft! plan_bfft! plan_fft plan_rfft plan_ifft plan_bfft plan_irfft plan_brfft

  plan_fft!(A [, dims]; flags=FFTW.ESTIMATE, timelimit=Inf)

  Same as plan_fft, but operates in-place on A.
```

But I just learned that you can apply the inverse plan with P \ Â which is cool!

**Comment by glwagner** [comment]
Sorry, you are right. You use set_num_threads.

See the constructors in

https://github.com/FourierFlows/FourierFlows.jl/blob/master/src/domains.jl

**Comment by ali-ramadhan** [comment]
Ah I see. So you just set the number of threads before planning. Then `nthreads` could be part of the `PoissonSolver` struct.

**Comment by glwagner** [comment]
Does it need to be stored?

**Comment by ali-ramadhan** [comment]
Ah good point, I meant it can be part of the `PoissonSolver` constructor.

A default value of `Sys.CPU_THREADS` (like FourierFlows.jl) seems like a good choice.

**Comment by glwagner** [comment]
Benchmark it!

**Comment by glwagner** [comment]
The number of threads for CPU FFTs is set by calling `FFTW.set_num_threads(nthreads)`.
