### ISSUE TITLE
Minimum time step for `TimeStepWizard`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1197]
Would be nice to be able to specify a minimum time step for the `TimeStepWizard`. For me the main use is to avoid "slow motion blowup" where a numerical instability causes the model to blow up but the time step wizard keeps decreasing the time step so it just blows up in slow motion when you want it to NaN and stop executing.

**Comment by tomchor** [comment]
I definitely second that. Just had the slow motion happen to me today and was looking for this feature!
