### ISSUE TITLE
Model constructor should check that inputs are named tuples.

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1204]
Some model constructor kwargs, e.g. `boundary_conditions` and `forcing` need to be named tuples otherwise things can silently fail (or fail in an obscure manner).

Would be nice if the model constructors threw an error if it expected a named tuple. Could just type the kwargs, e.g. `boundary_conditions::Union{Nothing,NamedTuple}` like we did for #1118.

cc @whitleyv

**Comment by glwagner** [comment]
Typing the kwargs seems like the simple, easy solution.
