### ISSUE TITLE
Cannot run examples within the Oceananigans environment

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1205]
I have been playing with the one_dimensional_diffusion.jl example and have found something a bit odd.

When I run it, with everything already installed, it seems to complain about [line18](https://github.com/CliMA/Oceananigans.jl/blob/a343711f1101b1a433124f5f9697ce60b1011a40/examples/one_dimensional_diffusion.jl#L18) with the following error,

```
ERROR: LoadError: package `Oceananigans [9e8cae18]` has same name or UUID as the active project
```

Is this expected?  

Is this something we want to avoid?

**Comment by ali-ramadhan** [comment]
Ah this might be because the example code was run inside the Oceananigans.jl git repository with `julia --project` so `pkg"add Oceananigans"` would fail...

I guess the examples were made to be run by a user (or without `--project`), not a developer.

Pretty sure there should be an easy way to fix this so they also work with `--project`.

**Comment by glwagner** [comment]
cc @navidcy

**Comment by navidcy** [comment]
Yes true...

Oh... I'm not sure still what's the best way. It's hard to make things automated for every possible scenario.

**Comment by johncmarshall54** [comment]
Greg and Ali, what's the status of the deep beta plane that blows up on
GPUs and not CPUs. Is this under control yet? I'd like to have the GPU
version available for obvious reasons. Have a good break, John

**Comment by francispoulin** [comment]
> Ah this might be because the example code was run inside the Oceananigans.jl git repository with `julia --project` so `pkg"add Oceananigans"` would fail...
> 
> I guess the examples were made to be run by a user (or without `--project`), not a developer.
> 
> Pretty sure there should be an easy way to fix this so they also work with `--project`.

Maybe adding a note saying something like this. 

Note that if you are using "julia --project" these inital commands may case problems and are not needed.

I don't think this is a problem that many/any people will come across.

P.S. Also sorry for the bad title.  When I first started I was having timestepping issues but figured that out, but forgot to change the title afterwards.  Will be more careful about that in the future.

**Comment by navidcy** [comment]
Should we close this? We added some remarks that hopefully help towards smoothing out the process in the examples.

**Comment by francispoulin** [comment]
Yes, happy to close those.
