### ISSUE TITLE
Running Oceananigans with 2 threads allocates the most memory

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1218]
Running with 2 threads is the worst memory-wise.

See benchmarks from https://github.com/CliMA/Oceananigans.jl/pull/1120#issuecomment-732516353 and similar results were reported by @francispoulin on a different machine from https://github.com/CliMA/Oceananigans.jl/pull/1210#issuecomment-734500922

Not sure if this is because of Oceananigans.jl or because of KernelAbstractions.jl

Multithreaded seems to allocate a ton of memory in general though.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
