### ISSUE TITLE
Upgrade to CUDA v2.3.0?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1220]
Manifest.toml restricts CUDA to v.1.3.3

https://github.com/CliMA/Oceananigans.jl/blob/4011a3431144c3a58671e5d827ab39da8fe6e948/Manifest.toml#L51

**Comment by ali-ramadhan** [comment]
Yeah that would be good to do.

I thought we were already on CUDA v2+ but looks like CompatHelper downgraded CUDA in https://github.com/CliMA/Oceananigans.jl/pull/1185 for some reason.
