### ISSUE TITLE
Unexpected behavior in NetCDF writer after upgrade to 0.44.2

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1227]
I have been exclusively using the netCDF output option and, after upgrading to v0.44.2, I've noticed the behavior of `NetCDFWriter` changed. 

- First thing is that I get a message that the mode hasn't been set even when it has, which seems like a bug to me. So, for example, setting the writer as 

```
using Oceananigans.OutputWriters

outputs_netcdf = (u = model.velocities.u,
                  v = model.velocities.v,
                 )

simulation.output_writers[:field_writer] =
    NetCDFOutputWriter(model, outputs_netcdf,
                       filepath = "mwe.nc",
                       schedule = TimeInterval(5seconds),
                       mode = "c")
```

I get a warning saying `mwe.nc already exists but no NetCDFOutputWriter mode was explicitly specified. Will default to mode = "a" to append to existing file.`, even though the mode is clearly set to clobber. And sure enough, if I run the simulation it appends to the previous netcdf file. (Also, the docs still say that the default mode is `"c"`, but it now changed to `"a"`).

- The other thing is that after I set up the `NetCDFWriter` the file is always open by the Julia REPL and unreachable from anywhere else. So for example if I want to check on the simulation by opening the output netcdf file with Python I get an error saying that the file is being used. So I need to either make a copy of the file and access the copy (which uses up space) or wait for the simulation to finish, which isn't ideal. I can't imagine opening and closing a netCDF file takes long (especially since we ideally won't write to it at every time step), so is there a reason for the netCDF file to always stay open inside Julia?

Thanks!

**Comment by ali-ramadhan** [comment]
Thanks for reporting this @tomchor!

For the first issue regarding `mode = "c"` not being respected, PR https://github.com/CliMA/Oceananigans.jl/pull/1219 should fix this issue. Just waiting for an approval so it can be merged, at which point I'll tag and release a new version.

For the second issue, we've changed the behavior a few times but I agree that keeping the NetCDF file open indefinitely is not good. Maybe a potential solution would be to open the file at the beginning of `run!(simulation)` then close the file at the end of `run!(simulation)`?

**Comment by tomchor** [comment]
I agree that creating the file when the simulation starts to run is better than the current behavior (I think right now it creates the file as soon as you create the netCDF writer, right?).

That still wouldn't allow one to access the file while the simulation is running though, right? I think that's important since we need to check the simulations, etc. Do you have any workarounds for that?

**Comment by ali-ramadhan** [comment]
> I agree that creating the file when the simulation starts to run is better than the current behavior (I think right now it creates the file as soon as you create the netCDF writer, right?).

Ah the NetCDF file will still be created when the `NetCDFOutputWriter` is constructed. There was an actual bug as you reported in that the `NetCDFOutputWriter` was not respecting the `mode` passed in.

> That still wouldn't allow one to access the file while the simulation is running though, right? I think that's important since we need to check the simulations, etc. Do you have any workarounds for that?

Yeah this would be good. I suppose the best we can do is open the NetCDF file right before output writing, then close it once output writing is done?

**Comment by tomchor** [comment]
>Ah the NetCDF file will still be created when the NetCDFOutputWriter is constructed. There was an actual bug as you reported in that the NetCDFOutputWriter was not respecting the mode passed in

Ah, sorry! I thought (from the title of the issue #1229) you were changing this behavior while also fixing the bug.

> Yeah this would be good. I suppose the best we can do is open the NetCDF file right before output writing, then close it once output writing is done?

From my point of view, yes (since I think opening and closing a netcdf file is a very small overhead). But I guess that should be discussed since I'm not sure what's going on behind the scenes.

**Comment by ali-ramadhan** [comment]
Awesome, I'll change the behavior in #1229 so it only opens the file as needed to write output.

Not sure what will happen if you open a file while the simulation is running (but not writing output) then try to access data while Oceananigans is writing output, but hopefully it'll all be well-behaved.

**Comment by tomchor** [comment]
That's a good point. Maybe oceananigans will fail when trying to write
output to a file that is already being accessed by another, which is a
problem. Maybe some testing/discussion is needed before implementing this?

**Comment by ali-ramadhan** [comment]
Hmmm yeah I can confirm that Oceananigans crashed with an HDF5 error when I purposely had a NetCDF file open as Oceananigans tried to open and write to it.

How do other models solve this issue?

For now I would be careful about opening NetCDF files for ongoing simulations. An easy solution is to copy the file to a temporary copy and analyze the copy.

A proper solution might involve figuring out how to use NCDatasets.jl to wait until file is free to open it (instead of just failing and throwing an error).

**Comment by glwagner** [comment]
@ali-ramadhan can you maybe summarize the problem? Sounds like there are some non-trivial trade-offs; eg opening and closing is expensive, so you don't want to do it often; but this optimization has downsides... ?
