### ISSUE TITLE
Do we need compat "^1.4" for OffsetArrays?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1233]
Compat for OffsetArrays is 

https://github.com/CliMA/Oceananigans.jl/blob/672fa9e06aa071360c0451404a1655ba37869b30/Project.toml#L37

Do we need greater than 1.4 so that we have https://github.com/JuliaArrays/OffsetArrays.jl/pull/59 ?

**Comment by ali-ramadhan** [comment]
Ah yes we need at least OffsetArrays v1.4!

**Comment by navidcy** [comment]
^1 includes 1.4 I think

**Comment by navidcy** [comment]
See, e.g., https://github.com/CliMA/Oceananigans.jl/blob/1b2efe5433ebc34257e4fbb56a8221106efafad5/Manifest.toml#L229-L233

**Comment by glwagner** [comment]
> ^1 includes 1.4 I think

I agree. However, ^1 also includes 1.3. But but this is incorrect, because Oceananigans will not work with OffsetArrays v1.3. The observation that 1.4 is permitted by a compat of ^1 does not resolve this issue.

**Comment by navidcy** [comment]
Indeed, what was I thinking? 🤔

Thanks for reopening.
