### ISSUE TITLE
Examples are NaNing out 😱

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1247]
Seems that examples are NaNing out while building documentation since PR #1198 was merged even though everything was fine for the latest Buildkite build on that PR: https://buildkite.com/clima/oceananigans/builds/649

Two failures on the same commit so it's a consistent issue:
https://buildkite.com/clima/oceananigans/builds/824
https://buildkite.com/clima/oceananigans/builds/830

I was able to reproduce locally as well.

Thankfully this is just master as PR #1198 was not part of v0.45.0.

Not sure how that happened but if this issue can't be fixed soon we should revert #1198.

**Comment by glwagner** [comment]
#1198 adds a NaN checker. Why does this _make_ the simulations NaN? I am confuzzled? 😕

**Comment by ali-ramadhan** [comment]
Same here... Examples are fine after reverting in PR #1248 but I also noticed that shallow water tests are passing in that PR but failing on master so that's pretty weird.

I'm pretty confused as well.

**Comment by glwagner** [comment]
Seems like the diagnostic is mutating the model state or something.

**Comment by ali-ramadhan** [comment]
Hmmm I wonder if this issue is actually due to #1254 (but with a NaN checker added we actually get errors).
