### ISSUE TITLE
Run simulation callback/progress function at iteration 0?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1250]
Right now the callback/progress function is only called for the first time when `iteration = iteration_interval` but I think we actually want to run the progress function at iteration 0 as it helps provide more feedback to the user at a time of heavy compilation.

This would help with #1013 and having output at iteration 0 tells the user that the simulation is starting to time step.

Sometimes when the terminal is blank for a while I'm not sure if Julia is still compiling or if I accidentally created a huge CPU model that's taking forever to take each time step.

**Comment by glwagner** [comment]
I think all the callbacks should be initialized at the beginning of run; this would be nice to add to part of the design spec in #1138.

**Comment by ali-ramadhan** [comment]
Added this issue to #1138 so I'll close now.
