### ISSUE TITLE
Time step should be updated before simulation callback/progress function

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1251]
So that we print the actual next time step in the simulation callback/progress function.

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Simulations/run.jl#L168-L170

**Comment by glwagner** [comment]
Ah, might be better just to add this to #1138 . Any fix for this would have to be fixed again when resolving #1138.

**Comment by ali-ramadhan** [comment]
Good idea. I'll close this issue and add a comment to #1138.
