### ISSUE TITLE
Definition of `length(grid)` is not consistent with Julia definition

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1253]
Seems like it should be `length(grid) = prod(size(grid))`. Maybe this is leftover from when the `extent` kwarg used to be called `length`. Perhaps we should define `extent(grid) = (grid.Lx, grid.Ly, grid.Lz)` to be consistent.

```julia
help?> length
search: length

  length(collection) -> Integer

  Return the number of elements in the collection.
```

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Grids/Grids.jl#L76

EDIT: `length(grid)` returning the number of grid points could confuse users while `length(grid)` returning the extent would confuse Julia users so maybe we should just not define it.

**Comment by glwagner** [comment]
Actually, I think `length(grid) = prod(size(grid))` is ok --- basically it returns the total DOF of your simulation, which is nice?

**Comment by navidcy** [comment]
Close this issue?

**Comment by glwagner** [comment]
Do we have `length(grid) = prod(size(grid))`?

**Comment by navidcy** [comment]
Nope.

**Comment by glwagner** [comment]
Let's close!
