### ISSUE TITLE
Taking a time step of 0 causes the model to NaN out

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1254]
This is because the right-hand-side of the pressure Poisson equation depends on 1/Δt so Δt=0 leads to an `Inf` source term:

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Solvers/solve_for_pressure.jl#L41

This wasn't an issue before since we never `time_step!(model, 0)` but now that the time step is aligned with output writing and simulation stop times, it's possible to end up calling `time_step!(model, 0)`:

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Simulations/run.jl#L159-L161

Not sure of the best solution to this but one possible solution is if calling `time_step!(model, 0)` causes it to return early without doing anything.

I added the "high priority" label to this issue since it can cause the output to contain `NaN` at the last time step, very undesirable for users.

**Comment by ali-ramadhan** [comment]
Hmmm maybe a better solution would be to break out of this loop if `model.clock.time == simulation.stop_time`

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Simulations/run.jl#L158-L166

but also print a warning if `time_step!(model, 0)` is called.

**Comment by glwagner** [comment]
Isn't it incorrect to choose dt=0 for the purpose of "aligning" a time step?

**Comment by ali-ramadhan** [comment]
It is.

The problem was that the simulation would keep chugging along for `iteration_interval` iterations no matter what. So when the simulation reaches the end as specified by `stop_time` it should stop, but instead it was completing the `iteration_interval` iterations which involved one or more Δt = 0 time steps since it's not supposed to go past `simulation.stop_time`.

PR #1255 causes the simulation to stop time stepping once `simulation.stop_time` is reached so it shouldn't choose Δt = 0 any more.

**Comment by glwagner** [comment]
Why was `dt=0`? User-specified?

**Comment by ali-ramadhan** [comment]
No, it was due to the alignment process but note that the time step is aligned with both output writing and the simulation stop time.

The simulation reached `simulation.stop_time` but it was forced to do more iterations in this loop (see below) so so the aligned time step turned out to be 0.

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Simulations/run.jl#L158-L166

Now the simulation won't end up in this situation anymore since it stops time stepping early if `simulation.stop_time` is reached.

**Comment by glwagner** [comment]
Oh. I didn't realize that the time-step was aligned with `simulation.stop_time`. I see then that the problem is intractable with the current "sub iterations" design.

This problem is avoided by the design proposed in #1138.
