### ISSUE TITLE
The Great Debate: NetCDF vs JLD2

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1261]
Not sure this issue will ever get closed.

**Comment by francispoulin** [comment]
I suppose there will always be someone on each camp.  Maybe the big question is do we want to maintian both options or push for one over the other?

Personally, I am in the NetCDF camp as I know it more and find it a bit more straightforward.

**Comment by vchuravy** [comment]
I am in the JLD2 camp since it has less dependencies and is easier to get working ;)

**Comment by ali-ramadhan** [comment]
Ah sorry not sure why I opened this issue now since it's seems worthwhile to continue developing and maintaining both the JLD2 and NetCDF output writers for the different camps.

The non-Julia and standardized nature of NetCDF might limit it's future capability but for Oceananigans that remains to be seen in my opinion.

The title of the issue might incorrectly suggest that Oceananigans development will continue with support for only one of the output writers.

The source of the debate might be unrelated to Oceananigans.jl itself so I'll close this issue now.
