### ISSUE TITLE
Tests fail because shallow water model with h=0 blows up when time stepped

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1262]
Not sure if the bug label is appropriate here but `ShallowWaterModel` is instantiated with uh = vh = h = 0 and the tendencies have 1/h terms in them so time stepping this "empty" shallow water model leads to blow up.

This is generally fine: if you time-step a nonsensical model it should blow up.

The issue is that we add a NaN checker by default (which will still be there in #1138) so the shallow water time stepping tests keep triggering the NaN checker and failing.

Should we just disable NaN checking for these tests by removing the NaN checker via `delete!(simulation.diagnostics, :nan_checker)`?

**Comment by francispoulin** [comment]
Can we isntead set h = 1?  Having a zero layer depth everywhere is very odd. Setting it to a non-zero constant should fix the bug, and it makes much more sense to me.
