### ISSUE TITLE
Warnings outputting with AveragedTimeScheduler when window is equal to interval

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1274]
Basically whenever I set a writer with `AveragedTimeInterval` where `interval` is the same as `window`, I get the following warnings:

```
┌ Warning: Returning a WindowedTimeAverage before the collection period is complete.
└ @ Oceananigans.OutputWriters ~/.julia/packages/Oceananigans/Mt2Rj/src/OutputWriters/windowed_time_average.jl:202
┌ Warning: Returning a WindowedTimeAverage before the collection period is complete.
└ @ Oceananigans.OutputWriters ~/.julia/packages/Oceananigans/Mt2Rj/src/OutputWriters/windowed_time_average.jl:202
```

The call I'm using is something like that:

```julia
simulation.output_writers[:averages] =
    NetCDFOutputWriter(model, outputs,
                       filepath = @sprintf("avg.%s.nc", simname),
                       schedule = AveragedTimeInterval(2seconds; window=2seconds, stride=1),
                      )
```

Note that if I change the schedule line to 

```julia
schedule = AveragedTimeInterval(2seconds; window=1.9seconds, stride=1),
```

The warning gets suppressed.

**Comment by glwagner** [comment]
@tomchor does this result occur with just one OutputWriter, or do you have more than one OutputWriter being used at the same time?

Averaging collection is finalized here:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/OutputWriters/windowed_time_average.jl#L179-L187

when `run_diagnostic!(wta::WindowedTimeAverage, model)` is called.

But the criterion that triggers output is

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/Utils/schedules.jl#L38-L52

I have to say I don't understand why we special case `time == schedule.previous_actuation_time + schedule.interval`, since `rem(time, schedule.interval)` should be 0 and the algorithm should still work. Or am I missing something? It does seem to assume that `0` is the initial time (we could avoid that maybe by saving the initial `model.clock.time`...)

**Comment by glwagner** [comment]
Anyways, I don't quite see it but that could be the issue. So we can try replacing

```julia
# Reset the "previous" interval time, subtracting a sliver that presents overshoot from accumulating. 
wta.schedule.previous_interval_stop_time = model.clock.time - rem(model.clock.time, wta.schedule.interval) 
```

with

```juila
if model.clock.time == wta.schedule.previous_interval_stop_time + wta.schedule.interval
    wta.schedule.previous_interval_stop_time = model.clock.time
else
    # Reset the "previous" interval time, subtracting a sliver that presents overshoot from accumulating. 
     wta.schedule.previous_interval_stop_time = model.clock.time - rem(model.clock.time, wta.schedule.interval)
end
```

Another possible solution is to have a different algorithm in which time-averaging is "finalized" when output is retrieved:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/OutputWriters/windowed_time_average.jl#L197-L205

**Comment by tomchor** [comment]
> @tomchor does this result occur with just one OutputWriter, or do you have more than one OutputWriter being used at the same time?

I had two! (Sorry, I didn't think that made a difference.)
One was set for 1hour and the other (that gave me the warnings) was set for 20minutes.

**Comment by glwagner** [comment]
> I had two! (Sorry, I didn't think that made a difference.)

I don't know if it matters, but @ali-ramadhan changed the way output writing works so the time-step is "aligned" for output. It could affect whats happening but I'm not sure...

**Comment by navidcy** [comment]
I'm wondering whether this was taken care of.

**Comment by glwagner** [comment]
I don't think so but I'm not 100% sure. We should test that the warning isn't generated --- it really shouldn't be (`window=interval` is the default after all...)

**Comment by tomchor** [comment]
Just tested this and apparently the warning isn't issued anymore. However, no warning is issued now even when `window > inertval`:

```julia
julia> using Oceananigans

julia> using Oceananigans.Utils

julia> using Oceananigans.Units

julia> grid = RegularRectilinearGrid(size=(4, 4, 4), x=(0, 1e6), y=(0, 1e6), z=(-4e3, 0))
RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 1.0e6], y ∈ [0.0, 1.0e6], z ∈ [-4000.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (4, 4, 4)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (250000.0, 250000.0, 1000.0)

julia> model = IncompressibleModel(
                  architecture = CPU(),
                          grid = grid,
       )
IncompressibleModel{CPU, Float64}(time = 0 seconds, iteration = 0) 
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=4, Ny=4, Nz=4)
├── tracers: (:T, :S)
├── closure: Nothing
├── buoyancy: SeawaterBuoyancy{Float64, LinearEquationOfState{Float64}, Nothing, Nothing}
└── coriolis: Nothing

julia> Δt = 20minutes
1200.0

julia> simulation = Simulation(model, Δt = Δt, iteration_interval = 20,
                                      stop_time = 3days)
Simulation{typename(IncompressibleModel){typename(CPU), Float64}}
├── Model clock: time = 0 seconds, iteration = 0 
├── Next time step (Float64): 20 minutes 
├── Iteration interval: 20
├── Stop criteria: Any[Oceananigans.Simulations.iteration_limit_exceeded, Oceananigans.Simulations.stop_time_exceeded, Oceananigans.Simulations.wall_time_limit_exceeded]
├── Run time: 0 seconds, wall time limit: Inf
├── Stop time: 3 days, stop iteration: Inf
├── Diagnostics: typename(OrderedCollections.OrderedDict) with 1 entry:
│   └── nan_checker => typename(NaNChecker)
└── Output writers: typename(OrderedCollections.OrderedDict) with no entries

julia> u, v, w = model.velocities; # unpack velocity `Field`s

julia> outputs = (u=u, v=v, w=w);

julia> using Oceananigans.OutputWriters: NetCDFOutputWriter, AveragedTimeInterval

julia> simulation.output_writers[:avg] = NetCDFOutputWriter(model, outputs,
                                                               schedule = AveragedTimeInterval(10Δt; window=11Δt),
                                                               filepath = "avg.nc",
                                                               mode = "c")
NetCDFOutputWriter scheduled on TimeInterval(3.333 hours):
├── filepath: avg.nc
├── dimensions: zC(4), zF(5), xC(4), yF(4), xF(4), yC(4), time(0)
├── 3 outputs: ["v", "w", "u"] averaged on AveragedTimeInterval(window=3.667 hours, stride=1, interval=3.333 hours)
├── field slicer: FieldSlicer(:, :, :, with_halos=false)
└── array type: Array{Float32}

julia> run!(simulation)
[ Info: Simulation is stopping. Model time 3 days has hit or exceeded simulation stop time 3 days.
```

**Comment by glwagner** [comment]
Ok, let's throw a warning in the constructor for that case. Is that the new topic of this issue?

**Comment by glwagner** [comment]
I think when the window is bigger than the interval the result is identical to the case that window=interval. Basically the algorithm starts averaging whenever the model time is greater than `end_of_next_interval - window`.
