### ISSUE TITLE
Use 0 default viscosity and diffusivity in `IsotropicDiffusivity`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1278]
`IsotropicDiffusivity` currently uses a viscosity and thermal diffusivity appropriate for water at 20 degrees Celsius and 35 psu:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/TurbulenceClosures/turbulence_closure_implementations/isotropic_diffusivity.jl#L11-L28

When I put this in I originally thought it was positive because it provided a reference. It's also cute because its "oceanic".

But as time has gone on I now fear its actually surprising and also not very useful, since it's not actually a common to use Oceananigans for direct numerical simulations of miniscule boxes with molecular transport coefficients. Instead, `IsotropicDiffusivity` is useful for 1) idealized problems, education, examples and 2) as a simple turbulence closure when setting up a simulation / testing ideas, possibly prior to implementing a more complicated closure. This "ocean-realistic" default is inconvenient for either case.

So, I propose changing the default for both the viscosity and diffusivity to 0.

cc @tomchor @xiaozhour

**Comment by tomchor** [comment]
I agree with your arguments. However, if I understood correctly, my only
concern (as a user) is that if you set them to zero by default,
setting `closure=IsotropicDiffusivity()` in a model will create a
simulation that will have no diffusivities and most likely will crash. From
a user perspective that's not the expected behavior I think, right?

**Comment by glwagner** [comment]
> my only
concern (as a user) is that if you set them to zero by default,
setting `closure=IsotropicDiffusivity()` in a model will create a
simulation that will have no diffusivities and most likely will crash. From
a user perspective that's not the expected behavior I think, right?

This is definitely the right way to think about it!

I guess with this default, `closure=IsotropicDiffusivity()` is equivalent to `closure = nothing`.

Note we _can_ run "inviscid" simulations. They don't always blow up if the time-step is small enough (even when the advection scheme conserved variances...) For example some of the work over at https://github.com/CliMA/GeophysicalDissipation.jl

We could just use 0 default for kappa and require nu. This is convenient for simulations with no tracers that don't need kappa. Then the idea I guess is that if you're using `IsotropicDiffusivity`, you have to at least specify `nu` or you get an error (rather than being able to run a model in which you don't know what the explicit dissipation model is).

**Comment by tomchor** [comment]
I agree that that approach is better.

(Interesting work with GeophysicalDissipation, btw.)

**Comment by xiaozhour** [comment]
Sorry to be late on this -- I would vote for explicitly asking for user input of kappa and nu ...

**Comment by glwagner** [comment]
One reason to have the default `kappa=0` is so that users don't have to specify `kappa` when they are running problems with no tracers.

**Comment by tomchor** [comment]
I agree with @glwagner that using a Prandtl number will lead to some unnecessary extra documentation. I also prefer working directly with κ. I also think that always requiring the user to specify κ is kinda weird when one is trying to run a simulation without tracers. With these things in mind, setting κ=0 as the default would be a reasonable choice.
