### ISSUE TITLE
Aborted (core dumped) on tutorial

### ISSUE THREAD

**Issue by drozzy** [CliMA/Oceananigans.jl#1281]
I'm trying to follow the [tutorial here](https://clima.github.io/OceananigansDocumentation/stable/generated/one_dimensional_diffusion/) using vscode (connected via remote-ssh to ubuntu machine).

However, I consistently get errors below (and `@animate` step doesn't finish): 
```
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

```

**Comment by navidcy** [comment]
1) Why not try locally? (Just a suggestion; don’t really need answer. Probably you have a compelling reason..)

2) Try calling `ENV["GKSwstype"] = "100"`
I’m not sure this will do the job for your issue — hopefully it will. This might disable figures from plotting up on the display but savefig and animate will still work and you should see output gifs/pngs...

**Comment by glwagner** [comment]
As @navidcy I think the difficulties here are using `Plots.jl` on a headless system.

To address this issue @navidcy is suggesting that you execute / write `ENV["GKSwstype"] = "100"` at the top of the tutorial.

Alternatively, you can avoid remote plotting and attempt to run the `@animate` block locally, after downloading the data. I do think it is convenient to plot remotely however, so it'd be nice if you can make that work for you.

Searching "headless plotting julia Plots" might turn up more information (I didn't find anything immediately, but I've seen useful threads before and it'd be nice to paste them here).

**Comment by drozzy** [comment]
My bad, it was remote-ssh in vscode acting up. For some reason it just stopping plotting full-size graphs and started giving me these errors.
Doing things locally Oceananigans works perfectly.
