### ISSUE TITLE
ShallowWaterModel needs more options

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1284]
Since IncompressibleModel accepts both `float_type` and `timestepper`, ShallowWaterModel should as well.  It should be an easy fix.  While I'm at it I should also introduce tracers.

**Comment by glwagner** [comment]
Note, we got rid of the `float_type` kwarg because it only affected the float type of the clock. The float type really has to be set when constructing the grid. We should probably remove `float_type` for `IncompressibleModel`.

**Comment by francispoulin** [comment]
Thanks and I agree. 

Did you want to keep this open until `float_type` is removed from `IncompressibleModel`?

**Comment by glwagner** [comment]
No... we should have a separate issue for that.

**Comment by glwagner** [comment]
oops, didn't mean to close

**Comment by francispoulin** [comment]
Okay. I guess I will leave this open until the PR gets merged into master.
