### ISSUE TITLE
ERROR: importing Flux into Main conflicts with an existing identifier

### ISSUE THREAD

**Issue by drozzy** [CliMA/Oceananigans.jl#1285]
Flux.jl is a pretty popular package. It seems Oceananigans conflicts with it.
If I do `using Flux` I get:
```
ERROR: importing Flux into Main conflicts with an existing identifier
```
Is there any way to import both?

**Comment by ali-ramadhan** [comment]
Ah yes exporting the `Flux` boundary condition type would conflict with Flux.jl. Resolving #1140 would fix this issue but for now, a possible approach/solution would be to explicitly use what you need from one package.

For example, if you use more stuff from Flux you could do

```julia
using Flux
using Oceananigans: A, B, C
```

or if you use Oceananigans stuff more than Flux you could do

```julia
using Oceananigans
using Flux: A, B, C
```

**Comment by drozzy** [comment]
Cool thanks. 
What's the difference between `using Flux: σ` and `import Flux: σ`?

**Comment by ali-ramadhan** [comment]
The Julia docs go into a lot of detail and have a useful summary (https://docs.julialang.org/en/v1.5/manual/modules/#Summary-of-module-usage-1) but I think `import` is used with the intention of extending a method via multiple dispatch.

So you would `import Flux: σ` if you wanted to define a new method for `σ`, e.g. if you wanted to define a custom `σ(x::Complex)`.

**Comment by drozzy** [comment]
Thanks
