### ISSUE TITLE
about Halo point

### ISSUE THREAD

**Issue by tomtomtomtony** [CliMA/Oceananigans.jl#1286]
I try to search for some materials about Halo point in this packages, Could you give me more hints?

**Comment by ali-ramadhan** [comment]
@tomtomtomtony What are you trying to understand?

I think ideally as a user you shouldn't have to worry about halo regions but we're not quite there yet...

This section of the documentation explains how the halo regions are used to enforce difference boundary conditions: https://clima.github.io/OceananigansDocumentation/stable/numerical_implementation/boundary_conditions/

The `fill_halo_regions*.jl` files under `Oceananigans.BoundaryConditions` contain the implementations: https://github.com/CliMA/Oceananigans.jl/tree/master/src/BoundaryConditions

**Comment by ali-ramadhan** [comment]
@tomtomtomtony I'm going to close this issue but please feel free to reopen if this didn't answer your question.
