### ISSUE TITLE
"NaN error in u" when trying to simulate open-ocean convection problem

### ISSUE THREAD

**Issue by Sumanshekhar17** [CliMA/Oceananigans.jl#1289]
```julia
using Printf
using Plots
using JLD2

using Oceananigans
using Oceananigans.Utils

using Oceananigans.Grids: nodes
using Oceananigans.Diagnostics: FieldMaximum
using Oceananigans.OutputWriters: JLD2OutputWriter, FieldSlicer, TimeInterval

grid = RegularCartesianGrid(size=(256, 256, 64), extent=(4, 4, 0.1))

buoyancy = SeawaterBuoyancy(equation_of_state=LinearEquationOfState(α=2e-4, β=0))

H=0.1 #dimension in vertical direction
W=4 #dimension in south-north direction
L=4 #dimension in east-west direction
Ra=1e9 #rayleigh number
Ro=0.24  #Horizontal Rossby number
v=2e-6 #diffusive viscocity
k=1e-6 #diffusivity 
l=W/2  #center of gaussian field
m=L/2  #center of gausian field

Bo=0.72e-4 #maximum surface flux

fo=0.5 #coriolis parameter

beta=3.75e-3

#Surface forcing
heat_flux(x,y,t) = Bo*exp(-0.5*((x-l)^2+(y-m)^2))

dTdz = 0 # K m⁻¹

T_bcs = TracerBoundaryConditions(grid,
                                 top = BoundaryCondition(Flux, heat_flux),
                                 bottom = BoundaryCondition(Gradient, dTdz))

#velocity boundary condition
u₁₀ = 1.0e-1     # m s⁻¹, average wind velocity 10 meters above the ocean
cᴰ = 2.5e-3  # dimensionless drag coefficient
ρₐ = 1.225   # kg m⁻³, average density of air at sea-level
ρₒ = 1026 # kg m⁻³, average density at the surface of the world ocean
Qᵘ = - ρₐ / ρₒ * cᴰ * u₁₀ * abs(u₁₀) # m² s⁻²

u_bcs = UVelocityBoundaryConditions(grid, top = BoundaryCondition(Flux, Qᵘ), bottom=ValueBoundaryCondition(0.0))
v_bcs = VVelocityBoundaryConditions(grid, top = BoundaryCondition(Flux, Qᵘ), bottom=ValueBoundaryCondition(0.0))
w_bcs = WVelocityBoundaryConditions(grid, top = ValueBoundaryCondition(0.0), bottom=ValueBoundaryCondition(0.0))

#Incompressible model initiation 
model = IncompressibleModel(architecture = CPU(),
                            timestepper = :RungeKutta3,
                            grid = grid,
                            coriolis = BetaPlane(f₀=fo, β=beta),
                            buoyancy = buoyancy,
                            closure = IsotropicDiffusivity(ν=v, κ=k),
                            boundary_conditions = (u=u_bcs, v=v_bcs, w=w_bcs, T=T_bcs))

# Random noise damped at top and bottom
Ξ(z) = randn() * z / model.grid.Lz * (1 + z / model.grid.Lz) # noise

# Temperature initial condition: a stable density gradient with random noise superposed.
Tᵢ(x, y, z) = 20 + dTdz * z + dTdz * model.grid.Lz * 1e-6 * Ξ(z)

# Velocity initial condition: random noise scaled by the friction velocity.
uᵢ(x, y, z) = sqrt(abs(Qᵘ)) * 1e-4 * Ξ(z)

# `set!` the `model` fields using functions or constants:
set!(model, u=uᵢ, v=uᵢ, w=uᵢ, T=Tᵢ)

wizard = TimeStepWizard(cfl=0.3, Δt=0.10, max_change=1.1, max_Δt=0.1minute)

wmax = FieldMaximum(abs, model.velocities.w)
umax = FieldMaximum(abs, model.velocities.u)
vmax = FieldMaximum(abs, model.velocities.v)


start_time = time_ns() # so we can print the total elapsed wall time

# Print a progress message
progress_message(sim) =
    @printf("i: %04d, t: %s, Δt: %s, wmax = %.1e ms⁻¹, umax = %.1e ms⁻¹, vmax = %.1e ms⁻¹, wall time: %s\n",
            sim.model.clock.iteration, prettytime(model.clock.time),
            prettytime(wizard.Δt), wmax(sim.model),umax(sim.model), vmax(sim.model),
            prettytime((time_ns() - start_time) * 1e-9))

simulation = Simulation(model, Δt=wizard, stop_time=10minutes, iteration_interval=10,
                        progress=progress_message)

simulation.output_writers[:fields] =
    JLD2OutputWriter(model, merge(model.velocities, model.tracers),
                           prefix = "open_ocean_convection2",
                         schedule = TimeInterval(0.2minute),
                            force = true)

run!(simulation)
```

**Comment by ali-ramadhan** [comment]
Hi @Sumanshekhar17, I couldn't immediately see the difference between your script and the "ocean wind mixing and convection" example but your script seems fine so I tried running it and it time-stepped with no errors with Julia 1.5 and Oceananigans v0.45.2.

![image](https://user-images.githubusercontent.com/20099589/103768518-a5f56400-4ff0-11eb-8cab-596d0b00e7a8.png)

Can you post more details about your issue and the error you're encountering? Full stacktrace + error would be helpful.

Would also be helpful to post the status of your Julia environment including your Julia version and the version of Julia you're using. You can do this with the `Pkg.status()` command: https://julialang.github.io/Pkg.jl/v1/repl/#repl-status

When posting code on GitHub it's always good to enclose the code in triple backticks (```) so it gets formatted as Julia code making it easier to read. I edited your post to do this.

It would also be good to keep the title short and concise if you can. You can always include more details in the comment.

**Comment by Sumanshekhar17** [comment]
Thank you very much for your reply sir, I am new to this community pardon me, I will take care from next time.

Sir this the status of Julia package-
![julia package](https://user-images.githubusercontent.com/67187927/103770697-71af9100-504c-11eb-991e-f22d2239efeb.PNG)

Sir I have Gaussian surface cooling function at the top of the surface and Beta plane approximation in my code with different grid size and spacing  and rest initial and boundary conditions are same. The following error come after 720 iteration-

![error1](https://user-images.githubusercontent.com/67187927/103771251-5ee98c00-504d-11eb-8a07-5395c6d1d74a.PNG)
   
I have also checked my CFL number by changing but this error remains and appear after some iteration. 

Thank you in advance!

**Comment by ali-ramadhan** [comment]
What are you trying to simulate?

It looks like you're trying to simulate a Gaussian surface cooling in a tiny 4 x 4 x 0.1 m box with a Coriolis parameter of f = 0.5 and beta = 3.75e-3?

Not sure if it makes sense to use a beta plane approximation on a domain that's only 4 meters long...

**Comment by Sumanshekhar17** [comment]
Sir actually I am trying to simulate a result that was given in a research paper. there they have used DNS and MOM6 both but they didn't specify the domain size for DNS , they only specified it for MOM6 that was (200km, 200km, 4km). As I am using LES here I took it as small. 
second is that in the paper they didn't mention the initial conditions and velocity boundary condition at the surface. so I took exactly the same boundary condition of u,v,w and initial condition that was in the "ocean wind mixing and convection" example. 
Sir by lowering the CFL number I increased the iteration but the session got killed I don't know why.
This also happened when I tried to refine the mesh and then simulate.

![iter2cfl_0 1](https://user-images.githubusercontent.com/67187927/103879663-2d7cc900-50fe-11eb-8f3b-622e46590350.PNG)

**Comment by glwagner** [comment]
I don't follow everything here but it looks like the simulation is being performed on a login node in the above screenshot. @Sumanshekhar17, your cluster may have a policy in place to stop ("kill") jobs that run on a login node.

To sort out script vs cluster issues I suggest running the script on your laptop first. If it runs to completion, and also starts and runs on the cluster with `architecture=GPU()`, then we know the problem is due to cluster policy or some other cluster-specific setting, rather than a problem with your script or Oceananigans.
