### ISSUE TITLE
Trying to calculate Richardson number using GPU kernel is failing at the bottom boundary

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1290]
So, I'm trying to create a kernel to calculate the Richardson number on GPUs and I'm basing myself off of LESbrary.jl. I have already implemented a calculation of the Rossby number in the same fashion and it seems to work, but for some reason I'm running into some trouble with the Richardson number.

Here's my code:

```julia
struct RichardsonNumber{A, G, U, V, B, Uz_bg, Vz_bg, N2_bg} <: AbstractField{Cell, Cell, Face, A, G}
    data :: A
    grid :: G
    u :: U
    v :: V
    b :: B
    dUdz :: Uz_bg
    dVdz :: Vz_bg
    N2 :: N2_bg
end

"""
    RichardsonNumber(model)

Returns an `AbstractField` representing the Richardson number of `model`.

Calling `compute!(Rich::RichardsonNumber)` computes the Richardson number
associated with `model` and stores it in `Rich.data`.
"""
function RichardsonNumber(model; data = nothing,
                          N²_bg = 0, dUdz_bg = 0, dVdz_bg = 0)

    if isnothing(data)
        data = new_data(model.architecture, model.grid, (Cell, Cell, Face))
    end

    u, v, w = model.velocities
    b = model.tracers.b

    return RichardsonNumber(data, model.grid, u, v, b, dUdz_bg, dVdz_bg, N²_bg)
end


function compute!(Rich::RichardsonNumber)

    arch = architecture(Rich.data)

    workgroup, worksize = work_layout(Rich.grid, :xyz, location=(Cell, Cell, Face))

    compute_kernel! = compute_richardson_number!(device(arch), workgroup, worksize)

    event = compute_kernel!(Rich.data, Rich.grid,
                            Rich.u, Rich.v, Rich.b,
                            Rich.dUdz, Rich.dVdz, Rich.N2; dependencies=Event(device(arch)))

    wait(device(arch), event)

    return nothing
end

@kernel function compute_richardson_number!(Ri, grid, u, v, b, Uz, Vz, N2)
    i, j, k = @index(Global, NTuple)

    #dBdz = ∂zᵃᵃᶠ(i, j, k, grid, b) + N2 # dbdz(c, c, f)
    #dUdz_tot = ℑxᶜᵃᵃ(i, j, k, grid, ∂zᵃᵃᶠ, u) + Uz # dudz(f, c, f) => dudz(c, c, f)
    #dVdz_tot = ℑyᵃᶜᵃ(i, j, k, grid, ∂zᵃᵃᶠ, v) + Vz # dvdz(c, f, f) => dvdz(c, c, f)

    #@inbounds Ri[i, j, k] = dBdz / (dUdz_tot^2 + dVdz_tot^2)
    @inbounds Ri[i, j, k] = N2 / (Uz^2 + Vz^2)
end
```

So, note that, as a test, I'm using using `N2`, `Uz` and `Vz` in the actual calculation at the end. These are all constants (background stratification and shear) and the value of Ri should be exactly `1` at end. However, this is what I'm getting (I'm showing a horizontal average of a time step):

```python
<xarray.DataArray 'Ri' (zF: 17)>
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])
Coordinates:
  * zF       (zF) float64 -100.0 -87.5 -75.0 -62.5 ... 62.5 75.0 87.5 100.0
    xC       float64 7.812
    xF       float64 0.0
    time     float64 600.0
```

For those unfamiliar with xarray, the output is `1` everywhere (good!) except at the upper boundary, where for some reason it is zero (bad!). Since I'm only using constants to calculate this, it seems to me that, for some reason, the corresponding `k` isn't being calculated at all. 

Any ideas of how I might fix this?

Thanks!

**Comment by ali-ramadhan** [comment]
Thanks for the detailed writeup! Was super helpful in understanding the problem.

Looks like you specified the `location` but I'm thinking you might just need to specify `include_right_boundaries=true` when calling `work_layout` (#908 has more details about this).

From the docstring: https://github.com/CliMA/Oceananigans.jl/blob/6e78edf957d49dc01a4d3f3785cf3a431e2ae599/src/Utils/kernel_launching.jl#L19-L21

**Comment by tomchor** [comment]
@ali-ramadhan thanks that seems to have worked! Could you please explain the need for that flag? When calculating the Rossby number (which is just horizontal derivatives) that doesn't seem to be needed. My first guess would be to include it whenever vertical derivatives are being taken, but none of the LESbrary.jl scripts seem to need that (not even the ones with vertical derivatives).

**Comment by glwagner** [comment]
It's needed when your computation is located on `Face`s. By default, `work_layout` returns a layout that extends from "1 to `N`". This default is used for time-stepping kernels. But for diagnostics you usually want that last grid point at `N+1`.

It might make sense to change the default value, since users / people writing new kernels probably want `include_right_boundaries=true`, and its only a minority of rarely-changed kernels (for time-stepping) that want `include_right_boundaries=false`.

**Comment by glwagner** [comment]
See `work_layout` here:

https://github.com/CliMA/Oceananigans.jl/blob/6e78edf957d49dc01a4d3f3785cf3a431e2ae599/src/Utils/kernel_launching.jl#L12-L55

**Comment by tomchor** [comment]
> It's needed when your computation is located on Faces

But in that case wouldn't kernels like the [shear production calculation](https://github.com/CliMA/LESbrary.jl/blob/master/src/TurbulenceStatistics/shear_production.jl) need that flag to be true also? It seems that none of the kernels in the LESbrary.jl repo has it.

**Comment by glwagner** [comment]
The shear production term is located at cell centers:

https://github.com/CliMA/LESbrary.jl/blob/8d17a94f91c86f55b029ee310762c567d607191e/src/TurbulenceStatistics/shear_production.jl#L1

because we've chosen to evaluate the TKE budget at cell centers.

**Comment by tomchor** [comment]
Then I think this might be a misunderstanding on my part of how the `ℑ` operators work. For example in the following calls

https://github.com/CliMA/LESbrary.jl/blob/8d17a94f91c86f55b029ee310762c567d607191e/src/TurbulenceStatistics/shear_production.jl#L51-L59

I thought when calculating, for example `ℑzᵃᵃᶜ(i, j, k, grid, w∂zΨ, w, U)` this is what was happening:

- w dU/dz was calculated at `(Cell, Cell, Face)` via `w[i, j, k] * ∂zᵃᵃᶠ(i, j, k, grid, Ψ)`
  - Actually I'm a little fuzzy on this one since from what I can tell `w` is located at `(Cell, Cell, Face)` but `∂z(U)` is located at `(Face, Cell, Face)`. So I must be missing something
- Only then this would be interpolated to `(Cell, Cell, Cell)` by the `ℑzᵃᵃᶜ(i, j, k, grid, w∂zΨ, w, U)` call.

What am I missing here?

Thanks!

**Comment by glwagner** [comment]
> but ∂z(U) is located at (Face, Cell, Face). So I must be missing something

`U` is a horizontal average, so has no horizontal location. Does that explain it?

**Comment by ali-ramadhan** [comment]
Not within scope for this issue of course but as part of supporting `Flat` topologies/dimensions, would it make sense to add a `Flat` or `Nothing` location for locations along `Flat` dimensions?

**Comment by tomchor** [comment]
> U is a horizontal average, so has no horizontal location. Does that explain it?

I think so. Thanks!

**Comment by glwagner** [comment]
> Not within scope for this issue of course but as part of supporting Flat topologies/dimensions, would it make sense to add a Flat or Nothing location for locations along Flat dimensions?

If I understand the suggestion correctly, we currently do this. See, for example, the implementation of `getindex` for `ReducedField`:

https://github.com/CliMA/Oceananigans.jl/blob/ab20c9cc97589842f71659dab18128491e6aa357/src/Fields/reduced_field.jl#L9-L28
