### ISSUE TITLE
Do Oceananigans and magnetohydrodynamics mix?

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1304]
In addition to studying problems in oceanography, I also investigate problems in solar physics.  Basically, the same equations as for the ocean but with magnetohydrodynamics.  After learning about Oceananigans, it would be very easy (and desirable for me) to add a model (sometime, not right away) that would solve the MHD Shallow Water Model.  This is something that I can see my students could use and benefit from.  However, this is not a pure ocean problem so it does not fit in terms of the physics.

**Question:** How would people feel about having an MHD model as part of Oceananigans?

If people agree that it doesn't fit, then I could learn to create another repo that piggy backs on Oceananigans, and that would be something that only I would be responsble to maintain.  Would this be an option for the Oceananigans group?

Any thoughts are welcome.

**Comment by francispoulin** [comment]
No reactions after a week.  I will take that to mean that no one is supportive of this, which is perfectly fine.  

Instead, I will build another repo that piggy backs on Oceananigans.  I have been told that @ali-ramadhan  did this with Atmosfoolery, or something, so will probably as him for help to get started.  When I get started that is.

**Comment by ali-ramadhan** [comment]
Ah sorry for the slow reply!

Yeah I think we've had some discussions about which models belong in Oceananigans and which don't. Some of that discussion might still be around in #605 and #1079.

A compressible atmospheric model was deemed outside the scope of Oceananigans so it's staying in a separate repo (Atmosfoolery.jl). Although if we add support for a compressible ocean than that part might belong in Oceananigans.jl?

MHD feels like it would also be outside the scope of *Ocean*anigans, unless we're modeling some super salty ocean on an icy moon that responds to the planetary magnetic field...?

Also an opportunity to come up with the most clever MHD package name!

**Comment by glwagner** [comment]
To add to @ali-ramadhan's point --- we've had some negative experiences with "mega" repositories / software packages that are designed to do many things at once. I think small, focused packages are easier to work with, develop, use, and explain to users. Oceananigans is already a bit of a megarepo --- so if anything, we might want to break it up, rather than glom on more stuff.

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan and @glwagner .  I agree with you completely.  It is important to be focused and clearly Oceananigans should focus on the Ocean, and Ocean related activities.  Now that I know I can import this repo into other repos, I am happy to piggy back on Oceananigans and have something else.  Maybe Magnetonanigans?  Still word smithing that.  

Thanks again for making Oceananigans happen as I know it's a great resouce and so happy to be able to learn from it and use it.
