### ISSUE TITLE
Adding background fields to perturbations fails when writing to NetCDF

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1308]
When creating a background field, I can add it to its respective perturbations to create a total field. However, this fails when writing to file. Here's a MWE:

```julia
using Oceananigans
using Oceananigans.AbstractOperations: compute!
using Oceananigans.Utils
using Oceananigans.OutputWriters

grid = RegularCartesianGrid(size=(16, 1, 16), extent=(1, 1, 1))

U(x, y, z, t) = 0.2 * z

model = IncompressibleModel(grid = grid, background_fields = (u=U,))

U_tot = model.background_fields.velocities.u + model.velocities.u

simulation = Simulation(model, Δt=2,
                        iteration_interval=5,
                        stop_iteration=5,)

outputs = (u = model.velocities.u, U_tot = U_tot,)
simulation.output_writers[:simple_output] = NetCDFOutputWriter(model, outputs,
                                                               filepath = "mwe.nc",
                                                               schedule = TimeInterval(20minutes),
                                                               mode = "c")
run!(simulation)
```

This fails in the last line with

> ERROR: LoadError: type BinaryOperation has no field data

Is this expected behavior? It would be very nice to be able to do this!

**Comment by ali-ramadhan** [comment]
Ah I think right now output writers know how to save a `ComputedField` to disk but not abstract operations like `BinaryOperation`.

So you might just need 

```julia
U_tot = ComputedField(model.background_fields.velocities.u + model.velocities.u)
```

**Comment by tomchor** [comment]
You're right! Sorry I missed this. Seems obvious in retrospect...

**Comment by ali-ramadhan** [comment]
I've made this mistake many times haha. Seems like it might be good to add a warning telling users they probably meant to pass in a `ComputedField` since the error isn't super useful and only shows up when you call `run!`.

**Comment by glwagner** [comment]
> I've made this mistake many times haha. Seems like it might be good to add a warning telling users they probably meant to pass in a ComputedField since the error isn't super useful and only shows up when you call run!.

We could limit the type of `values(outputs)` to callable objects and `AbstractField` ?

**Comment by ali-ramadhan** [comment]
That sounds like a better check that would generalize!

The `ComputedField` vs. `AbstractOperation` distinction could be a common enough mistake to warrant a user-friendly message.

**Comment by glwagner** [comment]
Something like

```julia
validate_output(name, output) = error("Output $name of type $(typeof(output)) is invalid!")
validate_output(name, ::Union(Base.Callable, AbstractField)) = nothing
validate_output(name, output::AbstractOperation) = error("Output $name is an AbstractOperation, which is invalid. You may have meant to use ComputedField($name).")
```
