### ISSUE TITLE
Linear Stability Calculator for `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1310]
Borrowing on previous code that a student and I wrote, I have created a julia code that will solve the linear stability problem for a Bickley Jet in the context fo the `ShallowWaterModel`.  It doesn't actually use Oceananigans at all, yet, but produces the followin four figures.

This is something that I plan to use to validate the growth rates in the nonlinear evolution of the Bickely jet in the `ShallowWaterModel`, but can easily be extended to other profiles and other models as well.

Is there any interest in integrating this in Oceananigans?

**Velocity and free-surface height of the basic state:**

![basic_state](https://user-images.githubusercontent.com/8239041/105401802-93844880-5bf4-11eb-8a7f-32878e09698c.png)

**Growth rates of the two most unstable modes:**

![growth_rates](https://user-images.githubusercontent.com/8239041/105401818-9717cf80-5bf4-11eb-9c12-79f755ce84ed.png)

**Plots of the 1D spatial strucutre of the most unstable mode:**

![modes_1D](https://user-images.githubusercontent.com/8239041/105401831-9bdc8380-5bf4-11eb-8226-c531129dc7ae.png)

**Plots of the 2D spatial strucutre of the most unstable mode:**

![modes_2d](https://user-images.githubusercontent.com/8239041/105401841-9da64700-5bf4-11eb-9cf6-c7efb9fce62e.png)

**Comment by navidcy** [comment]
It's interesting by itself! Why don't you share it in a GitHub repo at least; regardless whether it becomes part of Oceananigans.jl or not.

**Comment by ali-ramadhan** [comment]
I also agree with @navidcy. Would be great educational material as well.

If it uses `Oceananigans.ShallowWaterModel` then it could make a great example (akin to the Kelvin-Helmholtz stability example). But either way, as a notebook it makes for great educational material!

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan .  It doesn't use Oceananigams right now but if I could use Oceananigans to get the differentiation matrices for 2nd and 4th order dervivatives, that might be helpful.  That's if they are there for center differencing.

**Comment by glwagner** [comment]
We don't have matrices that correspond to 2nd or 4th order finite volume derivatives. It might be nice to write a new package to provide generic tools like that for finite volume or finite difference methods. There are packages out there for finite difference methods; could be worth searching around a bit.

**Comment by glwagner** [comment]
@francispoulin is this still an issue?

**Comment by francispoulin** [comment]
Nope, and sorry for not closing before.  Will do so now.
