### ISSUE TITLE
Extensive saving of model and simulation parameters in output metadata?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1313]
Right now the `NetCDFOutputWriter` saves some useful metadata (date, Julia version, Oceananigans version, schedule metadata) but this could be extended to saving model and simulation parameters (advection scheme, coriolis parameters, boundary condition parameters when possible, equation of state parameters, etc.).

This would be generally useful and reduce the burden to do this in other packages, e.g. LESbrary.jl.

This saving of metadata can easily be extended to work with `JLD2OutputWriter` as well.

**Comment by tomchor** [comment]
I can definitely vouch for this one. I think for most users (myself included) NetCDF output is still the primary output mode (primarily due to the possibility of using `xarray` for post-processing). So making it as self-contained as possible helps a lot. (I already do this manually with my scripts.)

**Comment by glwagner** [comment]
You might introduce a function `metadata(model_property, netcdf_file) = # something`. Then model properties like `coriolis::FPlane`, etc can define appropriate `metadata` methods. This could be used for both JLD2 and NetCDF, though its less crucial for JLD2 since the data can be serialized.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
