### ISSUE TITLE
Create two new advection schemes: `UpwindBiasedFirstOrder` and `CenterSixthOrder`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1320]
Given that the framework is set up already it should be easy to create each of these and add them to our collection.  

The only reason I can see for not creating them is that the number of advection schemes might be large.  Is this a concern?

**Comment by ali-ramadhan** [comment]
I'm not against a proliferation of advection schemes.

We should probably not merge new advection schemes without a convergence test though?

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan and I agree completely.

When I was working on the validation schemes I did test these schemes outside of Oceananigans and they did produce the correct slopes of -1 and -6.  Sixth order accuracy could actually be attractive for some applications.    Getting first order from upwinding may not sound llike much but it does ensure positivity, which might also be helpful for some cases where you want to ensure tracer concentrations are non-negative.

**Comment by glwagner** [comment]
We have these!
