### ISSUE TITLE
Unexpected behavior (bug?) when using background fields in AbstractOperations

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1323]
I'm trying to run a simulation with a geostrophic field that should be imposed as a background flow. In order to make the diagnostics easier I'm setting

```julia
    u_tot = ComputedField(u + U)
    b_tot = ComputedField(b + B)
```

But when I try to calculate some diagnostic fields (as depicted below) I get wrong results for the Richardson number specifically:

```julia
Ro_cons = -dudy / f0 # Constant (Float64)
Ri_cons = dbdz / dudz^2 # Constant (Float64)


Ro_abs = ComputedField(-∂y(u_tot) / f0)
Ri_abs =   ComputedField(∂z(b_tot) / (∂z(u_tot)^2))
dbdz_abs = ComputedField(∂z(b_tot))
dudz_abs =              ComputedField(∂z(u_tot))
Ri_abs2 =   ComputedField(dbdz_abs / dudz_abs^2)

compute!(Ro_abs) # Matches Ro_cons
compute!(Ri_abs) # Should match Ri_cons, but doesn't
compute!(Ri_abs2) # Should match Ri_cons, but doesn't
compute!(dbdz_abs) # Matches constant dbdz
compute!(dudz_abs) # Matches constant dudz
```

The ComputedFields should all match their constant counterparts in the example above, but `Ri_abs` and `Ri_abs2`. If I change my code and include the geostrophic jet as an IC, then `Ri_abs` appears to match, but `Ri_abs2` doesn't.

Is this expected behavior because I shouldn't be adding background fields to the perturbations? Am I missing something? Or is this a bug.

Here's [my MWE code](https://pastebin.com/dc16bAtX) in case someone wants to try this!

Output of `]st`:
```julia
  [052768ef] CUDA v2.4.1
  [9e8cae18] Oceananigans v0.46.0
  [91a5bcdd] Plots v1.10.2
  [10745b16] Statistics
```

**Comment by ali-ramadhan** [comment]
Hmmm, maybe more of a question for @glwagner but can you nest `ComputedField`s? I think I always passed an abstract operation to a `ComputedField`.

So I might try

```julia
u_tot = u + U
b_tot = b + B

Ro_abs = ComputedField(-∂y(u_tot) / f0)
Ri_abs = ComputedField(∂z(b_tot) / (∂z(u_tot)^2))
dbdz_abs = ComputedField(∂z(b_tot))
dudz_abs = ComputedField(∂z(u_tot))
Ri_abs2 = ComputedField(∂z(b_tot) / ∂z(u_tot)^2)
```

Otherwise might help to describe how `compute!(Ri_abs)` and `compute!(Ri_abs2)` are different from `Ri_cons`, e.g. is it completely wrong, factor of 2, only wrong at the boundary, etc.

**Comment by tomchor** [comment]
> Hmmm, maybe more of a question for @glwagner but can you nest ComputedFields (is it tested?)?

It appears you're right, that at least some of the problem comes from nested `ComputedField`s. (I need to run more tests later to be sure)

If nesting `ComputedField`s isn't allowed and can't be made to work, I'd suggest throwing an error if possible. However, nesting `ComputedField`s seems like a pretty useful feature to have. My talks with @glwagner over `KernelComputedField` lead me to believe that it's possible to make that work, no?

**Comment by glwagner** [comment]
Just to be precise: @ali-ramadhan is right that `ComputedField`s require `AbstractOperations`. So the question is whether `ComputedField`s can be used in `AbstractOperations`. We have _attempted_ to design the field infrastructure in this way (we'd like to use all types of fields, including `ComputedField`, `AveragedField`, and `KernelComputedField` in `AbstractOperations`)...

I think this issue is actually about `FunctionField` rather than `BackgroundField`. Here's some code:

```julia
grid = RegularCartesianGrid(size=(3, 3, 3), extent=(3, 3, 3))
model = IncompressibleModel(grid=grid, tracers=nothing, buoyancy=nothing, background_fields=(u=(x, y, z, t)->z,))
U = model.background_fields.velocities.u
```

This yields the output

```julia
FunctionField located at (Face, Center, Center)
├── func: #9
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
├── clock: Clock(time=0 seconds, iteration=0)
└── parameters: nothing
```

so `U` is an object called `FunctionField`: an `AbstractField` whose "data" consists of a function of `x, y, z, t`. Supposedly, `FunctionField`s can be used in `AbstractOperation`s:

```julia
julia> u = model.velocities.u

julia> u_total_operation = u + U
BinaryOperation at (Face, Center, Center)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
│   └── domain: x ∈ [0.0, 3.0], y ∈ [0.0, 3.0], z ∈ [-3.0, 0.0]
└── tree: 
    + at (Face, Center, Center) via identity
    ├── FunctionField located at (Face, Center, Center)
├── func: #5
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
├── clock: nothing
└── parameters: nothing
    └── FunctionField located at (Face, Center, Center)
├── func: #9
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
├── clock: Clock(time=0 seconds, iteration=0)
└── parameters: nothing
```

which can be inserted into `ComputedField`s:

```julia
julia> u_total = ComputedField(u + U)
ComputedField located at (Face, Center, Center) of BinaryOperation at (Face, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (5, 5, 5)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
├── operand: BinaryOperation at (Face, Center, Center)
└── status: time=0.0
```

I find that the vertical derivative of `u_total` is correct in the interior (away from halo regions)... but not correct adjacent to boundaries...

```julia
julia> using Oceananigans.AbstractOperations: ∂z

julia> using Oceananigans.Fields: compute!

julia> dudz_total = ComputedField(∂z(u_total))
ComputedField located at (Face, Center, Face) of Derivative at (Face, Center, Face)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (5, 5, 6)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=3, Ny=3, Nz=3)
├── operand: Derivative at (Face, Center, Face)
└── status: time=0.0

julia> compute!(dudz_total)

julia> dudz_total.data
5×5×6 OffsetArray(::Array{Float64,3}, 0:4, 0:4, 0:5) with eltype Float64 with indices 0:4×0:4×0:5:
[:, :, 0] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 1] =
 0.0   0.0   0.0   0.0  0.0
 0.0  -2.5  -2.5  -2.5  0.0
 0.0  -2.5  -2.5  -2.5  0.0
 0.0  -2.5  -2.5  -2.5  0.0
 0.0   0.0   0.0   0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.5  0.5  0.5  0.0
 0.0  0.5  0.5  0.5  0.0
 0.0  0.5  0.5  0.5  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 5] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
```

I need to think about why the result is wrong near boundaries. I feel this can be fixed.

@tomchor not sure this helps...

**Comment by tomchor** [comment]
> @tomchor not sure this helps...

Thanks for answer! I understand that apparently the issue is having a function in an `AbstractOperation`, right? I'm confused as to why this wasn't a problem in your example though (boundaries aside, of course).

My main question is: if this is indeed a limitation, is there any interest in improving/changing this in any way? From the point of view of a naive user like myself, it's odd that I can add two things without any error/warning, they get calculated normally, and then in the end the result is wrong.

**Comment by tomchor** [comment]
Also, for the record, I found out that a similar thing happens with `KernelComputedField` even without defining `u_tot` with `ComputedField`:

```julia
u_tot = u + U
b_tot = b + B

Ri = KernelComputedField(Center, Center, Face, compute_richardson_number!, model;
                         field_dependencies=(u_tot, v, b_tot, 0, 0, 0))

Ro = KernelComputedField(Face, Face, Center, compute_rossby_number!, model;
                         field_dependencies=(u_tot, v, 0, 0, model.coriolis.f))

PV = KernelComputedField(Center, Center, Face, compute_pv_from_Ro_Ri!, model;
                         field_dependencies=(Ri, Ro, dbdz, model.coriolis.f))
```

In the case above `Ri` and `Ro` get calculated correctly, but the result of `PV` is wrong. That doesn't happen if I use `u` instead of `u_tot`.

**Comment by glwagner** [comment]
Both `Function`s and `FunctionField`s are supposed to be supported in `AbstractOperation`s. In fact, supporting `Function`s in `AbstractOperations` is the original purpose of `FunctionField`. For example, see:

https://github.com/CliMA/Oceananigans.jl/blob/5ec4a7aa3d0ec054d1dc9fd369ca1b412109eae8/src/AbstractOperations/binary_operations.jl#L80-L82

Though I appreciate you may have tried to simplify your code from some original example to produce an MWE, I think it's still a bit complicated to diagnose the issue. I've shown that you can construct a `ComputedField` using a `Derivative` acting on a `BinaryOperation` between a concrete `Field` and `FunctionField`. What ingredient(s) do we need to add to my example to break it? What specifically is going wrong?

**Comment by glwagner** [comment]
I think your syntax is wrong for `KernelComputedField`, because `u_tot` is not an `AbstractField`, it is an `AbstractOperation`. Perhaps we should check that the elements of `field_dependencies` are `AbstractField`.

**Comment by glwagner** [comment]
I think it's definitely possible you've run across some kind of bug, I'm just having trouble figuring out what the bug might be because there's a lot going on in these examples. It might have to do with how `compute!` commands are propagated through an expression tree.

**Comment by tomchor** [comment]
> I think it's definitely possible you've run across some kind of bug, I'm just having trouble figuring out what the bug might be because there's a lot going on in these examples.

Got it! I'll try to simplify it more whenever I have time.

> I think your syntax is wrong for KernelComputedField, because u_tot is not an AbstractField, it is an AbstractOperation.

I'm passing `u_tot` as a field_dependency when calculating `Ro` and `Ri`, and those work fine! The PV calculation is the only that fails. Are you saying that `Ri` and `Ro` (and possibly `u_tot`?) should be passed with the `parameters` keyword?

**Comment by glwagner** [comment]
Well, this is interesting. I guess when we designed the interface for `KernelComputedField` I envisioned that `field_dependencies` would be a list of `AbstractField`s (hence the name). The point is that `compute!(element)` is called on every `element` of `field_dependencies`.

`u_tot` is not a field, its an `AbstractOperation`. The interesting thing is that `compute!(u_tot)` can actually do something, because `compute!` is _also_ defined for `AbstractOperations` (if `u_tot` has any `ComputedField`s in its tree, they get computed). This is a use case I didn't think of.

Other objects in `field_dependencies` (like integers, floating point numbers) are ok because there's a fallback `compute!(arbitrary_object) = nothing`. However, I don't like allowing this because it makes scripts confusing to read. An integer is an "integer dependency" (or just a "dependency") --- not a "field dependency".

**Comment by glwagner** [comment]
I think maybe you were interpreting "field dependency" as meaning "a dependency of `KernelComputedField`", rather than "a dependency that _itself_ is a field"... ? It's the latter definition that I was thinking of.

**Comment by glwagner** [comment]
There might be an issue with conditional computations but I'm not sure. For example, `ComputedField` has this `compute!` definition:

https://github.com/CliMA/Oceananigans.jl/blob/5ec4a7aa3d0ec054d1dc9fd369ca1b412109eae8/src/Fields/computed_field.jl#L61-L62

I think we want something similar; eg we want the `time` argument in `KernelComputedField`:

https://github.com/CliMA/Oceananigans.jl/blob/5ec4a7aa3d0ec054d1dc9fd369ca1b412109eae8/src/Fields/kernel_computed_field.jl#L76

and we want to use `compute_at!(dependency, time)` here:

https://github.com/CliMA/Oceananigans.jl/blob/5ec4a7aa3d0ec054d1dc9fd369ca1b412109eae8/src/Fields/kernel_computed_field.jl#L78-L80

**Comment by glwagner** [comment]
> In the case above Ri and Ro get calculated correctly, but the result of PV is wrong.

What is `dbdz`?

**Comment by tomchor** [comment]
I appreciate the help, Greg. There's a lot to go through here so let's go little by little.

@ali-ramadhan 's suggestion was right. Removing `ComputedField` from the definition of `u_tot` did the trick for my calculations. It seems that complexity is the limiting factor here. For example, this works

```julia
u_tot = ComputedField(u + U)
b_tot = ComputedField(b + B)

dbdz_abs = ComputedField(∂z(b_tot)) # Simple
dudz_abs = ComputedField(∂z(u_tot)) # Simple
Ri_abs2 = ComputedField(dbdz_abs/ dudz^2) # Try Ri again with but using other ComputedFields
compute!(Ri_abs2)
```

But trying to do all the calculations in one go fails for some reason:

```julia
u_tot = ComputedField(u + U)
b_tot = ComputedField(b + B)

Ri_abs = ComputedField(∂z(b_tot) / ∂z(u_tot)^2) # More complex
```

The above code computes something, but it's the wrong result. (Curiously the result it computes is numerically the same as the calculation of the Rossby number in the same script, which may be a clue.)

Here's my [Minimum Working Example](https://pastebin.com/v3hMpCWQ) made simpler. Hopefully it's easier to understand what's going on. There's a switch when defining `u_tot` to flip between an `AbstractOperation` definition and a `ComputedField` one.

I think this is interesting behavior, and it's kinda dangerous since it fails silently. Can you guys confirm that you can reproduce the behavior?

I think I'll open another issue for the `KernelComputedField` stuff since I think it's something different.

**Comment by glwagner** [comment]
Can you possibly paste this code into the REPL and post the output? We have defined `show` methods for a lot of these objects that may help. Printing out the `AbstractOperations` that are entered into the `ComputedField` might be especially helpful, because these show an expression tree that we can inspect.

**Comment by glwagner** [comment]
> Can you guys confirm that you can reproduce the behavior?

Can you post a single block of code or REPL session for us to use to reproduce the result?

**Comment by tomchor** [comment]
@glwagner Sorry, I missed these messages and just saw them now. I further inspected the code and it seems that the discrepancy comes from having one of the directions with `size=1`, simulating a `Flat` dimension. I'm not sure how worrisome this issue is given that you have PR https://github.com/CliMA/Oceananigans.jl/pull/1340, which may address this issue? 

So, for example, consider the code block below (btw, I'm sorry that my examples are large, but I don't quite know how to create fields with BCs very well without creating a model behind it...):

```julia
using Oceananigans
using Oceananigans.Utils
using Oceananigans.Fields


# Get simulation parameters
f0 = 1e-4
dudy = -1.25e-4
dudz = -4e-3
dbdz = 1e-5


#++++  GRID
topology = (Periodic, Bounded, Bounded)
grid = RegularCartesianGrid(size=(1, 4, 4), extent=(1000, 1000, 200),
                            topology=topology)


# Define our model!
u_g(x, y, z, t) = dudy * y + dudz * z
b_g(x, y, z, t) = dbdz * z
model = IncompressibleModel(architecture = CPU(),
                            grid = grid,
                            tracers = (:b,),
                            buoyancy = BuoyancyTracer(),
                            background_fields = (u=u_g, b=b_g,),
                            )


# START DIAGNOSTICS
import Oceananigans.Fields: ComputedField
using Oceananigans.AbstractOperations: @at, ∂x, ∂y, ∂z

u, v, w = model.velocities
b = model.tracers.b

U = model.background_fields.velocities.u
B = model.background_fields.tracers.b

u_tot = ComputedField(u + U)
b_tot = ComputedField(b + B)


# Get correct constant values
Ri_true = dbdz / dudz^2

# Abstract operations tests
Ri_abs = ComputedField(∂z(b_tot) / ∂z(u_tot)^2) # More complex

dbdz_abs = ComputedField(∂z(b_tot)) # Simple
dudz_abs = ComputedField(∂z(u_tot)) # Simple
Ri_abs2 = ComputedField(dbdz_abs/ dudz^2) # Try Ri again with but using other ComputedFields
 
compute!(Ri_abs)
compute!(Ri_abs2)
```

In the code above `Ri_abs2` gets calculated correctly, but `Ri_abs` does not:

```julia
julia> Ri_true
0.6250000000000001

julia> interior(Ri_abs2)
1×4×5 view(OffsetArray(::Array{Float64,3}, 0:2, 0:5, 0:6), 1:1, 1:4, 1:5) with eltype Float64:
[:, :, 1] =
 -2.1875  -2.1875  -2.1875  -2.1875

[:, :, 2] =
 0.625  0.625  0.625  0.625

[:, :, 3] =
 0.625  0.625  0.625  0.625

[:, :, 4] =
 0.625  0.625  0.625  0.625

[:, :, 5] =
 0.3125  0.3125  0.3125  0.3125

julia> interior(Ri_abs)
1×4×5 view(OffsetArray(::Array{Float64,3}, 0:2, 0:5, 0:6), 1:1, 1:4, 1:5) with eltype Float64:
[:, :, 1] =
 -0.373637  -0.410247  -0.452514  -0.501666

[:, :, 2] =
 1.25  1.25  1.25  1.25

[:, :, 3] =
 1.25  1.25  1.25  1.25

[:, :, 4] =
 1.25  1.25  1.25  1.25

[:, :, 5] =
 3.51166  8.85813  52.2449  284.444
```

This may be related to #1130, but then again there are no derivatives or interpolations at the boundary in the `x` direction (which is the one with size 1). However, when I change the `x` size from 1 to 2 (so `grid = RegularCartesianGrid(size=(2, 4, 4), ...`) I get a result for `Ri_abs` that looks better:

```julia
julia> interior(Ri_abs)
2×4×5 view(OffsetArray(::Array{Float64,3}, 0:3, 0:5, 0:6), 1:2, 1:4, 1:5) with eltype Float64:
[:, :, 1] =
 -0.186818  -0.205124  -0.226257  -0.250833
 -0.373637  -0.410247  -0.452514  -0.501666

[:, :, 2] =
 0.625  0.625  0.625  0.625
 1.25   1.25   1.25   1.25

[:, :, 3] =
 0.625  0.625  0.625  0.625
 1.25   1.25   1.25   1.25

[:, :, 4] =
 0.625  0.625  0.625  0.625
 1.25   1.25   1.25   1.25

[:, :, 5] =
 1.75583  4.42907  26.1224  142.222
 3.51166  8.85813  52.2449  284.444
```

Any thoughts?
