### ISSUE TITLE
Calculation of PV using KernelComputedField fails when interpolating one of the fields

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1324]
cc @glwagner 

When calculating PV from previously calculating fields, I get an error that comes from an interpolation I have to do. For example, this code, which I believe is the correct code, produces the wrong result:

```julia
using Oceananigans.Operators: ℑxyzᶜᶜᶠ
@kernel function compute_pv_from_Ro_Ri!(PV, grid, Ri, Ro, N², f₀)
    i, j, k = @index(Global, NTuple)

    Ro_int = ℑxyzᶜᶜᶠ(i, j, k, grid, Ro)

    @inbounds PV[i, j, k] = N²[i, j, k]*f₀ * (1 + Ro_int - 1/Ri[i, j, k])
end


Ri_kern = KernelComputedField(Center, Center, Face, compute_richardson_number!, model;
                         field_dependencies=(u_tot, v, b_tot, 0, 0, 0))

Ro_kern = KernelComputedField(Face, Face, Center, compute_rossby_number!, model;
                         field_dependencies=(u_tot, v, 0, 0, f0))

PV_kern = KernelComputedField(Center, Center, Face, compute_pv_from_Ro_Ri!, model;
                              field_dependencies=(Ri_kern, Ro_kern, N2_inf, f0))
```

In the above code, `f0`, `N2_inf` are constants and `u_tot` is an `AbstractOperation`. Ri and Ro get calculated correctly.

However, when I change the PV calculation so as to not interpolate, I get the correct result:

```julia
@kernel function compute_pv_from_Ro_Ri!(PV, grid, Ri, Ro, N², f₀)
    i, j, k = @index(Global, NTuple)

    @inbounds PV[i, j, k] = N²[i, j, k]*f₀ * (1 + Ro[i, j, k] - 1/Ri[i, j, k])
end
```

The code above produces the right numerical result (although it's "wrong" because I'd need to interpolate). This feels weird because `Ro` is constant everywhere, so interpolating it shouldn't make any difference.

Am I doing something wrong here? Also I'm attaching a [Minimum Working Example](https://pastebin.com/gH7CPNTA) just in case it's useful.

**Comment by glwagner** [comment]
How is the answer wrong when you don't interpolate `Ro`? Can you explain or show output from the REPL?

**Comment by glwagner** [comment]
As far as I can tell, the two examples can only be different if `Ro` is not constant -- unless there's a bug in `ℑxyzᶜᶜᶠ` that magically produces the right answer.

**Comment by tomchor** [comment]
I don't really know what's going on. Here's [another Minimum Working Example]() to reproduce what I'm about to post. Here's the output from the REPL:

```julia
julia> interior(PV_kern_int)
1×64×17 view(OffsetArray(::Array{Float64,3}, 0:2, 0:65, 0:18), 1:1, 1:64, 1:17) with eltype Float64:
[:, :, 1] =
 -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  …  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10

[:, :, 2] =
 2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  …  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11

[:, :, 3] =
 2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  …  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11

...

[:, :, 15] =
 2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  …  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11

[:, :, 16] =
 2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  …  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11  2.5e-11

[:, :, 17] =
 -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  …  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10  -2.875e-10

julia> interior(PV_kern_notint)
1×64×17 view(OffsetArray(::Array{Float64,3}, 0:2, 0:65, 0:18), 1:1, 1:64, 1:17) with eltype Float64:
[:, :, 1] =
 6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  …  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10

[:, :, 2] =
 6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  …  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10

[:, :, 3] =
 6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  …  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10

...

[:, :, 15] =
 6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  …  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10

[:, :, 16] =
 6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  …  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10  6.5e-10

[:, :, 17] =
 -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  …  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10  -6.0e-10

julia> PV_true
6.500000000000004e-10
```

So as you can see this doesn't look like a numerical error. I feel like I'm missing something kinda obvious here...

**Comment by glwagner** [comment]
This is a complicated example, it's not truly minimal!

You're using `Nx=1`, but there's still halo regions in x, which will be involved in interpolation. Can you print Ro at `i=0, 1, 2`?

**Comment by tomchor** [comment]
Thanks! You're right about the periodic condition and the halo region. Switching to a `8x8x8` did the trick! Although I would have thought that the interpolation routines appropriately calculated the fields at the periodic boundary. Is this expected behavior or a bug?

**Comment by glwagner** [comment]
It's a known issue: #1130 

We need boundary conditions for `ComputedField`s to interpolate correctly across the boundaries of the domain. I think it would be relatively easy to resolve #1130 by adding `ComputedField.boundary_conditions` with sensible defaults and `fill_halo_regions!` call in `compute!(field::ComputedField)` so we should do it.

**Comment by tomchor** [comment]
> It's a known issue: #1130

I see! Sorry I missed that. I'm open to collaborating on this issue. I think I'll close this issue though and we can work on the more fundamental issue #1130
