### ISSUE TITLE
Allow for computed fields diffusivities

### ISSUE THREAD

**Issue by sandreza** [CliMA/Oceananigans.jl#1327]
From https://github.com/CliMA/Oceananigans.jl/blob/glw/computed-field-diffusivities/test/test_turbulence_closures.jl, it would be nice to have this feature in the main branch. In particular, it would allow for users to implement their own turbulence closures or mimic the effect of no flux boundary conditions on an immersed boundary

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
