### ISSUE TITLE
Possibly out-of-date docs page

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1358]
I think this page is out-of-date: https://clima.github.io/OceananigansDocumentation/latest/model_setup/time_stepping/

Can someone please confirm?

**Comment by ali-ramadhan** [comment]
Ah yup! Wow that's old, before we even had `Simulation` haha.

Might not be worth rewriting that page until #1138 is resolved though, especially if we do it soon?

**Comment by glwagner** [comment]
I think better to remove it now so it doesn't confuse people, and revive when we have time.
