### ISSUE TITLE
Change "field dependencies" to "computed_dependencies" in KernelComputedField?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1369]
`KernelComputedField` contains a property called `field_dependencies`, which is supposed to be some kind of iterable whose members get `compute!` called on them:

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L76-L80

and then are later splatted into the function signature of the `kernel`:

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L92

But since `compute!` can be called on non-fields harmlessly, its possible to put any objects at all in `field_dependencies`. The name doesn't help clear things up, since the meaning of "field dependencies" is ambiguous (do we mean "dependencies of the KernelComputed _field_", and therefore any objects at all, or "specifically objects that are _fields_ on which the KernelComputedField depends"?)

Perhaps even worse is the fact that it makes sense to put `AbstractOperations` in `field_dependencies`, because its possible for `AbstractOperations` to themselves depend on fields, thus warranting the `compute!(abstract_operation)`.

A better name than `field_dependencies` is probably `computed_dependencies`. At least this makes clear what's happening under the hood.

We should also throw an error if `computed_dependencies` is not iterable (failure will occur later on anyways).

A more drastic change is to get rid of `parameters`, which I would be ok with too. However, I think it is potentially a nice feature that some users will appreciate and use to make their scripts and code a little cleaner and more interpretable.

See also the discussion on https://github.com/tomchor/Oceanostics.jl/issues/1

cc @tomchor @ali-ramadhan

**Comment by tomchor** [comment]
I agree with this. It makes it clearer what's happening behind the scenes. I'd prefer keeping the `parameters` keyword for now though.
