### ISSUE TITLE
Docstring for KernelComputedField is incorrect

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1370]
The docstring for KernelComputedField:

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L14

is incorrect, since the function signature is actually

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L45-L49

**Comment by tomchor** [comment]
I guess I'm confused about these signatures. I feel like in Python the function signatures are very clearly communicated by the prompt itself, etc. But in Julia I often get confused. For example, from the lines you mentioned I'd think the signature would be

```
         KernelComputedField(kernel, arch, grid; kwargs...) 
```

But in practice we actually call it as
```julia
ε = KernelComputedField(Center, Center, Center, isotropic_viscous_dissipation_ccc!, model;
                            field_dependencies=(νₑ, u, v, w))
```
because of multiple dispatch here: https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L70-L71

So I'd think that the signature should really be
```
         KernelComputedField(X, Y, Z, kernel, model; kwargs...) 
```

Or, because they're all valid ways to call the function, should they be all of those?

**Comment by glwagner** [comment]
Julia and python docstrings follow similar conventions. We apply similar standards to julia docstrings as to python docstrings.

A major difference between the two languages is that julia supports _multiple dispatch_ natively. This means for julia functions we often need to document multiple _methods_ which are all bound to the same function name.

As you point out the most important user-facing method is

```julia
KernelComputedField(X, Y, Z, kernel, model::AbstractModel; kwargs...) = 
     KernelComputedField{X, Y, Z}(kernel, model.architecture, model.grid; kwargs...) 
```

For documentation we have two choices. One is to document multiple methods in a single docstring. This makes sense when the methods are all defined in the same place in a particular codebase (which is currently the case for `KernelComputedField`).
We can also choose to document just one of the methods (the one that we deem is "user-facing").

Another possibility is to define different docstrings where different methods are defined. 
If we do this, all docstrings are printed at the REPL separated by a horizontal rule, eg:

```
help?> mean
search: mean mean! median median! SegmentationFault macroexpand @macroexpand @macroexpand1 Meta numerator enumerate timedwait promote_shape

  mean(itr)

  Compute the mean of all elements in a collection.

  │ Note
  │
  │  If itr contains NaN or missing values, the result is also NaN or missing (missing takes precedence if array contains both). Use the
  │  skipmissing function to omit missing entries and compute the mean of non-missing values.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> using Statistics
  
  julia> mean(1:20)
  10.5
  
  julia> mean([1, missing, 3])
  missing
  
  julia> mean(skipmissing([1, missing, 3]))
  2.0

  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  mean(f::Function, itr)

  Apply the function f to each element of collection itr and take the mean.

  julia> using Statistics
  
  julia> mean(√, [1, 2, 3])
  1.3820881233139908
  
  julia> mean([√1, √2, √3])
  1.3820881233139908

  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  mean(f::Function, A::AbstractArray; dims)

  Apply the function f to each element of array A and take the mean over dimensions dims.

  │ Julia 1.3
  │
  │  This method requires at least Julia 1.3.

  julia> using Statistics
  
  julia> mean(√, [1, 2, 3])
  1.3820881233139908
  
  julia> mean([√1, √2, √3])
  1.3820881233139908
  
  julia> mean(√, [1 2 3; 4 5 6], dims=2)
  2×1 Array{Float64,2}:
   1.3820881233139908
   2.2285192400943226

  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  mean(A::AbstractArray; dims)

  Compute the mean of an array over the given dimensions.

  │ Julia 1.1
  │
  │  mean for empty arrays requires at least Julia 1.1.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> using Statistics
  
  julia> A = [1 2; 3 4]
  2×2 Array{Int64,2}:
   1  2
   3  4
  
  julia> mean(A, dims=1)
  1×2 Array{Float64,2}:
   2.0  3.0
  
  julia> mean(A, dims=2)
  2×1 Array{Float64,2}:
   1.5
   3.5
```

This is important if methods are defined in different places (or different packages).

In our case I think it's fine to have just one docstring attached to the main user-facing method. The PR that resolves this issue could therefore move the docstring for `KernelComputedField` to

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L70-L71

and use the correct function signature for that method.
