### ISSUE TITLE
A more general `NonTraditionalFPlane` to match the upcoming tilted gravity feaure

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1372]
At the moment `NonTraditionalFPlane` only takes `fz` and `fy`, probably because it is designed for a coordinate where `y` is always the latitude and `z` is always aligned with gravity. 

https://github.com/CliMA/Oceananigans.jl/blob/cfe93e0b0688b0cd6545d8c82c46754df6fa462f/src/Coriolis/non_traditional_f_plane.jl#L30

However, based on https://github.com/CliMA/Oceananigans.jl/issues/1151 and https://github.com/CliMA/Oceananigans.jl/pull/1242, situations might emerge when we need `fx` to be non-zero. So it would be nice if it could be expanded to also take that argument.

Alternatively, `FPlane` could also be generalized to take a 3-element tuple/array, just like @ali-ramadhan did for the tilted gravity.

**Comment by ali-ramadhan** [comment]
This sounds like a good idea!

I guess it shouldn't be too hard to extend the implementation to support `fx`, `fy`, and `fz` like you're suggesting.

**Comment by tomchor** [comment]
We could implement an interface similar to `Buoyancy`, but I think this may be more easily done with `FPlane`, since `NonTraditionalFPlane` seems to be dedicated not for tilting domains, but for decomposing rotation based on latitude. We'd have something like

```julia
θ_rad = 0.05 # radians
g̃ = (sin(θ_rad), 0, cos(θ_rad))
buoyancy = Buoyancy(model=BuoyancyTracer(), vertical_unit_vector=g̃)
coriolis = FPlane(f=1e-4, vertical_unit_vector=g̃)
```

Thoughts?

**Comment by francispoulin** [comment]
Seems like a good idea and a good way to start trying to do this.

**Comment by glwagner** [comment]
Might be nice to have a `vertical_unit_vector` for both, right? Tilting the Coriolis force adds identical terms that are added when considering the full Coriolis force. Does it make sense to tilt the Coriolis force but retain the traditional approximation?

**Comment by tomchor** [comment]
> Might be nice to have a `vertical_unit_vector` for both, right? Tilting the Coriolis force adds identical terms that are added when considering the full Coriolis force. Does it make sense to tilt the Coriolis force but retain the traditional approximation?

Just to be clear, you're saying that it might nice to have `vertical_unit_vector` for both traditional and non-traditional f-plane implementations? If so, I'm not sure.... I'd need to think more. Although with a tilting parameter `FPlane` can kinda do everything `NonTraditionalFPlane` can do and more, no?

**Comment by glwagner** [comment]
Ah, I see what you're saying.

I think there's some potential confusion about the naming. "f-plane" refers specifically to the traditional approximation, which leverages the small aspect ratio of the flow to neglect the components of the Coriolis force that act in the vertical momentum equation (consistent with the hydrostatic approximation).

The "non-traditional f-plane" is really just the "full" Coriolis force, retaining all components.

So it sounds like you really want to implement a non-traditional f-plane --- just not one tilted in the direction that the current implementation of `NonTraditionalFPlane` assumes.

I guess it's really a question of names here, we can implement the math wherever...

**Comment by tomchor** [comment]
If the `FPlane` name really is supposed to be a vertical-component-only f-plane then it might make sense to implement it using the `NonTraditionalFPlane`. 

Although, if I'm being honest, these names aren't helpful to me at all. If more people agree could we also think about renaming them? I'm not sure what names would be good here, but something with "vertical" and "full"?

**Comment by glwagner** [comment]
> If the `FPlane` name really is supposed to be a vertical-component-only f-plane then it might make sense to implement it using the `NonTraditionalFPlane`.
> 
> Although, if I'm being honest, these names aren't helpful to me at all. If more people agree could we also think about renaming them? I'm not sure what names would be good here, but something with "vertical" and "full"?
> 
> EDIT: Maybe we only need `FPlane` and that's it? Then passing `FPlane(f=0)` would default to `vertical_unit_vector=ZDirection()`. Although the name `vertical_unit_vector` might be inappropriate if you're trying to consider the horizontal component because you're close to the equator, not because your domain is tilted...

It seems like we really just need one type, something like `BackgroundRotation`. 

`FPlane` could be an alias that inserts `rotation_axis=ZDirection()` or something.

Aliases are bad for various reasons, mostly because you have to learn not only the "real" names of things, but their aliases too to understand code.

But Oceanographers know what `FPlane` means. Long ago this was discussed (at that time, I advocated for `BackgroundRotation` or something similar), but it was rejected in favor of `FPlane` and friends.

We can even reuse `BackgroundRotation` for grids with a latitude-longitude coordinate system (by dispatching on `grid` and `coriolis` simultaneously).

**Comment by tomchor** [comment]
If I understand what you're saying, you're proposing that instead of having `NonTraditionalFPlane` and `FPlane` we keep `FPlane` (either an alias or not) and transform `NonTraditionalFPlane`  into `BackgroundRotation`, which then would have an arbitrary direction of rotation. Is that right?

**Comment by glwagner** [comment]
Yes. I don't think we want the alias `FPlane` in this case. And maybe `rotation_axis` is better than "direction of rotation"?

We could also consider merging this abstraction with `HydrostaticSphericalCoriolis`, but that might be more difficult.

On the other hand, it's a bit confusing that _all_ Coriolis forces ultimately represent a "background rotation rate"...
