### ISSUE TITLE
Vertically stretched grid: example + docs

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1394]
I suggest we convert the plankton example to use a vertically stretched grid. Then we can delete the `sandbox` directory from the repo.

Also in the https://clima.github.io/OceananigansDocumentation/dev/model_setup/grids/ we should point the user to this example in the discussion (that doesn't exist yet?) about vertically stretched grid.

**Comment by glwagner** [comment]
I like that idea.

**Comment by ali-ramadhan** [comment]
Woops sorry I meant to delete the sandbox! Would be great to increase variety among the existing examples so it's a great idea.

**Comment by navidcy** [comment]
Resolved by #1762.
