### ISSUE TITLE
Is `convert_output` for `NamedTuple` sufficiently general?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1398]
The implementation of `convert_output` for a `NamedTuple` of outputs:

https://github.com/CliMA/Oceananigans.jl/blob/51ceb8ead22badb90e6412c713e2661385ba27ca/src/OutputWriters/fetch_output.jl#L27-L28

assumes that the values of the named tuple are arrays. Should `convert_output` be called individually on each item in the `NamedTuple` so that this function will not fail for `NamedTuple`s of non-array output?

**Comment by glwagner** [comment]
Is this case needed for `LagrangianParticles` @ali-ramadhan ?

**Comment by glwagner** [comment]
Just to be completely clear I am suggesting changing the above to

```julia
 convert_output(outputs::NamedTuple, writer) = 
     NamedTuple{keys(outputs)}(Tuple(convert_output(output, writer) for output in outputs))
```

**Comment by ali-ramadhan** [comment]
Yes I think your suggestion would be good!

I think I did add that function for Lagrangian particles, which is kinda weird since it returns N arrays to be written to disk. Maybe there's a cleaner way of doing output for particles though.
