### ISSUE TITLE
Examples should plot without using any Oceananigans functions

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1405]
Take the 1D diffusion example: https://clima.github.io/OceananigansDocumentation/stable/generated/one_dimensional_diffusion/

This is the plotting code:

```julia
using JLD2

file = jldopen(simulation.output_writers[:temperature].filepath)

iterations = parse.(Int, keys(file["timeseries/t"]))

anim = @animate for (i, iter) in enumerate(iterations)

    T = file["timeseries/T/$iter"][1, 1, :]
    t = file["timeseries/t/$iter"]

    plot(T, z, linewidth=2, title=@sprintf("t = %.3f", t),
         label="", xlabel="Temperature", ylabel="z", xlims=(0, 1))
end
```

But where did `z` come from? From `z = znodes(model.tracers.T)` some lines above.

But what if I want to plot in a separate script? Or what if I run my simulation on a cluster and want to plot some data on a different machine?

One solution would be to use `z = file["grid/zC"]`. However, users may be surprised to learn that this output is not sliced and includes halos though (https://github.com/CliMA/Oceananigans.jl/issues/1194) so many plotting libraries will error because of some dimension mismatch.

So if you don't have access to the `grid` then you can't plot the coordinates correctly without wrangling with `file["grid"]` (which requires users to know about halos). And users may want to plot using other programming languages and libraries/programs where you can't get access to an Oceananigans grid.

---

I guess I'm advocating for plotting without using any Oceananigans functions to make the examples more useful for users.

We can make the plotting code more local which would make it more copy-paste-able for users (more user friendly).

**Comment by glwagner** [comment]
This could conflict with the idea that users "shouldn't have to know about the staggered grid" --- or maybe I am missing something?

We could maybe solve both problems by interpolating output to an output grid. Interpolated data might be more friendly; "native" data is perhaps needed only for more advanced / scientific applications. Certainly as grids get more complicated we will probably make use of interpolated output more and more.

**Comment by francispoulin** [comment]
Hmmm, since the data is produced in Oceananigans it seems reasonable to me that one would use part of the library.  Having said that, having been a new user not so long ago, I remember thinking it was a bit confusing since I didn't know what the library did.  Maybe the idea of plotting things using NetCDF only might be helpful for those who know it already?

**Comment by navidcy** [comment]
Isn't to something like this where a Plot recipe comes handy?

**Comment by glwagner** [comment]
Perhaps, but that only works in julia and would seem to count as an "Oceananigans function"?
