### ISSUE TITLE
Rename `NonDimensionalModel`?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1411]
I noticed (while starting a [discussion](https://github.com/CliMA/Oceananigans.jl/discussions/1410)) that there is a `Oceananigans.Models.NonDimensionalModel`.

Gives that it just starts a normalized `IncompressibleModel` (it's even inside `Oceananigans.Models.IncompressibleModels`), should it be renamed to `NonDimensionalIncompressibleModel`?

**Comment by ali-ramadhan** [comment]
Yes! Obviously it got left behind when we renamed `Model` -> `IncompressibleModel` even though this was a long time ago now...
