### ISSUE TITLE
Warnings when starting Oceananigans 0.52

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1419]
When I start Oceananigans 0.52 I am greeted with the following warnings:

>WARNING: using Diagnostics.run_diagnostic! in module Oceananigans conflicts with an existing identifier.
WARNING: using OutputWriters.write_output! in module Oceananigans conflicts with an existing identifier.

Something tells me this has something to do with the fact that I recently moved `FieldSlicer` to `Diagnostics` to be used with `WindowedSpatialAverage`, but I haven't been able to confirm.

**Comment by glwagner** [comment]
If we fix this can we also get `FieldSlicer` into `Oceananigans.Fields`?

**Comment by ali-ramadhan** [comment]
Just fixed it but I didn't touch `field_slicer.jl`.

I think it was a different problem: we were abusing scoping rules and sub-modules in a couple of places.
