### ISSUE TITLE
Passing abstract operations (and `ComputedField`?) to `mapreduce`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1422]
We should look into using `mapreduce` as a way of computing reduced grid metrics and statistics using abstract operations. This could speed up `AveragedField` (and upcoming `SummedField`, `IntegratedField`, etc.) and make them lighter by not having to store a scratch space.

There are two methods for `mapreduce`:

```julia
mapreduce(f, op, itrs...; [init])
mapreduce(f, op, A::AbstractArray...; dims=:, [init])
```

The first one might be useful for abstract operations (as long as `getindex` is defined?).

Might be useful to do a bit of benchmarking to see if we can use them (and potentially get rid of some existing code).

The second function I guess would only be useful if we already have a `ComputedField` with an array.

We already use `mapreduce` a bit (the second method) but crucially we needed to pass in a view into a `CuArray` (and not a view into an `OffsetArray{CuArray}`): https://github.com/CliMA/Oceananigans.jl/blob/master/src/Solvers/preconditioned_conjugate_gradient_solver.jl#L57-L58

**Comment by glwagner** [comment]
The relevant code that will change is here:

https://github.com/CliMA/Oceananigans.jl/blob/master/src/AbstractOperations/averages_of_operations.jl

Currently we build a `ComputedField` when users ask for averages of `AbstractOperations`:

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/AbstractOperations/averages_of_operations.jl#L23

**Comment by glwagner** [comment]
Thinking about this a bit more --- do we need to use `mapreduce` at all? Supposedly `mean` will take an iterator as an argument:

```julia
help?> mean
search: mean mean! median median! SegmentationFault macroexpand @macroexpand @macroexpand1 Meta numerator enumerate timedwait promote_shape MethodSummary

  mean(itr)

  Compute the mean of all elements in a collection.
```

Does this mean we can use `AbstractOperations` directly in `mean` (if they iterate correctly?) 

This may also provide a way to compute correct averages on-the-fly on stretched grids, combined with #1452 (which we haven't discussed yet).

I might be missing something about specifically how we would use `mapreduce`.

As a side note, if we do need to use `mapreduce`, we may want to use `Base.mapreducedim!` (which stores results in a previously allocated array, as I think we want).
