### ISSUE TITLE
(θ, φ) or (λ, ϕ) or (λ, ϑ)  for coordinates on a sphere?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1437]
Surprise! People use different conventions for coordinates on a sphere. Which should we use?

Right now the code uses λ (`\lambda`) for longitude, and ϕ (`\phi`) for latitude as it seems to be the standard for geographical coordinates.

Here are the three major conventions I could find:
1. Spherical coordinates used in math and physics use θ (`\theta`) for the azimuthal angle (longitude) and φ (`\varphi`) for the polar angle (latitude): https://en.wikipedia.org/wiki/Spherical_coordinate_system#Conventions
2. Geographical coordinates use λ (`\lambda`) for longitude, and φ (`\varphi`) for latitude: https://en.wikipedia.org/wiki/Geographic_coordinate_system#Latitude_and_longitude
3. If we take Vallis (2nd edition) as gospel: they use λ (`\lambda`) for longitude and ϑ (`\vartheta`) for latitude. Definitely not standard. Seems that θ (`\theta`) is reserved for potential temperature, ϕ (`\phi`) is reserved for kinematic pressure, and φ (`\varphi`) is reserved for passive tracers lol.

I propose we use convention 2. Which probably means we should be using φ (`\varphi`) in the code and not ϕ (`\phi`), although you probably need a good font like JuliaMono to distinguish the two...

cc @sandreza

**Comment by francispoulin** [comment]
Good question.  

I also vote for 2, also considering that the MITgcm uses that notation already and many people take that as a standard reference.

**Comment by glwagner** [comment]
I like 2 as well! We use `\phi` for pressure / geopotential in the docs. I imagine we want to continue doing that. And I thnk `\varphi` is a fun letter.

**Comment by navidcy** [comment]
`\varphi` is indeed better than `\phi`. Only downside that it's a bit more cumbersome to type..

**Comment by christophernhill** [comment]
🦆 sounds good 😈
