### ISSUE TITLE
Rename `master` branch to `main`?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1446]
Should be pretty easy now: https://github.com/github/renaming#renaming-existing-branches

Some CI might break for a bit but should be easy to fix if anything does break.

**Comment by francispoulin** [comment]
This sounds fine to me but what's the inspriation for doing this?

**Comment by ali-ramadhan** [comment]
Ah I agree with the GitHub reasons: https://github.com/github/renaming#why-main

Since `main` is the new default I've been converting some of my other repos to `main` so I can rely on muscle memory without mistaking `master` vs `main` lol.

**Comment by glwagner** [comment]
I agree with this change!

**Comment by francispoulin** [comment]
Sounds great!

**Comment by navidcy** [comment]
I think let's keep it `master`, I'm just afraid it'll create a mess...
@ali-ramadhan, what do you think?

**Comment by vchuravy** [comment]
I have migrated a few repos and sofar it has not caused any issues.

**Comment by navidcy** [comment]
Oh, ok...! Good to know! I take it back then :)

**Comment by glwagner** [comment]
Ok, I renamed it.

**Comment by glwagner** [comment]
When the `Oceananigans` github page is opened it might present this helpful message:

![image](https://user-images.githubusercontent.com/15271942/136055771-2191957e-eced-4696-9362-03aac3e10722.png)

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
