### ISSUE TITLE
Modify `test_dynamics.jl` to includes tests for `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1448]

**Comment by glwagner** [comment]
Since our test scripts are already too long, I suggest creating a new script `test_shallow_water_dynamics.jl`. We also need this if we want to run the script in the `shallow_water` `TEST_GROUP`.

**Comment by navidcy** [comment]
Is this still outstanding?

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
