### ISSUE TITLE
Test non-equal MPI domain decompositions soon

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1450]
Right now `Oceananigans.Distributed` requires the grid points to be split evenly among the ranks, e.g. if you have 4 ranks along the x-direction then `grid.Nx` must be a multiple of 4.

@christophernhill suggested generalizing this. He's written some code for dividing nearly evenly into N subdomains when the global number of points is not exactly divisable by N: https://github.com/christophernhill/iap-2021-12.091/blob/e79dfe9dca5441e561cefd65b4c052b1a1dea5a3/step3.py#L36

`IncompressibleModel` can only be decomposed in y but `ShallowWaterModel` and `HydrostaticFreeSurfaceModel` can be decomposed in x and y so we should try this out with one of them.

With shallow water model in this PR we could test different x, y, and xy domain decompositions (all non-equal).

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.

@simone-silvestri feel free to add info if you have it.
