### ISSUE TITLE
Grid metrics and differences as AbstractOperations

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1452]
It might be useful if grid metrics and differences (`δx`) were provided as abstract operations. For example:

```julia
struct GridMetric{M, G} <: AbstractOperation
    metric :: M
    grid :: G
end

getindex(gm::GridMetric, i, j, k) = gm.metric(i, j, k, grid)
```

We can then define operations for grid spacings and area, which would mean, for example, that an operation computing vertical vorticity could be constructed via

```julia
Δyᶜᶠᵃ = GridMetric(Oceananigans.Operators.Δyᶜᶠᵃ, grid)
Δxᶠᶜᵃ = GridMetric(Oceananigans.Operators.Δyᶠᶜᵃ, grid)
Axᶠᶠᵃ = GridMetric(Oceananigans.Operators.Axᶠᶠᵃ, grid)

Γ = δx(Δyᶜᶠᵃ * v) - δy(Δxᶠᶜᵃ * u)
ζ = Γ / Axᶠᶠᵃ
```

For this we also need

```julia
struct Difference{D} <: AbstractOperation
    δ :: D
    grid :: G
end
```

similar to `Derivative` for partial derivatives with respect to x, y, z.

**Comment by ali-ramadhan** [comment]
This would be pretty sweet!

Are you opening a "wishlist" issue because you think a current implementation would hit issue #1241?

**Comment by glwagner** [comment]
I just wanted to write down the details of idea while it was in my head!
