### ISSUE TITLE
introduce immersed boundary method to `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1458]
It should be pretty easy to adapt `correct_incompressible_immersed_tendencies.jl` to create `correct_shallow_water_immersed_tendencies.jl` to this features to `ShallowWaterModel`.  It may also make it easier to test the immersed boundary method as there is no need for a pressure solve in simulating the equations.

**Comment by glwagner** [comment]
I think we might be able to improve on what's done for `IncompressibleModel`. A simple implementation would simply mask the immersed boundary in `update_state!`.

**Comment by francispoulin** [comment]
thanks @glwagner .  Maybe we could plan to meet for an hour this week and give this a try?  It would be great for `ShallowWaterModel` and could also be helpful for testing the immersed boundary methods in a simpler model.  Happy to disucss on slack as you like.

**Comment by navidcy** [comment]
Is this done now? Perhaps we just missed closing the issue?

**Comment by glwagner** [comment]
For sure, `ShallowWaterModel` supports immersed boundaries now.
