### ISSUE TITLE
Validation + Convergence tests: images not showing up

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1459]
See, e.g., the Stratified Couette flow validation section in Docs: 

<img width="750" alt="Screen Shot 2021-03-13 at 4 44 11 pm" src="https://user-images.githubusercontent.com/7112768/111020624-6e090380-841b-11eb-8658-1130d560d86b.png">

**Comment by ali-ramadhan** [comment]
We should probably find these figures and add them back in, but probably not as part of the repo to avoid inflating the repo size. We could use a GitHub issue for figures or we could use https://github.com/CliMA/OceananigansArtifacts.jl for figures as well.

X-Ref: https://github.com/CliMA/Oceananigans.jl/issues/1212
