### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1468]
I just installed Oceananigans on a server that has GPUs and is running julia 1.1.1

When I try and update I get an error saying that the package name could no be resolved.

```
(v1.1) pkg> update Oceanigans
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * Oceanigans (not found in project or manifest)
Please specify by known `name=uuid`.
```

Could this be because of the old version of julia?  I have asked if they can update it but no idea if they will.

**Comment by ali-ramadhan** [comment]
Ah Julia 1.1 is quite old and will end up using an ancient version of Oceananigans.jl so you probably need Julia 1.5+ (you should be able to download a binary from https://julialang.org/downloads/).

But in this case I think Oceananigans is mispelled as Oceanigans.

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan .  I hope they will update a newer version, otherwise I can try and install it myself and I don't imagine they will have any problem with that.  We will see.

**Comment by navidcy** [comment]
> Thanks @ali-ramadhan . I hope they will update a newer version, otherwise I can try and install it myself and I don't imagine they will have any problem with that. We will see.

Install Julia yourself and don't rely on IT... :)
(that's what I do on Australia's HPC...)

**Comment by francispoulin** [comment]
Excellent advice @navidcy , I will probably do just that.  I do install it on my ubuntu machine but suppose I need to learn to install it for a user only.  A good thing to learn.
