### ISSUE TITLE
Triggers  tagbot to register update to v0.53.1

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1473]
@JuliaRegistrator register

**Comment by tomchor** [comment]
@ali-ramadhan Hopefully this is the right way to do it!

**Comment by navidcy** [comment]
This is one way for sure. It does the job :)

**Comment by glwagner** [comment]
@tomchor we typically comment on the commit itself, as in:

https://github.com/CliMA/Oceananigans.jl/commit/73f1e331ac4742a7df4bfaba6948abfd14e58fc0

**Comment by navidcy** [comment]
Yes, should have mentioned it @tomchor. That's much simpler :) (no need to open issue etc..)

**Comment by ali-ramadhan** [comment]
I also took the liberty of picking an emoji for v0.53.1: ✈️
