### ISSUE TITLE
Add "GPU simulation tips" section to the docs

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1478]
There are a few gotchas when setting up GPU simulations so it's not always as simple as just changing `CPU` to `GPU`, mainly related to things the GPU compiler does not like.

A common one that produces a very non-obvious error is using global variables in forcing functions or any function that will get used in a GPU kernel (e.g. https://github.com/CliMA/Oceananigans.jl/issues/1203#issuecomment-733435704 and https://github.com/CliMA/Oceananigans.jl/issues/1477).

Might be helpful for users if we add a section or page to the docs that describes these issues.

**Comment by tomchor** [comment]
I completely agree. I'd even go further and suggest a section for simulation tips in general, and then a subsection for GPU tips specifically.

As an example, I noticed that defining as many things as `const` as possible helps with performance, even if I'm running on a CPU. It seems kinda obvious in hindsight, but it took me a few months to think of that.

**Comment by francispoulin** [comment]
@tomchor Thanks for pointing out the `const` as I had no idea before today that this would help.

**Comment by tomchor** [comment]
> @tomchor Thanks for pointing out the const as I had no idea before today that this would help.

Just a disclaimer, I did notice it when running some stuff on my laptop, but I also never ran any actual rigorous tests, so there's the possibility that it was a fluke too :)

**Comment by francispoulin** [comment]
I learned today that cuda failed if I did not define a parameter as a constant, which I had no idea about before.

**Comment by glwagner** [comment]
It makes sense that using `const` for variables referenced "globally" in functions increases CPU performance, see: https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables

**Comment by tomchor** [comment]
From the talks we've had here and in [this discussion](https://github.com/CliMA/Oceananigans.jl/discussions/1482), as well me looking things I have some things we could include as tips. Please let me know if I'm missing something

## General simulation tips
- In general defining variables (that are used in the calculations) as constants makes things faster as it helps the compiler optimize things
- It's probably worth inlining small functions that get called often to reduce function call overhead (at the very least it's worth playing with this)

## GPU simulation tips:
- Any global variable that needs to be accessed by the GPU needs to be a constant or the simulation will crash
- Complex `ComputedField`s may not work, so the user can either nest `ComputedField`s (simple, but costly; probably good for development) or use `KernelComputedField`s (complex but efficient; probably what you wanna use for production-ready code)
- GPU runs are generally memory-limited, so it's good to both keep track of and try to reduce the size of your runs. Useful tips in this regard are
  - Try to use higher-order schemes as you need fewer grid points to achieve the same resolution
  - Use `nvidia-smi` to monitor the memory usage of the GPU
  - Manually define scratch space to be reused in diagnostics, to avoid creating one scratch space for each separate diagnostic you have.

**Comment by ali-ramadhan** [comment]
These are great! Can't think of more off the top of my head right now but will definitely add any I think of. We could start adding them to the docs. Hmmm, should it be on a new "Simulation tips" page?

**Comment by tomchor** [comment]
I would say so, so that it's easier to find. I also can't think of anotger
good place where it'd fit, but I'm open to suggestions

**Comment by navidcy** [comment]
I'm voting for a PR.

**Comment by ali-ramadhan** [comment]
True. Should probably also link to https://docs.julialang.org/en/v1/manual/performance-tips/

**Comment by tomchor** [comment]
Leaving this here for future reference, but also for discussion: maybe include some guidelines on using, slicing, and even viewing arrays when working on GPUs. These are definitely not obvious. It might be useful for users using external data (as arrays) in simulations, such as https://github.com/CliMA/Oceananigans.jl/issues/1509.
