### ISSUE TITLE
Use time index for `JLD2OutputWriter` instead of the iteration number?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1491]
Right now `JLD2OutputWriter` indexes each output with the iteration number, i.e. `"timeseries/$name/$iter"`

https://github.com/CliMA/Oceananigans.jl/blob/2dc082670958212098eb543f5bc4f6d56bb34cdf/src/OutputWriters/jld2_output_writer.jl#L233

but I wonder if it would be better to switch to using a time index, i.e. 0, 1, 2, 3, 4, ... since the exact iteration number isn't all that useful and could be stored in `file["timeseries/iteration/*"]` if needed.

It would definitely make it easier to manually iterate over the outputs.

This could be a dangerous breaking change however as there are quite a few scripts out there that analyze Oceananigans.jl JLD2 files...

cc @adelinehillier

**Comment by glwagner** [comment]
This change was proposed in #963 so maybe we should close this issue in favor of that one?

**Comment by glwagner** [comment]
Let's ruminate on #963 instead of this issue.
