### ISSUE TITLE
Gent-McWilliams mesoscale eddy flux parameterization

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1492]
Some time ago @sandreza and @xiaozhour suggested it would be useful to add the GM-Redi parameterization to Oceananigans.jl since we may want to train mesoscale eddy parameterizations.

I'm opening this issue to discuss on what exactly needs to be implemented. My main reference is https://mitgcm.readthedocs.io/en/latest/phys_pkgs/gmredi.html

It seems that there are three different new closures that could potentially be added:
1. Redi (symmetric) tensor diffusivity.
2. Gent-McWilliams (anti-symmetric) tensor diffusivity.
3. GM-Redi combining the two.

Note: @glwagner has already implemented parts of the Redi tensor and GM for `TwoDimensionalLeith` so GM-Redi might not need too much extra work: https://github.com/CliMA/Oceananigans.jl/blob/master/src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl

# Questions/proposal

1. Do we make the small-angle approximation? I would say yes.

In Oceananigans.jl right now each component of the tensor diffusivity is calculated on-the-fly so the unapproximated tensor could end up being 2-4x more expensive to compute. We cannot compute the full tensor in one go (reusing the isopycnal slopes) and we may not want to since it takes up a lot of memory (9 extra field?). But maybe there's a good reason to not make the small-angle approximation? We could eventually support both (unapproximated and small-angle approximation).

See https://mitgcm.readthedocs.io/en/latest/phys_pkgs/gmredi.html#redi-scheme-isopycnal-diffusion for a comparison of the two.

2. Is GM-Redi the main parameterization of interest? Would people use the fully symmetric or the fully anti-symmetric diffusivity tensor by themselves?

If not then maybe we can save some time by just implementing one new closure, `GMRedi` or `GentMcWilliamsRedi`. If we take the isopycnal diffusivity to be the same for both the symmetric and anti-symmetric tensor then we the resulting tensor is quite cheap to compute (only 3 components) if performance is important:

From https://mitgcm.readthedocs.io/en/latest/phys_pkgs/gmredi.html#griffies-skew-flux
![image](https://user-images.githubusercontent.com/20099589/111556957-1abbeb80-8762-11eb-9fb3-870d447efa5f.png)

**Comment by johncmarshall54** [comment]
I think we should do 1. and 2., keeping them separate.
