### ISSUE TITLE
One stop shop: `Oceananigans.DataAnalysis` through abstract operations

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1493]
# Motivation

This issue is a summary of some not-so-recent discussions with @glwagner that have over time convinced me that adding some native post-processing and data analysis capabilities to Oceananigans.jl by relying on `Oceananigans.AbstractOperations` under the hood would be a killer feature.

This would eventually allow users to compute new/complex terms, close budgets, etc. on any grid without worrying about the staggered grid. So it might finally fulfill the dream of going from idea -> model/simulation -> analysis -> paper purely in Julia and (most importantly) without needing to know anything about the staggered grid.

Since the interface remains very similar between the different models and grid, this could potentially allow future users to easily switch between different equation sets and grids while keeping the same analysis script.

I thought we opened an issue about this but I can't seem to find it so maybe not? Either way this has been on my mind lately (and would help quite a bit with OceanParameterizations.jl) so I thought I'd write down some thoughts.

# Plan?

The main feature would be the ability to construct `Field`s from output. Then the machinery of `Oceananigans.AbstractOperations` is available! Some extra quality-of-life features would allow for a more xarray-like experience such as named axis behavior (#457) through https://github.com/rafaqz/DimensionalData.jl.

Maybe the easiest thing would be to first create a new field, `TimeSeriesField` or something with a `DimensionalData.DimArray` under the hood, that stores (x, y, z, t) data from a file and works with abstract operations?

# Some thoughts

1. It's probably easiest to add support for constructing fields from JLD2 first then NetCDF.
2. Complex abstract operations on the GPU can fail but most data analysis is done on the CPU so #1241 probably won't be an issue.
3. While there is some overlap with xgcm support (#1334) these two issues are quite orthogonal. Why not both!
4. We might have to find a way of lazily loading data from disk with DimensionalData.jl so we can analyze large datasets without loading the complete dataset into memory, but this could come later.
5. One of the big features of xarray is that together with Dask you can analyze huge datasets that do not fit in memory using many cores quite quickly. This is probably not possible with Julia right now (maybe with Dagger.jl in the future), but it seems that this might be an edge case. Most users will probably be able to get by with lazily loading data from disk?

# Example?

I was thinking what would be a good example would be to showcase this feature. The example could show how to go from math -> setup -> simulation -> analysis -> results. So it would have to be pretty simple but with enough complexity to showcase the power of the framework. So probably no closing of TKE budgets...

**Comment by glwagner** [comment]
There's a preliminary implementation here:

https://github.com/CliMA/Oceananigans.jl/blob/master/validation/bickley_jet/disk_time_series.jl

It's used for plotting the Bickley jet here:

https://github.com/CliMA/Oceananigans.jl/blob/62c8abb1f39fb2f4fd24e274165ee2765e130933/validation/bickley_jet/bickley_jet.jl#L142-L159

The principal change that's needed for `JLD2OutputWriter` is to serialize a bit more information. This is done manually for the Bickley jet:

https://github.com/CliMA/Oceananigans.jl/blob/62c8abb1f39fb2f4fd24e274165ee2765e130933/validation/bickley_jet/bickley_jet.jl#L101-L107

but it would be easy to implement saving this kind of metadata as a default.

**Comment by glwagner** [comment]
There's a preliminary implementation here:

https://github.com/CliMA/Oceananigans.jl/blob/master/validation/bickley_jet/disk_time_series.jl

It's used for plotting the Bickley jet here:

https://github.com/CliMA/Oceananigans.jl/blob/62c8abb1f39fb2f4fd24e274165ee2765e130933/validation/bickley_jet/bickley_jet.jl#L142-L159

The principal change that's needed for `JLD2OutputWriter` is to serialize a bit more information. This is done manually for the Bickley jet:

https://github.com/CliMA/Oceananigans.jl/blob/62c8abb1f39fb2f4fd24e274165ee2765e130933/validation/bickley_jet/bickley_jet.jl#L101-L107

but it would be easy to implement saving this kind of metadata as a default.

**Comment by ali-ramadhan** [comment]
Ah that looks quite nice. Would it make sense to try and integrate `DiskTimeSeries` with a `DimensionalData.DimArray` to get named axis behavior?

**Comment by francispoulin** [comment]
Question: @glwagner suggested serializing the operations.  Do we want the option to do this in parallel?  I know NetCDF does parallel reading and writing and that could be helpful.  I agree that first getting it running in serial would be a good idea.

Sorry if I misunderstood.

**Comment by glwagner** [comment]
@ali-ramadhan that sounds neat! Also integrate DimArray with AbstractField so the spatial dimensions can also be named? That might be the first thing to do; then we just have to add Time to DiskTimeSeries. You are a lot more familiar with DimArray so whatever makes sense.

**Comment by tomchor** [comment]
>  So it might finally fulfill the dream of going from idea -> model/simulation -> analysis -> paper purely in Julia and (most importantly) without needing to know anything about the staggered grid.

I like the idea of doing the whole thing in Julia! But does the whole thing need to be _inside_ Oceananigans? I think that are more advantages to considering creating a separate package just for the data analysis, but still within the Oceananigans "ecosystem".

**Comment by ali-ramadhan** [comment]
True, I think there will be a lot of reliance on `Oceananigans.AbstractOperations` but it could be in a separate package for sure. We probably want to encourage more packages anyways.

We could call it OceananigansDataAnalysis.jl?

There's a huge number of things you might want to do in post-processing, e.g. compute zonally-averaged streamfunctions, close TKE budgets, that would clutter up Oceananigans.jl but could belong in OceananigansDataAnalysis.jl.

**Comment by tomchor** [comment]
> We could call it OceananigansDataAnalysis.jl?

`DataAnanigans`? `Oceanalysis`? Possibilities are endless haha

Another option would possibly be to broaden the scope of Oceanostics.jl to include that, which I wouldn't be opposed to.

**Comment by ali-ramadhan** [comment]
Haha I love Oceanalysis.jl!

> Another option would possibly be to broaden the scope of Oceanostics.jl to include that, which I wouldn't be opposed to.

Yeah that make sense. I guess right now Oceanostics.jl provides kernels for `KernelComputedField` but this could fall under "data analysis" and "post processing".

Other packages/ecosystems do this as well, e.g. Pluto.jl and https://github.com/fonsp/PlutoUtils.jl

**Comment by glwagner** [comment]
The main advantage of having `DiskTimeSeries` in `Oceananigans` would be to use it in examples without depending on another package. I think the implementation of `DiskTimeSeries` is light. It also _requires_ certain features (for example, location metadata must be saved by `JLD2OutputWriter` for `DiskTimeSeries` to work). This tight coupling between `DiskTimeSeries` and `OutputWriters` could motivate including `DiskTimeSeries` in `Oceananigans.jl`.

Other aspects of analyzing Oceananigans data might be more appropriate in another package. I'm not exactly sure what specific features are up for debate in this issue.

**Comment by tomchor** [comment]
> The main advantage of having DiskTimeSeries in Oceananigans would be to use it in examples without depending on another package.

I'm not sure what `DiskTimeSeries` specifically is, I guess I missed that discussion. But I don't think Oceananigans examples depending on other packages is necessarily a bad thing. In fact I see it as a good thing. 

Right now there is at least one package, possibly two (LESbrary.jl and Oceanostics.jl) that can make the user's life easier when running Oceananigans. At the moment, there is no way for the user to find out that these packages exist, unless they joined the slack or stumbled upon them in an Oceananigans issue (unless I missed something in the docs). I also bet there are many other useful Julia packages that could make one's life easier in Oeananigans that I and many users have never used or heard of.

I think including these packages in at least some examples would encourage users to experiment and explore. One of the advantages of python is its powerful ecosystem of packages, and I guess this could be the start of something similar for physical oceanographers in Julia.

**Comment by glwagner** [comment]
@tomchor see my second comment on this thread. It links to the code that implements `DiskTimeSeries`, and links to an example of it being used.

**Comment by glwagner** [comment]
Couple thoughts from a discussion with @ali-ramadhan today:

To get `DiskTimeSeries` working with `JLD2OutputWriter`, we'll need to 1) serialize the grid (mostly for convenience...) and 2) serialize "meta" for fields by adding lines like

```julia
file["serialized/grid"] = model.grid

for (i, out) in enumerate(outputs)
    field_name = keys(outputs)[i]
    out isa AbstractField && (file["timeseries/$field_name/meta/location"] = location(out))
end
```

We need a bit of extra work for `ReducedField`. Alternatively, this logic can be built into `DiskTimeSeries`.

Some logic for serializing boundary conditions might be nice too (sometimes, but not always possible).

This, plus changing the default `FieldSlicer` to `nothing`, are the primary changes that's needed for `JLD2OutputWriter`, I think.

For `NetCDFOutputWriter`, the field location needs to be saved as a string in the field's attributes. I think we have what we need to reconstruct the grid otherwise. @ali-ramadhan can comment. I think we also want to make the default `field_slicer` to `nothing` so that the framework is friendly.

The broadcasting infrastructure being developed on #1596 will make analysis with Oceananigans fields even nicer (since we can bypass `ComputedField` and launch kernels / make computations immediately via julia's broadcasting syntax).

**Comment by glwagner** [comment]
Another thought... I wonder if we should come up with a utility that "slices" a grid in the same way that fields are sliced. Then we can enable analysis on sliced output without any new types (eg `DiskTimeSeries` can build ordinary `Field`s on the `sliced_grid`).

**Comment by glwagner** [comment]
We have `Oceananigans.OutputReaders` so I think we can close this issue.
