### ISSUE TITLE
Is the name gravitational_unit_vector misleading?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1496]
So, only now am I realizing that maybe the name `gravitational_unit_vector` is misleading since it points the opposite way as it should. 

I think what we had in mind was the vertical unit vector, which should point up, but we ended up naming it `gravitational_unit_vector`, which actually points down! I suggest a change to `vertical_unit_vector` which is more in line with what we want, and also the same name can be used when we implement that tilting of the Coriolis parameter. So a user could set-up a simulation as

```julia
model = IncompressibleModel(grid, buoyancy = Buoyancy(model=BuoyancyTracer(), vertical_unit_vector=g̃),
                                  coriolis = FPlane(f=1e-4, vertical_unit_vector=g̃,)
```

**Comment by glwagner** [comment]
Vertical might work. What we really want is something like `geopotential_normal`. But while this name is better for planetary models, it might be obscure for limited-area models.

If we're going to add `vertical_unit_vector` to `FPlane` and `NonTraditionalFPlane` then we may also need `validate_vertical_unit_vector(buoyancy, coriolis)` for constructors (or something similar).

**Comment by francispoulin** [comment]
Interesting problem. I guess in the standard case, we know gravity poins down but usually have a negative in the buoyancy term and then define the unit vector to be upwards `(0,0,1)`.  I agree that to be consistent with convention, picking the `gravitational_unit_vector` to be antiparallel to the gravitation force, makes sense.

**Comment by francispoulin** [comment]
what if we call it `buoyancy_unit_vector`?  To me this suggests the direction things will float, but `geopotential_normal` also has a nice ring to it

**Comment by glwagner** [comment]
> what if we call it buoyancy_unit_vector?

That'd be a nice name, but alas we may want to apply the same terminology to the Coriolis force, since it would also need to be rotated with the domain.

**Comment by glwagner** [comment]
Would also be fun to have a function `rotate_domain(model::IncompressibleModel)` :-P

**Comment by tomchor** [comment]
> That'd be a nice name, but alas we may want to apply the same terminology to the Coriolis force, since it would also need to be rotated with the domain.

Yeah, I'm all in favor of having a simple name that is unified for `FPlane()` and `Buoyancy()`.

My vote goes to `vertical_unit_vector`, as it is intuitive and works for both (with the trade-off that the vertical direction doesn't always align perfectly with the geopotential normal, but I think that's okay).

I'll make the PR as soon as we agree
