### ISSUE TITLE
`grid` not identical to `model.grid`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1501]
@ali-ramadhan and I discovered today in developing `fjp/flat-for-shallow-water-model` that `grid` is set up with default halos but `model.grid` actually has the correct halos needed for the advection scheme.  Note that the advection scheme is not specified until after the grid is created so given the current framework I think this is necessary.  I realize this might be less than ideal but as long as you are focusing on the physcial domain, the two agree exactly.

Is this a concern?

**Comment by glwagner** [comment]
I think we should change the defaults as suggested by #1245 so this is uncommon.

**Comment by francispoulin** [comment]
Good idea.  

Following the discussion, and the fact that people seem to be using high order advection schemes like `WENO5`, I changed the defalt in this branch from `1` to `3`.  This can be revisited when it becomes a PR so I will close this issue.

**Comment by ali-ramadhan** [comment]
Changing the default would make inflating halos less common. I still think it would be useful to print a warning/info when halos are inflated so the user knows `grid` and `model.grid` are different now.

**Comment by francispoulin** [comment]
I'm happy to put a warning if people agree. What would we say exactly and where would we say it?

**Comment by ali-ramadhan** [comment]
How about this?

```julia
@warn "Inflating model grid halo size to ($Hx, $Hy, $Hz) and recreating grid. " *
      "The model grid will be different from the input grid. To avoid this warning, " *
      "pass halo=($Hx, $Hy, $Hz) when constructing the grid."
```

**Comment by francispoulin** [comment]
> How about this?
> 
> ```julia
> @warn "Inflating model grid halo size to ($Hx, $Hy, $Hz) and recreating grid. " *
>       "The model grid will be different from the input grid. To avoid this warning, " *
>       "pass halo=($Hx, $Hy, $Hz) when constructing the grid."
> ```

Sounds great!  I have added it in my branch.  I will close this issue and we cna modify this when the branch makes its way as a PR. Soon I hope!
