### ISSUE TITLE
`MultiCPU` or `MPI_CPU`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1502]
In the distirbuted models we use `multiCPU` to denote the `MPI` runs that are done on `CPU`s. It occurred to me that `MultiCPU`s could also mean threaded runs, but that's not what we are doing.

Would it be more precise to say `MPI_CPU` or maybe without the underline?

**Comment by ali-ramadhan** [comment]
True. I guess we don't have a separate architecture for multi-threaded.

I agree that `MPI_CPU` or `MPICPU` would be more precise. What do you think of `DistributedCPU` and `DistributedGPU`?

**Comment by francispoulin** [comment]
I am happy with both names but do we need a distributed for each framework?  I thought they were almost identical but don't remember the details.

Francis
________________________________

**Comment by ali-ramadhan** [comment]
You are right they are identical right now.

We could have a combined type, e.g. `DistributedArchitecture` then we can have `DistributedArchitecture{CPU}` and `DistributedArchitecture{GPU}`.

But we want to be able to dispatch on `::AbstractCPUArchitecture` and `::AbstractGPUArchitecture`. For reference, right now we have that `CPU <: AbstractCPUArchitecture` and `MultiCPU <: AbstractCPUArchitecture`.

Unfortunately `DistributedArchitecture{CPU}` cannot be a sub type of `AbstractCPUArchitecture`.

So to me the only solution seems to be to have two identical structs, `MultiCPU` and `MultiGPU`, where `MultiCPU` is a sub-type of `AbstractCPUArchitecture` and `MultiGPU` is a sub-type of `AbstractGPUArchitecture`.

**Comment by francispoulin** [comment]
I am happy with `MultiArch`.  Much better. 

Are people doing this on multiple GPUs yet or is it still in development?

**Comment by glwagner** [comment]
#2253 is the PR that implements support for multiple GPUs (single node, without MPI)
