### ISSUE TITLE
Normalizing different Grids

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1506]
The Grid function that I use the most is `RegularRectilinerGrid` and is nice as you only really need to specify the size and the topology, and it will build a grid for the user.

After starting to use `RegularLatitudeLongitudeGrid`, I see that the defualts are quite different, you need to specify latitude, longitude, and z.  Also, there is no topology option at all.

Do we want to normalize these so that they are more similar?  If yes, how would we want to do that?

**Comment by ali-ramadhan** [comment]
Normalizing the different grids would definitely be good if we can do it. I would also add the grid properties. Right now there's also e.g. `grid.Δx` and `grid.Δλᶜᶜᵃ`.

> After starting to use `RegularLatitudeLongitudeGrid`, I see that the defualts are quite different, you need to specify latitude, longitude, and z.

I guess the main limitation is that the different grids use different coordinates (which have different names). Not sure I see a way around this besides calling `longitude` `x` and `latitude` `y` etc.

> Also, there is no topology option at all.

Yeah for the `RegularLatitudeLongitudeGrid` the topology depends on the `longitude` bounds. I thought it made sense to make y and z `Bounded` and only make x `Periodic` if `longitude = (-180, 180)`. So then not sure what would happen if a user passes an inconsistent `topology`.

**Comment by francispoulin** [comment]
I think we can, and should, keep different names between the two grids.  We could find a way to convert from spherical coordinates to Cartesian, or the user should be able to do that.  

But I think that having a default extent would be nice and also having topology.  We allow for periodic topology in the vertical because people do that sort of thing, even though it is not strictly correct physically.  I think that allowing for periodic topologies in all three directions would be a nice feature.  This shouldn't be difficult, should it be?

**Comment by glwagner** [comment]
@francispoulin still an issue? Is there a path towards resolving this?

**Comment by francispoulin** [comment]
I have only used the regular grid.  I will start to play with the lat-lon grid soon (hopefuly) and then I will get a better feeling about normalizing.  Will close for now and revisit if the need arises in the future (and I have any ideas).
