### ISSUE TITLE
More comprehensive contributors list?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1519]
What do people think of adding something like https://github.com/all-contributors/all-contributors to our README? 

Basic idea:

> This is a specification for recognizing contributors to an open source project in a way that rewards each and every contribution, not just code.

Could encourage future contributions!

**Comment by francispoulin** [comment]
Neat idea and why not

**Comment by tomchor** [comment]
That's pretty cool! Wasn't aware that existed and I think it's a good idea

**Comment by christophernhill** [comment]
👍

**Comment by glwagner** [comment]
I like it!

**Comment by navidcy** [comment]
I can do this but I think I need repo owner rights (to install the bot)?

**Comment by glwagner** [comment]
@navidcy still interested in this?

**Comment by navidcy** [comment]
let's close this
