### ISSUE TITLE
Error while running a GPU code

### ISSUE THREAD

**Issue by Sumanshekhar17** [CliMA/Oceananigans.jl#1533]
Hi all,
I have been trying to learn this solver, and to do so, I had started with the Convection problem with surface forcing on CPU and slowly increased its complications, and it worked very fine, and now I want to switch to GPU, but I am having an error like this-
```
ERROR: ArgumentError: Cannot create a GPU model. No CUDA-enabled GPU was detected!
Stacktrace:
 [1] IncompressibleModel(; grid::RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}, architecture::GPU, float_type::Type{T} where T, clock::Clock{Float64}, advection::WENO5, buoyancy::SeawaterBuoyancy{Float64,LinearEquationOfState{Float64},Nothing,Nothing}, coriolis::FPlane{Float64}, surface_waves::Nothing, forcing::NamedTuple{(),Tuple{}}, closure::SmagorinskyLilly{Float64,Float64,Float64}, boundary_conditions::NamedTuple{(:u, :v, :T),Tuple{NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Value,Float64},BoundaryCondition{Flux,Int64}}}},NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Value,Float64},BoundaryCondition{Flux,Int64}}}},NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Gradient,Int64},BoundaryCondition{Flux,Array{Float64,2}}}}}}}, tracers::Tuple{Symbol,Symbol}, timestepper::Symbol, background_fields::NamedTuple{(),Tuple{}}, velocities::Nothing, pressures::Nothing, diffusivities::Nothing, pressure_solver::Nothing) at /home/552/ss1986/.julia/packages/Oceananigans/Mt2Rj/src/Models/IncompressibleModels/incompressible_model.jl:102
 [2] top-level scope at REPL[192]:1
```
But the matter of fact is that I am running this code on GPU backed node, and still, it throws an error like this. I have called an interactive session using GPU as following- 
```
[ss1986@gadi-login-03 julia]$ qsub -I -qgpuvolta  -Pds2 -lwalltime=0:30:00,ncpus=12,ngpus=1,mem=50GB,jobfs=100GB,wd
```
And in addition to that, I don't know why it started downloading different versions of CUDA after calling my model function-
```
julia> model = IncompressibleModel(architecture = GPU(),
                                   advection = WENO5(),
                                   timestepper = :RungeKutta3,
                                   grid = grid,
                                   coriolis = FPlane(f=f),
                                   buoyancy = buoyancy,
                                   closure = SmagorinskyLilly(),
                                   boundary_conditions = (u=u_bcs, v=v_bcs, T=T_bcs))
Downloading artifact: CUDA110
-=O=-                                            #     #    #    #            
Downloading artifact: CUDA110
-=O=-                                                         #    #  #  #    
Downloading artifact: CUDA102
-=O=-                                                   #    #    #   #       
Downloading artifact: CUDA102
-=O=-                                                   #    #    #   #       
Downloading artifact: CUDA101
-=O=-                                                   #    #    #   #       
Downloading artifact: CUDA101
-=O=-                                                   #    #    #   #       
ERROR: ArgumentError: Cannot create a GPU model. No CUDA-enabled GPU was detected!
```

Please provide me with some insights into why this problem is happening. Is it with the cluster, or I need to add something?

**Comment by francispoulin** [comment]
@Sumanshekhar17 When we use CUDA, sometimes it needs to download the latest version.  I wonder if that's what your computer is trying to do.  

If you open julia in the project envirnment and try `using CUDA` does that work?  That might be a starting point to know whether you can use `CUDA` on your systme.

**Comment by Sumanshekhar17** [comment]
@francispoulin, yes, sir, I have tried it at the beginning itself, and it worked fine. I am putting the initial piece of my code because that is only the relevant ones. See In this, I tried using CUDA, and it didn't give me any error. 

```
julia> using JLD2

julia> using Oceananigans

julia> using Oceananigans.Utils

julia> using Oceananigans.Grids: nodes

julia> using Oceananigans.Diagnostics: FieldMaximum

julia> using Oceananigans.OutputWriters: JLD2OutputWriter, FieldSlicer, TimeInterval

julia> using Statistics

julia> using CUDA

julia> #number of grid spacing in south, north and vertical direction
       Nx=256
256

julia> Ny=256
256

julia> Nz=64
64
```

**Comment by francispoulin** [comment]
Thanks for checking, and glad you are able to use CUDA.  I presume the above model works if you switch from GPU to CPU?   Have you tried a simpler example?  Say just including the grid and the architecture?  Do you still get the error?

**Comment by Sumanshekhar17** [comment]
Sir, this code worked perfectly on the CPU; that is where I had decided to go to the next level and tried it on GPU. 
Yes, sir, I had tried the suggested example code given in the documentation to run on GPU, The "Wind- and convection-driven mixing in an ocean surface boundary layer" problem. It throws the same error and at the same point after writing the model function in the same way.

**Comment by ali-ramadhan** [comment]
@Sumanshekhar17 Are you building CUDA on a login node that only has a CPU?

Some clusters don't have GPUs on the login node so you might need to instantiate/build/precompile Julia packages on the compute node where a GPU is available.

The error you posted suggests that the packages were built on a CPU node maybe.

**Comment by Sumanshekhar17** [comment]
@ali-ramadhan sir, I was initially building on the CPU node as you have pointed. But I had realised this thing later and ran the code on nodes backing the gpuvolta queue. This is why I am very confused that why I am getting this error. To support my statement I have checked weather I have CUDA module or not-

```
[ss1986@gadi-gpu-v100-0106 julia]$ module avail cuda
---------------------------------------------------------------------------------------- /apps/Modules/modulefiles ----------------------------------------------------------------------------------------
cuda/10.1  cuda/11.0.3  
```

**Comment by glwagner** [comment]
This error is thrown if `CUDA.has_cuda()` is false. @Sumanshekhar17, to debug how julia is connected to your GPU I suggest first just working at the REPL to get `CUDA.has_cuda()` to return `true`.

Can you print the output of `nvidia-smi` from the shell?

**Comment by Sumanshekhar17** [comment]
Sir, I have printed it from gpuvolta node where I am running the code.

![nvidia-smi](https://user-images.githubusercontent.com/67187927/113329377-1cc5a300-933b-11eb-9b1f-c4accf56dd67.PNG)

You were right, ```CUDA.has_cuda()``` gave false as a result.

**Comment by glwagner** [comment]
> You were right, CUDA.has_cuda() gave false as a result.

This means that for some reason `CUDA.jl` doesn't know that you have a cuda installation or a GPU.

This page might help: https://juliagpu.gitlab.io/CUDA.jl/installation/overview/

You may have to ensure that you have the right modules loaded when you build `CUDA.jl`? You can use `Pkg.build(package)` to rebuild a `package`.

**Comment by glwagner** [comment]
PS there's no need to refer to anybody here as "Sir"! I prefer "Greg" (or my github handle).

**Comment by Sumanshekhar17** [comment]
Thank you @glwagner. I sorted out the issue related to CUDA compatibility. Now as I run my code it gives some error which states that there is some array that is not GPU compatible-

```
ERROR: GPU compilation of kernel gpu__fill_top_halo!(Cassette.Context{nametype(CUDACtx),KernelAbstractions.CompilerMetadata{KernelAbstractions.NDIteration.StaticSize{(256, 256)},KernelAbstractions.NDIteration.DynamicCheck,Nothing,Nothing,KernelAbstractions.NDIteration.NDRange{2,KernelAbstractions.NDIteration.StaticSize{(16, 16)},KernelAbstractions.NDIteration.StaticSize{(16, 16)},Nothing,Nothing}},Nothing,KernelAbstractions.var"##PassType#253",Nothing,Cassette.DisableHooks}, typeof(Oceananigans.BoundaryConditions.gpu__fill_top_halo!), OffsetArrays.OffsetArray{Float64,3,CuDeviceArray{Float64,3,1}}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux,Array{Float64,2}}, Int64, Int64) failed
KernelError: passing and using non-bitstype argument

Argument 5 to your kernel function is of type BoundaryCondition{Oceananigans.BoundaryConditions.Flux,Array{Float64,2}}, which is not isbits:
  .condition is of type Array{Float64,2} which is not isbits.
```
I want to mention that I was solving Open ocean convection problem with heat flux as surface forcing. Now the cooling is occurring on a cooling pad which is itself a gaussian function, So I created it as an array like this-
```

const Bo_modified=9e-5/(1-exp(-0.5)) #maximum surface flux

const f=-0.5386   #coriolis parameter

#no Beta plane approximation for periodic boundary condition
#deving the centre of cooling disk
const xc= computational_grid.xC.-mean(computational_grid.xC)
const yc= computational_grid.yC.-mean(computational_grid.yC)

R=zeros(257,257)

for i in 1:1:257
    for j in 1:1:257
        R[i,j]=xc[i]*xc[i]+yc[j]*yc[j]
    end
end

length(R)

findall(R.>1)

Q=zeros(257,257)

for i in 1:1:257
    for j in 1:1:257
        Q[i,j]=Bo_modified*(exp(-0.5*R[i,j])-exp(-0.5))
    end
end

length(Q)

Q[findall(R.>1)].=0

findall(Q.>0)

const dTdz = 0 # K m⁻¹




T_bcs = TracerBoundaryConditions(computational_grid,
                                 top = FluxBoundaryCondition(Q),
                                 bottom = GradientBoundaryCondition(dTdz))
```
I think the problem lies with this, maybe I must upload this data to GPU but the question is HOW?

**Comment by ali-ramadhan** [comment]
@Sumanshekhar17 When using arrays on the GPU you want to use a `CuArray` from the CUDA.jl package. So in your case you want `Q` to be a `CuArray`.

See https://juliagpu.github.io/CUDA.jl/dev/usage/array/ and https://juliagpu.github.io/CUDA.jl/dev/usage/workflow/#UsageWorkflowScalar for more details.

**Comment by Sumanshekhar17** [comment]
@ali-ramadhan, I thought Oceananigans is capable of adopting all CPU arrays into CuArray.  Though you, after manually setting that Q to a CuArray, It worked. And thank you for pointing to the scalar indexing page. It actually threw an error related to that.

**Comment by ali-ramadhan** [comment]
Not yet unfortunately. Definitely something to try and improve by v1.0 though.

Not sure if `arch_array` is exported but you can use it to make your scripts more architecture-agnostic, i.e. it'll use `Array` when `arch = CPU()` and `CuArray` when `arch = GPU()`: https://github.com/CliMA/Oceananigans.jl/blob/407bbd5142b2a072ca663089c2deeeb00ee7f4a4/src/Architectures.jl#L69-L72

**Comment by Sumanshekhar17** [comment]
Thank you @ali-ramadhan 
I got my first GPU result.  For simulating 11 minutes of physics, the CPU took 7 hours, and GPU took to around 5 minutes to simulate the same. That was an incredible speed. The number of GPUs that we have used was 1. And the number of CPUs that were used while we were simulating on a CPU backed node was 48.

https://user-images.githubusercontent.com/67187927/114205003-7a7b7000-9977-11eb-8f54-5d5e022dc8e5.mp4

**Comment by glwagner** [comment]
We have found speed ups of around 200x from a single CPU (one thread) to GPU.

256^3 is a large problem, so I'm not surprised that it runs slowly on a single node with CPUs.

**Comment by glwagner** [comment]
Visualization is beautiful!

**Comment by glwagner** [comment]
@Sumanshekhar17 you might want to look at using a function to specify your boundary condition rather than an array. Functions are more flexible and your script will be a bit easier to read (and you don't have to wrestle with array types).

**Comment by Sumanshekhar17** [comment]
@glwagner, ok Greg. I will take care of these things. Thank you all once again for being nice throughout and for your advice.
