### ISSUE TITLE
Can `AbstractOperations` convert functions to `FunctionField`?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1538]
Might be nice if this worked (although right now we can use `FunctionField` directly which isn't too hard):

```julia
julia> Ψ(λ, φ, z) = - R * u₀ * (sind(φ) * cosd(α) - cosd(λ) * cosd(φ) * sind(α))

julia> ∂x(Ψ)
```

```
julia> ∂x(Ψ)
ERROR: MethodError: no method matching ∂x(::typeof(Ψ))
Closest candidates are:
  ∂x(::Union{Type{Nothing}, Type{Center}, Type{Face}}, ::Union{Type{Nothing}, Type{Center}, Type{Face}}, ::Union{Type{Nothing}, Type{Center}, Type{Face}}) at /home/alir/Oceananigans.jl/src/AbstractOperations/derivatives.jl:45
  ∂x(::Tuple, ::Oceananigans.Fields.AbstractField{X,Y,Z,A,G} where G where A) where {X, Y, Z} at /home/alir/Oceananigans.jl/src/AbstractOperations/derivatives.jl:62
  ∂x(::Oceananigans.Fields.AbstractField{X,Y,Z,A,G} where G where A) where {X, Y, Z} at /home/alir/Oceananigans.jl/src/AbstractOperations/derivatives.jl:89
Stacktrace:
 [1] top-level scope at REPL[18]:1
```

I guess for it to work we would also have to sepcify the location of the function, maybe via
```julia
julia> ∂x(@at (Face, Face, Center) Ψ)
```

**Comment by glwagner** [comment]
`AbstractOperations` does convert functions to `FunctionField` in `BinaryOperations` when the location is specified:

https://github.com/CliMA/Oceananigans.jl/blob/0a880a8bcd9c0efd44f918bc515576d1daaf4ed5/src/AbstractOperations/binary_operations.jl#L80-L81

and can default to the location of the other field involved in the operation when the location is not specified:

https://github.com/CliMA/Oceananigans.jl/blob/0a880a8bcd9c0efd44f918bc515576d1daaf4ed5/src/AbstractOperations/binary_operations.jl#L89-L90

But as you've mentioned for `UnaryOperation` and `Derivative` the location has to be provided.

The syntax you suggest would work though (and is equivalent to `∂x((Face, Face, Center), Ψ)`).

**Comment by glwagner** [comment]
Ah wait, there's no grid either. We need a grid too...

**Comment by glwagner** [comment]
I guess the central point is that `AbstractOperation` are really _discrete_ abstract operations. So we can't generically differentiate functions; however, we can differentiate functions on a particular grid (and at a particular location on the staggered grid).

**Comment by glwagner** [comment]
The suggestion doesn't work because `AbstractOperations` need a grid.

However, binary operations between fields and functions do work because in that case the field provides both the grid and location.
