### ISSUE TITLE
`Connected` topologies

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1582]
For distributed parallelism and cubed spheres it would be useful to introduce the idea of `Connected` topologies: dimensions along which the model is connected to another domain or another model.

They behave very much like `Periodic` dimensions in that you only need to store the first N faces along the dimension, which face N+1 being shared with the domain/model it's connected to. Contrast this with `Bounded` dimensions in which all N+1 faces are stored.

The boundary conditions associated with a `Connected` topology will be some sort of communication, e.g. `HaloCommunication` or `CubedSphereExchange` right now.

For MPI we will also need `LeftConnected` and `RightConnected` for wall-bounded cases where you have a wall on your left and are communicating with another rank on your right (or vice versa).

PR #1522 just adds `const Connected = Periodic` for now since it behaves exactly like `Periodic` for now except with different boundary conditions. We may want to dedicate a separate PR to fleshing out this idea of `Connected` topologies.

**Comment by glwagner** [comment]
> PR #1522 just adds const Connected = Periodic for now since it behaves exactly like Periodic for now except with different boundary conditions.

This is only for the specific case where all of the faces together also cover a Periodic domain, right?

**Comment by ali-ramadhan** [comment]
`Connected{Side}` would be nice, that's a good idea!

> This is only for the specific case where taken together the faces cover a `Periodic` domain, right?

I don't think it matters that the full cubed sphere is `Periodic`. I think the topology is somewhat undefined especially since the `i` or "x"-direction doesn't point in any particular dimension.

I guess the commonality is that with `Periodic` and `Connected` face N+1 is shared with another face whereas with `Bounded` face N+1 is a distinct face.

**Comment by glwagner** [comment]
> I don't think it matters that the full cubed sphere is Periodic. I think the topology is somewhat undefined especially since the i or "x"-direction doesn't point in any particular dimension.

Right, I guess I am thinking of a domain consisting of two connected grids in which the whole domain is bounded. It seems that if `Connected` behaved exactly as `Periodic` then we would have no need for a new type. (I think you understand this and imply it in your text, but I just want to be clear that the only reason `const Connected = Periodic` works is best we are only considering one case).
