### ISSUE TITLE
Non-traditional f-plane approximation

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1591]
In the docs, we have that `γ=−4Ωφ0/R.` but in the code we actually compute the following `γ  = -4Ω*sind(φ)/R`.  There is a sin in the second but note the first. Which of these is correct?

Also, could we have a reference for the final expression for f in the docs?  I admit that I haven't seen this before and would like to look it up.

**Comment by ali-ramadhan** [comment]
Ah sorry there's definitely at least two typos here! I assume you're looking at https://clima.github.io/OceananigansDocumentation/stable/physics/coriolis_forces/#The-non-traditional-f-plane-approximation-2

The section header should be "The non-traditional β-plane approximation". And indeed the code is correct while the docs are wrong.

The implementation is based off of section 5 of Dellar (2011).

Attached: [Dellar, 2011, Journal of Fluid Mechanics, Variations on a beta-plane - derivation of non-traditional beta-plane equations from Hamilton's.pdf](https://github.com/CliMA/Oceananigans.jl/files/6313262/Dellar.2011.Journal.of.Fluid.Mechanics.Variations.on.a.beta-plane.-.derivation.of.non-traditional.beta-plane.equations.from.Hamilton.s.pdf) DOI: https://doi.org/10.1017/S0022112010006464

**Comment by francispoulin** [comment]
Thanks for confirming and the reference.  It's easy for me to change the docs to match with the code if you like?

**Comment by ali-ramadhan** [comment]
That would be great if you have the time!

Indeed the non-traditional β-plane is probably obscure enough that it warrants a citation.
