### ISSUE TITLE
More concise `show(field::Field)` that prints data (like `show(a::Array)`?)

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1612]
Wondering if it makes sense to change how we `show` `Field`, or more generally `AbstractDataField`.

It's nice to see some values, especially for working and debugging at the REPL, without having to type `interior(field)` or `field.data`.

**Comment by glwagner** [comment]
This is what happens now at the REPL:

```julia
julia> a
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (6, 6, 6)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=4, Ny=4, Nz=4)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```

**Comment by navidcy** [comment]
This gets cumbersome (lots of output) if the `data` is 3D...

**Comment by glwagner** [comment]
Maybe a summary like showing `extrema(interior(a))`, and even a mean or standard deviation... ?!?

**Comment by glwagner** [comment]
I do agree that we should take a different approach than Base takes with `Array`, since we can expect that the data is going to be pretty big.
