### ISSUE TITLE
KernelFunctionOperation <: AbstractOperation to enable fast reduction of custom kernel functions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1623]
Now that we have an interface for fast on-the-fly reductions, it might make sense to implement a `KernelFunctionOperation` feature that accepts custom `kernel_function(i, j, k, grid, fields...)` so these can be reduced. (And in fact, this might also provide a replacement for `KernelComputedField`). Something like

```julia
struct KernelFunctionOperation{LX, LY, LZ, P, A, G, T, K, D} <: AbstractOperation{LX, LY, LZ, A, G, T}
    op :: K
    grid :: G
    architecture :: A
    computed_dependencies :: D
    parameters :: P
end

@inline Base.getindex(κ::KernelFunctionOperation, i, j, k) = κ.op(i, j, k, grid, κ.computed_dependencies..., κ.parameters}
@inline Base.getindex(κ::KernelFunctionOperation{LX, LY, LZ, <:Nothing}, i, j, k) where {LX, LY, LZ} = κ.op(i, j, k, grid, κ.computed_dependencies...}
```

With an appropriate `compute!` (or `compute_at!`) method for ensuring that `computed_dependencies` get computed, this might be a better / leaner interface than the one provided by `KernelComputedField`, with the added, extremely useful benefit that it can be reduced on the fly just like other `AbstractOperation`.

**Comment by glwagner** [comment]
Another name might be better too. Something like `FunctionOperation` perhaps, with a property `func`. Since that's all `op` is: just a user-defined function of `(i, j, k, grid, fields..., parameters)`.

**Comment by glwagner** [comment]
@tomchor

**Comment by tomchor** [comment]
That's great. So the differences between this and `KernelComputedField` are the here we can reduce on the fly and we don't need to define a `getindex` method?

**Comment by glwagner** [comment]
Here's the main differences:

1. `FunctionOperation` is not backed by data; eg it doesn't allocate memory (its just a wrapper for a function)
2. `KernelComputedField` requires a `KernelAbstractions` `@kernel`. `FunctionOperation` requires a function of `i, j, k, grid, fields..., parameters)`. It's a subtle but real distinction. Sometimes defining `@kernel` may be more convenient / more readable.
3. The `kernel` in `KernelComputedField` cannot be reduced on the fly (unless this is supported by `KernelAbstractions` someday, somehow, eg https://github.com/JuliaGPU/KernelAbstractions.jl/issues/234, but we don't know what this would look like yet)

Taking the vertical vorticity for curvilinear / cubed sphere grids as an example, usage is

```julia
using Oceananigans.Operators: ζ₃ᶠᶠᵃ # called with signature ζ₃ᶠᶠᵃ(i, j, k, grid, u, v)

grid = model.grid
u, v, w = model.velocities

ζ_op = FunctionOperation(Face, Face, Center, ζ₃ᶠᶠᵃ, grid, computed_dependencies=(u, v))

ζ = ComputedField(ζ_op) # identical to `VerticalVorticityField`

barotropic_ζ = AveragedField(ζ_op, dims=3)
```

On the CubedSphere, `ζ₃ᶠᶠᵃ` cannot be expressed in terms of `AbstractOperations` due to the need to create corners in a special manner.

**Comment by tomchor** [comment]
Understood. Seems like a nice feature!

**Comment by tomchor** [comment]
Oh, wow, talk about fast development! Nice!

**Comment by glwagner** [comment]
🌴
