### ISSUE TITLE
I can't start Oceananigans normally anymore even starting from a fresh install

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1625]
So, let me start by saying that I'm not 100% sure that this issue is an Oceananigans issue or not, but it did start a few weeks ago when the errors due to `ArrayInterface` started and the error only happens with Oceananigans. Also, the error happens in the server I use, but not on my laptop for some reason.

Consider the following session on my laptop. Here I'm trying to make an environment as fresh as possible. (Which is why I'm creating a project from scratch and defining a new `DEPOT_PATH` that isn't `~/.julia`.)

```
(base) tomas@np900:~/Dropbox/tests$ mkdir julia_test
(base) tomas@np900:~/Dropbox/tests$ cd julia_test/
(base) tomas@np900:~/Dropbox/tests/julia_test$ touch Project.toml
(base) tomas@np900:~/Dropbox/tests/julia_test$ export JULIA_DEPOT_PATH="`pwd`/julia_depot"
(base) tomas@np900:~/Dropbox/tests/julia_test$ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.4 (2021-03-11)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(julia_test) pkg> sr
ERROR: Could not determine command

(julia_test) pkg> st
Status `~/Dropbox/tests/julia_test/Project.toml` (empty project)

(julia_test) pkg> st --manifest
Status `~/Dropbox/tests/julia_test/Manifest.toml` (empty manifest)

(julia_test) pkg> add Oceananigans

# LOTS OF THINGS HAPPEN THAT I'M SKIPPING

(julia_test) pkg> precompile
Precompiling project...
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]

julia> using Oceananigans

julia> 

```

So basically this works as expected. You can see the complete output [here](https://pastebin.com/XwghaH7e).

However, if I do that same thing on the server, I get the following. (Note that I'm even using a freshly downloaded Julia binary, to be as general as possible.)

```
(p39) tomasc@casper-login1:~/scratch_cheyenne$ mkdir julia_test
(p39) tomasc@casper-login1:~/scratch_cheyenne$ cd julia_test/
(p39) tomasc@casper-login1:~/scratch_cheyenne/julia_test$ touch Project.toml
(p39) tomasc@casper-login1:~/scratch_cheyenne/julia_test$ export JULIA_DEPOT_PATH="`pwd`/julia_depot"
(p39) tomasc@casper-login1:~/scratch_cheyenne/julia_test$ ~/Downloads/julia-1.5.4/bin/julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.4 (2021-03-11)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(julia_test) pkg> st
Status `/glade/scratch/tomasc/julia_test/Project.toml` (empty project)

(julia_test) pkg> st --manifest
Status `/glade/scratch/tomasc/julia_test/Manifest.toml` (empty manifest)

(julia_test) pkg> add Oceananigans

# THINGS HAPPEN HERE THAT I'LL SKIP

(julia_test) pkg> precompile
Precompiling project...
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]

julia> using Oceananigans

```

The complete session is [here](https://pastebin.com/9frpW70Z).

Everything here is pretty much same, with the only difference being that now the REPL hangs after `using Oceananigans` and nothing happens. I have tested this with other packages but this only happens with Oceananigans.

Something ever weirder: after I get impatient I can cancel the command (pressing `Ctrl+C` repeatedly) and then if I issue the line again it works!:

```julia
julia> using Oceananigans
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^CWARNING: Force throwing a SIGINT

julia> using Oceananigans

julia> grid = RegularRectilinearGrid(size=(1,1,1), extent=(1,1,1))
RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (1, 1, 1)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (1.0, 1.0, 1.0)

julia> 
```

So basically I'm very lost on this one. Two main questions are:

- Why is the `using` command hanging in the first place? (And then working if I cancel and try again?)
- Why is the behavior different between these two machines? I thought I was ensuring that I was starting from a fresh environment in both cases.

Any help here is appreciated!

**Comment by tomchor** [comment]
cc @glwagner

**Comment by glwagner** [comment]
I don't have very much to offer, but I believe that compiler behavior / execution can differ on different machines due to difference in underlying packages and compiler dependencies, even when the julia packages are identical.

If someone else has encountered the same issue then maybe we can make progress?

It'll be nice if upgrading to 1.6 (#1514) solves this.

**Comment by tomchor** [comment]
> I don't have very much to offer, but I believe that compiler behavior / execution can differ on different machines due to difference in underlying packages and compiler dependencies, even when the julia packages are identical.

Yeah, I thought so too, but even using the pre-compiled binaries doesn't seem to fix this so idk anymore...

> It'll be nice if upgrading to 1.6 (#1514) solves this.

I have high hopes that it will!

**Comment by tomchor** [comment]
I'm going to close this since the issue appears to have resolved itself. I didn't change anything on my end, but when I ran the same steps on the server today everything worked, so I'm guessing it had something to do with the server environment that I don't have any control over. Apart from that, I still have no idea what was causing the issue and I hope it doesn't come back to haunt me in the future!
