### ISSUE TITLE
instal

### ISSUE THREAD

**Issue by liasiegelman** [CliMA/Oceananigans.jl#1635]
Hello, I am getting this error while trying to add Oceananigans on the NASA Pleiade cluster. Any ideas? Thanks a lot ! Lia

(@v1.6) pkg> update Oceananigans
    Updating registry at `~/.julia/registries/General`
   Installed HDF5_jll ─── v1.10.5+7
   Installed ColorTypes ─ v0.11.0
   Installed HTTP ─────── v0.9.8
   Installed HDF5 ─────── v0.13.7
   Installed URIs ─────── v1.3.0
  Downloaded artifact: HDF5
  No Changes to `~/.julia/environments/v1.6/Project.toml`
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [3da002f7] ↑ ColorTypes v0.10.12 ⇒ v0.11.0
  [f67ccb44] ↑ HDF5 v0.13.6 ⇒ v0.13.7
  [cd3eb016] ↑ HTTP v0.8.19 ⇒ v0.9.8
  [5c2747f8] + URIs v1.3.0
  [0234f1f7] ↓ HDF5_jll v1.12.0+1 ⇒ v1.10.5+7
    Building HDF5 → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/0b812e7872e2199a5a04944f486b4048944f1ed8/build.log`
Precompiling project...
  ✗ Oceananigans
  15 dependencies successfully precompiled in 101 seconds (143 already precompiled)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

**Comment by liasiegelman** [comment]
then this
<img width="750" alt="Screen Shot 2021-05-04 at 2 43 36 PM" src="https://user-images.githubusercontent.com/37456301/117073736-2c902880-ace7-11eb-86ff-941f7a754f93.png">

**Comment by ali-ramadhan** [comment]
Hi @liasiegelman Oceananigans.jl doesn't fully support Julia 1.6 just yet unfortunately (it's a work in progress in PR #1514).

Does it work if you try with Julia 1.5?

**Comment by ali-ramadhan** [comment]
Hmmm it should precompile with Julia 1.6 (at least as of a week or two ago) so the error is a bit surprising. How did you first install Oceananigans?

**Comment by liasiegelman** [comment]
i used the package manager
