### ISSUE TITLE
using warning

### ISSUE THREAD

**Issue by liasiegelman** [CliMA/Oceananigans.jl#1636]
Hi, do you know how to fix the following ? Thanks 
<img width="751" alt="Screen Shot 2021-05-04 at 2 59 28 PM" src="https://user-images.githubusercontent.com/37456301/117075360-85f95700-ace9-11eb-9d85-3b7cf65491ac.png">

**Comment by ali-ramadhan** [comment]
Oh this is kinda weird. I don't think Oceananigans uses StaticArrays anymore.

What version of Oceananigans.jl and Julia are you using? You should be able to get this info from executing `versioninfo()` and `using Pkg; Pkg.status()` at the REPL.

**Comment by liasiegelman** [comment]
![Uploading Screen Shot 2021-05-04 at 3.26.02 PM.png…]()

**Comment by liasiegelman** [comment]
<img width="403" alt="Screen Shot 2021-05-04 at 3 26 02 PM" src="https://user-images.githubusercontent.com/37456301/117077525-200ece80-aced-11eb-9ee2-c1c60f2870fd.png">

**Comment by ali-ramadhan** [comment]
Ah Julia installed Oceananigans v0.5.1 (an extremely ancient version), probably due to conflicts between dependency versions. The latest release is Oceananigans v0.57.1.

To grab the latest version you can try to explicitly update by typing `] add Oceananigans@0.57.1` in the REPL.

There may be conflicts with some other packages like CUDA v3.1.0. Oceananigans is still depending on CUDA v2 so you might have to `] rm CUDA` to be able to `] add Oceananigans@0.57.1`.

This might also explain the weird error you reported in #1635.

PS: You might encounter issues when using Oceananigans.jl with Julia 1.6 right now. It still requires Julia 1.5 for now.

**Comment by liasiegelman** [comment]
ah thanks but the all point is that I would like to test the GPU  ...

**Comment by liasiegelman** [comment]
I ll try with CUDA there and see what I get.

**Comment by liasiegelman** [comment]
it works but gives me this warning
<img width="746" alt="Screen Shot 2021-05-04 at 4 10 14 PM" src="https://user-images.githubusercontent.com/37456301/117080708-3e77c880-acf3-11eb-8b56-53423c51ce79.png">

**Comment by ali-ramadhan** [comment]
When you `] add Oceananigans` it will bring in a compatible version of CUDA.jl as well so you can still use the GPU.

You only need to `] add CUDA` if you want to use CUDA.jl directly.

**Comment by ali-ramadhan** [comment]
Ah I wouldn't worry about the MPI warning for now.

**Comment by liasiegelman** [comment]
ok cool thanks a lot ! 
So when trying running https://clima.github.io/OceananigansDocumentation/stable/generated/ocean_wind_mixing_and_convection/
I get this warning, seems ok no? 
<img width="788" alt="Screen Shot 2021-05-04 at 4 14 02 PM" src="https://user-images.githubusercontent.com/37456301/117081270-6c114180-acf4-11eb-9b9b-bc25d7f07a63.png">

**Comment by ali-ramadhan** [comment]
That looks good! It's a mostly harmless warning about halo regions that the original `grid` is now different from `model.grid`.

Hopefully if you run the entire example you'll end up with a movie that looks like the one from the example.

**Comment by liasiegelman** [comment]
Yay, thanks a lot Ali !

**Comment by francispoulin** [comment]
@ali-ramadhan and I created that warning message.  Maybe it's too agressive and we should rethink it as people clearly become concerned by it?  Will have to think about that a bit more but glad it's working!

**Comment by glwagner** [comment]
I think the warning is a good idea. Probably a solution to alleviating user stress is to make `halo=(3, 3, 3)` the default, so that the warning is rarely invoked. #1245

**Comment by navidcy** [comment]
Is this resolved or should it stay open?

**Comment by francispoulin** [comment]
I'm okay with the warning message that we have and closing this.
