### ISSUE TITLE
"Dimension-aware" behavior of `set!` and `interior` with `Flat` directions?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1655]
EDIT: We can't set the locations of _all_ `Field` to `Nothing`. So I'm changing this issue topic to a discussion of whether we should support 1- and 2-argument functions for `set!` (when 2 or 1 directions are `Flat`), and also `dropdims` the `Flat` dimensions in `interior`.

Previously:
This would allow us to use two- or one-argument function specification in `set!`, as well as two- and two-dimensional indexing.

It might also make sense to `dropdims` `Nothing` locations when outputting raw field data... (it makes broadcasting with reduced fields, etc more difficult, but probably makes _most_ activities easier, like plotting)... ?

This would automagically solve @francispoulin's pain provided that `Flat` vertical topologies are enforced in the constructor for `ShallowWaterModel`.

**Comment by francispoulin** [comment]
Great idea and I needless to say I'm in favour.

**Comment by glwagner** [comment]
@navidcy @ali-ramadhan any comments? This would change examples and API, because if `Flat` directions have `Nothing` locations then users will specify function initial conditions with 2D or 1D functions, rather than always using 3D functions even in 2D domains as it works now.

**Comment by navidcy** [comment]
I think this makes absolute sense. If one sets up a 2D grid then they can't be imposing 3D initial conditions/forcing functions. :)

This change will allow this if I understood correctly, right?

**Comment by glwagner** [comment]
Correct. `Flat` dimensions will have to be omitted from initial conditions and forcing functions if we make this change.

**Comment by glwagner** [comment]
@simone-silvestri thoughts about this? Major API change so maybe we want to do it sooner rather than later.

I'm not sure if this will affect ensemble models. I don't think it will but I'm not sure.

We probably want to wait until after #2246 .

**Comment by simone-silvestri** [comment]
Hmmm, will the underlying data of a field be 2D and/or 1D in that case?

I think that will be extremely intrusive in the code and create a lot of problems in the future....

**Comment by glwagner** [comment]
All data is always 3D, even when a field has `Nothing` location. See

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/Grids/new_data.jl#L58-L65

and 

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/Grids/grid_utils.jl#L110

In other words, fields with `Nothing` location have size 1.

This change therefore likely affects `set!` primarily. The inner kernels don't know about field location, and we already do endless dispatch on `Flat`:

There is an exception for `Flat` topology, because in this case `N>1` is used for ensemble models; thus https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/Grids/grid_utils.jl#L111-L113

My main concern in fact for this change is how it might affect ensemble models. It _shouldn't_ matter but we may have used a few cheats here and there regarding field location in `Flat` directions...

An alternative strategy, which might actually be better (now that I think about it), is to predicate alternative behavior for functions like `set!` and `interior!` on the grid topology, rather than changing the field location. We can just check for the case that `topology(grid, i) === Flat` and `size(grid, i) == 1`. We can also support _both_ 3D and ND function input (eg `try` 3D, and then resort to ND?)

**Comment by glwagner** [comment]
I guess the way this goes down is via these functions:

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/Fields/function_field.jl#L57-L59

that's why

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/examples/geostrophic_adjustment.jl#L73-L77

is 2D for the free surface.

This'll affect #2246 .

**Comment by glwagner** [comment]
Ok, now I realize that we actually can't do this because it will probably prevent GPU compilation. `ReducedField` keep their location on the GPU, but we can't keep the locations of all fields on the GPU.

I'll change this issue to a discussion of behavior changes for `set!` and `interior` with `Flat` directions.

**Comment by glwagner** [comment]
We changed `set!`.
