### ISSUE TITLE
Change of boundary condition from Periodic to Bounded problem

### ISSUE THREAD

**Issue by jmbeckers** [CliMA/Oceananigans.jl#1656]
I run https://github.com/CliMA/Oceananigans.jl/blob/master/examples/two_dimensional_turbulence.jl with success

but when trying to adapt the  y-boundary ( or x or both) to Bounded

grid = RegularRectilinearGrid(topology=(Periodic, Bounded, Flat),size=(128, 128),extent=(2π, 2π))

 I get the following error (I included a show to show the grid and its size)

```julia
grid = RegularRectilinearGrid{Float64, Periodic, Bounded, Flat}
                   domain: x ∈ [0.0, 6.283185307179586], y ∈ [-1.2810265668750775e-18, 6.283185307179586], z ∈ [0.0, 0.0]
                 topology: (Periodic, Bounded, Flat)
  resolution (Nx, Ny, Nz): (128, 128, 1)
   halo size (Hx, Hy, Hz): (1, 1, 0)
grid spacing (Δx, Δy, Δz): (0.04908738521234052, 0.04908738521234052, 0.0)
┌ Warning: Inflating model grid halo size to (3, 3, 0) and recreating grid. The model grid will be different from the input grid. To avoid this warning, pass halo=(3, 3, 0) when constructing the grid.
└ @ Oceananigans.Grids C:\Users\jmbeckers\.julia\packages\Oceananigans\zj42o\src\Grids\automatic_halo_sizing.jl:41
size(model.grid) = (128, 128, 1)
ERROR: LoadError: DimensionMismatch("array could not be broadcast to match destination")
Stacktrace:
 [1] check_broadcast_shape at .\broadcast.jl:520 [inlined]
 [2] check_broadcast_shape at .\broadcast.jl:521 [inlined]
 [3] check_broadcast_axes at .\broadcast.jl:523 [inlined]
 [4] instantiate(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}},typeof(identity),Tuple{Array{Float64,3}}}) at .\broadcast.jl:269
 [5] materialize! at .\broadcast.jl:848 [inlined]
 [6] materialize! at C:\Users\jmbeckers\.julia\packages\Oceananigans\zj42o\src\Fields\broadcasting_abstract_fields.jl:19 [inlined]
 [7] set!(::Field{Center,Face,Center,CPU,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularRectilinearGrid{Float64,Periodic,Bounded,Flat,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Float64,NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.NormalFlow,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.NormalFlow,Nothing}},CoordinateBoundaryConditions{Nothing,Nothing}}}}, ::Array{Float64,3}) at C:\Users\jmbeckers\.julia\packages\Oceananigans\zj42o\src\Fields\set!.jl:16
 [8] set!(::IncompressibleModel{Oceananigans.TimeSteppers.RungeKutta3TimeStepper{Float64,NamedTuple{(:u, :v, :w),Tuple{Field{Face,Center,Center,CPU,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularRectilinearGrid{Float64,Periodic,Bounded,Flat,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},Float64,NamedTuple{(:x, :y, :z) ....
```

Julia 1.5.2 and sorry if I missed something obvious

**Comment by jmbeckers** [comment]
ok found a partial information 

https://github.com/CliMA/Oceananigans.jl/issues/1192

So I guess it would be nice to have in the doc a list of available combinations ?

**Comment by ali-ramadhan** [comment]
Hi @jmbeckers all topologies are supported now!

I think the issue is that on the staggered grid face-centered fields use N+1 grid cells along `Bounded` dimensions in Oceananigans.jl. So when `topology = (Periodic, Periodic, Flat)` like in the example then

```julia
julia> size(model.velocities.u)
(128, 128, 1)

julia> size(model.velocities.v)
(128, 128, 1)
```

but when you change to `topology = (Periodic, Bounded, Flat)` then the v field gets an extra grid cell in y:

```julia
julia> size(model.velocities.u)
(128, 128, 1)

julia> size(model.velocities.v)
(128, 129, 1)
```

so the initial condition from the example no longer works since it creates an array of size 128x128x1 to use for both u and v:

```julia
u₀ = rand(size(model.grid)...)
u₀ .-= mean(u₀)

set!(model, u=u₀, v=u₀)
```

Perhaps the simplest solution would be to do something like

```julia
u₀ = rand(size(model.velocities.u)...)
u₀ .-= mean(u₀)

v₀ = rand(size(model.velocities.v)...)
v₀ .-= mean(v₀)

set!(model, u=u₀, v=v₀)
```

so that u and v use different random noise arrays with the correct size. I think the example should still exhibit two-dimensional turbulence.

**Comment by jmbeckers** [comment]
yep, makes sense and works. 
Suggestion: add some comments/explanations in https://clima.github.io/OceananigansDocumentation/stable/model_setup/grids/

Thanks !

**Comment by ali-ramadhan** [comment]
Awesome! Yes unfortunately the code has changed a lot recently and the docs have become stale in many places, we're hoping to revise them soon.

> Maybe another possibility is to always have the user interface present fields centered and only when going into calculations doing the decentering/staggering internally. That would keep the user away from internals and staggering conventions.

Yeah for sure. I think one of our goals with Oceananigans.jl is to eventually make it so users never have to think about the staggered grid.

Most examples use functions to initialize fields like

```julia
random_noise(x, y, z) = rand()
set!(model, u=random_noise, v=random_noise)
```

which will work no matter the size of the field, but in the 2D turbulence example we wanted the noise to have zero mean so we had to use arrays.

Perhaps it can be revised to use functions. Either way we can keep this issue open until the docs (or the examples) are revised.

**Comment by francispoulin** [comment]
@ali-ramadhan thanks for finding the problem here.  Did you want to create a new issue or have it resolved here?  

I suppose it is easy to put in your fix for the moment and then revisit this when we try and minimize the users knowledge of the grid?

**Comment by ali-ramadhan** [comment]
I think we can just leave this issue open. I agree it should be easy to switch to

```julia
random_noise(x, y, z) = rand() - 0.5
set!(model, u=random_noise, v=random_noise)
```

if someone wants to open a PR. We might need to modify the plotting code (colorbar limits?) a bit but maybe not too much?

I think the intention behind using random noise with zero mean is so that the vorticity field being visualized looks "nice" being equally negative and positive. But using `random_noise(x, y, z) = rand() - 0.5` might get us close enough for visualization purposes.

**Comment by jmbeckers** [comment]
m2c 

keeping one example with 

u₀ = rand(size(model.velocities.u)...)
u₀ .-= mean(u₀)

v₀ = rand(size(model.velocities.v)...)
v₀ .-= mean(v₀)

set!(model, u=u₀, v=v₀)

would allow to "hide" somehow the staggering, yet allow for easy generalizations by users who really want to work with initializations from arrays instead of functions

**Comment by glwagner** [comment]
Since we can now use broadcasting on fields, another possibility is

```julia
u₀(x, y, z) = rand()
set!(model, u = u₀, v = u₀)
model.velocities.u .-= mean(model.velocities.u)
model.velocities.v .-= mean(model.velocities.v)
```

This emphasizes using function input, which is generally a better way to work, and avoids annoyances associated with `size` (and is shorter and possibly clearer).

**Comment by glwagner** [comment]
> I think the intention behind using random noise with zero mean is so that the vorticity field being visualized looks "nice" being equally negative and positive.

The mean flow has no impact on vorticity --- but you're right that the purpose is aesthetic (a mean flow advects the vorticity field around...) Your original suggestion to use `rand() - 0.5` would essentially solve the problem elegantly (I think `randn` would also work).

I'd be interested to hear from others if they prefer array input. I think for array initial conditions it makes sense to bypass `set!` and just use broadcasting with patterns like `u .= rand(size(u)...)`. I'm curious what a canonical / recommended use case for array input might be.

**Comment by jmbeckers** [comment]
>  I'm curious what a canonical / recommended use case for array input might be. It'd be nice to provide such an example.

Maybe a case using real observations or a case where a coarse resolution model is used to initialize a high resolution model ?

**Comment by francispoulin** [comment]
I think it's nice to explain how to use array input but it's not clear to me that this example is the best place to do it.  I like the idea of having a simple fix here, as was suggested above, and then another example that reads in data or something, as @jmbeckers  suggested.

**Comment by glwagner** [comment]
> > I'm curious what a canonical / recommended use case for array input might be. It'd be nice to provide such an example.
> 
> Maybe a case using real observations or a case where a coarse resolution model is used to initialize a high resolution model ?

Yes, that seems promising! For some problems of that nature we have recommended that people write functions to interpolate their discrete data, since one can then change resolution seamlessly... but perhaps there's a case where writing an interpolator doesn't make sense or is too cumbersome for a simple setup. 🤔

**Comment by jmbeckers** [comment]
> Yes, that seems promising! For some problems of that nature we have recommended that people write functions to interpolate their discrete data, since one can then change resolution seamlessly... but perhaps there's a case where writing an interpolator doesn't make sense or is too cumbersome for a simple setup. 🤔

Writing an interpolator function would certainly be the most elegant way but some user might already be used to other regridding tools (like nco) and would prefer to read in some fields?

A simple fun example for using array inputs:

Prepare a tracer field by backward advecting the attached image or a logo in a Stommel gyre. Save the distorted image and now prepare the example using this distorted image as the initial condition for a forward advection :-)

More seriously you could do the example including backward and forward integration to show the quality difference of several advection schemes.

![image](https://user-images.githubusercontent.com/19711382/118604859-ef7f6800-b7b5-11eb-87de-98934b4df17d.png)

**Comment by glwagner** [comment]
> but some user might already be used to other regridding tools (like nco) and would prefer to read in some fields?

I hadn't thought of that possibility --- that makes sense! Especially since there are often non-trivial constraints on regridding, such as a need for high-order accuracy and/or conservation of volume budgets.

> Prepare a tracer field by backward advecting the attached image or a logo in a Stommel gyre.

I love this idea! We can use this example to both demonstrate working with array data in `HydrostaticFreeSurfaceModel` and also using `velocities = PrescribedVelocityFields` (in addition to demonstrating various advection schemes as you suggest), perhaps on a latitude longitude grid or vertically stretched grid (which have few or no examples right now).
