### ISSUE TITLE
GKS not in proper state

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1657]
Yesterday I tried running the diffusion example on a server and it run but there was a lot of output that appeared when doing simple plotting, see below.  This is not an oceananigans thing as much as a `Plots.jl` thing.

We found out that adding the line `ENV["GKSwstype"]="nul"` seemed to resolve the issue.

Do people know how common a problem this is? If not then nothing to do but if it does happen a lot I wonder whether addin this line in the examples, or somewhere, might be helpful?

```
julia> plt = plot(1:10)
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine FILLAREA
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine FILLAREA
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine POLYLINE
```

**Comment by ali-ramadhan** [comment]
Yeah this has always been an issue on my local setup and at some point Plots.jl/GR.jl stopped working haha (I'm probably missing some library) so I fully switched to CairoMakie.jl.

We use `ENV["GKSwstype"]="nul"` in CI for this reason. It could be good to add to the examples so users don't encounter this issue but it's been a long-standing issue in Plots.jl/GR.jl (https://github.com/JuliaPlots/Plots.jl/issues/1649) but the solution seems to involve installing extra libraries (https://gr-framework.org/julia.html#installation) which gets somewhat user unfriendly...

I wouldn't mind switching to CairoMakie.jl for plotting but Plots.jl is still popular and Makie is still maturing so not sure of the best solution.

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan .  Given that `Plots.jl` is a part of Oceananigans and it does work I don't think there is a need to make any changes necessarily.

I will close this issue here and watch to see what people decide is best for the future of the library.

**Comment by francispoulin** [comment]
Recently, I treid running this example with the change to the environment and now get an error.  See below.  This is more of a problem as no mp4 file is created.  

@ali-ramadhan any suggestions on how to fix this?  

One option is not using `Plots.jl`, but is that what people might want to consider?

```
ERROR: LoadError: failed process: Process(`/home/fpoulin/.julia/artifacts/7f40eeb66d90d3026ae5fb68761c263b57adb840/bin/ffmpeg -v 16 -framerate 15 -i /tmp/jl_CtisJw/%06d.png -vf format=yuv420p -loop 0 -y /scratch/fpoulin/software/Oceananigans.jl/examples/one_dimensional_diffusion.mp4`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:525 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:440
  [3] run
    @ ./process.jl:438 [inlined]
  [4] (::FFMPEG.var"#4#6"{Cmd})(command_path::String)
    @ FFMPEG ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:112
  [5] (::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String})()
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:49
  [6] withenv(::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String}, ::Pair{String, String}, ::Vararg{Pair{String, String}, N} where N)
    @ Base ./env.jl:161
  [7] withenv_executable_wrapper(f::Function, executable_path::String, PATH::String, LIBPATH::String, adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:48
  [8] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [9] invokelatest
    @ ./essentials.jl:706 [inlined]
 [10] #ffmpeg#7
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [11] ffmpeg
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [12] #exe#2
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:111 [inlined]
 [13] ffmpeg_exe
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:123 [inlined]
 [14] buildanimation(anim::Animation, fn::String, is_animated_gif::Bool; fps::Int64, loop::Int64, variable_palette::Bool, verbose::Bool, show_msg::Bool)
    @ Plots ~/.julia/packages/Plots/FKcum/src/animation.jl:101
 [15] #mp4#240
    @ ~/.julia/packages/Plots/FKcum/src/animation.jl:66 [inlined]
 [16] top-level scope
    @ /scratch/fpoulin/software/Oceananigans.jl/examples/one_dimensional_diffusion.jl:153
in expression starting at /scratch/fpoulin/software/Oceananigans.jl/examples/one_dimensional_diffusion.jl:153
```

**Comment by glwagner** [comment]
In an ideal world we would illustrate visualization with a range of plotting utilities, including Plots, Makie, etc.

If you can distill the problem you're encountering to a simple example, you might report it to Plots.jl?

**Comment by francispoulin** [comment]
Thanks @glwagner .  I agree with your vision of an idea world, and hope we get there sometime soonish.

Yes, this is a Plots.jl problem.  I was able to generate exactly the same error with a minimal example, which I posted as an issue [here](https://github.com/JuliaPlots/Plots.jl/issues/3583).  Unfortunately, they have hundreds open issues and not sure when they will be able to address this.

Luckily for me I can run the example on my desktop without a problem but whenever my students and I try it on the server we get an error.  Maybe a problem with how the server is set up?  

I suppose a bandaid would be for us to read in the datafiles and plot them separate, maybe using Makie.  If this turns out to be fruitful maybe it can make its way into the example.

For the moment I will keep this issue open.

**Comment by glwagner** [comment]
Is the server headless? Have you tried writing

```julia
ENV["GKSwstype"] = "100"
```

before running the script?

This is a known issue with GR on headless systems:

* https://github.com/jheinen/GR.jl/issues/278
* https://discourse.julialang.org/t/deactivate-plot-display-to-avoid-need-for-x-server/19359

**Comment by glwagner** [comment]
It might be a GR problem rather than a Plots.jl problem. It might be worth trying to use PyPlot as a backend.

**Comment by francispoulin** [comment]
I did try the `ENV` that you suggested.  Still no go.

I agree that using PyPlot is worth trying.  Unfortunately, that backend doesn't work on the server.  Another thing I need to ask about, because it shoulld

**Comment by glwagner** [comment]
Another thing to try is to ensure that `ffmpeg` works independently.

**Comment by francispoulin** [comment]
Yes, I agree that's a good idea. I will look into that.  Thanks!

**Comment by navidcy** [comment]
Is this resolved?

**Comment by francispoulin** [comment]
Yes, the problem was with ffmpeg on the servers we were using.  Solved as of this morning.  Please close.

Francis


________________________________
