### ISSUE TITLE
Should `examples/mpi_shallow_water_turbulence.jl` be in `examples`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1658]
This script is not being literated so that it appears in the Docs. Does it perhaps belong somewhere else?

**Comment by francispoulin** [comment]
@ali-ramadhan and I talked about having an MPI example and we were going to base it on this one.  To change the physics a ltitle, we thought of introducing a beta-plane and f-plane turbulence already has an example. 

I presume people are in favour of having an MPI example?

**Comment by glwagner** [comment]
Definitely in favor of an MPI example!

I think the point is that the script is not an example now, so it could make sense to put the script in `validation/` until it's ready / someone has time to write the example in Literate style and built into the documentation, and perhaps implement the suggested updates to the physics.

**Comment by francispoulin** [comment]
Good idea.  I will move it to validation in a new PR today then @ali-ramadhan and I can talk about turning this into a real example.
