### ISSUE TITLE
Model setup/Overview is biased towards `IncompressibleModel`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1708]
[Model setup/Overview](https://clima.github.io/OceananigansDocumentation/stable/model_setup/overview/) in Docs only talks about `IncompressibleModel`.

**Comment by glwagner** [comment]
Yes! It'd be nice to add a more meaty example and update the model setup docs for the hydrostatic model since it's at least nascent now.

**Comment by francispoulin** [comment]
I guess a lot of the docs were written for `IncompressibleModel` and the model development has happened faster than the doc development.  I agree we should have more docs on the other models and certainly  happy to help with this for `ShallowWaterModel`, and others as well too.
