### ISSUE TITLE
Model `struct` definitions should be `mutable`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1709]
Should this
https://github.com/CliMA/Oceananigans.jl/blob/6e1842a20e79c85865e294f1a89032462b4d6dd8/src/Models/ShallowWaterModels/shallow_water_model.jl#L41
be a `mutable struct`, like, e.g.
https://github.com/CliMA/Oceananigans.jl/blob/6e1842a20e79c85865e294f1a89032462b4d6dd8/src/Models/IncompressibleModels/incompressible_model.jl#L22
and
https://github.com/CliMA/Oceananigans.jl/blob/6e1842a20e79c85865e294f1a89032462b4d6dd8/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L29
?

**Comment by navidcy** [comment]
cc @francispoulin, @glwagner, @ali-ramadhan

**Comment by glwagner** [comment]
I think making it `mutable` is convenient. In fact, we can probably make a lot more structs `mutable` (eg `Field`...). This could be convenient for some applications, like changing boundary conditions or swapping out parameters in a turbulence closure.

**Comment by navidcy** [comment]
> I think making it `mutable` is convenient. In fact, we can probably make a lot more structs `mutable` (eg `Field`...). This could be convenient for some applications, like changing boundary conditions or swapping out parameters in a turbulence closure.


27d14cb does that
