### ISSUE TITLE
What's the use of `clock` as argument in the `Models`' constructors?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1710]
https://github.com/CliMA/Oceananigans.jl/blob/2d20b90f2a8a9064b8efa50b678702f6fb162135/src/Models/ShallowWaterModels/shallow_water_model.jl#L63

I can't see what this is used for. Should we remove it perhaps? @francispoulin?

**Comment by glwagner** [comment]
Surely there's a `model.clock` property.

I agree that it's almost practically pointless to have it as a kwarg though. It's not very hard to write `model.clock.iteration = new_iteration` if you want to change the clock iteration.

**Comment by navidcy** [comment]
My point was not that it shouldn't be part of the model but I didn't understand the necessity being a kwarg in the constructor.

**Comment by francispoulin** [comment]
I can't say that I know why this is here and I am happy to for it to be changed to something that makes more sense.

**Comment by navidcy** [comment]
OK, that's what I meant really. Not so much that it could never be used but I thought it was a rather strange feature to support: that is allowing the user to create a clock outside and providing it in the constructor.

**Comment by glwagner** [comment]
I agree it's not a necessary feature to support. Also since the model is `mutable` you can always replace `model.clock` with something else if you really must (eg if you need to share `clock` with another object).

**Comment by navidcy** [comment]
I'll simplify the ShallowWaterModel constructor in a new PR...

**Comment by navidcy** [comment]
I now saw that the `Clock` is in all model constructors...

**Comment by glwagner** [comment]
Yeah, let's remove from all! Ha!

**Comment by navidcy** [comment]
OK, perhaps the `test_simulations.jl` helped me see now the reason for introducing `clock` as `kwarg`. You initialise a model with any starting date you like. Let's leave the `clocks` there. I'm closing the PR.
