### ISSUE TITLE
`ShallowWaterModel` on `Float32`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1724]
At the moment I think it's not an option. But I think it will be easy to implement.

**Comment by glwagner** [comment]
I think if you make the grid `Float32` it should make most of the model `Float32`? I think we should use this abstraction for `IncompressibleModel` too.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
