### ISSUE TITLE
Bug in `VerticallyStretchedRectilinearGrid` constructor

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1725]
Looks like this should be `upper_exterior_Δzᵃᵃᶜ`:

https://github.com/CliMA/Oceananigans.jl/blob/ff61bea400a05435561809df7d65a61c8d32dc33/src/Grids/vertically_stretched_rectilinear_grid.jl#L208

**Comment by navidcy** [comment]
Resolved by #1754.
