### ISSUE TITLE
problems in setting `BoundaryConditions` in `ImmersedBoundary`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1730]
Building on #1718 , I'm trying to set boundary conditions in a `ShallowWaterModel` example using `ImmersedBoundary`.  The actual problem I want is more complicated then this but as a first step I thought I would just set the height to be a fixed value at the north and south boundaries.  The immersed boundary creates a cap on the west.

```
using Oceananigans
using Oceananigans.Grids
using Oceananigans.Models
using Oceananigans.ImmersedBoundaries: ImmersedBoundaryGrid, GridFittedBoundary

using Oceananigans.BoundaryConditions: NormalFlow, Value

grid = RegularRectilinearGrid(size=(16, 16), x=(-10, 10), y=(0, 5), topology=(Periodic, Bounded, Flat))

bump(x, y, z) = y < exp(-x^2)

grid_with_bump = ImmersedBoundaryGrid(grid, GridFittedBoundary(bump))

@inline inflow(i, k, grid, clock, model_fields)  = @inbounds model_fields.h[i, 1, 1]

@inline outflow(i, k, grid, clock, model_fields) = @inbounds model_fields.h[i, grid.Ny, 1]

h_bcs = TracerBoundaryConditions(grid;
                               north = BoundaryCondition(Value, 2.0),
                               south = BoundaryCondition(Value, 2.0),
                             )

model = ShallowWaterModel(grid=grid_with_bump, gravitational_acceleration=1, boundary_conditions=(h=h_bcs,))

set!(model, h=1)
```

The error that I get is copied below. Any one know why `set!` is trying to use `Δy`?

```
ERROR: TaskFailedException

    nested task error: MethodError: no method matching Δy(::Int64, ::Int64, ::Int64, ::ImmersedBoundaryGrid{Float64, Periodic, Bounded, Flat, RegularRectilinearGrid{Float64, Periodic, Bounded, Flat, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}}, GridFittedBoundary{typeof(bump)}})
    Closest candidates are:
      Δy(::Any, ::Any, ::Any, ::RegularRectilinearGrid{FT, TX, Flat, TZ, R} where {TZ, R}) where {FT, TX} at /home/fpoulin/software/Oceananigans.jl/src/Operators/spacings_and_areas_and_volumes.jl:58
      Δy(::Any, ::Any, ::Any, ::AbstractRectilinearGrid) at /home/fpoulin/software/Oceananigans.jl/src/Operators/spacings_and_areas_and_volumes.jl:35
```

**Comment by glwagner** [comment]
It looks like `set!` for `ShallowWaterModel` calls` update_state!`:

https://github.com/CliMA/Oceananigans.jl/blob/070eab4079eafd9ecc966637ccff949f84906677/src/Models/ShallowWaterModels/set_shallow_water_model.jl#L17

This function may fill halo regions, which require grid spacings.

**Comment by glwagner** [comment]
I will implement halo filling for curvilinear boundary conditions to solve this.

Until then, can you try a horizontally-periodic domain for this example?

**Comment by francispoulin** [comment]
I changed the domain to be periodic in both horizontal directions and unfortunately, it still results in the same error.

**Comment by glwagner** [comment]
Even if you change the boundary conditions?

**Comment by francispoulin** [comment]
No, that was with the same boundary conditions.  I suppose if the domain is periodic I should impose derivative boundary conditions?

**Comment by glwagner** [comment]
You cannot impose boundary conditions in a periodic direction. See #1732 .

**Comment by glwagner** [comment]
Sorry about the unclear advice. Here's what I mean:

1. Change the x-boundary conditions to periodic, and use an initially constant inflow (I now see this was already the case --- sorry for not reading the code more closely. I was confused by the functions called `inflow` and `outflow` and assumed that non-periodic conditions were being used in `x`)
2. Eliminate Coriolis so the flow does not have to be in geostrophic balance
3. Use default boundary conditions on `h`

Thinking about this more, I am not sure that `ShallowWaterModel` supports `Value` and `Gradient` boundary conditions. These can only be specified with respect to a second-order flux. Without a flux there is no possibility to support `Value` and `Gradient`.

Another possibility to keep Coriolis + meridional height gradient is to impose relaxation to a constant gradient as a forcing in the height equation. Or, you can impose `Flux` boundary conditions that restore the height field to 1 and 2 at the north and south boundaries.

**Comment by francispoulin** [comment]
Thanks for the further thoughts.

We don't actually want a `Value` boundary condition I just wanted to find a simple example to set something.  Clearly I choose badly.  Sorry.

What I actually need to impose `NormalFlow` boundary condition, as I first mentoined to you. Unfortunately, when I tried that it didn't seem to have any effect.  I should go back to the problem I wanted to solve originally and try and figure out why the boundary condtions were not being imposed.  I'm pretty sure that normal flow is something we can impose without having second-order fluxes.

**Comment by glwagner** [comment]
You should be able to impose `NormalFlow` (we've done this for flow past a cylinder, I think).

The outflow condition is tricky. In reality we want a condition like an Orlanski / radiation boundary condition, but we don't have those implemented. In lieu of that you'll have to use a sponge layer to relax the velocity / transport to what's specified at the outflow. But in that case a periodic domain + downstream sponge layer could work just as well.

A `NormalFlow` boundary condition doesn't need grid metrics so that should work without this particular error.

**Comment by glwagner** [comment]
But more fundamentally I do not think that a `Value` boundary condition can be enforced on `h` because it is a first-order field, correct?

**Comment by francispoulin** [comment]
Yes I agree that we should not be imposing a `Value` condition on `h`. Sorry I tried doing such silliness.

I agree that imposing inflow wiith a sponge would be a nice way of doing things and I should probably start in a rectangular domain, since that is easier.  

I know there are some examples of sponges but don't know which one I should look at.  I pressume using Rayleigh damping is the way to go.  Is there a particular script you can suggest I start to look at?

**Comment by glwagner** [comment]
There's some examples here:

https://clima.github.io/OceananigansDocumentation/stable/model_setup/forcing_functions/#Relaxation

Some don't like `GaussianMask` because its too broad. It could be better to define a custom mask with a `tanh` that's sharper.

**Comment by glwagner** [comment]
Here's some sample code:

```julia
        damping_rate = 1/100 # relax fields on a 100 second time-scale
temperature_gradient = 0.001 # ⁰C m⁻¹
 surface_temperature = 20    # ⁰C (at z=0)

const x0= 10 # center point of sponge
const dx = 0.5 # sponge width
smoothed_step_mask(x, y, z) = 1/2 * (1 + tanh((x-x0) / dx))

uh_sponge = Relaxation(rate=damping_rate, mask=smoothed_step_mask, target=1)
  h_sponge = Relaxation(rate=damping_rate, mask=smoothed_step_mask, target=1)
```

**Comment by francispoulin** [comment]
I dont think the inflow is from the cape as the cape is the west boundary.

I am happy to have a zonal flow instead, but what I was trying to do was just rotated by 90 degrees.  In either case the inflow outflow should be parallel to the boundary that is immersed.

**Comment by glwagner** [comment]
Ah, but the "cape" is oriented in x --- it sticks out from the southern boundary with unit 1 and tapers to 0 as x -> -infty and +infty. If the flow comes in from the west, it would impinge on the cape. Right?

**Comment by jmbeckers** [comment]
For imposing elevation (h) at boundaries (as for tides), you might want to use Flather's (1976) approach.

**Comment by francispoulin** [comment]
Clearly I was very mixed up in terms of my directions but I think I have improved things and you can see my code below.

- At the moment, the sponge is only to the west.  Since I am imposing outflow conditions to the east I feel like I should have a second sponge there.  Or, said differently, have a sponge that is zero in the interior but turns on both to the west and east. Agreed?
- Some good news is that I do seem to be imposing boundary conditions.  Bad news, there is some asymmetry in that the inflow condition does no seem to be imposed at `x=-10` along the southern wall.  I can't think if a physical reason why that would be the case.  Any ideas?
- Is there an easy way to plot the grid?  It occurs to me that if I had done this at the beginning I would have avoided a bit of trouble that I created for myself.

```
julia> model.solution.uh[:,:,1]
14×14 OffsetArray(::Matrix{Float64}, -2:11, -2:11) with eltype Float64 with indices -2:11×-2:11:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

```

```
using Oceananigans
using Oceananigans.Grids
using Oceananigans.Models
using Oceananigans.ImmersedBoundaries: ImmersedBoundaryGrid, GridFittedBoundary

using Oceananigans.BoundaryConditions: NormalFlow

grid = RegularRectilinearGrid(size=(8, 8),
                              x=(-10, 10), y=(0, 5),
                              topology=(Periodic, Bounded, Flat),
                              halo=(3,3))

bump(x, y, z)  = y < exp(-x^2)
grid_with_bump = ImmersedBoundaryGrid(grid, GridFittedBoundary(bump))

damping_rate = 1/100     # relax fields on a 100 second time-scale
const x0 = -10           # center point of sponge
const dx = 1.0           # sponge width
smoothed_step_mask(x, y, z) = 1/2 * (1 + tanh((x - x0) / dx))

uh_sponge = Relaxation(rate=damping_rate, mask=smoothed_step_mask, target=1)
 h_sponge = Relaxation(rate=damping_rate, mask=smoothed_step_mask, target=1)

@inline inflow(j, k, grid, clock, model_fields)  = @inbounds model_fields.h[1,       j, 1]
@inline outflow(j, k, grid, clock, model_fields) = @inbounds model_fields.h[grid.Nx, j, 1]

uh_bcs = VVelocityBoundaryConditions(grid,
        west = NormalFlowBoundaryCondition(inflow,  discrete_form=true),
        east = NormalFlowBoundaryCondition(outflow, discrete_form=true));

model = ShallowWaterModel(grid=grid_with_bump,
                          gravitational_acceleration=1,
                          boundary_conditions=(uh=uh_bcs,),
                          forcing = (uh=uh_sponge, h=h_sponge))

set!(model, h=1)
simulation = Simulation(model, Δt=1.0, stop_iteration=1)
run!(simulation)
```

**Comment by francispoulin** [comment]
Thanks @jmbeckers for the suggestion. I don't konw that paper but I will dig it up and take a look.
