### ISSUE TITLE
Changing an example to use VerticallyStretchedGrids

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1752]
I noticed that none of the examples currently use a `VerticallyStretchedGrid`. In the future I have plans of adding a bottom boundary layer example that will do just that, but in the meantime I was thinking of converting one of the examples to a vertically stretched grid.

The candidates for me are the [convecting plankton](https://clima.github.io/OceananigansDocumentation/stable/generated/convecting_plankton/), [ocean wind and convection](https://clima.github.io/OceananigansDocumentation/stable/generated/ocean_wind_mixing_and_convection/) and the [Langmuir turbulence](https://clima.github.io/OceananigansDocumentation/stable/generated/langmuir_turbulence/) one. My preference was to apply it to the [ocean wind and convection](https://clima.github.io/OceananigansDocumentation/stable/generated/ocean_wind_mixing_and_convection/) example.

Would anyone oppose or should I open a PR?

**Comment by glwagner** [comment]
I think `ocean_wind_and_convection.jl` is a good choice!

#1744 also uses `VerticallyStretchedRectilinearGrid`.
