### ISSUE TITLE
Manual adjustment invalidates grid spacings in `VerticallyStretchedRectilinearGrid`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1753]
The constructor for `VerticallyStretchedRectilinearGrid` contains:

https://github.com/CliMA/Oceananigans.jl/blob/55500496bc76e5870a0e455d1dda059793e827d3/src/Grids/vertically_stretched_rectilinear_grid.jl#L160-L162

which adjusts the vertical grid spacing at the cell interface just below the top boundary.

This adjustment must then render grid calculations inaccurate, because none of the other metrics or node locations are adjusted.

What's going on?

**Comment by glwagner** [comment]
Found it.

This line:

https://github.com/CliMA/Oceananigans.jl/blob/55500496bc76e5870a0e455d1dda059793e827d3/src/Grids/vertically_stretched_rectilinear_grid.jl#L208

should use `upper_exterior_...`.

The grid metrics must not be tested, otherwise these bugs could not exist.

**Comment by glwagner** [comment]
This will hopefully fix the first problem.

https://github.com/CliMA/Oceananigans.jl/pull/1754

**Comment by tomchor** [comment]
Didn'y https://github.com/CliMA/Oceananigans.jl/pull/1755 solve this issue?

**Comment by glwagner** [comment]
Hmm yes, thanks for catching that; not sure why it didn't get closed automagically.
