### ISSUE TITLE
Change notation in Docs/Pressure Decomposition

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1757]
Should we change φ -> p at 
https://clima.github.io/OceananigansDocumentation/dev/numerical_implementation/pressure_decomposition/
to be in compliance with notation in
https://clima.github.io/OceananigansDocumentation/dev/physics/incompressible_model/
or
https://clima.github.io/OceananigansDocumentation/dev/physics/hydrostatic_free_surface_model/
?

**Comment by francispoulin** [comment]
Seems like a good idea to me.  I vote yes

**Comment by glwagner** [comment]
I support this. I think originally there was some desire to preserve "p" for the _dynamic_ pressure (rather than kinematic pressure). But we don't mention dynamic pressure in the docs so this desire doesn't seem crucial right now.
