### ISSUE TITLE
Does `docs/make.jl` adds the right directory to path?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1777]
I believe that 

https://github.com/CliMA/Oceananigans.jl/blob/b22057a49dfe25b1b091d4d4c9cdb0e126bc0c62/docs/make.jl#L1

should be replaced with

```julia
push!(LOAD_PATH, joinpath(@__DIR__, "."))
```

Supposedly `docs/make.jl` from the repo's home directory, right? Thus going a level up is not appropriate?

But a better way to do it is to delete `push!(LOAD_PATH...` from within `docs/make.jl` completely and make sure we include it in our workflow when building the docs locally or on servers, e.g., see 

https://github.com/JuliaGPU/CUDA.jl/blob/96d6e11259053573ad8164f462d9f9eb8e204893/.buildkite/pipeline.yml#L338-L342

cc: @ali-ramadhan, @glwagner

**Comment by glwagner** [comment]
No, the purpose of this line is to add the Oceananigans root directory to the load path. This allows the local version of `Oceananigans` to be used when building the docs.

**Comment by glwagner** [comment]
Maybe I didn't answer the question. The macro `@__DIR__` returns the path of the file it's written in. In this case, it returns that path of `docs/make.jl`. Thus we have to go up one level to get to the root directory for Oceananigans.

**Comment by navidcy** [comment]
```Julia
help?> @__DIR__
  @__DIR__ -> AbstractString

  Expand to a string with the absolute path to the directory of the file containing the macrocall. Return
  the current working directory if run from a REPL or if evaluated by julia -e <expr>.
```

**Comment by navidcy** [comment]
OK, I see your point @glwagner and I agree.

I want to raise something else then, I suggest we change

```
push!(LOAD_PATH, joinpath(@__DIR__, ".."))
```

to 

```
pushfirst!(LOAD_PATH, joinpath(@__DIR__, ".."))
```

so that Oceananigans.jl main repo folder has priority over the Julia's generic environment on the particular computer. That is, of course, with the assumption that the order in the `LOAD_PATH` vector matters.

**Comment by glwagner** [comment]
Agree that `pushfirst!` is better than `push!`. We ran into this issue with @whitleyv the other day.

@simonbyrne tagging you since we discussed this some weeks ago.

**Comment by navidcy** [comment]
I think this is the issue @francispoulin was having.

**Comment by glwagner** [comment]
`push!` fails when `Oceananigans` is present in the global environment.

**Comment by navidcy** [comment]
> `push!` fails when `Oceananigans` is present in the global environment.

Exactly!
