### ISSUE TITLE
Can units be `nothing`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1778]
Some problems are not formulated in dimensional units, see, e.g., [2D turbulence example](https://clima.github.io/OceananigansDocumentation/dev/generated/two_dimensional_turbulence/#Running-the-simulation) and thus reporting time in `seconds` seems weird. Any (easy) way to inform `Clock` that time is non-dimensional?

**Comment by tomchor** [comment]
Do you mean through approaches such as incorporating [Unitful.jl](http://painterqubits.github.io/Unitful.jl/stable/) to Oceananigans? Or just a flag on `Simulation`/`Model` that switches from SI to nondimensional?

**Comment by glwagner** [comment]
@navidcy may be referring to a couple of places / messages where "no units" is assumed to mean "SI units". I don't think we support explicit units though. It seems overkill to wrap every float for the purpose of a few messages. We could maybe attach some metadata to `Simulation`. What kind of API would be "easy" @navidcy ? Is it `Clock` that needs to know dimensions, or just things that print messages?

**Comment by navidcy** [comment]
I was thinking of `Clock` but I agree it may be overkill. Let's leave it for now and deal with other issues :)

**Comment by navidcy** [comment]
Also, btw, this is a duplicate of #1462.
