### ISSUE TITLE
GPU CI is actually running tests on the CPU

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1794]
Looking at the latest Buildkite build for the master branch it looks like GPU CI is only running CPU tests: https://buildkite.com/clima/oceananigans/builds/3045

Not sure why this would be the case... `CUDA.versioninfo()` seems to return the expected info on Sverdrup during initialization: https://buildkite.com/clima/oceananigans/builds/3045#ad4268d2-9b56-4cc0-ab46-ab9fdd61527b/31-253

I wonder if `CUDA.has_cuda()` is returning `false` on Sverdrup for some weird reason? https://github.com/CliMA/Oceananigans.jl/blob/dfc028667493bdd0eb1056d66d287c46e2591a7f/test/runtests.jl#L56

**Comment by ali-ramadhan** [comment]
Looks like this happened in PR #1740 as https://buildkite.com/clima/oceananigans/builds/2893 looks fine (GPU tests) but the next commit/build on master is not fine https://buildkite.com/clima/oceananigans/builds/2895 (no GPU tests).

Maybe this had something to do with CUDA.jl v3.3.0 or with the addition of the `JULIA_CUDA_USE_BINARYBUILDER="true"` environment variable?

**Comment by navidcy** [comment]
This is important to fix!

Why is `JULIA_CUDA_USE_BINARYBUILDER="true"` needed?

**Comment by glwagner** [comment]
I can use CUDA on sverdrup:

```julia
julia> using CUDA

julia> CUDA.has_cuda()
true

julia> CuArray(rand(3))
3-element CuArray{Float64, 1}:
 0.5230283963088462
 0.0396121811777137
 0.04373785020067866
```

so this suggests that indeed the problem is with the buildkite setup.

> Why is JULIA_CUDA_USE_BINARYBUILDER="true" needed?

This was needed briefly when an nvidia driver went out of date. It is no longer out of date, however, so this environment variable is not needed anymore.

**Comment by glwagner** [comment]
Interesting tidbit: while calling `CUDA.versioninfo` here:

https://github.com/CliMA/Oceananigans.jl/blob/b4e217244f1d594ce2854260e4dfa5c97156e162/.buildkite/pipeline.yml#L27

seems innocuous, it actually triggers `CUDA` to download things like `CUDNN`:

```
julia> CUDA.versioninfo()
CUDA toolkit 11.3.1, artifact installation
CUDA driver 11.3.0
NVIDIA driver 465.27.0

Libraries: 
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+465.27
  Downloaded artifact: CUDNN
- CUDNN: 8.20.0 (for CUDA 11.3.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA Quadro P6000 (sm_61, 23.343 GiB / 23.869 GiB available)
```

I don't think we need to download those artifacts otherwise. But I'm not 100% sure.

it also seems to be throwing an error on #1799 though I'm not sure why.
