### ISSUE TITLE
Inconsistency in `Field`s constructors?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1813]
Seems like the `CenterField` docstring claims that default `arch` is `CPU()` but the code doesn't seem to be in  agreement with that, right?

https://github.com/CliMA/Oceananigans.jl/blob/e5a3d10df0d350af541613b5a47e963252f8f35d/src/Fields/field.jl#L70-L84

(Btw, similarly for `DFaceField` where `D in [X, Y, Z]`.)

**Comment by glwagner** [comment]
The docstring relies on code being correct a few lines down:

https://github.com/CliMA/Oceananigans.jl/blob/e5a3d10df0d350af541613b5a47e963252f8f35d/src/Fields/field.jl#L134-L138
