### ISSUE TITLE
`T` or `θ` for conservative temperature and `S` or `sᴬ` for absolute salinity?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1814]
There are some inconsistencies in the docstrings. E.g.,

https://clima.github.io/OceananigansDocumentation/dev/library/#Oceananigans.BuoyancyModels.LinearEquationOfState   

https://clima.github.io/OceananigansDocumentation/dev/library/#Oceananigans.BuoyancyModels.∂x_b-Tuple{Any,%20Any,%20Any,%20Any,%20SeawaterBuoyancy,%20Any}

**Comment by glwagner** [comment]
Right. We should either use `θ, sᴬ` in the code, or `T, S` in the docstring.

It's probably convenient for some people to use `T, S` in the code. I would be open to `θ, S` too but I don't think it matters much. I used to be annoyed by `T, S`...
