### ISSUE TITLE
Regular lat-lon grid can only be [-180, 180]?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1815]
https://github.com/CliMA/Oceananigans.jl/blob/e5a3d10df0d350af541613b5a47e963252f8f35d/src/Grids/regular_latitude_longitude_grid.jl#L33

What if we wanted to use `λ ∈ [-280, 80]`?

(Often people use this domain to avoid having the "seam" in the middle of the Pacific...)

**Comment by glwagner** [comment]
I don't think there's any reason to use those specific endpoints. We probably just want to make sure that there aren't more than 360 deg of longitude... ?
