### ISSUE TITLE
Energy/enstrophy conserving schemes for Coriolis

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1818]
On a c-grid computing the Coriolis term could lead to energy/enstrophy loss. Schemes by Sadourny (1975) help alleviate this. These schemes are implemented on the sphere, e.g.,

https://github.com/CliMA/Oceananigans.jl/blob/master/src/Coriolis/hydrostatic_spherical_coriolis.jl

However, they are not implemented for `RegularRectilinearGrid`.

cc: @glwagner

**Comment by francispoulin** [comment]
I don't know how the spherical hydrostatic model does this but I agree this would be nice to have for the rectilinear model as well.

From what I recall from Sadourny (1975) you can have either energy or enstrophy conserving schemes, depending on how you do the averaging.  When I played around with them I found that the enstrophy conserving scheme managed to prevent a numercial instability that can occur, but the energy conserving scheme did not.  But getting either one (or both) working would be great!

**Comment by glwagner** [comment]
All that's really needed is to define

https://github.com/CliMA/Oceananigans.jl/blob/0415938fa0fbd9cb581e3301b31083e064519b06/src/Coriolis/hydrostatic_spherical_coriolis.jl#L33-L34

for other `coriolis` schemes and possibly grids.

The code should be restructured a bit. If we do that, the only that makes coriolis "spherical" or not is the dependence of `f` on `i, j`. So we should put the definition of the Sabourny stencils in a new file.

**Comment by glwagner** [comment]
We have this
