### ISSUE TITLE
Should we store `architecture` in `grid`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1825]
In the general case of a pre-computed grid or mesh, the `architecture` on which the grid is stored has be known. Thus in general, the `architecture` of a grid must be provided.

The few special cases to this rule are grids with metrics that are either constant or can be computed on the fly, like `RegularRectilinearGrid`. Up to recently `RegularRectilinearGrid` was the only option, so we hadn't the motivation to ponder whether `architecture` belonged as a model property, field property, or grid property...

Putting `architecture` in `grid` would mean that we don't have to specify it in model constructors. Since `grid` is so central we wouldn't really need `architecture` as a property anywhere else. For example, we wouldn't need to store `architecture` in every.single.field object, as we do now. Alleviating this boilerplate makes the change feel especially right...

The main downside is a loss of flexibility for those grids that are truly architecture-independent, like `RegularRectilinearGrid` and `RegularLatitudeLongitudeGrid`. On the other hand, we have to specify `architecture` somewhere and rarely helpful to mix `CPU` and `GPU` computations using the same grid.

**Comment by francispoulin** [comment]
Thanks for the nice summary @glwagner .  

I vote for storing `architecture` in `grid`.

**Comment by navidcy** [comment]
`architecture` lives in the `Grid` in FourierFlows.jl (if that's an argument.. haha)

**Comment by navidcy** [comment]
Also, `float_type` is part of the grid and all field defined on the grid could inherit that, right?
(perhaps this is already the case?)

**Comment by glwagner** [comment]
`eltype(grid)` propagates everywhere because of defaults like

https://github.com/CliMA/Oceananigans.jl/blob/f7408dc08c30ec6a3ced11d70d3458634f0fd071/src/Grids/new_data.jl#L67

`grid` seems like a good place for users to specify `architecture` and `grid`. I think the API is better if important things like that only need to be specified once.

**Comment by glwagner** [comment]
@ali-ramadhan would be good to get your thoughts before doing anything. Does this help / hurt memory distributed models?

**Comment by francispoulin** [comment]
Out of curiosity, when we create a PR, is it possible to find out how long the tests take compared to before? It seems like it might be useful when making a change like this, as well as pretty much anything else.

**Comment by glwagner** [comment]
The amount of time it takes each step to run is reported by `buildkite`:

![image](https://user-images.githubusercontent.com/15271942/125081447-3e919d00-e083-11eb-9207-fd179caf44a4.png)

**Comment by francispoulin** [comment]
Thanks.  And I guess you can go to the latest merge to find out how long it used to take? It seems like showing the difference might be helpful, in case there is a big difference but that is probably wishing for the stars.

**Comment by glwagner** [comment]
Right, you can reference prior PRs to compare old build times to a new build time.

Custom reports might be possible, I don't know! Could be worth checking out the buildkite documentation. If you want something written into the PR I think you have to build a bot or something. Also possible, probably not "hard" once you know what to do.

**Comment by navidcy** [comment]
But since all tests run on a computer at MIT the time it takes also depends on how many tests are running (eg how many prs were just open) and other random factors.

**Comment by glwagner** [comment]
Right, there are some caveats on how you interpret those times. They aren't a benchmark.

**Comment by francispoulin** [comment]
I guess bennchmarks are the best way to tell and we should run those often enough to see whether anything has changed singificantly.  Thanks.

**Comment by glwagner** [comment]
Looking at the code for `DistributedIncompressibleModel`:

https://github.com/CliMA/Oceananigans.jl/blob/6e39d3fcc098c69ac207cc21be759cf6bd3ec604/src/Distributed/distributed_incompressible_model.jl#L8-L36

suggests to me that it's important to include `architecture` when constructing `grid`, even for grids that are _device_ independent. Specifically, our `architecture` object combines information about the memory layout and the device that's used for computation (CPU or GPU). `RegularRectilinearGrid` is _device_ independent, but, apparently, is in practice not `architecture` in dependent (because we need to restrict ourselves to knowledge of just a "local" grid for local computations).

One complication is that, apparently, the pressure solver requires the global grid:

https://github.com/CliMA/Oceananigans.jl/blob/6e39d3fcc098c69ac207cc21be759cf6bd3ec604/src/Distributed/distributed_incompressible_model.jl#L40-L41

We'll have to look into that in more detail to understand what needs to be done for that, and for other solvers like the `PreconditionedConjugateGradientSolver`.

**Comment by glwagner** [comment]
@ali-ramadhan can we "reconstruct" the full grid parameters needed to build the `DistributedFFTPoissonSolver`, rather than passing `full_grid` as an argument to the constructor?

https://github.com/CliMA/Oceananigans.jl/blob/6e39d3fcc098c69ac207cc21be759cf6bd3ec604/src/Distributed/distributed_fft_based_poisson_solver.jl#L13-L31

I think we just need an `Allgather` to infer the global number of grid points and global grid extent from each process-local grid. 

`DistributedShallowWaterModel` doesn't use the global grid at all except to build the process-local grids.

**Comment by glwagner** [comment]
As for the API, it might simplify matters to have `architecture` as a positional argument, so that we dispatch on it. So we might end up with syntax that looks something like

```julia
grid = RegularRectilinearGrid(CPU(); float_type=Float32, size=(1, 1, 1), x=(0, 1), y=(1, 2), z=(-3, 0))
```

We can also add an `architecture` kwarg if others think that's better.

@christophernhill might have some useful comments.

**Comment by francispoulin** [comment]
Dispatching over `architecture` sounds like a good idea to me, but I don't pretend to understand all the details of the two approaches.
