### ISSUE TITLE
Trying to use QuadGK for initial conditions

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1826]
With a student, we are trying to initialize `IncompressibleModel` with a flow that is in thermal wind balance.  We specify the velocity and then compute the buoyancy using the package `QuadGK`.  The lines that we use are the following:

```
parms = (f₀ = Coriolis.f,      # s⁻¹, Coriolis parameter
         N² = 1e-4,            # s⁻¹, buoyancy frequency
          D = grid.Lz,         # m, ocean depth
        L_y = Ly/2,            # m, jet width scale
        L_z = Lz/2,            # m, jet depth scale
         σz = 2,               # jet width parameter
         σy = 5,               # jet depth parameter
          γ = 1/2,             # jet skew parameter
      U_max = 2)               # jet velocity scale

ū(x, y, z, t, p) = p.U_max * sech(p.σz * z/p.L_z - p.σy * ( y/p.L_y + p.γ * z/p.L_z)^2)^2

dudz(x, y, z, t, p) =  2*p.U_max/p.L_z * (2*p.γ*p.σy * (y/p.L_y + p.γ * z/p.L_z) - p.σz) * tanh(p.σz * z/p.L_z - p.σy * ( y/p.L_y + p.γ * z/p.L_z)^2) * sech(p.σz * z/p.L_z - p.σy * ( y/p.L_y + p.γ * z/p.L_z)^2)^2

b̄(x, y, z, t, p) = quadgk(yp -> p.N² * (z + p.D) - p.f₀*dudz(x, yp, z, t, p), -Ly/2, y)[1]
```

It doesn't give any errors but seems to freeze when running the simulation.  In the case of a 16x16 grid my student waited 4 hours and nothing.

Any idea what the problem is?

There are a bunch of other ways for numerical integration that we can use but this does seem attractive.  Any other suggestions would be appreciated.

**Comment by glwagner** [comment]
An easier method might be to use a streamfunction (a field at Face, Face, Center and use  built in operators and broadcasting to calculate the velocity field and buoyancy in terms of this steam function. You avoid bringing in another package with this method and I think the result is closer to the discrete finite volume balance condition.

**Comment by glwagner** [comment]
For example:

```julia
psi = Field(Face, Face, Center, CPU(), grid)
set!(psi, (x, y, z) -> sin(x))
v .= ∂x(psi)
```

etc for buoyancy and `u`.

**Comment by glwagner** [comment]
> It doesn't give any errors but seems to freeze when running the simulation. In the case of a 16x16 grid my student waited 4 hours and nothing.

Are you trying to initialize a flow, or implement a geostrophic solution as a background flow / basic state?

I think if you're trying to use `BackgroundFields` the function `b(x, y, z, t, p)` is called at every grid point and time step. So I think you want to precalculate a background `Field` rather than provide a function that's recomputed every time step.

**Comment by francispoulin** [comment]
Thanks @glwagner for the suggestion.  Yes, I agree that would be much easier as there is no need to differentiate or integrate.  Will think about that.

We are specifying a `BackgroundField`, so given the fact that the buoyancy is calculated at every time step and every grid point, then having it precalculated would make more sense.  

It occurs to me that if we solve for the buoyancy using array operators at the beginning, then we can specify the`BackgroundField` using arrays.  Should that work?  I don't know if I have seen how to specify `BackgroundField` as an array but I presume it's like how the turbulence example specifies the initial conditions in terms of an array?

**Comment by glwagner** [comment]
You can specify `BackgroundField` with `Field`. I'm not sure if we support `Array`. But `Field` is better because you can use a streamfunction with abstract operations to calculate the background fields.

**Comment by glwagner** [comment]
On second thought I think a regular `Array` would be tough to use because I think it needs to have halo regions. It's probably best to use `Field`.

**Comment by francispoulin** [comment]
If we have an array, say `b_array`, then can we can turn it into a field using `b_field = ComputedField(b_array)`?

**Comment by francispoulin** [comment]
On a different note, if a `BackgroundField` is time dependent then evaluating it at every time step makes sense. But if it's time independent, as in this case, then it's working a lot more than it should.

Would it be of interest to have an option for it to not compute it at every time?  I am not suggesting this be done for this problem, but thinking more in the future

**Comment by glwagner** [comment]
> On a different note, if a `BackgroundField` is time dependent then evaluating it at every time step makes sense. But if it's time independent, as in this case, then it's working a lot more than it should.

Agreed!

> If we have an array, say b_array, then can we can turn it into a field using b_field = ComputedField(b_array)?

Just `b_field .= b_array`.

> Would it be of interest to have an option for it to not compute it at every time?

There are two ways to achieve this. The underlying data for a concrete `BackgroundField` can be updated via the `progress` callback every time step. A better method that's currently only possible currently with `HydrostaticFreeSurfaceModel` is to add it to the model's list of `auxiliary_fields`. In this case `compute!(field)` is called on every member of that list, so if the `BackgroundField` has a `compute!` method (eg if it's a `ComputedField`, or some other custom `Field` with a `compute!` method) then it will be updated.

**Comment by francispoulin** [comment]
Thanks, I figured out yesterday that I didn't need `ComputedField`, but appreciate the confirmation.

I like the "better solution", not just because of the name ;).  However, that requires adding `auxiliary_fields` to the two other models.  How much work would that be?  I've not touched it so have no idea but seems like it would be something worth doing, sometime.

**Comment by francispoulin** [comment]
@glwagner : We have defined `B` to be a `Field` and then assigned it with the correct values.  However, when we define the model, we have tried to pass `B` in place of a `BackgroundField` but it complains because it's only a `Field`, which it is.

How can we convert a `Field` to a `BackgroundField`?

**Comment by francispoulin** [comment]
I guess you can't convert a `Field` to a `BackgroundField` but I created #1826 to see if we could use a `Field` as a background state.

**Comment by francispoulin** [comment]
In the end we took @glwagner 's advice and defined the pressure and computed `BackgroundFields` using our balanced relations. I think this might actually work out better so thanks for the discussion.
