### ISSUE TITLE
Using a `Field` as a `BackgroundField` 

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1831]
Is there any reason why we can't set things up to specify a `Field` as a `BackgroundField`?

**Comment by francispoulin** [comment]
From talking to @ali-ramadhan , I wonder if it's as simple as adding a function to `regularize_background_field` that works for `Fields` in `background_fields.jl`.

```
regularize_background_field(X, Y, Z, f::BackgroundField{<:Function}, grid, clock) =
    FunctionField{X, Y, Z}(f.func, grid; clock=clock, parameters=f.parameters)

regularize_background_field(X, Y, Z, func::Function, grid, clock) =
    FunctionField{X, Y, Z}(func, grid; clock=clock)
```

**Comment by glwagner** [comment]
For reference, `regularize_background_field` is here:

https://github.com/CliMA/Oceananigans.jl/blob/4e9e5b79407e287005aa28d03d2fe3ffd37da194/src/Fields/background_fields.jl#L59-L63

You need something like

```julia
regularize_background_field(X, Y, Z, field::AbstractField, grid, clock) = field
```

Slightly better would be

```julia
function regularize_background_field(X, Y, Z, field::AbstractField, grid, clock)
    if location(field) != (X, Y, Z)
        throw(ArgumentError("Cannot use field at $(location(field)) as a background field at $((X, Y, Z))"))
    end

    return field
end
```

I thought we already had this method (and were using it... ?), but looks like it might've slipped through the cracks somehow.

**Comment by francispoulin** [comment]
Thanks @glwagner , glad to know we want this to exsit.

Thanks for the suggestion.  I'll give your suggestion a try and if all goes well create a PR and we can move the discussions there.
