### ISSUE TITLE
Leftover exports in `Oceananigans.Advection`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1841]
I don't' think these functions even exists...

https://github.com/CliMA/Oceananigans.jl/blob/1756bc9380999f160f3d2b96f64bf76771614c60/src/Advection/Advection.jl#L5

Am I missing something?

**Comment by francispoulin** [comment]
I did a search using trusty `grep -r` and agree they only appear in this line.  Unless someone has plans for creating such functions, I support the idea fo deleting these lines.
