### ISSUE TITLE
Should examples be written so that the "part 2" (load output and plot/process) is independent of "part 1" (setup and run)?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1850]
The way examples are written now is that there is the there is a **part 1** that sets up and runs a simulation and saves output. Then, **part 2** loads the `.jld2`/`.nc` file and plots an animations or what not.

However, the way part 2 is currently coded up in most examples *it requires that part 1 is run** as it references on things like `grid` or `fields` constructed by part 1. E.g., 
https://github.com/CliMA/Oceananigans.jl/blob/3c930b00f0ccfdcc20556a9b6ac888b63aeb58d2/examples/eady_turbulence.jl#L317-L324

Ideally, one would like to be able to run the "load `.jld2` file and animate" independently. That's the whole idea, right? At the moment the way I do it is that I have to run part 1 until **just before** the `run!(simulation)`, make sure I overwrite the `.jld2` placeholder file that is created with the one that has been populated by some other run previously, and then move on with loading output and animating.

Thoughts?

**Comment by glwagner** [comment]
It can't be completely independent because it still needs `using Oceananigans`, but it could be _more_ independent. I agree that's desirable.

I think using absolute filepaths rather than referencing the existing output writers, and using more explicit `nodes` functions could help, eg

```julia
xζ, yζ, zζ = nodes((Face, Face, Center), grid) 
xδ, yδ, zδ = nodes((Center, Center, Center), grid)
```

I think the grid is serialized so you could load it from file (though this feature isn't very robust right now since it doesn't work for stretched grids, for example).

**Comment by glwagner** [comment]
If you're using `JLD2` output you can write

```julia
# above this we have using Oceananigans, using JLD2, etc
grid = file["serialized/grid"]
x, y, z = nodes((Center, Center, Center), grid)
```

**Comment by ammtD** [comment]
Should this method work in Oceananigans v 64.1 already?   It doesn't seem to...

**Comment by glwagner** [comment]
Might require some archaeology to figure that out! Here's the tag:

https://github.com/CliMA/Oceananigans.jl/tree/v0.64.1

Looks like we did serialize back in those ancient times:

https://github.com/CliMA/Oceananigans.jl/blob/2b1bf10d69706277101e35cf4c566995572d7c63/src/OutputWriters/jld2_output_writer.jl#L186-L189

and we should have serialized the grid:

https://github.com/CliMA/Oceananigans.jl/blob/2b1bf10d69706277101e35cf4c566995572d7c63/src/OutputWriters/jld2_output_writer.jl#L9-L11

**Comment by ammtD** [comment]
thanks!

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
