### ISSUE TITLE
Incomplete docstring?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1851]
I think this docstring is incomplete? It refers to either `Center` cells or `Face` with `topo=Periodic`. Right?

https://github.com/CliMA/Oceananigans.jl/blob/f7408dc08c30ec6a3ced11d70d3458634f0fd071/src/Grids/new_data.jl#L9-L13

**Comment by glwagner** [comment]
It looks like it's missing some text. It called for both `Center` and `Face` with `topo=Periodic`, and also for `Center` with `topo=Bounded`.
