### ISSUE TITLE
Poincare constant in AMD

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1856]
[This paper](https://www.repository.cam.ac.uk/bitstream/handle/1810/285031/SPC_reviewed.pdf?sequence=1) cites the poincare constant `C` as `C^2=1/12`. The [docs](https://clima.github.io/OceananigansDocumentation/stable/physics/turbulence_closures/) list it as `C=1/12`. Unless I'm missing something, there's a discrepancy here.

I kinda got lost in the many functions used to calcuate AMD in our code, but it seems like our code implements what we actually list in the docs (I think). Which leads to the question: do we have the wrong constant for AMD?

**Comment by glwagner** [comment]
C_VreugdenhilTaylor^2 = C_Oceananigans. This formula implies the definition of C_VreugdenhilTaylor:

![image](https://user-images.githubusercontent.com/15271942/125494288-861a5909-180c-452e-bbfa-78d4d8afa2e9.png)

Whereas C_Oceananigans is used here:

https://github.com/CliMA/Oceananigans.jl/blob/89a6c6c4369c98e3a1b56eb74dc0a2028ec7210c/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L157

**Comment by glwagner** [comment]
So the docs are wrong, since they say

![image](https://user-images.githubusercontent.com/15271942/125494485-17eafb77-2fc3-4ad5-b6f4-40ad9a38df91.png)

**Comment by glwagner** [comment]
The key function `calculate_diffusivities!` calculates eddy diffusivities in Oceananigans. For AMD this is defined here:

https://github.com/CliMA/Oceananigans.jl/blob/89a6c6c4369c98e3a1b56eb74dc0a2028ec7210c/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L184

Working backwards from there leads to the kernel `calculate_viscosity!`:

https://github.com/CliMA/Oceananigans.jl/blob/89a6c6c4369c98e3a1b56eb74dc0a2028ec7210c/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L207-L210

which leads to the function where the eddy viscosity is calculated:

https://github.com/CliMA/Oceananigans.jl/blob/89a6c6c4369c98e3a1b56eb74dc0a2028ec7210c/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L142

**Comment by tomchor** [comment]
Thanks! Already opened an issue to fix it.

Are these dispatches ever used? (i.e., cases where `C` is not a constant.)
https://github.com/CliMA/Oceananigans.jl/blob/89a6c6c4369c98e3a1b56eb74dc0a2028ec7210c/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L139-L140
