### ISSUE TITLE
Adding `initial_conditions` argument to model constructors

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1890]
I find it a bit odd that I can specify everything for the model at the time of creation, but the initial conditions. Also having to use `set!` (which kinda feels like (idk if it actually is)) a low-level function kinda threw me off as a user at first.

Is that by design? If not, should we add a `initial_conditions` argument to the model constructors that just call `set!` in the background?

**Comment by glwagner** [comment]
This is by design. The keyword arguments in the model constructor _need_ to be there. `set!` does not and I think scripts are easier to read if they are outside.
