### ISSUE TITLE
Docs aren't being generated

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1909]
I think the docs page hasn't been generated since v0.60.0:

![Screenshot from 2021-07-29 08-26-21](https://user-images.githubusercontent.com/13205162/127521194-8e4835aa-b5a7-4bc5-aee4-00abfcec60e9.png)

I also haven't been able to see PR previews in a while. I assumed I was doing something wrong but maybe there's an issue here.

**Comment by glwagner** [comment]
This might coincide with tartarus' operating system upgrade.

**Comment by navidcy** [comment]
Hm.. we might need to regenerate Documenter keys/Documenter repo secret?
Only repo owners could deal with that?

**Comment by glwagner** [comment]
Ah! How do we do it?

**Comment by navidcy** [comment]
Let's see if #1920 dealt with this. Otherwise we can zoom and try to sort it out?

**Comment by navidcy** [comment]
Actually I take that back. It's obvious that it's a Documenter Key issue. See https://buildkite.com/clima/oceananigans/builds/3601#23153082-70fa-4e5c-8f9e-eb72dbc3d204/24-571

**Comment by glwagner** [comment]
Great, let's sort that out.

**Comment by tomchor** [comment]
Has this been sorted out? I think this caused at least part of confusion in https://github.com/CliMA/Oceananigans.jl/issues/1929 since the `restore_from_checkpoint` function is still up but doesn't exist in the code anymore.

Someone probably needs to do [this process](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh) again. The process needs to be attached to a username so probably either @ali-ramadhan or @glwagner have to do it.

**Comment by navidcy** [comment]
Nope, it's outstanding still...

**Comment by glwagner** [comment]
For future reference, I believe that updating the ssh deploy keys requires two things:

1. Access to tartarus
2. Admin privileges on the documentation repo, https://github.com/CliMA/OceananigansDocumentation

The [`Documenter.jl` documentation for generating deploy keys](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh) reads confusingly because we don't use Travis CI, but I do think we need to do something like what's outlined.

**Comment by glwagner** [comment]
We also need to figure out how to adapt instruction 2:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/15271942/129913721-0a12190d-af28-43c6-9070-92eb9e8f5a25.png">

to buildkite.

**Comment by glwagner** [comment]
For future reference, instead of the second step above, we need to add an environment variable `DOCUMENTEY_KEY=path_to_long_provide_key` to the file `/etc/buildkite-agent/hooks/environment` (which may not exist yet).
