### ISSUE TITLE
7-10x performance difference between 2D models in "xy" versus "xz"

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1919]
When attempting to run the problem in #1916 I noticed something alarming: models that are 2D in "xz" are far less performant than models that are 2D in "xy" on both the CPU and the GPU. On the CPU, 2D models in "xz" have alarmingly high memory allocation (allocations also seem high for "xy", something it seems we've lost track of).

I tested this on a number of branches / versions and found similar behavior on all them, so it doesn't seem there's been a performance regression (at least not recently). I haven't tested any branches requiring julia 1.5 --- I'd like to try that too.

To illustrate this I put together a small benchmarking script:

```julia
using Oceananigans
using Oceananigans.TimeSteppers: time_step!
using BenchmarkTools

xy_grid = RegularRectilinearGrid(size = (512, 512, 1), extent = (2π, 2π, 2π), topology = (Periodic, Periodic, Bounded))
xz_grid = RegularRectilinearGrid(size = (512, 1, 512), extent = (2π, 2π, 2π), topology = (Periodic, Periodic, Bounded))
yz_grid = RegularRectilinearGrid(size = (1, 512, 512), extent = (2π, 2π, 2π), topology = (Periodic, Periodic, Bounded))

function ten_steps!(model)
    for i = 1:10
        time_step!(model, 1e-6)
    end
    return nothing
end

for arch in (CPU(), GPU())
    for grid in (
                 xy_grid,
                 xz_grid,
                 yz_grid,
                )

        model = NonhydrostaticModel(architecture = arch,
                                    timestepper = :RungeKutta3,
                                    advection = UpwindBiasedFifthOrder(),
                                    grid = grid,
                                    buoyancy = nothing,
                                    tracers = nothing)

        @info "Benchmarking $model..."
        @btime ten_steps!($model)
    end
end
```

The results are alarming: on the CPU we find

* `xy_grid`:  616.285 ms (429912 allocations: 114.29 MiB)
* `xz_grid`:  4.638 s (944291 allocations: 2.63 GiB)
* `yz_grid`:  3.240 s (405223 allocations: 2.60 GiB)

Notice the `xz` configuration is 7 times slower than the `xy` configuration. In addition to that, allocations are through the roof --- 200 MiB of allocation per time-step?? (the benchmark tests 10 time-steps).

On the GPU we find

* `xy_grid`:  48.438 ms (128139 allocations: 45.68 MiB)
* `xz_grid`:  531.077 ms (637499 allocations: 53.51 MiB)
* `yz_grid`:  147.963 ms (166797 allocations: 46.33 MiB)

and therefore an even larger (10x) performance difference, though allocations are more under control.

I ran the benchmarks for a few different topologies to see if the pressure solver was the culprit. But I noticed similar behavior whether or not `y` or `z` was `Periodic` or `Bounded`.

I also tested whether the vertical integral for hydrostatic pressure was a problem by updating and then running code from #1910 . This didn't fix the problem either.

I'm perplexed, so I think we should drill into this a bit more. Or --- am I misinterpreting or setting up the benchmarks incorrectly?

@ali-ramadhan @christophernhill

**Comment by tomchor** [comment]
I got a similar result running on my laptop's CPU. Although for me the slowdown for an `yz` grid was only of a factor of two:

- `xy_grid`: 2.421 s (50571 allocations: 26.21 MiB)
- `xz_grid`: 21.497 s (52491 allocations: 2.91 GiB)
- `yz_grid`: 4.723 s (52491 allocations: 2.91 GiB)

Results were the same using a triply periodic domain. I'm not sure if it matters but I got virtually no slowdown for `yz` using `Flat` topologies.

**Comment by glwagner** [comment]
> I'm not sure if it matters but I got virtually no slowdown for `yz` using `Flat` topologies and the allocations were all the same (21 MB).

That's an extremely important clue...

**Comment by ali-ramadhan** [comment]
Yeah this is pretty worrying... I'm pretty sure this is the cause of https://github.com/CliMA/Oceananigans.jl/issues/1420 which has been open for a while so this slowdown must have been around for a while (and just flew under the radar). [Profiling](https://docs.julialang.org/en/v1/manual/profile/) might help pinpoint the bottleneck.

**Comment by christophernhill** [comment]
> Yeah this is pretty worrying... I'm pretty sure this is the cause of #1420 which has been open for a while so this slowdown must have been around for a while (and just flew under the radar). [Profiling](https://docs.julialang.org/en/v1/manual/profile/) might help pinpoint the bottleneck.

It looks like there are some extra temporary arrays being created for the cases with non-trivial (although still pretty trivial) indexing patterns. Profiling could be good - also just turning off as much as possible and then building up from the FFT alone, simple stencil etc... - if that is possible?

**Comment by glwagner** [comment]
> > Yeah this is pretty worrying... I'm pretty sure this is the cause of #1420 which has been open for a while so this slowdown must have been around for a while (and just flew under the radar). [Profiling](https://docs.julialang.org/en/v1/manual/profile/) might help pinpoint the bottleneck.
> 
> It looks like there are some extra temporary arrays being created for the cases with non-trivial (although still pretty trivial) indexing patterns. Profiling could be good - also just turning off as much as possible and then building up from the FFT alone, simple stencil etc... - if that is possible?

I did try with a different advection scheme (and `halo_size=(1, 1, 1)`) and the allocations were mitigated. This and @tomchor's result suggests that halo filling for periodic directions is a likely culprit.

Profiling is a good idea. I also had the thought of commenting out much of the time-stepping loop and building up to try to pinpoint which functions trigger allocations as @christophernhill suggests.

**Comment by francispoulin** [comment]
Glad someone found this and we are discussing it.

Maybe a silly question but what happens when we have purely 1D problems in `x`, `y` and `z`?  If we get a slow down in `z` then maybe that is an even more MWE?

**Comment by glwagner** [comment]
That's a good idea!

**Comment by glwagner** [comment]
xy model:

![image](https://user-images.githubusercontent.com/15271942/128091219-726f7058-5f26-4a23-81d5-9bc8e4ce641a.png)

xz model:

![image](https://user-images.githubusercontent.com/15271942/128091658-67620574-89ad-4031-a5fd-7c2edd7be090.png)

Both seem to spend way too much time in `update_state!` (and filling halo regions) but maybe I am reading it wrong.

**Comment by glwagner** [comment]
Things are looking up...

![image](https://user-images.githubusercontent.com/15271942/128102265-24c25476-9e5f-4fc7-ab19-ecc492c6fcbc.png)
