### ISSUE TITLE
Test for incompressibility in hydrostatic and non-hydrostatic models

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1934]
This follows from the discussions after the bug fix in #1932.

cc: @kburns, @sandreza, @francispoulin

**Comment by glwagner** [comment]
We test that `NonhydrostaticModel` maintains incompressibility on both fully regular and vertically-stretched grids:

https://github.com/CliMA/Oceananigans.jl/blob/e929631eb3a233ae3f3358d2146e5d6004f9a06c/test/test_time_stepping.jl#L311-L341

We don't have tests for the hydrostatic model however.

A similar but possibly slightly simpler test might test that `compute_w_from_continuity!` correctly calculates a vertical velocity field given some horizontally divergent horizontal velocity field.

**Comment by francispoulin** [comment]
Since like a good idea

**Comment by glwagner** [comment]
So, we do have tests for incompressibilty
