### ISSUE TITLE
scalings for the distributed models

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1948]
Thanks to @hennyg888 , we now have scalings results for the distributed shallow water and nonhydrostatic models for both weak and strong scaling going up to 128 cores.  

https://github.com/CliMA/Oceananigans.jl/blob/master/docs/src/appendix/benchmarks.md

The good news is that the `ShallowWaterModel`, in both weak and strong scaling, reaches efficienties of around 80% on 128 cores.  This is something we can probably make better but not the first concern.

The not so good news is that the `NonhydrostaticModel`, the efficiency goes down close to 10%.  I don't know why but wanted to mention it as it's something that we should be able to do much better with.

Thoughts? @christophernhill @glwagner @ali-ramadhan

**Comment by glwagner** [comment]
So there is a performance issue with the FFT? How does `PencilFFTs` scale when run stand-alone?

**Comment by francispoulin** [comment]
It could be the `FFT`.  That is something that is used in the `NonhydrostaticModel`, which is not used in `ShallowWaterModel`.  

@hennyg888 didn't do any `PencilFFT` runs but I remember that @ali-ramadhan did a comprison between pencils and slabs a long time ago, only on a course grid, and he didn't find any big difference between the two.  Maybe differences only occur at higher numbers of cores?

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
