### ISSUE TITLE
Documentation build is failing

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1949]
I think #1930 broke the documentation:

https://buildkite.com/clima/oceananigans/builds/3719#6b051652-7cab-4257-82c6-4be2bfb04f92

@hennyg888 should we revert #1930, or can this problem be easily fixed with a new PR?

**Comment by hennyg888** [comment]
The documentation buildkite test was failing for #1930 already so I don't think that it is what broke it.

**Comment by glwagner** [comment]
The previous build, before #1930 was merged, passed:

![image](https://user-images.githubusercontent.com/15271942/130260204-166ae3be-68c4-41a4-8103-95fa9f4ab4d2.png)

**Comment by glwagner** [comment]
#1930 updates the docs, so its highly probable that #1930 is what caused the failing docs build, right?

**Comment by glwagner** [comment]
Ok, let's revert #1930, and re-open the PR and get the docs to build before merging.

**Comment by francispoulin** [comment]
Good idea!

Francis


________________________________

**Comment by hennyg888** [comment]
#1950 passed all tests and I approved and merged it. I'll open a new PR to add my branch with the updated benchmark docs back in.
