### ISSUE TITLE
Implementing a tensor diffusivity rotated into the isopycnal coordinate frame

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1972]
To implement the "Gent-McWilliams" turbulence closure (and variants of this closure) we need a turbulence closure that accepts skew and symmetric diffusivity components (?), and rotates the diffusive / viscous fluxes into the isopycnal coordinate frame.

I think this requires simplifying the already-implemented `TwoDimensionalLeith` closure, which defines functions like

```julia
# Components of the Redi rotation tensor

@inline function Redi_tensor_xz_fcc(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    bx = ∂x_b(i, j, k, grid, buoyancy, C)
    bz = ℑxzᶠᵃᶜ(i, j, k, grid, ∂z_b, buoyancy, C)
    return ifelse(bx == 0 && bz == 0, zero(FT), - bx / bz)
end

@inline function Redi_tensor_xz_ccf(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    bx = ℑxzᶜᵃᶠ(i, j, k, grid, ∂x_b, buoyancy, C)
    bz = ∂z_b(i, j, k, grid, buoyancy, C)
    return ifelse(bx == 0 && bz == 0, zero(FT), - bx / bz)
end

@inline function Redi_tensor_yz_cfc(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    by = ∂y_b(i, j, k, grid, buoyancy, C)
    bz = ℑyzᵃᶠᶜ(i, j, k, grid, ∂z_b, buoyancy, C)
    return ifelse(by == 0 && bz == 0, zero(FT), - by / bz)
end

@inline function Redi_tensor_yz_ccf(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    by = ℑyzᵃᶜᶠ(i, j, k, grid, ∂y_b, buoyancy, C)
    bz = ∂z_b(i, j, k, grid, buoyancy, C)
    return ifelse(by == 0 && bz == 0, zero(FT), - by / bz)
end

@inline function Redi_tensor_zz_ccf(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    bx = ℑxzᶜᵃᶠ(i, j, k, grid, ∂x_b, buoyancy, C)
    by = ℑyzᵃᶜᶠ(i, j, k, grid, ∂y_b, buoyancy, C)
    bz = ∂z_b(i, j, k, grid, buoyancy, C)
    return ifelse(by == 0 && bx == 0 && bz == 0, zero(FT), (bx^2 + by^2) / bz^2)
end
```

The users most interested in this feature in the immediate future are @sandreza and @xiaozhour . @sandreza and @xiaozhour , can you provide a mathematical description of the closure you would like implemented? Are the Redi tensor functions defined above sufficient? I think they make a small-angle approximation. Do we need to use a more general formulation, or allow for tapering?

**Comment by sandreza** [comment]
specifically: http://svante.mit.edu/~jscott/html/phys_pkgs/gmredi.html

**Comment by glwagner** [comment]
The off diagonal components of 

![image](https://user-images.githubusercontent.com/15271942/132757032-976f5f6d-90be-4999-a668-31d73a473cf8.png)

look identical to the code I pasted above. Do you agree?

**Comment by glwagner** [comment]
The difference between this parameterization and the currently implemented `TwoDimensionalLeith` parameterization is that the diffusivities are user-provided rather than being a 3D field that's computed from the vorticity and divergence. That's why this parameterization is actually a simplification of `TwoDimensionalLeith`.

**Comment by sandreza** [comment]
I agree that the components of the tensor look the same! I guess it leaves the tapering scheme to be implemented and the anti-symmetric part to be limplemented

**Comment by glwagner** [comment]
The anti-symmetric part just has a few terms with the opposite sign:

![image](https://user-images.githubusercontent.com/15271942/132763337-7845074d-7bff-4b5a-99e1-0185b2fa67a0.png)

In the current code this leads to things like

https://github.com/CliMA/Oceananigans.jl/blob/335e47659a11b92df32bf844cebe6e518dec9fc8/src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl#L140-L141

(note the `-` sign) and 

https://github.com/CliMA/Oceananigans.jl/blob/335e47659a11b92df32bf844cebe6e518dec9fc8/src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl#L180-L183

**Comment by glwagner** [comment]
@navidcy
