### ISSUE TITLE
Why is bottom drag multiplied by domain depth?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1974]
https://github.com/CliMA/Oceananigans.jl/blob/bb35dcbefad63c038cd311c5eed43ac5326bb824/validation/mesoscale_turbulence/eddying_channel.jl#L96-L97

**Comment by glwagner** [comment]
Multiplying by domain depth means the barotropic mode is damped at the rate `p.μ`.

More generally, if we're using linear drag model to specify a momentum flux, then the model "free parameter" is a _velocity scale_ (eg, length-scale divided by time-scale, which here is `1/p.μ`. We choose that length scale to be the domain depth.

Are there other recommendations out there in the literature? It could be nice to provide some kind of reference to a discussion about it...

**Comment by navidcy** [comment]
Oh yeah right...

Well, I don't know any "good reference". I've seen some people use an ad-hoc "boundary layer depth" of few tenth's of meters. In isopycnal coordinates (e.g. mom6) one uses the depth of the bottom layer, or an average of the fluid layers within e.g. 10 meters.

**Comment by glwagner** [comment]
Ahh I see.

There are two free parameters (the damping rate and the height scale) so we really only have an interpretation if we consider the two together. If the height scale is the domain depth, then the damping rate is the rate at which momentum is removed from the barotropic mode. If the height scale is the boundary layer depth, then I guess the damping rate is the rate at which momentum is removed from the bottommost "layer"?
