### ISSUE TITLE
Column stability for convective adjustment: `∂z_b > 0`, or `∂z_b >= 0`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1980]
I think it should be `∂z_b >= 0`, otherwise ~~you can get surprising / unphysical behavior~~ tracers are rapidly diffused in neutrally stable regions with no convection! Right now we use `∂z_b > 0`.

https://github.com/CliMA/Oceananigans.jl/blob/6cf27c42de084ae08a5085e90f683f28350e1657/src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl#L106

Discovered with @navidcy .

We should have

```julia
 @inline is_stableᶜᶜᶠ(i, j, k, grid, tracers, buoyancy) = ∂z_b(i, j, k, grid, buoyancy, tracers) >= 0
```

**Comment by francispoulin** [comment]
From what I understand, the following is true.

If we have `∂z_b <0` then the fluid is convectively **unstable**.  

If `∂z_b >0` then this is convectively **stable** (some might call **asymptotically stable**).

If we consider `∂z_b = 0` then it is **neutrally stable**.  

What sort of surprising/unphysical behavour can you get if you include the neutrally stable case?

I'm okay with having `>=0` but am curious if there is something more going on here than I currely appreciate.

**Comment by navidcy** [comment]
@francispoulin you are in principle correct!

However, without the equality in the criterion, me and @glwagner were trying to setup a very simple, idealized example with linear background stratification and somehow the convective adjectment started working in the bottom of the domain because the criterion was precisely zero there. This is the "unphysical situation" that @glwagner is referring to -- perhaps he can elaborate a bit more?

**Comment by tomchor** [comment]
> @francispoulin you are in principle correct!
> 
> However, without the equality in the criterion, me and @glwagner were trying to setup a very simple, idealized example with linear background stratification and somehow the convective adjectment started working in the bottom of the ocean (!!) because the criterion was precisely zero there. This is the "unphysical situation" that @glwagner is referring to -- perhaps he can elaborate a bit more?

Interesting... I wouldn't think this would be a problem (although I definitely see how it can be). I'd be curious to see some animations of this if you have them ready. (Just out of curiosity; no need to post them if it'll take work...)

**Comment by navidcy** [comment]
Or maybe, @glwagner, was this issue related to the no-flux boundary condition at the bottom which by construction imposes zero buoyancy gradient and that's what was triggering the convecting adjustment?

**Comment by glwagner** [comment]
Here's the issue: if `∂z_b = 0`, there is no convection in the real world. But currently, the convective adjustment scheme marks regions with `∂z_b = 0` as "convecting", and sets the diffusivity equal to the `convective_kappa` there.

To make this more concrete, consider a domain which is completely unstratified with `∂z_b = 0` everywhere, but has some non-trivial passive tracer distribution. Our scheme would mark the entire domain as "convecting" and diffuse the tracer rapidly, even if in the "real" scenario, such a situation would be completely quiescent with negligible / molecular diffusion.

**Comment by glwagner** [comment]
I guess it would be better to use a function `is_unstable` here...

**Comment by glwagner** [comment]
There's another limitation of the current scheme that's worth mentioning. The scheme currently precomputes the 3D diffusivity / viscosity field at cell centers, which means that a cell is "unstable" if _either_ vertical interface has a negative buoyancy gradient. But what we really want to do is precompute _stability_ (or the buoyancy gradient), which is more naturally located at vertical cell interfaces. This provides the tracer diffusivity directly; the momentum diffusivity can be calculated by checking the stability of two neighboring regions.
