### ISSUE TITLE
Default tracers and buoyancy model for `NonhydrostaticModel `

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1984]
Currently when you construct a nonhydrostatic model without arguments the constructor defaults to a `SeawaterBuoyancy()` buoyancy model and automatically adds temperature and salinity as tracers.

Do we want that? This isn't a big deal, but that's the option with the most computational cost. Maybe we should default to `nothing` or `BuoyancyTracer()`?

**Comment by glwagner** [comment]
I agree `nothing` would be better...

Perhaps also `tracers = ()`?

I changed the name of the issue because the tracers and buoyancy model are related.
