### ISSUE TITLE
Add method to `AveragedField` to prescribed averaged dimensions with names, e.g., `dims = (:x, :y)`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2006]
https://github.com/CliMA/Oceananigans.jl/blob/73be08d708131a66402eb8fc0086c47ef80a2d0e/src/Fields/averaged_field.jl#L38-L39

**Comment by glwagner** [comment]
Let's table this, one nice thing about numbers is that we avoid the need for "x" and "lambda"
