### ISSUE TITLE
Package description - oceanic library

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2017]
This is a minor thing but I just noticed that the package's description is this:

![Screenshot_20211016_073544](https://user-images.githubusercontent.com/13205162/137591563-50280525-ffbd-46cf-b838-b0983a7ed0d2.png)

Maybe it's because I'm not a native English speaker, but  "oceanic library" reads pretty weird to me. Maybe "ocean-focused" lilbrary? Or maybe something simpler but a bit more verbose: "A library for fast, friendly, data-driven fluid dynamics on CPUs and GPUs with a focus on the ocean".

**Comment by navidcy** [comment]
@glwagner or @ali-ramadhan probably can change that.

I actually like the description as is. :)
I'd probably just add the "flexible" to the current description: "A flexible oceanic..."

**Comment by glwagner** [comment]
I put some work into the description, removing "oceanic" in favor of "ocean-flavored" and adding "flexible". Please reopen if there's still an issue!
