### ISSUE TITLE
Trigonometric functions may be causing slowdown on a simulation when running on GPUs

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2034]
This is related to [this PR](https://github.com/CliMA/Oceananigans.jl/pull/2029). To summarize:

- I have a production-ready research code (that's far too complicated to post here) that does sines/cosines calculations for a background field
- If these sine/consine calculations are performed inside the background field function the code is about 100x slowed than if I perform these calculations outside the function, and just pass the pre-calculated sine and cosine
- I tried making a MWE to reproduce this behavior but failed, which indicates that it's not _just_ the trig functions that are causing the slowdown. It's the trig functions plus something else (I have no idea what)

So that's the state of things. I'll try to start from my code and cut down on things one by one to try and post a small MWE whenever I have time.

CC: @glwagner @navidcy @francispoulin

**Comment by navidcy** [comment]
Fair enough. Can you change the issue title to "may be causing" since this is still uncertain?

**Comment by tomchor** [comment]
> Fair enough. Can you change the issue title to "may be causing" since this is still uncertain?

Fair point. Done.

**Comment by glwagner** [comment]
Is this still an issue?

**Comment by tomchor** [comment]
Haven't had the time to dig more into it unfortunately :/

**Comment by glwagner** [comment]
I guess I more meant do we have reason to believe that trig functions slow things down 100x?

We use trig functions in the lat-lon grid without this issue for example, so it seems unlikely.

If we're observing expected slow downs (perhaps up to 2-3x for an expensive trig function that's called often), then I don't think we need to keep this issue open.

**Comment by tomchor** [comment]
I don't really know how to answer that. All I know is what is summarized in the first post: using trig functions in the background field calculations for that code makes it 100x slower than not doing so. It's possible that this effect only happened in that code in conjunction with something else, but I haven't had time to investigate this further.

If you prefer to close this issue since the amount of evidence is small, I'm okay with it.

**Comment by glwagner** [comment]
> using trig functions in the background field calculations for that code makes it 100x slower than not doing so.

Is is possible that the 100x slowdown occurred for some other reason than using the trig functions?

**Comment by tomchor** [comment]
> > using trig functions in the background field calculations for that code makes it 100x slower than not doing so.
> 
> Is is possible that the 100x slowdown occurred for some other reason than using the trig functions?

It's possible, but then it would have to be something that's triggered by the use of trig functions since I tried dozens of ways to run that script, but every time so trig calculations were used in the background field it caused that slowdown (no exceptions). Every time the trig calculations were done outside the script was fast (no exceptions).

**Comment by glwagner** [comment]
To clarify what we know a little more:

We can use trig functions on the GPU without 100x slowdown in many cases. For example, the latitude-longitude grid (without precomputed metrics) uses trig functions to compute cell spacings, areas, and volumes. We find that computing these metrics on the fly is _sometimes_ slower than precomputing them --- perhaps by 2-3x, but not by 100x.

**Comment by glwagner** [comment]
This isn't an oceananigans issue: trig functions are slow cause they are slow
