### ISSUE TITLE
HydrostaticFreeSurfaceModel does not enforce halo correctness

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2041]
Unlike the `NonhydrostaticModel`, which has these lines:

https://github.com/CliMA/Oceananigans.jl/blob/1c96350d03e1ee066d5c9060089e043e15f711d6/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L120-L122

It's nice to validate the halos, because sometimes there are non-intuitive constraints (eg on #1994 we may have discovered that isopycnal closures need halos of size 2).

cc @navidcy

**Comment by navidcy** [comment]
Yes, yes, yes.

**Comment by glwagner** [comment]
It does now.
