### ISSUE TITLE
Should we test also models run with tuple of closures and/or using different models?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2047]
E.g., in addition of this:
https://github.com/CliMA/Oceananigans.jl/blob/057e25cea75a0da5e2e0f2328d39205ebaf2b0dc/test/test_time_stepping.jl#L25-L40
we also have tests using, e.g., `closure = (AnisotropicDiffusivity(FT), Closure(FT))` and also some tests using, e.g., `HydrostaticFreeSurfaceModel`?

**Comment by navidcy** [comment]
(The backstory of this is that I wasn't able to run `HydrostaticFreeSurfaceModel` with two closures on the GPU...)

**Comment by glwagner** [comment]
Pretty sure we do test closure tuples
