### ISSUE TITLE
bug in vertically implicit diffusion solver ?

### ISSUE THREAD

**Issue by jm-c** [CliMA/Oceananigans.jl#2065]
It seems that the ivd_diagonal (main diagnonal) has not the right 1/ Δz factor:
idv_diagonal(k) should only be function of  Δz_c(k) and also  Δz_f(k) &  Δz_f(k+1); I think by switching k_f & k_c in the definition of "kappa_ Δz^2" it should fix this (to check).
This problem should only shows up with vertically streched grid.

For the 2 other diagonals ((upper & lower), it's not clear to me because I don't really know what this comment: "# Shift to adjust for Tridiagonal indexing convenction" means: Does this means that we don't pick one of the 2 simpler conventions for indexing the tri-diagonal coeff, i.e, either by line/row or by columns ?

**Comment by glwagner** [comment]
@jm-c there are two `ivd_diagonal` functions --- which one do you mean? Here are the two:

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl#L52-L59

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl#L75-L82

We should adapt this dynamics test:

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/test/test_dynamics.jl#L447

to use a vertically-stretched grid. Hopefully that would isolate this issue.

**Comment by glwagner** [comment]
Here's the definition of `κ_Δz²`:

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl#L37

**Comment by glwagner** [comment]
> I don't really know what this comment: "# Shift to adjust for Tridiagonal indexing convenction" means: Does this means that we don't pick one of the 2 simpler conventions for indexing the tri-diagonal coeff, i.e, either by line/row or by columns ?

I believe this refers to the fact that julia's `Tridiagonal` (whose conventions are followed in the `BatchedTridiagonalSolver`) has three vectors: `d` (diagonal), `du` (upper diagonal) and `dl` (lower diagonal). `d` has length `N`, but `du` and `dl` both have length `N-1`. So for example the matrix component "1, 2" is index `1` in the lower diagonal vector --- I think?

**Comment by glwagner** [comment]
Here are the two functions with that comment:

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl#L46-L50

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl#L69-L73

**Comment by jm-c** [comment]
@glwagner Thanks for the explanation of the "indexing convention" of the tridiag matrix.
And regarding the ivd_diagonal expression, I only looked at the first one (with aac subscript) that is used for tracers, and does not look right to me (again, it's just about Δz_c and  Δz_f so will not affect results unless non-uniform vertical resolution is used).

**Comment by glwagner** [comment]
I'll work on a new test that catches this bug, then we can try to fix it.

**Comment by navidcy** [comment]
That's interesting. GM implementation blows up very shortly with stretched grid but not with regular.

**Comment by glwagner** [comment]
> That's interesting. GM implementation blows up very shortly with stretched grid but not with regular.

Yeah. Or is it the whole simulation that's the problem? This issue would only affect convective adjustment in that setup.

**Comment by navidcy** [comment]
Convective adjustment was on in the examples I have in mind that were blowing up...
