### ISSUE TITLE
Refactor `regrid!` so that it works with non-flat `x` and `y` dimensions?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2067]
Currently we only support regrinding for `SingleColumnGrid` (i.e., grids in which `x` and `y` dimensions are `Flat`).

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/Fields/regridding_fields.jl#L60

But the same code could also work as is, only for regrinding in `z` even if `x` and `y` dimensions weren't `Flat`. Isn't it?

cc: @glwagner

**Comment by navidcy** [comment]
Hm, I see... We'd have to make sure that the `x` and `y` dimensions of the input and output grids are exactly identical.

**Comment by glwagner** [comment]
I was wondering if we can regrid in 3D simply by regridding in each dimension in serial. Eg first regrid in x, then, y, then z. It'll be a bit more computation, but we still have the option of future optimization...

**Comment by navidcy** [comment]
This might be relevant: https://github.com/pangeo-data/xESMF
