### ISSUE TITLE
Warnings regarding `Diagnostics.error_if_nan_in_field`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2068]
I'm getting this:

```julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
WARNING: could not import Diagnostics.error_if_nan_in_field into CubedSpheres
[ Info: Oceananigans will use 12 threads

julia>
```

which  is probably related to:

https://github.com/CliMA/Oceananigans.jl/blob/02f4d9dc17293a399ca3adf68b6de71ee7d59f16/src/CubedSpheres/CubedSpheres.jl#L113-L119

`

**Comment by glwagner** [comment]
Oh. That function lives in `Oceananigans.Simulations` now after #2048

**Comment by navidcy** [comment]
Actually, now after #2069
```julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
WARNING: could not import Simulations.error_if_nan_in_field into CubedSpheres
```

Truth is that `error_if_nan_in_field` doesn't exist. So `Oceananigans.CubeSpheres` need not import it but just define it?

**Comment by glwagner** [comment]
Bleh. I was wrong...

https://github.com/CliMA/Oceananigans.jl/blob/0a5d367bd23a10fd6c8167c2c27065e4f86d786f/src/Simulations/nan_checker.jl#L14-L22

I guess we want to change this to something like

```julia
hasnan(field) = any(isnan, parent(field))

 function (nc::NaNChecker)(simulation) 
     for (name, field) in pairs(nc.fields) 
         if hasnan(field)
             @info "NaN found in field $name. Stopping simulation." 
             simulation.running = false 
         end 
     end 
     return nothing 
 end 
```

And then we can generalize `hasnan` for fields on the cubed sphere.
