### ISSUE TITLE
Do we really need AbstractCPUArchitecture?

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2072]
If we are thinking to unify `MultiCPU` and `MultiGPU` in a more general `MultiArch` which will contain the `child_architecture` information, `AbstractCPUArchitecture` and `AbstractGPUArchitecture` become obsolete...

**Comment by glwagner** [comment]
Agree! I think this is a duplicate of #2020 ?

**Comment by simone-silvestri** [comment]
Kind of :). I was thinking to just remove the AbstractCPU and AbstractGPU acrhitecture types

**Comment by glwagner** [comment]
Ah for sure. Yeah, it doesn't seem like it'd have any impact on the code.

**Comment by simone-silvestri** [comment]
No, just `AbstractMultiArchitecture` (which we might want to delete) and `AbstractArchitecture`

**Comment by glwagner** [comment]
Then I'm closing
