### ISSUE TITLE
RectilinearGrid broken? 

### ISSUE THREAD

**Issue by ammtD** [CliMA/Oceananigans.jl#2077]
I just updated my packages and now I get an error ....

UndefVarError: RectilinearGrid not defined
Stacktrace:
 [1] top-level scope
   @ In[8]:18
 [2] eval
   @ .\boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116

....with even the simples grid-defenition, e.g. 
```
Nz = 24 # number of points in the vertical direction
Lz = 32 # domain depth
grid = RectilinearGrid(size = (32, 32, Nz),
                          x = (0, 64),
                          y = (0, 64),
                          z = (-64, 0))
```
What am I doing wrong?

**Comment by navidcy** [comment]
Perhaps a bit more context to help us identify the issue? E.g., what's the output of 

```julia
julia> using Pkg; Pkg.status()
```

**Comment by ammtD** [comment]
Status `C:\Users\Owner\.julia\environments\v1.6\Project.toml`
  [5ae59095] Colors v0.12.8
  [7073ff75] IJulia v1.23.2
  [033835bb] JLD2 v0.4.14
  [9e8cae18] Oceananigans v0.64.1
  [f0f68f2c] PlotlyJS v0.18.8
  [91a5bcdd] Plots v1.22.4
  [d330b81b] PyPlot v2.10.0

From other issues I get the impression that what was first 'RegularRectilinearGrid' is being changed to 'RectilLinearGrid' ....but perhaps that doesn't work yet in the version I have?
