### ISSUE TITLE
Use Doctest filtering in doctests

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2080]
We'd like to convert this example:

https://github.com/CliMA/Oceananigans.jl/blob/1f7792ac8be223a0b32bf38d0d8954ea57e9d294/src/Advection/weno_fifth_order.jl#L79-L89

into a doctest. But to do so, we need to [filter out] from the output the two lines related to the `@warn ...`.

I tried to do that, but I had trouble properly creating the regular expression to capture both these lines.

E.g.,

<pre>
<code>
```@meta
DocTestFilters = [Regex("Warning: defaulting"), Regex("Oceananigans.Advection")"]
```

```jldoctest
julia> using Oceananigans

julia> WENO5()
┌ Warning: defaulting to uniform WENO scheme with Float64 precision, use WENO5(grid = grid) if this was not intended
└ @ Oceananigans.Advection ~/Research/OC2/src/Advection/weno_fifth_order.jl:90
WENO5 advection scheme with:
    ├── X regular
    ├── Y regular
    └── Z regular
```
</code>
</pre>

didn't work because, apparently, I was only capturing the "Warning: defaulting" and "Oceananigans.Advection" from each line. What I'd like is something like `* "Warning: defaulting" *` but I don't know how to write a `Regex` to do so. Anyone could help?

cc @tomchor

**Comment by tomchor** [comment]
Thanks for opening this!

I don't have a lot of server/internet access right now so I can't properly test this, but using `.*┌ Warning.*\n` and `.*└ @ Oceananigans.*\n` seems to work.

You can test things out here: https://regexr.com/

Also, it seems like there's an extra quote in your regex line?

`DocTestFilters = [Regex("Warning: defaulting"), Regex("Oceananigans.Advection")"]` 

maybe should be

`DocTestFilters = [Regex("Warning: defaulting"), Regex("Oceananigans.Advection")]`?

**Comment by navidcy** [comment]
Yeah, I think my extra quote was a typo...

**Comment by navidcy** [comment]
Thanks, that seems to have worked! I think there were point doctest filtering would come handy in https://github.com/CliMA/Oceananigans.jl/pull/1989.
