### ISSUE TITLE
Should we have models infer the architecture from the `grid`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2089]
See, e.g., 

https://github.com/CliMA/Oceananigans.jl/blob/82a1d83ff96f22b2aafc19f2640f6156f838d3d7/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L89-L113

@glwagner, @simone-silvestri

**Comment by simone-silvestri** [comment]
I think it is a good idea to have such a change. It is done (probably not in the best way) in PR #2078. The major change would be making fields and all other constructors infer the architecture from the grid

**Comment by navidcy** [comment]
Or at least, if the user does not give any architecture, then the default is to be inferred from `grid`?

**Comment by navidcy** [comment]
Oh, I forgot that #2078 was not merged yet ;)

**Comment by glwagner** [comment]
This is of course the True and Correct Path for Oceananigans

**Comment by glwagner** [comment]
We do this now.
