### ISSUE TITLE
Do we want to go triply-Bounded for `test_boundary_conditions_integration.jl`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2091]
I noticed this deprecated warning...

https://github.com/CliMA/Oceananigans.jl/blob/d9e2c31e20e78f1b1dcb4d9bd01a959c51bcb60e/test/test_boundary_conditions_integration.jl#L139-L140

**Comment by glwagner** [comment]
Yes --- and the test should be generalized to have east-west boundary conditions as well.
