### ISSUE TITLE
`HydrostaticModel` should do something if the halo is too small

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2106]
Yesterday, with @glwagner, we discovered that using higher order advection schemes gave larger error when you don't set the halo to be the large size.  

How about we check the halo size we give an error?

**Comment by glwagner** [comment]
> Yesterday, with @glwagner, we discovered that using higher order advection schemes gave larger error when you don't set the halo to be the large size.
> 
> How about we check the halo size we give an error?

Just to clarify, if the halos aren't set properly then results aren't "less accurate" --- instead, they are wrong, even if they are finite. A segfault and program failure is another possibility.

**Comment by francispoulin** [comment]
Yes to what @glwagner said.  To be more precise, the integral of the tracer should be exactly concserved in our finite volume scheme.  This is something that is not true when the halo is to small, hence the results are wrong.

**Comment by glwagner** [comment]
And when I ran the same code, i received a segmentation fault and Julia failed!
