### ISSUE TITLE
Upgrade to single/unified stretched vertical grid spacing 3D elliptic solver?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#211]
@christophernhill Was wondering if your stretched vertical grid spacing 3D elliptic solver would be efficient enough to use for the case where _Δz_ is constant.

If it is, then we can make do with a single solver. And if there are no DCTs, then we can merge the CPU and GPU Poisson solvers! But maybe it's also good to keep the elliptic solver we currently have too.

Just had this thought so leaving the issue open to discuss in the future.

**Comment by christophernhill** [comment]
Yes - that makes sense.

**Comment by ali-ramadhan** [comment]
Closing as I don't think this is possible for all topologies. See https://github.com/CliMA/Oceananigans.jl/pull/1403#issue-580571823
