### ISSUE TITLE
Remove warning from `HydrostaticFreeSurfaceModel`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2111]
Is it about time we remove this warning?

https://github.com/CliMA/Oceananigans.jl/blob/23cf5a7cdf0d06e0146e13f75a93d4934f28f400/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L106

**Comment by francispoulin** [comment]
One thing I would suggest is resolving #2106, so the user does not get wrong answers if the halo is not correctly specified.

**Comment by navidcy** [comment]
Sounds good.
