### ISSUE TITLE
Replace `AnisotropicDiffusivity` and `AnisotropicBiharmonicDiffusivity` with their curvilinear-friendly counterparts

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2113]
It'd be simpler to maintain just one 2nd order and 4th order diffusivity implementation. Also, `HorizontallyCurvilinearAnisotropicBiharmonicDiffusivity` is _truly_ biharmonic, whereas `AnisotropicBiharmonicDiffusivity` is not.

Deletion of the existing schemes and renaming of the curvilinear-friendly schemes will easily resolve this issue.

**Comment by navidcy** [comment]
If the curvilinear analogues fall back to "the usual" for Rectilinear grids then I'd say: Yes. Yes. Yes.

**Comment by glwagner** [comment]
I think they are identical on a regular grid, but on a stretched grid they are potentially slightly different (in that case the "curvilinear" flavors are preferred because they have better conservation properties).

**Comment by glwagner** [comment]
#1400 and #1279 are related. 

cc @simone-silvestri
