### ISSUE TITLE
Add `parameters` to `Callback`

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2127]
Probably related:

I saw the new `Simulation` API and the new `Callback` idea. This brought a change: the old way of building a Simulation included a `parameters` arguments. This `parameters` was accesible from the `progress` function. With the new way, we build callbacks and then register them, but there is no way to pass additional parameters to it. 

In one of my usages I was hacking a progress function https://github.com/aramirezreyes/RamirezReyes_ShallowWaterInFPlane/blob/c1971c0cb3fc99fbb2dbf3303a8fd60b17a59d5a/scripts/run_oceananigans_example_cpu.jl#L101 to update some arrays on a parameterization. Unfortunately, this depended on the `parameters` argument. The more generalized idea of the `callbacks` is very elegant and works nice, but it loses some power from the lack of ability to add additional parameters to the callback function.

Is there a way to recover this ability? (there are other ways of getting it to work but having it in the design would be nice).

_Originally posted by @aramirezreyes in https://github.com/CliMA/Oceananigans.jl/issues/1895#issuecomment-1001102006_

**Comment by glwagner** [comment]
@aramirezreyes one possibility is a `parameters` feature for `Callback`; when `!isnothing(callback.parameters)`, the callback function is called with `func(simulation, parameters)`.

**Comment by glwagner** [comment]
Before this issue is resolved, one solution is to use callback objects:

```julia
struct ParameterizedCallback{P}
    parameters :: P
end

(cb::ParameterizedCallback)(simulation) = # function that depends on both `sim` and `cb.parameters`

cb = ParameterizedCallback(parameters) # builds the callable object, capturing `parameters`

simulation.callbacks[:callback] = Callback(cb, IterationInterval(10))
```

**Comment by aramirezreyes** [comment]
Thanks!
The solution I came with was using a function with a default argument.
```julia
mycallback(simulation, parameters = my_parameters)
simulation.callbacks[:callback] = Callback(mycallback, IterationInterval(10))
```

I have not checked if the way in which both capture the object would be equivalent.

**Comment by glwagner** [comment]
A default argument works great too! You can also capture data as a global variable:

```julia
julia> a = 3
3

julia> f(x) = x * a
f (generic function with 4 methods)

julia> f(2)
6
```
