### ISSUE TITLE
halo_size definition duplicated

### ISSUE THREAD

**Issue by aramirezreyes** [CliMA/Oceananigans.jl#2129]
Halo is defined both in lines 69 and 86, both are exactly the same. 

https://github.com/CliMA/Oceananigans.jl/blob/4f80c386930a5b703f753bafd4af76419dbbcac9/src/Grids/grid_utils.jl#L69

https://github.com/CliMA/Oceananigans.jl/blob/4f80c386930a5b703f753bafd4af76419dbbcac9/src/Grids/grid_utils.jl#L86

If it is usefull I can make a PR to remove one of them.

**Comment by navidcy** [comment]
Yeap!

**Comment by navidcy** [comment]
Resolved by #2121
