### ISSUE TITLE
Return statement in a test seems incomplete

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2135]
Is `nothing` missing from here? Or something else?

https://github.com/CliMA/Oceananigans.jl/blob/4f80c386930a5b703f753bafd4af76419dbbcac9/test/test_matrix_poisson_solver.jl#L70

cc @simone-silvestri

**Comment by simone-silvestri** [comment]
I think here `return` and `return nothing` would have the same effect (probably also just avoiding the whole `return` statement). I'll investigate a little more

**Comment by glwagner** [comment]
I think we should use `return nothing` at the end of every function to avoid confusion.
