### ISSUE TITLE
Specifying multiple forcings for a model field

### ISSUE THREAD

**Issue by pjrusello** [CliMA/Oceananigans.jl#2136]
Mentioned in #2134, I want to include both a `Relaxation` and `Forcing` for a velocity component, specifically a sponge layer at the top and bottom of the domain and a forcing function within the non-sponge domain.

One potential syntax for this suggested by @glwagner is passing a tuple to the model constructor:  
```
forcing = (; u = (u_relaxation, u_sponge)),
```

This seems like a straightforward syntax from a user perspective since it's similar to other model constructor syntax, e.g., specifying tracers.

Since a `Relaxation` can be called from within a `Forcing` function, it might be easier to simple provide an example of that syntax to create a combined `Forcing`. The calling order of the forcings is explicit in that case since the user is writing the function and it doesn't require any additional development (well, other than an example).

**Comment by glwagner** [comment]
Forcing tuples are also helpful in #2385 !
