### ISSUE TITLE
Error if using too low julia version?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2142]
Should we throw an error if users try to run code with a julia version that's too low?

cc @mukund-gupta

**Comment by vchuravy** [comment]
Just set the `compat` correctly?

**Comment by navidcy** [comment]
This,

https://github.com/CliMA/Oceananigans.jl/blob/affa548de5cfbad9d8f835a180cd69b617aadd95/Project.toml#L61

won't let people use Julia < 1.6

**Comment by glwagner** [comment]
Ok, so maybe I misinterpreted what someone said.
