### ISSUE TITLE
Why is `simulation.stop_iteration` not an integer?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2144]
https://github.com/CliMA/Oceananigans.jl/blob/affa548de5cfbad9d8f835a180cd69b617aadd95/src/Simulations/simulation.jl#L11

**Comment by navidcy** [comment]
Is it because the default value is `Inf`?

**Comment by glwagner** [comment]
Ding ding ding!

**Comment by navidcy** [comment]
Gotcha!
