### ISSUE TITLE
K-Profile Parametrization

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2149]
We might need to implement the K-Profile boundary layer turbulence closure so that we can use it to compare the CATKE performance. 

Ideally, we'd like to calibrate the K-Profile parametrisation using [OceanTurbulenceParameterEstimation.jl](http://github.com/CliMA/OceanTurbulenceParameterEstimation.jl) alongside with CATKE closure and then compare how the two perform under various scenarios.

@glwagner, would it be easy to implement KPP, similarly as done in [OceanTurb.jl](https://github.com/glwagner/OceanTurb.jl)?

cc @rafferrari

**Comment by glwagner** [comment]
It is possible, but not easy.

I suggest that we implement a more modern turbulence closure if we would like a second one for comparisons with CATKE.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
