### ISSUE TITLE
Function interface for extracting properties from models

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2156]
An important missing component of our user interface is a function-based API for extracting properties from models. For example, we often write

```julia
u, v, w = model.velocities
```

when we really should write something like

```julia
u, v, w = velocity_field(model)
```

A major advantage of a function-based interface is that it is more robust to changes to the underlying model implementation. For example, we will eventually need a `VectorField` implementation for velocities (eg for the cubed sphere, or non-orthogonal grids). We'll be sorry that we've written `u, v, w = model.velocities` everywhere when we need to change `model.velocities` to `model.velocity_field`. But with a function-based interface we only have to change `velocity_field(model) = model.velocities` to `velocity_field(model) = model.velocity_field`.

A few other functions besides `velocity_field` that we might want are

* `tracers(model)`
* `free_surface_displacement(model)`
* `kinematic_pressure(model)`
* `buoyancy(model)`

`viscosity(model)` and `diffusivities(model)` might be nice too. One challenge there is figuring out what to do when the viscosity or diffusivities are really tensors rather than scalars (eg we need `VectorField` but we also may need `TensorField`...)

**Comment by francispoulin** [comment]
Great idea, but I admit I have no idea how much work this is going to be.

One minor comment is that if we don't have the word `field` for the 4 other fields, maybe we would just want `velocity` instead of `velocity_field`?

**Comment by glwagner** [comment]
It's very little coding work! Most of the work is designing the interface.

That's true we don't use `tracer_fields`...

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
