### ISSUE TITLE
Do we need `Ax`, `Ay`, `Az` and `volume` from `Operators.jl`?

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2158]
These are just functions which retrieve `Ax`, `Ay`, `Az` and `V` on the location of interest. On the other hand, they conflict with the same variables exported from `AbstractOperations`. I think they should be exported only by the latter because as `AbstractOperations` they have a unique functionality whereas from `Operators` they are just a renaming of `Axᵃᵃᵃ`, `Ayᵃᵃᵃ`, `Azᵃᵃᵃ`and `Vᵃᵃᵃ`

**Comment by glwagner** [comment]
That makes sense to me! It might be a bad idea to export from submodules purely for internal usage anyways. But the metrics are user-facing, so we definitely want to export those.
