### ISSUE TITLE
Serialize grid with `CPU` architecture?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2179]
I think it might make sense to serialize grids in JLD2 files with `CPU` architecture by default; this way they can be loaded on systems without a GPU. 

The downside is that users with GPUs would have to write

```julia
cpu_grid = file["serialized/grid"]
grid = on_architecture(GPU(), cpu_grid)
```

to load their grid on the GPU.

**Comment by glwagner** [comment]
To close this issue I think we probably just need to define `serializeproperty!` for `p::AbstractGrid`:

https://github.com/CliMA/Oceananigans.jl/blob/c71770c10f40ebd0789491a33bbb3f8b4f6de14a/src/OutputWriters/output_writer_utils.jl#L51

**Comment by navidcy** [comment]
I've been running onto this very same problem myself :)

How about a utility like

```Julia
function read_serialized_grid(file; architecture = CPU())
    grid = file["serialized/grid"]

    if architecture == GPU()
        grid = on_architecture(GPU(), grid)
    end

    return grid
end
```

**Comment by glwagner** [comment]
We can extend `on_architecture` to have different behavior when `grid::String` (and thus a path to file).

**Comment by navidcy** [comment]
How about add a keyword argument in the JLD2 writer? `; serialized_grid_architecture = CPU()`?

**Comment by glwagner** [comment]
Mmmm. We should use just `architecture` as the kwarg though right?
