### ISSUE TITLE
Poisson solver tests on GPU still take too long

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2183]
Perhaps we can split the `.jl` file, e.g., put these:

https://github.com/CliMA/Oceananigans.jl/blob/c71770c10f40ebd0789491a33bbb3f8b4f6de14a/test/test_poisson_solvers.jl#L280-L312

in a different script and on their own buildkite process?

**Comment by glwagner** [comment]
Or just move the vertically stretched tests to a different file... ?

**Comment by glwagner** [comment]
I would promote splitting up the tests rather than splitting loops if possible!

**Comment by navidcy** [comment]
Moving the vertically stretched tests to a different file is what I was thinking also! :)
