### ISSUE TITLE
Mean of stretched dimension using `WindowedSpatialAverage`

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2185]
I can see through the definition of `Reduction` that averages in stretched grids are correctly calculated: https://github.com/CliMA/Oceananigans.jl/blob/2f9269df54e836117d9ac8b9790d1c3383bd6384/src/AbstractOperations/metric_field_reductions.jl#L29-L46

However, the same doesn't happen for `WindowedSpatialAverage`: https://github.com/CliMA/Oceananigans.jl/blob/2f9269df54e836117d9ac8b9790d1c3383bd6384/src/Diagnostics/windowed_spatial_average.jl#L44-L50

What's the preferred way to include this into `WindowedSpatialAverage`? Or maybe it would be best to abandon `WindowedSpatialAverage` and add the slicing functionality to `Reduction`?

**Comment by tomchor** [comment]
Actually, I'm just noticing that `Reduction` has a option `mask`. Is that already enough to mimic the windowing behavior?

**Comment by glwagner** [comment]
For reducing any `AbstractField` over "windows", `ConditionalOperation` is sufficient. The task there is to define `condition` appropriately (`mask` is chosen as the "neutral" value for the particular reduction). I guess there isn't an ordinary constructor for `ConditionalOperand`, but there is a function `condition_operand`...

https://github.com/CliMA/Oceananigans.jl/blob/b5bf45ed51587954f61ca7492e946fef69ff72ee/src/AbstractOperations/conditional_operations.jl#L23

(@simone-silvestri why is this function not simply a constructor for `ConditionalOperand`?) This feature is new so the API might change. We also need doc strings...

## On views of `Field`...

We may also eventually want to implement the concept of `view`s of `Field`s. I think if that were implemented properly, we'd be able to reduce those objects. 

#2177 is related; the location `Level` proposed there could handle slices across a whole dimension (but not necessarily "windowing"...)

This is for another issue, but field "windows" might be easy to support by using a `view` for `data`. Cause then:

```julia
julia> a = rand(4, 4)
4×4 Matrix{Float64}:
 b0.720962  0.484984  0.935646  0.453511
 0.41186   0.805359  0.105536  0.724929
 0.738268  0.287272  0.24803   0.782426
 0.777353  0.999748  0.515442  0.321921

julia> b = view(a, 2:3, 2:3)
2×2 view(::Matrix{Float64}, 2:3, 2:3) with eltype Float64:
 0.805359  0.105536
 0.287272  0.24803

julia> propertynames(b)
(:parent, :indices, :offset1, :stride1)

julia> b.indices
(2:3, 2:3)
```

we have our indices.

**Comment by tomchor** [comment]
> For reducing any `AbstractField` over "windows", `ConditionalOperation` is sufficient. The task there is to define `condition` appropriately (`mask` is chosen as the "neutral" value for the particular reduction). I guess there isn't an ordinary constructor for `ConditionalOperand`, but there is a function `condition_operand`...
> 
> https://github.com/CliMA/Oceananigans.jl/blob/b5bf45ed51587954f61ca7492e946fef69ff72ee/src/AbstractOperations/conditional_operations.jl#L23

Is there an example of how to do that? If not, do you mind writing a quick example? I saw that Oceananigans gained this `ConditionalOperation` lately, but the code has been growing so fast lately that it's hard to keep track, so I really don't know how I'd do it. Also I couldn't find `ConditionalOperation` on the docs or in the PRs (although I know it's in one of the PRs).

**Comment by simone-silvestri** [comment]
@tomchor `ConditionalOperation` is used "under-the-hood" to reduce a field with a condition. A reduction on a field can now be called with two additional keyword arguments: `condition` and `mask`. Where `condition` evaluates to `false` the field to be reduced will be masked with `mask` which (if not specified) is `-Inf, Inf, 1, 0` for `maximum, minimum, prod` and `sum`, respectively, such that region where `condition = false` can be excluded from the reduction. 

(probably not the right place to say it but I see now that we might have a problem with `maximum(abs, field, condition = something)`)

An example is here
```
julia> grid = RectilinearGrid(arch, size = (4, 1, 1), extent = (1, 1, 1))
RectilinearGrid{Float64, Periodic, Periodic, Bounded}
             architecture: CPU()
                   domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
        size (Nx, Ny, Nz): (4, 1, 1)
        halo (Hx, Hy, Hz): (1, 1, 1)
             spacing in x: Regular, with spacing 0.25
             spacing in y: Regular, with spacing 1.0
             spacing in z: Regular, with spacing 1.0

julia> field = Field{Center, Center, Center}(grid)
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (4, 1, 1)
├── grid: RectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=4, Ny=1, Nz=1)
└── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux

julia> set!(field, [1, 2, 3, 4])

julia> sum(field)
10.0

julia> sum(field, condition = field .> 2)
7.0

julia> sum(field, condition = field .> 2, mask = 100)
207.0

julia> sum(field, condition = (i, j, k, grid, field) -> grid.xᶜᵃᵃ[i] < 0.3)
1.0
```

A `ConditionalOperation` just contains the "operand" to reduce (might be an `AbstractField` or an `AbstractOperation`), a grid, the condition (which can be a `Function` or an `AbstractArray`), and the `mask` (which at the moment is just a number)

You can construct it with `condition_operand(field, condition, mask)`. But most of the time you probably won't need it as reductions already automatically construct it when you specify a condition through the keyword argument

@glwagner `condition_operand` is used because we needed to define it in `Fields.jl` which is added before `AbstractOperations.jl`

**Comment by tomchor** [comment]
Oh wow that's super nice. I think this makes `WindowedSpatialAverage` obsolete, no? Instead of doing:

```julia
julia> grid = RectilinearGrid(size = (4, 1, 1), extent = (1, 1, 1))
4×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=0.25
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=1.0

julia> field = Field{Center, Center, Center}(grid)
4×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux
└── data: 6×3×3 OffsetArray(::Array{Float64, 3}, 0:5, 0:2, 0:2) with eltype Float64 with indices 0:5×0:2×0:2
    └── max=0.0, min=0.0, mean=0.0

julia> set!(field, [1, 2, 3, 4])
4×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux
└── data: 6×3×3 OffsetArray(::Array{Float64, 3}, 0:5, 0:2, 0:2) with eltype Float64 with indices 0:5×0:2×0:2
    └── max=4.0, min=1.0, mean=2.5

julia> wav = WindowedSpatialAverage(field, dims=(1,2,3), field_slicer=FieldSlicer(i=3:4))
WindowedSpatialAverage{Field{Center, Center, Center, Nothing, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, CPU}, Float64, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing}, FieldSlicer{UnitRange{Int64}, Colon, Colon}, Tuple{Int64, Int64, Int64}}(4×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux
└── data: 6×3×3 OffsetArray(::Array{Float64, 3}, 0:5, 0:2, 0:2) with eltype Float64 with indices 0:5×0:2×0:2
    └── max=4.0, min=1.0, mean=2.5, FieldSlicer{UnitRange{Int64}, Colon, Colon}(3:4, Colon(), Colon(), false), (1, 2, 3))
```

One can apparently do the following and get the right result:

```julia
julia> av2 = Field(Average(field, dims=(1,2,3), condition=(i, j, k, grid, field) -> grid.xᶜᵃᵃ[i] > 0.5))
1×1×1 Field{Nothing, Nothing, Nothing} reduced over dims = (1, 2, 3) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 1)
├── grid: 4×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── operand: mean! over dims (1, 2, 3) of Conditioned Field at (Center, Center, Center)
└── status: time=0.0

julia> compute!(av2)
interior(av2)

julia> interior(av2)
1×1×1 view(::Array{Float64, 3}, 1:1, 1:1, 1:1) with eltype Float64:
[:, :, 1] =
 3.5
```

Let me know if I'm not missing anything and I'll open a PR to remove `WindowedSpatialAverage`.

**Comment by simone-silvestri** [comment]
Ah nice! sure, maybe using `ConditionalOperation` is a bit slower that `WindowSpatialAverage` because it actually computed the whole domain, but I agree to nuke `WindowSpatialAverage` if it has the same functionality

**Comment by glwagner** [comment]
Agree too, less code = better.
