### ISSUE TITLE
Do we need to better differentiate between regular and stretched grids?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2192]
For example, the grid below is perfectly regularly spaced in all dimensions but Oceananigans doesn't "see" it that way...

```Julia
julia> grid = RectilinearGrid(size = (4, 4, 2), x = (0, 1), y=[0, 1//4, 2//4, 3//4, 1], z=[0, 0.5, 1])
4×4×2 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 1.0) regularly spaced with Δx=0.25
├── Periodic y ∈ [0.0, 1.0) variably spaced with min(Δy)=0.25, max(Δy)=0.25
└── Bounded  z ∈ [0.0, 1.0] variably spaced with min(Δz)=0.5, max(Δz)=0.5
```

(This may be also relevant in a solution/warning to be shown to the user regarding #2191.)

**Comment by navidcy** [comment]
Possibly a solution could be that as part of the validation of the grid we check whether
```Julia
min(Δy) - max(Δy) < abstol
```
and if the above is true then recreate the grid with `y = (min(grid.y), max(grid.y))`?

**Comment by tomchor** [comment]
I think the current behavior is useful for testing purposes. It seems to me this would be beneficial only in a very small handful of cases. I vote we keep the current behavior.

**Comment by simone-silvestri** [comment]
We could put a warning when `min(Δy) == max(Δy)`
```
@warn " current grid is stretched but min(Δy) = max(Δy), you might want to recreate the grid with y = ($(grid.y[1], $grid.y[grid.Ny+1]):"
```

**Comment by glwagner** [comment]
A warning might make sense.

`show` can be more specific (spacing `Array` doesn't mean that the spacing is variable, it means the spacing is given by an `Array`). It's good at least now that `show` helps you realize that `Array` spacings are special.

**Comment by glwagner** [comment]
Should we close this? I'm not sure it makes sense to add code for this case. It's perfectly fine for users to do this.

**Comment by tomchor** [comment]
I vote to close
