### ISSUE TITLE
Show free surface solver method in `show(::IO, ::HydrostaticFreeSurfaceModels)`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2197]
I believe it'll be a useful addition.

https://github.com/CliMA/Oceananigans.jl/blob/c1f06d2e602ef22bcfbdc799948a018785815613/src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl#L4

cc: @simone-silvestri, @glwagner

**Comment by simone-silvestri** [comment]
Sure!
