### ISSUE TITLE
32-bit indices for decreased GPU register pressure

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2202]
Some recent improvements in `CUDA.jl`:

https://juliagpu.org/post/2022-01-28-cuda_3.5_3.8/#preserving_array_indices

attempt to avoid promoting index types from 32-bit to 64-bit integers (64-bit integers are Julia's default).

Throughout `Oceananigans` we use 64-bit integers by using the constant `1` for index calculations:

https://github.com/CliMA/Oceananigans.jl/blob/9f6d841393094b123c99287fab7157a65db4d513/src/Operators/difference_operators.jl#L7

According to that blog post, changing the above line

```julia
 @inline δxᶜᵃᵃ(i, j, k, grid, u) = @inbounds u[i+0x1, j, k] - u[i,   j, k] 
```

may decrease register pressure (perhaps dramatically, especially for wide stencils with lots of indices). `0x1` is the integer 1 with type `UInt8`:

```julia
julia> i = 0x1
0x01

julia> typeof(i)
UInt8

julia> i == 1
true

julia> i === 1
false
```

The amount of code that generates our stencils is not all that large. We find stencil calculations in

* `Operators`
* `Advection`
* `ImmersedBoundaries`

I also found a few stray index manipulations in random places like

https://github.com/CliMA/Oceananigans.jl/blob/9f6d841393094b123c99287fab7157a65db4d513/src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl#L211

I think this issue also implies that we should strive to minimize the number of places where we do index calculations, to minimize the chances that we accidentally convert to `Int64`.

We might also want to do some profiling to see the specific effect moving to `UInt8` indices might have. Perhaps we should benchmark two fully-loaded models, a `NonhydrostaticModel` LES with high-order advection, and a global-configuration of `HydrostaticFreeSurfaceModel` with an immersed boundary / continents, etc.

**Comment by navidcy** [comment]
Note that we have pinned CUDA at v3.3.6. Any time I tried to update beyond that version things seem to break. I'll press on with the efforts in #1701...

**Comment by glwagner** [comment]
> Note that we have pinned CUDA at v3.3.6. Any time I tried to update beyond that version things seem to break. I'll press on with the efforts in #2005...

Is it worth upgrading until we are ready to tackle this issue?

**Comment by tomchor** [comment]
> According to that blog post, changing the above line
> 
> ```julia
>  @inline δxᶜᵃᵃ(i, j, k, grid, u) = @inbounds u[i+0x1, j, k] - u[i,   j, k] 
> ```
> 
> may decrease register pressure (perhaps dramatically, especially for wide stencils with lots of indices). `0x1` is the integer 1 with type `UInt8`:

Sorry I don't quite understand: Is this potentially affecting the calculations right now, or will it only be an issue if we upgrade to CUDA 3.5+?

Also, it took me a while to figure out what the term "register pressure" meant, so I'm also leaving the relevant wikipedia page here for whoever needs it: https://en.wikipedia.org/wiki/Register_allocation

**Comment by glwagner** [comment]
> Sorry I don't quite understand: Is this potentially affecting the calculations right now, or will it only be an issue if we upgrade to CUDA 3.5+?

CUDA 3.8 includes features that may allow us to decrease register pressure or implement performance optimizations that would otherwise be difficult or impossible.

**Comment by glwagner** [comment]
@simone-silvestri should we close?

**Comment by simone-silvestri** [comment]
yep, I tried and it didn't make much difference. We can revisit this later on

**Comment by glwagner** [comment]
Ok, closing.
