### ISSUE TITLE
Bug in show for column Hydrostatic models

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2210]
Column Hydrostatic models don't have a free surface and, therefore, produce an error here:
https://github.com/CliMA/Oceananigans.jl/blob/ce461f90e991a85105962e165ca4ceab15b1159a/src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl#L13

**Comment by simone-silvestri** [comment]
It happens also when we use 'velocity = PrescribedVelocityFields` (or I think that might be also the case for the column models)
