### ISSUE TITLE
Testing problem

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2222]
Often when running CI, the tests fail on tartarus because of a loading error (there are apparently some missing files),

example
```
ERROR: LoadError: LoadError: SystemError: opening file "/storage5/buildkite-agent/.julia-5513/compiled/v1.6/Oceananigans/hU93i_FjLMs.ji": No such file or directory
```

Retrying the test clears the error, but maybe we should look a bit into it so that we don't have to manually retry...

**Comment by navidcy** [comment]
Yeah. I find this a lot. What could it be? I have no idea…

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
