### ISSUE TITLE
Simplifying notation for difference and interpolation operators

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2236]
Now that most operators are 3D we could simplify the nomenclature for the difference and interpolation operators by getting rid of the `ᵃ`, no? I think it would make code more legible.

For example something like this (from [Oceanostics](https://github.com/tomchor/Oceanostics.jl/blob/da1d9174480df4bacd05b0e050fa9f25f51ab337/src/TKEBudgetTerms.jl#L29-L33))

```julia
@inline function turbulent_kinetic_energy_ccc(i, j, k, grid, u, v, w, U, V, W)
    return (ℑxᶜᵃᵃ(i, j, k, grid, ψ′², u, U) +
            ℑyᵃᶜᵃ(i, j, k, grid, ψ′², v, V) +
            ℑzᵃᵃᶜ(i, j, k, grid, ψ′², w, W)) / 2
end
```

could become this, which I think is way easier on the eyes:

```julia
@inline function turbulent_kinetic_energy_ccc(i, j, k, grid, u, v, w, U, V, W)
    return (ℑxᶜ(i, j, k, grid, ψ′², u, U) +
            ℑyᶜ(i, j, k, grid, ψ′², v, V) +
            ℑzᶜ(i, j, k, grid, ψ′², w, W)) / 2
end
```

Double interpolators could go from `ℑxyᶠᶜᵃ` to `ℑxyᶠᶜ` or `ℑxᶠyᶜ`.

Thoughts?

This was originally suggested by @simone-silvestri in #2214

**Comment by tomchor** [comment]
Just saw that @simone-silvestri mentioned that in https://github.com/CliMA/Oceananigans.jl/pull/2214#issue-1122249491, my bad. I'll modify the issue to reflect that

**Comment by glwagner** [comment]
I prefer the three letter notation because it's more explicit. I'm worried that mistakes might be easier to make, since the current format has a redundancy that in my experience often catches hard to find bugs when coding and formatting long expressions.

Here's an example of such an expression:

https://github.com/CliMA/Oceananigans.jl/blob/b7871d3fc8b53e8bfecb5395e80287ac9c12d0da/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L262-L301

I agree though that the "minimal" notation is more readable for short expressions like the example above.

**Comment by francispoulin** [comment]
Even though it takes more effort, because there are three directions, I also prefer having three letters.  It seems more explicit, even thought it mght be more information than is necessarily needed.

**Comment by glwagner** [comment]
@tomchor do you mind if I reopen this? I think it's worth discussing more!

**Comment by tomchor** [comment]
Not at all

**Comment by simone-silvestri** [comment]
I am in favour of removing the indices, but not necessarily too much against keeping them either.  I can see reasons for both. Since these functions are not user-facing (and would be understandable either way),  I guess the best choice is to do what makes the most developers happy.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
