### ISSUE TITLE
`TurbulenceClosures` consolidation of diffusivities

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2239]
@simone-silvestri brainstormed today about ways to clean up `TurbulenceClosures`.

One idea that came up is to combine `IsotropicDiffusivity` and `HorizontallyCurvilinearAnisotropicDiffusivity` into a single `ScalarDiffusivity` (where isotropy in various directions is _implied_). We'll also simplify the "anisotropic" diffusivity in this process. The user interface could look something like

```julia
three_dimensional_diffusivity = ScalarDiffusivity(ThreeDimensional(), ν=1)
horizontal_diffusivity = ScalarDiffusivity(Horizontal(), ν=1)
vertical_diffusivity = ScalarDiffusivity(Vertical(), ν=1)
```

so, no more `νh` and `νz`.

The advantage is that we eliminate / share much more code. Arguably the API is a bit cleaner as well. (We can discuss aliases and defaults like `HorizontalScalarDiffusivity`, etc.)

Under the hood we'll add the `Directionality` type to the type parameters of `ScalarDiffusivity`:

```julia
struct ScalarDiffusivity{TimeDisc, Nu, Kappa, Directionality} <: AbstractScalarDiffusivity{TimeDisc, Dir}
    ν :: Nu
    κ :: Kappa

    function IsotropicDiffusivity{TimeDisc}(dir::Dir, ν::Nu, κ::Ka) where {TimeDisc, Dir, Nu, Ka}
        return new{TimeDisc, Nu, Ka, Dir}(ν, κ)
    end
end
```

Then `abstract_isotropic_diffusivity.jl` becomes `abstract_scalar_diffusivity.jl`, and will implement the necessary abstractions for 3D isotropic scalar diffusivities, horizontally-isotropic diffusivities (a la MITgcm), and vertical diffusivities. 

Consolidating code is an important precursor to a larger refactor that might

1) support `AbstractOperation` viscosities and diffusivities at all locations on the grid
2) eliminate `diffusivity_fields` and
3) perhaps also involve fixing `TwoDimLeith` and implementing a biharmonic Leith.

**Comment by navidcy** [comment]
more flexible and less code -- what can go wrong?

yeap!
