### ISSUE TITLE
Export `Horizontal` and `Vertical` diffusivity isotropies from top-level?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2254]
We shouldn't have to import them into user-scripts as in

https://github.com/CliMA/Oceananigans.jl/blob/80f328b9d94bb4f13af8347f06356b93127638cc/examples/eady_turbulence.jl#L123

if we have conflicts then we might need more verbose names like `HorizontalIsotropy`, `VerticalIsotropy`. Should resolve ASAP if we need a name change.

**Comment by tomchor** [comment]
I agree with exporting them by default. I also think if we change notation to `ZDirection`, `XDirection` etc., it will probably decrease the chance for name conflicts.

**Comment by navidcy** [comment]
Yeap, export!

**Comment by glwagner** [comment]
Stale
