### ISSUE TITLE
Need test for (Cu)Array of `IsopycnalSkewSymmetricDiffusivity` closures

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2258]
https://github.com/CliMA/Oceananigans.jl/pull/2257/

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
