### ISSUE TITLE
Euler time-stepping in the `QuasiAdamsBashforth2TimeStepper` is buggy --- a NaN will persist!

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2259]
The Euler time stepping here is done by setting `χ=-0.5`

https://github.com/CliMA/Oceananigans.jl/blob/383e5b60ca8d3bfb3c8497b11b6be30946a25728/src/TimeSteppers/quasi_adams_bashforth_2.jl#L55

which then at 

https://github.com/CliMA/Oceananigans.jl/blob/383e5b60ca8d3bfb3c8497b11b6be30946a25728/src/TimeSteppers/quasi_adams_bashforth_2.jl#L138

implies that `G⁻` is multiplied with zeros (and thus ignored!).

But, what if `G⁻` includes a NaN? since `0 * NaN = NaN` then we don't get the expected behaviour here!

This (heroic) discovery was made by @glwagner after a week (or weeks) of trying to understand why NaN particles persisted in http://github.com/CliMA/OceanTurbulenceParameterEstimation.jl. See also http://github.com/CliMA/OceanTurbulenceParameterEstimation.jl/pulls/210.

**Comment by navidcy** [comment]
Could a potential solution be to include zero-ing out `timestepper.G⁻` inside

https://github.com/CliMA/Oceananigans.jl/blob/383e5b60ca8d3bfb3c8497b11b6be30946a25728/src/TimeSteppers/quasi_adams_bashforth_2.jl#L35-L38

?

**Comment by navidcy** [comment]
Or perhaps write a separate `euler_step!` that does not depend on special values of `χ`. Not sure if that would have an extra GPU cost. But even if so, it'll only be for one time-step, right?

**Comment by glwagner** [comment]
The problem with a separate `euler_step!` is that we might have to define it for a few different models.

Another possibility is zero out `G-` if `euler == true`.

If `euler` is robust then we don't need to zero it in `reset!`, though we could do that too.

**Comment by navidcy** [comment]
Let's zero out `G⁻` when `euler = true`!

Is there anything else that might be causing "trouble" for particular models? E.g., does `G⁻` include the free surface tendency for a `HydrostaticFreeSurfaceModel`? Just wondering if a NaN could remain NaN there and bring about the issue.

**Comment by glwagner** [comment]
I believe it does include the free surface tendency for `HydrostaticFreeSurfaceModel`.

The only annoying thing is that `G⁻.w` is `nothing` for `HydrostaticFreeSurfaceModel`, so you do have to check whether a field `isnothing` before zeroing it with `parent(field) .= 0`.
