### ISSUE TITLE
Is there a better word than `isotropy` to use for the new ScalarDiffusivity?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2261]
I'm just now reading about the new `ScalarDiffusivity` and trying to use it. I think it's a great idea and I love how it simplifies things, but the use of the word "isotropy" kinda threw me off a bit.

To me setting a scalar diffusivity as `ScalarDiffusivity(..., isotropy=Horizontal())`, implies that the diffusivity is the same in the horizontal directions, but that you can also set a different diffusivity in the vertical direction. Which you can't in this instance of the constructor; you have to create a new one.

There's an extra issue I think if you set `ScalarDiffusivity(..., isotropy=Vertical())`. Since by definition isotropy is [uniformity in all orientations](https://en.wikipedia.org/wiki/Isotropy#:~:text=Isotropy%20is%20uniformity%20in%20all,the%20prefix%20an%2C%20hence%20anisotropy.), I don't think it's accurate to say something is isotropic over one single direction.

Maybe a better word would be "directions"? Or directionality? (if that's even a word...)

**Comment by glwagner** [comment]
We can consider changing this kwarg to `directions`. I don't think we had much a conversation about it, but the two we considered originally were `direction` and `isotropy`. One motivation for using `isotropy` is to smoothly transition from "IsotropicDiffusivity" (with three-dimensionality implied) and "AnisotropicDiffusivity" (meaning, different in the horizontal and vertical directions) to a single struct. But having a clear meaning for most people is more important than that continuity.

Isotropy in _one_ direction is accurate in my opinion, though I agree its the trivial case (like a "set" with one element) and therefore reads a little awkwardly. Diffusion can act in the "horizontal directions" while being horizontally-anisotropic (ie the diffusion of a vector depends on its orientation), so the meaning is a bit different. But, we can document that `ScalarDiffusivity` is isotropic in its `directions` for vectors like momentum.

> To me setting a scalar diffusivity as `ScalarDiffusivity(..., isotropy=Horizontal())`, implies that the diffusivity is the same in the horizontal directions, but that you can also set a different diffusivity in the vertical direction.

We can indeed use a second closure to set a vertical diffusivity.

**Comment by rafferrari** [comment]
I tend to agree that "direction" is a better descriptor. Isotropy implies same kappa in different directions, so it requires at least two directions to be meaningful.

**Comment by glwagner** [comment]
I think we should make this change ASAP if we're going to do it (since its core API), but it'd be nice to hear from a few others...

**Comment by glwagner** [comment]
I changed the title to be a bit friendlier.

#2264 is related. We can solve it the same way by using positional arguments coupled with verbose type names `ZDirection()`, `HorizontalDirections()`, `AllDirections() / `ThreeDirections()` (the latter would be default, so won't be used much). This solution also eliminates `isotropy` as a keyword argument name.
