### ISSUE TITLE
Possibly changing calculation of `solid_interface` function

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2263]
Right now the the function that calculates whether a face location is a solid interface looks like this:

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/Grids/grid_solid_nodes.jl#L42-L50

This means that it'll return `true` even if the face location is completely inside the immersed solid (i.e. the two adjacent centers are inside the solid, not just one). Is this by design? In my view it would make more sense to use `xor` there instead of `or`. That way it would return `false` if the `Face` is completely inside the immersed in the solid, and it would only return `true` in the actual edges of the immersed solid.

This is relevant when implementing boundary conditions to the immersed solids.

cc @whitleyv

**Comment by glwagner** [comment]
Since we throw away any calculations that are entirely inside a solid, we usually don't care what happens there. I think that's why it's called `solid_interface` rather than `fluid_solid_interface`, but @simone-silvestri can confirm.

I think we need a bit more information for boundary conditions right? We have to know the _direction_, eg

```julia
east_fluid_solid_interface(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, LY, LZ, i-1, j, k, grid)
```

This returns `true` when our cell is not immersed, but the eastern boundary is a fluid-solid interface.

**Comment by glwagner** [comment]
All 6 boundaries are something like

```julia
using Oceananigans.AbstractOperations: flip

east_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(flip(LX), LY, LZ, i, j, k, grid)
west_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(flip(LX), LY, LZ, i+1, j, k, grid)
south_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, flip(LY), LZ, i, j, k, grid)
north_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, flip(LY), LZ, i, j+1, k, grid)
bottom_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, LY, flip(LZ), i, j, k, grid)
top_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, LY, flip(LZ), i, j, k+1, grid)
```

something like that. There could be a mistake.

**Comment by glwagner** [comment]
And

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/AbstractOperations/derivatives.jl#L39-L41

**Comment by simone-silvestri** [comment]
> All 6 boundaries are something like
> 
> ```julia
> using Oceananigans.AbstractOperations: flip
> 
>   east_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(flip(LX), LY, LZ, i, j, k, grid)
>  south_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, flip(LY), LZ, i, j, k, grid)
> bottom_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, LY, flip(LZ), i, j, k, grid)
> 
>   west_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(flip(LX), LY, LZ, i+1, j, k, grid) 
>  north_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, flip(LY), LZ, i, j+1, k, grid)
>    top_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(LX, LY, flip(LZ), i, j, k+1, grid)
> ```
> 
> something like that. There could be a mistake.

Yep I think this would work...
Depends if we wan tot exclude the points or edges or not (i.e where `solid_interface` is true but `solid_node` is not), in that case we would need 
```
bottom_bounded(LX, LY, LZ, i, j, k, grid) = solid_node(LX, LY, LZ, i, j, k-1, grid) & !solid_node(LX, LY, LZ, i, j, k, grid))
```

**Comment by tomchor** [comment]
I agree with what you're saying (although I didn't know every calculation inside the solid was thrown away; I thought it was just some stuff like setting the velocities to zero). However, wouldn't using `xor` make the functions simpler and decrease the number of computations?

```julia
east_bounded(LX, LY, LZ, i, j, k, grid) = !solid_node(LX, LY, LZ, i, j, k, grid) & solid_interface(flip(LX), LY, LZ, i, j, k, grid)
```

The above could be replaced by the following line

```julia
east_bounded(LX, LY, LZ, i, j, k, grid) = solid_interface(flip(LX), LY, LZ, i, j, k, grid)
```

Idk if this matters in the grand scheme of a complete simulation, but as a rule `if` statements and comparisons are pretty expensive, so it might be better to try and decrease them, no?

**Comment by glwagner** [comment]
We won't reduce computations, because these operators are not short-circuiting (this is what we want to maximize performance for these inner functions).

Evaluating booleans isn't expensive. Short-circuiting logic can be expensive (or rather, prevent compiler optimizations) in hot inner loops. We've written the code so we don't use short-circuiting logic (`ifelse` rather than `if`, `&` rather than `&&`).

**Comment by glwagner** [comment]
Either way we need both `east_bounded` _and_ `solid_interface` so the question is just how we shuffle logic between the two. We can consider changing `solid_interface`. If we change its behavior I would recommend calling it `fluid_solid_interface`.

**Comment by tomchor** [comment]
> We won't reduce computations, because these operators are not short-circuiting (this is what we want to maximize performance for these inner functions).
> 
> Evaluating booleans isn't expensive. Short-circuiting logic can be expensive (or rather, prevent compiler optimizations) in hot inner loops. We've written the code so we don't use short-circuiting logic (`ifelse` rather than `if`, `&` rather than `&&`).

Ah, I see. I hadn't noticed that. 


> Either way we need both `east_bounded` _and_ `solid_interface` so the question is just how we shuffle logic between the two. We can consider changing `solid_interface`. If we change its behavior I would recommend calling it `fluid_solid_interface`.

I think changing `solid_interface` to `fluid_solid_interface` (along with it's definition of course) is clearer. Especially because `solid_interface` confused me at first; I thought it effectively was supposed to test for the fluid-solid interface. But at this point I don't feel strongly about it.

**Comment by glwagner** [comment]
> Depends if we wan tot exclude the points or edges or not (i.e where `solid_interface` is true but `solid_node` is not)

Hmm yeah I am a little worried that I misunderstood the meaning of `solid_interface` since I think it does assume that the immersed boundary is "referenced" to a tracer cell (ie because `solid_interface(::C, ::C, ::C, i, j, k, grid) = solid_node(c, c, c, i, j, k, grid)`). But I'm not 100% sure.

**Comment by tomchor** [comment]
I see, and I agree with that. I was asking my questions from a grid-fitted boundary which (please correct me if I'm wrong @whitleyv) is always referenced to a cell center, and always has boundaries at faces.

**Comment by glwagner** [comment]
`GridFittedBottom` and `GridFittedBoundary` blank out cells based on some rule evaluated at the cell center (eg a low-order approximation of some shape). We also have `PartialCellBottom` in the works. I don't really know but it could matter in the future to have more general implementations, like `ShavedCellBottom` or maybe even 3D shaved cells.
