### ISSUE TITLE
`Explicit`/`Implicit` names for time-discretizations are a bit vague?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2264]
The recent diffusivity refactor #2247 changed `ExplicitTimeDiscretization` -> `Explicit`.

https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/TurbulenceClosures/implicit_explicit_time_discretization.jl#L8-L27

We are importing these in http://github.com/CliMA/OceanTurbulenceParameterEstimation.jl and it seems a bit vague to import

```Julia
using Oceananigans.TurbulenceClosures: Explicit
```

Should we go back to bit more verbose names?

cc: @simone-silvestri, @glwagner

**Comment by glwagner** [comment]
I agree.

Maybe we can fix this issue by using positional instead of keyword arguments to specify the time discretization. So rather than something like

```julia
closure = ScalarDiffusivity(ν=1, time_discretization=VerticallyImplicitTimeDiscretization())
```

we can have

```julia
closure = ScalarDiffusivity(VerticallyImplicitTimeDiscretization(), ν=1)
```

this way we achieve the same characters / brevity savings, but get to have verbose names for the types.

**Comment by navidcy** [comment]
Could the constructors work with optional positional argument? e.g.

```
function ScalarDiffusivity(time_discretization=VerticallyImplicitTimeDiscretization(); ν=1)
...
```

I believe it'll be OK. Let's do that?

**Comment by simone-silvestri** [comment]
I'm ok with that, but then let's also change `Horizontal` and `ThreeDimensional` to `HorizontalIsotropy` and `ThreeDimensionalIsotropy` and so on

**Comment by glwagner** [comment]
Right, or `HorizontalDirections()` and `ThreeDirections` or `AllDirection()` as discussed on #2261 .
