### ISSUE TITLE
Update on CATKE default parameter values?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2272]
Recent calibration developments may have produced better defaults, e.g., here:
https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl#L108
and
https://github.com/CliMA/Oceananigans.jl/blob/b3ddbc84c8f35aaf5b93fbbfdb4cffcada5c6533/src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl#L69-L85

Should we update these values?

(I'd like to add CATKE closure to the channel...)

**Comment by rafferrari** [comment]
It would be great to add CATKE to the channel to address its computational cost. I agree that it makes sense to update the default parameters.
