### ISSUE TITLE
Do we need to refer to MITgcm manual for horizontal vs vertical diffusivity implementation?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2282]
Do we need to refer to MITgcm manual here:

https://github.com/CliMA/Oceananigans.jl/blob/e1d9d803575c9a9497f6c5afc67bb0c859291d37/docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md#L38-L40

**Comment by glwagner** [comment]
@simone-silvestri can we instead provide a self-contained description of the closures?

**Comment by glwagner** [comment]
This can be closed right?

**Comment by simone-silvestri** [comment]
I think so
