### ISSUE TITLE
Local definition of `area` sometimes is `Δx`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2285]
So here a local variable `area` is defined but `area` could be `Δx`. This is confusing... right?

https://github.com/CliMA/Oceananigans.jl/blob/4f1fe0fa7edd9489ba20875be64b69daa0a77b95/src/Operators/products_between_fields_and_grid_metrics.jl#L8

@simone-silvestri

**Comment by simone-silvestri** [comment]
I guess we could call it `grid_metric` instead of `area` and the iterator can be called `met` or `m` or `grid_term` instead

**Comment by navidcy** [comment]
Sounds good!

**Comment by glwagner** [comment]
If `area = Δx` is not confusing then nothing is sacred
