### ISSUE TITLE
Reduntant `Clock` constructor?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2323]
These two inner and outer `Clock` constructors look the same to me. Am I missing something? Do we need both (and with different docstrings)?

https://github.com/CliMA/Oceananigans.jl/blob/6a7ab79fc116612d8c156b069cbb60b06416bfa8/src/TimeSteppers/clock.jl#L19-L34

@glwagner @simone-silvestri

**Comment by simone-silvestri** [comment]
I think the outer one just transforms `kwargs` in positional `args` by requiring a `time` specified and filling the type of time in the parametric type `T`. 

I think we don't need the interior constructor

**Comment by navidcy** [comment]
I deleted it in #2322 -- let's see what happens.
