### ISSUE TITLE
Fill Halo not working in julia < 1.7

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2358]
In my last PR (#2335) I introduced tupled halo filling. 

This PR required inferring the length of a Tuple of different element types on the GPU (which is not necessarily easy).
I found a hack to do it, but I was working in julia 1.7.

Today, running a simulation with several different functional boundary conditions (in `discrete_form`) with julia 1.6, I found out that the compiler does not like my solution and does not infer the Tuple length (spitting out an `Invalid LLVM` error). This error is not there in julia-1.7

Unfortunately, I already merged my PR because I stupidly did not think to test all possible BC with julia-1.6.

Now, to revert to a non-tupled halo filling which works across julia distribution it's a one-liner (in `field_tuples.jl`)
```
@inline fill_halo_regions_field_tuple!(full_fields, grid, args...; kwargs...) = 
        fill_halo_regions!(extract_field_data.(full_fields), extract_field_bcs.(full_fields), grid, args...; kwargs...)
```
to
```
@inline fill_halo_regions_field_tuple!(full_fields, grid, args...; kwargs...) = 
   for field in full_fields
      fill_halo_regions!(field, args...; kwargs...)
   end
end
```

What should we do? We could change this line and leave the infrastructure intact for when we update to julia-1.7 (then we would't have tupled halo filling till then) or find a completely different solution (which will require a lot of restructuring)
Probably we also need more tests for boundary conditions with different BC on different sides.

I see that the tests that run on julia-1.6 do not return an error though.  Do other people encounter the same error?

**Comment by navidcy** [comment]
Ideally we want to finish #2307 at some point... :)
