### ISSUE TITLE
Error while using `ImmersedBoundaries` on GPU

### ISSUE THREAD

**Issue by iuryt** [CliMA/Oceananigans.jl#2367]
Hi,

I know that `ImmersedBoundaries` is not yet there, but I am trying to use it to define the walls of a numerical rotating tank experiment. I am using `Oceananigans v0.73.1`.

The model instantiation below

```julia
model = NonhydrostaticModel(grid = grid,
                            advection = UpwindBiasedFifthOrder(),
                            tracers = (:T, :S),
                            coriolis = coriolis,
                            buoyancy = SeawaterBuoyancy(),
                            closure = ScalarDiffusivity(ν=1e-6,κ=1e-6),
                            boundary_conditions = (u=u_bcs,v=v_bcs))

set!(model,T=25,S=0)
```

which only returns the following error while using `GPU()`

```julia
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device 
CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)

Stacktrace:
  [1] throw_api_error(res::CUDA.cudaError_enum)
    @ CUDA ~/.julia/packages/CUDA/DL5Zo/lib/cudadrv/error.jl:105
  [2] macro expansion
    @ ~/.julia/packages/CUDA/DL5Zo/lib/cudadrv/error.jl:115 [inlined]
  [3] cuCtxSynchronize()
    @ CUDA ~/.julia/packages/CUDA/DL5Zo/lib/utils/call.jl:26
  [4] device_synchronize
    @ ~/.julia/packages/CUDA/DL5Zo/lib/cudadrv/context.jl:319 [inlined]
  [5] CUDA.CuModule(data::Vector{UInt8}, options::Dict{CUDA.CUjit_option_enum, Any})
    @ CUDA ~/.julia/packages/CUDA/DL5Zo/lib/cudadrv/module.jl:41
  [6] CuModule
    @ ~/.julia/packages/CUDA/DL5Zo/lib/cudadrv/module.jl:23 [inlined]
  [7] cufunction_link(job::GPUCompiler.CompilerJob, compiled::NamedTuple{(:image, :entry, :external_gvars), Tuple{Vector{UInt8}, String, Vector{String}}})
    @ CUDA ~/.julia/packages/CUDA/DL5Zo/src/compiler/execution.jl:442
  [8] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/fG3xK/src/cache.jl:94
.
.
.
```

The code runs when I use the `underlying_grid` instead or if I change to `CPU`.
The full code is available and can be run on Google Colab.

https://github.com/iuryt/OceanGyreTank.jl/blob/main/OceanGyreTank.ipynb

**Comment by navidcy** [comment]
Can't see what version of Oceananigans you are using.

Also, why the error says `Run Julia on debug level 2 for device stack traces`?

**Comment by navidcy** [comment]
better view of notebook at [nbviewer](https://nbviewer.org/github/iuryt/OceanGyreTank.jl/blob/main/OceanGyreTank.ipynb)

**Comment by glwagner** [comment]
I don't see anything obvious, but I would try

```julia
@inline tank(x, y) = ifelse(radius(x, y) < L, -H, 0.0)
```

so that `tank` always returns `Float64`, rather than sometimes `Int64` (eg, `0`), and sometimes `Float64` (`-H`).

If that doesn't work, we'll have to strip this script down to a more minimal example so that we can debug it. For example, the forcing functions and all the constants and parameters associated with them may not be relevant? Perhaps we can try

```julia
@inline tank(x, y) = -0.15
```

as the immersed boundary function first, too.

**Comment by glwagner** [comment]
I guess another thing to try is to remove the boundary conditions, since the error comes from

```julia
 [13] fill_bottom_and_top_halo!(::NTuple{5, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuArray{Float64, 3}}}, ::Tuple{BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, ::Tuple{BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Oceananigans.BoundaryConditions.ContinuousBoundaryFunction{Face, Center, Nothing, 20, typeof(Qᵘ), Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Oceananigans.BoundaryConditions.ContinuousBoundaryFunction{Center, Face, Nothing, 20, typeof(Qᵛ), Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Oceananigans.BoundaryConditions.Open, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, ::GPU, ::CUDAKernels.CudaEvent, ::ImmersedBoundaryGrid{Float64, Bounded, Bounded, Bounded, RectilinearGrid{Float64, Bounded, Bounded, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Fl...
    @ Oceananigans.BoundaryConditions ~/.julia/packages/Oceananigans/JIHfS/src/BoundaryConditions/fill_halo_regions.jl:153
```

This code was recently changed in #2335 and launches this kernel function:

https://github.com/CliMA/Oceananigans.jl/blob/2436895ee931c730c077031d955dd1780816b2ac/src/BoundaryConditions/fill_halo_regions.jl#L136-L145

My main guess is that something is going wrong during compilation. Might be a task for https://github.com/aviatesk/JET.jl...

**Comment by simone-silvestri** [comment]
Might be... I ll take a look at the problem

**Comment by simone-silvestri** [comment]
Indeed, it seems like 

```
@inline tank(x, y) = ifelse(radius(x, y) < L, -H, Float64(0.0))
```
clears the problem. Interesting... Do you guys have any idea why that could influence the `fill_halo_bottom`?

**Comment by iuryt** [comment]
Had some research deadline and couldn't come back to this problem. I will test with your suggestion and let you know.

**Comment by glwagner** [comment]
> Indeed, it seems like
> 
> ```
> @inline tank(x, y) = ifelse(radius(x, y) < L, -H, Float64(0.0))
> ```
> 
> clears the problem. Interesting... Do you guys have any idea why that could influence the `fill_halo_bottom`?

If there's a function that can return two possible types (which is inferred to a type `Union` I think) then this might propagate downstream in the compiled code (ie two possible scenarios must be maintained; one when the returned value is `Float64`, and another with different intrinsics for when the returned value is `Int`). I think in principle this can greatly complicate the kernel function for filling the boundary condition.

This is just heuristics though. Someone with deeper knowledge of the Julia compiler / compilation system might have a better answer. Also these things can change by the day with package upgrades and new Julia versions.

**Comment by glwagner** [comment]
This blog post may be relevant:

https://julialang.org/blog/2018/08/union-splitting/

**Comment by iuryt** [comment]
I am closing the issue because the solution is to give always `Float64` as suggested by @simone-silvestri 

```julia
@inline tank(x, y) = ifelse(radius(x, y) < L, -H, Float64(0.0))
```

**Comment by glwagner** [comment]
> I am closing the issue because the solution is to give always `Float64` as suggested by @simone-silvestri
> 
> ```julia
> @inline tank(x, y) = ifelse(radius(x, y) < L, -H, Float64(0.0))
> ```
> 
> I tested and this is working now. Had some issues in the boundaries, but I might discuss that in another issue/discussion.

Note there is no difference between `0.0` and `Float64(0.0)`.

**Comment by iuryt** [comment]
> > I am closing the issue because the solution is to give always `Float64` as suggested by @simone-silvestri
> > ```julia
> > @inline tank(x, y) = ifelse(radius(x, y) < L, -H, Float64(0.0))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tested and this is working now. Had some issues in the boundaries, but I might discuss that in another issue/discussion.
> 
> Note there is no difference between `0.0` and `Float64(0.0)`.

Sorry,

What I actually used was
```julia
@inline tank(x, y) = ifelse(radius(x, y) < L, -H, 0.0)
```

**Comment by tomchor** [comment]
I just saw this issue and I know I'm late to the party but I just I'd report that I've encountered this same error before in the past, and what solved the issue was exactly the solution that you guys found here. 

It was long ago enough that the version of CUDA was different, so I'd say this probably isn't a bug in this CUDA version, rather it is some kind of compiler limitation.
