### ISSUE TITLE
Do we need `@unroll` in fill halo flux functions?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2369]
For `FluxBoundaryCondition` we fill _all_ the halos:

https://github.com/CliMA/Oceananigans.jl/blob/2436895ee931c730c077031d955dd1780816b2ac/src/BoundaryConditions/fill_halo_regions_flux.jl#L31

However, I think since #2276 handles boundary conditions for `ScalarBiharmonicDiffusivity`, I don't think there's any point in filling halo points beyond the first.

@simone-silvestri is this true?

**Comment by simone-silvestri** [comment]
Sure! only the first halo node is required since we have 2nd order viscous terms and advection reduces to second order near the boundary
