### ISSUE TITLE
Can't we have a 2D simulation on the sphere?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2372]
In a lat-lon grid, why do we require the vertical topology to be `Bounded`? Why can't it be `Flat`?

https://github.com/CliMA/Oceananigans.jl/blob/1db38fefc123fc0000176c5eed369edac28b7246/src/Grids/latitude_longitude_grid.jl#L210

**Comment by glwagner** [comment]
Just because we calculate the free surface tendency by integrating the vertical velocity. So we need to special-case vertically Flat (calculate free surface directly from divergence) to support it. It's possible!

**Comment by navidcy** [comment]
But what you say is for `HydrostaticFreeSurface` model.

I suggest that the grid constructor does not restrict the `z` topology then but instead the `HydrostaticFreeSurface` does so. Right?

**Comment by glwagner** [comment]
True. But, that's the only model that works with `LatitudeLongitudeGrid` because we don't have a non-hydrostatic pressure solver on the sphere or a valid advection scheme for `ShallowWaterModel`.

**Comment by glwagner** [comment]
> I suggest that the grid constructor does not restrict the `z` topology then but instead the `HydrostaticFreeSurface` does so. Right?

That's fine with me, perhaps the error message will be clearer.
