### ISSUE TITLE
Form of viscosity in `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2403]
@glwagner and @simone-silvestri : 

I updated the Overleaf document to include what form of viscosity we should be using.

In summary, following [Gent (1993) ](https://www.cgd.ucar.edu/staff/gent/swe.pdf), I think the should choose the viscosity for `ShallowWaterModel` to be

ν/h ∇⋅ ( h ∇ 𝐯 ) 

The reasons he states are as follows:

-  h ∇ 𝐯 is a parameterization of the turbulent flux and therefore should be proportional to the depth.
-  This ensures that the diffusion of momentum is in the form of the divergence of a stress tensor (Schar and Smith 1993)
- It has a negative definite effect on the KE budget if the viscous boundary condition is either no slip or free slip.

Of course a problem occurs where h=0 but I guess we just don't apply viscosity where there is no fluid.

If we wanted to generalize this to biharmonic viscosity, I would guess the following, 

ν/h ∇² ( h ∇² 𝐯) 

but this is something that should be done later, of course.

**Comment by francispoulin** [comment]
Yes, more generally, we should include `nu` in the bracket, as you showed above.  Good point.

Thanks @glwagner and I agree that your 4 steps seem like a good way to proceed, and well worth trying.  I can give this a try next week after my teaching is done for the semester.  Unless someone else wanted to give it a try.  I don't want to slow things down.

**Comment by glwagner** [comment]
Updating the code is easy; but testing will be more time consuming. So we just need someone who's willing to run experiments.

**Comment by francispoulin** [comment]
I am certainly happy to run experimenets to get this working.

**Comment by glwagner** [comment]
Alright, I'll put in a PR.

**Comment by francispoulin** [comment]
@glwagner : I added to the overleaf document this morning.  There are two forms that one could consider.  

The one that I mentioned above, equation 7 in Overleaf, is the cheaper of the two but does not correspond to a symmetric stress tensor.

The other one, which is based on the stress tensor, equation 8 in Overlaf, is more expensive, should dissipate more, but does have a symmetric stress tensor.

My guess is that the first one should be the default but maybe there is interest in having the second one as an option?

Also, I go through the details in showing how the other two forms do not give rise to negative definite terms in the energy equation.

**Comment by francispoulin** [comment]
@glwagner : do you think we should only have one form of viscosity in `ShallowWaterModel` or can we have several?

It occurs to me that the first method with `\nu/h \nabla^2 \vec v` might actually be a pain to impliment in a Finite Volume formulation as it's not in divergence form.  If that's the case then I would advocating for the one in divergence form since 1) it's easy to apply and 2) it ensures kinetic energy does not increase because of viscosity.  

In that case we could just have the one and leave it at that.

**Comment by glwagner** [comment]
What if we use

```
h⁻¹ ∇ ⋅ (ν h ∇u)
```

?

We have many closures for all existing models; the same can be true for `ShallowWaterModel`. Hopefully we can reuse existing closures.

**Comment by glwagner** [comment]
Can you paste the equation from the overleaf here?

**Comment by francispoulin** [comment]
Good idea and here goes Of the 4 possibilities I think the 3rd one is the one that is what I would use more often than anything else. 
![Screenshot from 2022-04-05 15-51-57](https://user-images.githubusercontent.com/8239041/161838181-a62fcc14-4ac0-479f-9ac6-79914a982016.png)

**Comment by glwagner** [comment]
Can you write these possibilities for variable `ν` (eg `ν` must always appear inside the divergence)? These don't all have the same dimensions --- what's happening?

**Comment by francispoulin** [comment]
If we want to allow for variable `nu`, which is a good idea, then the first two have the problem of not guaranteeing that viscosity reduces the kinetic energy,

The third form is the one to focus on, and is what would appear in the non-conservative of vector invariant forms.

For the conservative form we need to mutliply the 3rd equation by `h`, and then `nu` has the correct dimensions: length^2/time.

**Comment by glwagner** [comment]
Are the three options then

```
h⁻¹ ∇ ⋅ (ν h ∇u)
h⁻¹ ∇ ⋅ (ν ∇hu)
∇ ⋅ (ν ∇u)
```

? These all have the same dimensions but different properties.

**Comment by glwagner** [comment]
I see that

```
u ∇ ⋅ (ν h ∇u) = ∇ ⋅ (ν u h ∇u) - ν h |∇u|^2
```

Which shows this has positive definite dissipation of `h|u|^2` with `ν>0` and `h > 0`.

**Comment by francispoulin** [comment]
Yes, if we are dealing with the conservative form, `1.` is the one that I am suggesting, and iut does ensure that kinetic energy is disispated by viscosity. I don't believe that `2.` and `3.` have that property.

**Comment by glwagner** [comment]
> Yes, if we are dealing with the conservative form, `1.` is the one that I am suggesting, and iut does ensure that kinetic energy is disispated by viscosity. I don't believe that `2.` and `3.` have that property.

Right! And just to clarify, it conserves the kinetic energy density `h |u|^2`. The form of kinetic energy is crucial, because `∇ ⋅ (ν ∇u)` _does_ conserve `|u|^2`. Note that `∇ ⋅ (ν ∇hu)` conserves the "transport variance" `|hu|^2`. Also,

```
u ∇ ⋅ (ν ∇hu) = ∇ ⋅ (ν u ∇hu) - ν ∇u ⋅ ∇hu = ∇ ⋅ (ν u ∇hu) - ν h |∇u|^2 - ν u ∇u⋅ ∇h
```

**Comment by glwagner** [comment]
> P.S. How do you include latex here?

I'm just copy-pasting the unicode `∇` and `⋅`

**Comment by glwagner** [comment]
> If we use \nabla \cdot (\nu \nabla u) then we don't have the right units as we are evolving h u.

Sorry for being unclear. What I meant was that if we use the dissipation term

```
h ∇ ⋅ (ν ∇u)
```

then we dissipate the quantity `|u|^2` monotonically. To see this, we divide by `h` and then derive a conservation equation for `|u|^2`.

**Comment by francispoulin** [comment]
I see what you mean that `h ∇ ⋅ (ν ∇hu)` also satisfies some nice properties.  I haven't seen that before but why not?  Seems like a viable option.  Maybe add that to the list of possible viscosity for shallow water?

It would be fun to test what difference these terms have on a simple problem.  Just need to think about the problem, and of course get the code working.

**Comment by francispoulin** [comment]
@glwagner : did you want to schedule a pair programming session sometime to start the proposed PR?

**Comment by glwagner** [comment]
I do! I'll send a message on slack.
