### ISSUE TITLE
API for bottom drag over bathymetry

### ISSUE THREAD

**Issue by sandreza** [CliMA/Oceananigans.jl#2407]
Specifying where the bottom drag is located in the presence of bathymetry is currently cumbersome. A suggested API change would be to decouple the specification of the immersed boundary and location of the bottom drag. Perhaps a struct like LinearDrag() or QuadraticDrag() that gets passed to the boundary conditions (BottomDrag(LinearDrag()) maybe?)

**Comment by glwagner** [comment]
There's currently a property in `FieldBoundaryConditions` called `immersed`. So the plan is to use that with something like

```julia
u_drag(x, y, z, t, u, v, w, Cd) = - Cd * u * sqrt(u^2 + v^2 + w^2)
u_immersed_bc = FluxBoundaryCondition(u_drag, parameters=Cd, field_dependencies=(:u, :v, :w))
u_boundary_conditions = FieldBoundaryConditions(immersed=u_immersed_bc)
```

and the same for other velocity components.

**Comment by sandreza** [comment]
That looks like exactly what is needed!

**Comment by glwagner** [comment]
There's additional discussion about this topic at https://github.com/CliMA/Oceananigans.jl/pull/2275#issuecomment-1050094675

**Comment by sandreza** [comment]
sounds good to me!
