### ISSUE TITLE
Errors in the output writers docs page

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2427]
I just realized that the output writers docs page has errors relating to the purging of `FieldSlicer()`: https://clima.github.io/OceananigansDocumentation/stable/model_setup/output_writers/#Examples

![image](https://user-images.githubusercontent.com/13205162/162648339-b7b30179-a9cc-4c05-ab34-9833e7603044.png)

Now that `FieldSlicer()` doesn't exist anymore, part of that section may be out of date and needs to be re-written.

**Comment by glwagner** [comment]
The syntax translation is

```
field_slicer = FieldSlicer(; i, j, k)
```

becomes

```
indices = (i, j, k)
```

**Comment by tomchor** [comment]
> These should be `jldoctest`'d

They are. But apparently the error made it into the source files: https://github.com/CliMA/Oceananigans.jl/blob/b945655a8363f60d03077253edcd77a56936c5cc/docs/src/model_setup/output_writers.md?plain=1#L89-L101

Apparently these slipped through the cracks here: https://github.com/CliMA/Oceananigans.jl/pull/2246/files#diff-9192b98dd6db72149d0d09e5af4820a650091d3509aeb1c2327c27c3e5d8d1b4 

I'll fix these in https://github.com/CliMA/Oceananigans.jl/pull/2416
