### ISSUE TITLE
Should we add `location` to the `export` list?

### ISSUE THREAD

**Issue by iuryt** [CliMA/Oceananigans.jl#2438]
Should we add location to the export list?
https://github.com/CliMA/Oceananigans.jl/blob/74ebfa0ceb6e547e50dbb5dcf350fe1b2ded2d1d/src/Oceananigans.jl#L35-L38

The code below
```julia
using Oceananigans
?location
```

Returns:
```julia
search:

Couldn't find location
Perhaps you meant position or local
No documentation found.

Binding location does not exist.
```

But we have it here

https://github.com/CliMA/Oceananigans.jl/blob/9eb055064e68f6a725cebcf9973a3ebf1cbad16b/src/Fields/abstract_field.jl#L37-L40

**Comment by glwagner** [comment]
Good idea! This deserves to be part of the "primary" API!

**Comment by iuryt** [comment]
I will make a PR for that, then.
