### ISSUE TITLE
Benchmarking scripts for immersed boundaries and immersed boundary conditions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2452]
We need to benchmark various flavors of `ImmersedBoundaryGrid` including

* `GridFittedBoundary` for immersed boundaries that are both function-based (computed on the fly) and array-based (precomputed)
* `GridFittedBottom` for the same (I think for _this_ case, precomputation is always wise. That's not the case for `GridFittedBoundary` though. The benchmarks will hopefully show this.)
* Various immersed boundary conditions implemented in #2437 

These should be implemented for both `NonhydrostaticModel` and `HydrostaticFreeSurfaceModel`.

**Comment by francispoulin** [comment]
If we are doing this, could we also try doing immersed coastal boundaries for `ShallowWaterModel`?  It shouldn't be any harder and would be nice to make sure everything works there as well.
