### ISSUE TITLE
Is the finite volume discretization of the barotropic pressure gradient correct?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2475]
We use `∂xᶠᶜᶜ(i, j, k, grid, η)` to represent the x-component of the barotropic pressure gradient, for example:

https://github.com/CliMA/Oceananigans.jl/blob/be040379ec20d77a8968ba3c0dff71aeed1b2a38/src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl#L49-L50

which also appears in the left-side operator for the implicit free surface solver:

https://github.com/CliMA/Oceananigans.jl/blob/be040379ec20d77a8968ba3c0dff71aeed1b2a38/src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl#L141-L142

But a finite volume discretization of x-component of the barotropic pressure gradient term (ie integrating over cell areas, then using Gauss' theorem to transform the volume integral into a surface integral) would look like

<img width="308" alt="image" src="https://user-images.githubusercontent.com/15271942/165198034-1a4fb702-2abc-4ea8-a028-dae750fdeee3.png">

where I've canceled some `dz`, but don't seem to be able to cancel `dy`. Are we making some latent approximation here that we may not need to make?

@simone-silvestri @christophernhill ?

**Comment by glwagner** [comment]
@jm-c might need to see this too

**Comment by simone-silvestri** [comment]
it seems to me that the correct formulation would be, indeed, `1/Az *δₓᵃᵃᶠ(Δy * η)`.  
What was the original reason to use `∂xᶠᶜᶜ`?

On the other hand, I think the way we do it on the LHS is consistent with how we discretize the LHS of the implicit viscous diffusion

**Comment by glwagner** [comment]
But the LHS isn't quite Poisson... it's _similar_ to a Poisson equation, but is derived by combining the momentum and continuity equations and surface boundary condition... and the "Poisson-like" operator arises precisely by differentiating and summing the horizontal pressure gradient term...

**Comment by simone-silvestri** [comment]
But still, I think that you first derive the equation for \eta (after the time discretization) and then integrate in volume. In the end it is still a derivative of a derivative (Following the docs from mitgcm https://mitgcm.readthedocs.io/en/latest/algorithm/algorithm.html). So the \partial x on the LHS should be correct. You 'll see that that term that doesn't cancel (as you derived above) is contained in the integral of the area.

On the other hand, I think we should change the batropic pressure gradient correction

**Comment by glwagner** [comment]
Actually, I think those docs are misleading. The straightforward way to arrive at the implicit step equation is to first discretize in space, and then after that derive the fractional step method. The key steps are:

1. Discretize the continuity equation, and then sum in the vertical to obtain the finite-volume discretized free surface equation in terms of the vertically integrated transports
2. Introduce the predictor velocities in the discretized momentum equation, and then sum the discretized momentum equation in the vertical.
3. Combine the discretized momentum equation with the free surface equation by taking the divergence of the vertically-summed momentum equation.

Steps 2 introduces the vertical sum of the discretized barotropic pressure gradient into the implicit step equation, which is how we see that these two contributions in fact come from the same place.

**Comment by simone-silvestri** [comment]
I don't understand why the space discretization should be done before? When deriving the Poisson equation for pressure in the predictor corrector, that is a step that you do after the discretization in time. Why would the implicit free surface be different?

**Comment by glwagner** [comment]
It just helps to ensure that the discrete continuity equation (and thus discrete conservation of mass) is handled correctly. It's possible that it's not necessary (but it's the reason that the vertically integrated lateral face areas pop up in the numerics).

Here are some notes:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/15271942/165295054-4f3205c2-bf71-46b2-947a-b1c23241328e.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/15271942/165295160-16e73fe2-8116-4ef3-9497-9f0cd4806411.png">

**Comment by simone-silvestri** [comment]
I agree that if you discretize in space before deriving the implicit equation you have a "finite volume" derivative in the LHS. We definitely reach another conclusion by discretizing in space afterwards.

**Comment by francispoulin** [comment]
I wanted to comment on the first step, just to make sure everything is perfectly clear.

The x-component of the momentum equation can be written as

`` 
∂ₜu + g ∂ₓη = Gₓ
``

The first step of the finite volume method is to integrate over the volume and then divide by the volume.  This leads to 

``
∂ₜū + g/Vfcc ∭ ∂ₓη dV = 1/Vfcc ∭ G_x dV
``

So far we all agree.

If we integrate the term with the free-surface we don't get a line integral, we get a surface integral.  Using Gauss' divergence theorem, second integral yields

``
∭ ∂ₓη dV = ∬ [ η ]_{left}^{right} dA
``

Line integrals happen from Green's/Stokes' theorems but those begin with area integrals.  Unless you are keeping the vertical integral fixed and using Green's theorem on the horizontal integral over the area?

If you wanted to use Green's Theorem in the horizontal, then I believe you would get

``
∭ ∂ₓη dV = ∫ [∮ η dy  ] dz

``

I just want to make sure we are being careful and using the right theorem here.

**Comment by francispoulin** [comment]
I think I have answered my own question.

If you think of the momentum equation in terms fo the stress tensor, then in vector form it is

``
∂ₜuᵢ - ∂ⱼ⋅σᵢⱼ= 0,
``

where the second term is the divergence of the stress tensor.  If we integrate this over the volume, and divide by the volume then we get upon using **Gauss' Divergence Theorem**

``
∂ₜū =1/Vfcc∭  ∂ⱼ⋅σᵢⱼ = 1/Vfcc ∬ σᵢⱼ⋅n̂ dS
``

In the case of an idea fluid we have `σᵢⱼ=-pδᵢⱼ` and therefore our equation above becomes

``
∂ₜū =  1/Vfcc ∬ σᵢⱼ⋅n̂ dS = - 1/Vfcc ∬ p δᵢⱼ⋅ n̂ⱼ dS = - 1/Vfcc ∬ p n̂_i dS
``

This shows that the desired result follows from application of Gauss' Divergence Theorem on the stress tensor.

**Comment by glwagner** [comment]
It's correct.
