### ISSUE TITLE
Oceananigans Port to AMDGPU

### ISSUE THREAD

**Issue by matinraayai** [CliMA/Oceananigans.jl#2493]
Hello,
My [fork](https://github.com/matinraayai/Oceananigans.jl) of Oceananigans.jl is in the process of adding AMDGPU support for the code base. I've added a new architecture called ROCMGPU, and changed the name of the GPU architecture to CUDAGPU. 
Some of the operations are ported, and the tests are updated to use ROCMGPU as well. @christophernhill and I are in the process of running each test suite to see what other operations need to be tweaked for AMDGPU.
1. I would like to push this work on a branch on the main codebase, called amdgpu for it to get more attention.
2. Any help on getting the tests working would be much appreciated.
Thanks

**Comment by glwagner** [comment]
@matinraayai can you please open a PR?

**Comment by glwagner** [comment]
> @christophernhill requested my fork to be kept in the main repo. It will be eventually upstreamed in main but for now its own separate branch for developing it should be the way to go.

To achieve this, please open a PR to the branch `amdgpu`.

**Comment by glwagner** [comment]
Also --- really cool that you're working on this!

**Comment by matinraayai** [comment]
@glwagner I can work with the aliasing name and I agree with the user-friendliness of the approach. I will have to go back and change Architecture.jl.
I will open a PR to the branch ```amdgpu``` to get everyone started for now.
Thanks for the quick reply.

**Comment by matinraayai** [comment]
Thanks for merging, I'm closing this issue.
