### ISSUE TITLE
Tests for `OffsetArrays-Field` broadcasts 

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2501]
with @glwagner we introduced broadcasts across fields and `OffsetArrays` that include halos, so that

```
field1 = CenterField(grid)
field2 = CenterField(grid)

set!(field1, (x, y, z) -> x)

data = field1.data

field2 .= data
```
or alternatively
```
set!(field2, data)
```
will set not only the interior of the field, but also the halos, without the need of `fill_halo_regions!`

We need tests to make sure this feature does not break somewhere...

**Comment by francispoulin** [comment]
Very nice!

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
