### ISSUE TITLE
Add Multi GPU testing

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2526]
with the development of multi GPU we have to expand our test capabilities to include this functionality. 
We should introduce a new Agent that can handle single-node and multi-node multi GPU to our CI pipeline. 

@christophernhill @glwagner @navidcy, any candidates in mind?

**Comment by glwagner** [comment]
tartarus?

**Comment by christophernhill** [comment]
@glwagner can we add a second card to sverdrup?

**Comment by glwagner** [comment]
probably?
