### ISSUE TITLE
TEOS10 Equation of State: Depth vs Height

### ISSUE THREAD

**Issue by sandreza** [CliMA/Oceananigans.jl#2528]
In the equation of state for TEOS10 the function plugged in for depth has a different sign than what is assumed in the seawater polynomial package

https://github.com/CliMA/Oceananigans.jl/blob/main/src/BuoyancyModels/nonlinear_equation_of_state.jl#L27

In the SeawaterPolynomials package, the 'Z' variable must be positive. Thus one (or both) packages must be changed to have the right sign

**Comment by sandreza** [comment]
The companion issue for SeawaterPolynomials is here: https://github.com/CliMA/SeawaterPolynomials.jl/issues/19

**Comment by simone-silvestri** [comment]
That might be why the is-situ density was decreasing with height at same T, S?

**Comment by sandreza** [comment]
It does indeed explain that oddity

**Comment by glwagner** [comment]
Do you have any figures or reasoning about how you found the bug (could help if we or someone has similar issues in the future)?
