### ISSUE TITLE
`NetCDF`: filename vs filepath

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2541]
I was trying use `NetCDFOutputWriter` to write some data using the syntax that is used in the example [here](https://clima.github.io/OceananigansDocumentation/stable/generated/shallow_water_Bickley_jet/) and tried the following:

```
julia> simulation.output_writers[:fields] = NetCDFOutputWriter(model, outputs;
                                                               filename = "buoyancy_displacement.nc",
                                                               schedule = TimeInterval(0.1))
```

That did not work.  The error was `keyword argument filepath not assigned`.  

I checked `help` it said I should be using `filepath` instead of `'filename`.  Hence I tried the following, which did work.

```
julia> simulation.output_writers[:fields] = NetCDFOutputWriter(model, outputs;
                                                               filepath = "buoyancy_displacement.nc",
                                                               schedule = TimeInterval(0.1))
```

I am using juliav1.6 and `NCDatasets v0.12.4`, which seems to be the latest version.  

Does anyone have any suggestions as to what I might be doing wrong?

**Comment by glwagner** [comment]
It's `filename` in the source:

https://github.com/CliMA/Oceananigans.jl/blob/920abd1c3c2c2bab91b5be1e838c448c9c694c15/src/OutputWriters/netcdf_output_writer.jl#L284

the docstring signature:

https://github.com/CliMA/Oceananigans.jl/blob/920abd1c3c2c2bab91b5be1e838c448c9c694c15/src/OutputWriters/netcdf_output_writer.jl#L138

and the docstring body:

https://github.com/CliMA/Oceananigans.jl/blob/920abd1c3c2c2bab91b5be1e838c448c9c694c15/src/OutputWriters/netcdf_output_writer.jl#L157

what version of Oceananigans are you using?

**Comment by navidcy** [comment]
I think it used to be `filepath` and now it's `filename`... So @francispoulin I guess you are on a bit earlier Oceananigans version than the bleeding edge ;)

**Comment by navidcy** [comment]
see https://github.com/CliMA/Oceananigans.jl/pull/2416

**Comment by francispoulin** [comment]
Thank you @glwagner and @navidcy , you are correct my Oceananigans was not the latest and greatest.  I am happy to say that I updated and it's all better now.
