### ISSUE TITLE
Should we check the size of grids in stretched directions?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2548]
At the moment this is possible:

```julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=(4, 4, 4),
                              x = 1:1:10, y=1:1:10,
                              z = 1:1:10, 
                              halo=(3,3,3),
                              )
4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [1.0, 5.0) variably spaced with min(Δx)=1.0, max(Δx)=1.0
├── Periodic y ∈ [1.0, 5.0) variably spaced with min(Δy)=1.0, max(Δy)=1.0
└── Bounded  z ∈ [1.0, 5.0] variably spaced with min(Δz)=1.0, max(Δz)=1.0

julia> grid.Nz
4

julia> length(grid.zᵃᵃᶜ)
10
```
Meaning, you can pass a certain size to the constructor, say `Nx`, and also pass an array for that direction (to "stretch it") that has a different size than `Nx`.

I haven't investigated the consequences of this, but this feels like it could cause problems. Should we throw a warning/error in these cases?

**Comment by francispoulin** [comment]
Good observation and I would vote for yes.  I would prefer if we check and if the sizes don't match the user gets an error and is asked to fix it.

**Comment by simone-silvestri** [comment]
Agreed! Happened to me many times and a warning would be helpful!

**Comment by glwagner** [comment]
The length is correct -- 4 points plus 3 halo points on either side.

**Comment by glwagner** [comment]
Just to clarify that the output was expected (z^aac is an OffsetArray that includes halo points). But I agree a warning would be nice if the length of a coordinate's interfaces does not match the requested cells + 1.

**Comment by tomchor** [comment]
> The length is correct -- 4 points plus 3 halo points on either side.

You're right! That was a bad example. But like you mentioned later, an error/warning is desired
