### ISSUE TITLE
Do we want a `HorizontalDivergenceField`?

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2575]
Thanks to @simone-silvestri , I learned today that we cannot compute the divergence on a `LatitudeLongitudeGrid` using the simple formula of

$$
\zeta = \partial_x(v) - \partial_y(u)
$$

Instead, we should use `VerticalVorticityField`.  

Since this function exists, do we also want to create a [`HorizontalDivergenceField`](https://github.com/CliMA/Oceananigans.jl/blob/main/src/Models/HydrostaticFreeSurfaceModels/vertical_vorticity_field.jl), which computes the equivalent of the following but correctly on all grids?

$$
\delta = \partial_x(u) - \partial_y(v)
$$

I for one expect that I would use this almost as often.

**Comment by glwagner** [comment]
What is the stencil that we use for horizontal divergence?

**Comment by francispoulin** [comment]
If we compute it at the cell centers, then it's very easy.  See below.

This differs from the vorticity, which we compute at the corners.

This picture tries to illustrate the idea where $d = \nabla_H \cdot \vec u_H$.

```
 --- v ---
|         |
u    d    u
|         |
 --- v ---
 ```

**Comment by glwagner** [comment]
If that's the case, then the syntax

```julia
δ = ∂x(u) + ∂y(v)
```

is valid on all grids --- isn't it?

**Comment by glwagner** [comment]
Also to clarify, it's not that the "naive" vorticity stencil is "wrong" on some grids, it's just that it 1) does not generalize to the cubed sphere and 2) apparently, has some other advantages as argued by [Adcroft et al. 2004](https://journals.ametsoc.org/view/journals/mwre/132/12/mwr2823.1.xml?tab_body=abstract-display) (see section 3.c.1).

**Comment by francispoulin** [comment]
> If that's the case, then the syntax
> 
> ```julia
> δ = ∂x(u) + ∂y(v)
> ```
> 
> is valid on all grids --- isn't it?

Yes, I agree that it should be the case.  

By the same rationale, the formulas for vorticity should also work on all grids, except maybe a cubed sphere?

I will experiment with the two approaches on the lat-lon grid and see what I can learn.  

I will close this and return to it if I think there's a need.

**Comment by glwagner** [comment]
> By the same rationale, the formulas for vorticity should also work on all grids, except maybe a cubed sphere?

To answer this question, you'll have to clarify what you mean by "work on all grids".

The fact is that we use the "integral / circulation form" to calculate vorticity for a vector invariant advection scheme --- _not_ the difference formula. We do this even if the difference formula is a "valid approximation" to vorticity.
