### ISSUE TITLE
Unnecessary GPU check?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2595]
Is this redundant? If there is no CUDA-enabled GPU then how could a `grid` on GPU be provided as constructor argument?

https://github.com/CliMA/Oceananigans.jl/blob/d675d8b9f7359219941fa81ce098eb51b7c5ac8f/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L125-L127

**Comment by glwagner** [comment]
Agree this is redundant and if we aren't checking in the grid constructor, we should.
