### ISSUE TITLE
Can we have advection like terms in the forcing?

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2609]
This question is a bit of a detour from the Ocean, but might occur in the oceanographic context sometime, maybe?

With @writingindy, we have put together a one-layer shallow water magnetohydrodynamic model as presented in [Gilman 2000](https://iopscience.iop.org/article/10.1086/317291/meta).  You can see the results of a simulation in the animation below and find the code [here](https://github.com/writingindy/SWMHD/blob/main/sw_mhd_adjustment.jl). To do this we simply needed to add a tracer for the magnetic potential and add a Lorentz force.  Luckily, Oceananigans makes it easy to do both!  In our formulation, we wrote the Lorentz force as  Jacobian, which means that it tends to be noisy and needs dissipation for numerical stability.

The Lorentz  force can also be written in in terms of advection, but the advection is by a tracer field, which leads to the following question:

Can we use advection schemes in the forcing functions?

https://user-images.githubusercontent.com/8239041/173368598-90b26027-63ab-4fcd-91e9-76618ae002bc.mp4

**Comment by simone-silvestri** [comment]
you might want to take a look at `AdvectiveForcing`, maybe it can be used for your problem

PR #2389

**Comment by glwagner** [comment]
`AdvectiveForcing` is defined here:

https://github.com/CliMA/Oceananigans.jl/blob/066c45aee9cd1400ba3e6f2c775eb198cf062e92/src/Forcings/advective_forcing.jl#L15-L55

It's also possible to use the advection kernels directly in a forcing function with `discrete_form=true`. For this you'll have to import either the tracer advection operators:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/Advection/tracer_advection_operators.jl

or the momentum advection operators:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/Advection/momentum_advection_operators.jl

and call them inside the discrete form forcing function with appropriate arguments.

**Comment by navidcy** [comment]
@francispoulin is this resolved?

**Comment by francispoulin** [comment]
Yes, we have almost completed it but the ideas were presented here so let's call it closed.
