### ISSUE TITLE
Change `Ny = 1` to `Flat` in `test_implicit_free_surface_solver.jl`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2625]
Why in the tests for the implicit free surface we use a grid with `Ny = 1` and not `Flat` y?

https://github.com/CliMA/Oceananigans.jl/blob/27f7d044619b4159154a5940443be1d3d843aa5b/test/test_implicit_free_surface_solver.jl#L84-L86

cc @elise-palethorpe

**Comment by glwagner** [comment]
I don't think there's a good reason, but I'm not totally sure. @christophernhill might know.
