### ISSUE TITLE
Need to check for constant depth *before* we use the `FFTBasedPoissonSolver` in `HydrostaticFreeSurfaceModel`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2626]
Here,

https://github.com/CliMA/Oceananigans.jl/blob/27f7d044619b4159154a5940443be1d3d843aa5b/src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl#L92

we only check whether the grid is horizontally regular and use the `FFTBasedPoissonSolver`. But don't we need to check that the grid's depth is constant as well?

[11:12](https://climate-machine.slack.com/archives/D02A6B67YSJ/p1656465148285909)
but what if there is uneven bathymetry?

**Comment by glwagner** [comment]
"horizontally regular" is defined here:

https://github.com/CliMA/Oceananigans.jl/blob/27f7d044619b4159154a5940443be1d3d843aa5b/src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl#L88-L89

So it's `false` for an `ImmersedBoundaryGrid`.

**Comment by navidcy** [comment]
Gotcha
