### ISSUE TITLE
Should we make `Conjugate Gradient` + `FFTBased-preconditioner` the default for `HydrostaticFreeSurfaceModel`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2635]
Seems that https://github.com/CliMA/Oceananigans.jl/pull/2412/ suggests that this is the fastest way for grids that don't have regular horizontal spacing or have an immersed boundary. 

Yet, the free surface solver constructor falls back to the `MatrixBasedSolver` in those cases.

https://github.com/CliMA/Oceananigans.jl/blob/95206ae73e10460beebb2ce9d5fc9945523e5724/src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl#L101

Should we change that?

**Comment by simone-silvestri** [comment]
Sounds good! we have to leave it only for `LatitudeLongitudeGrid`

**Comment by simone-silvestri** [comment]
I wonder about CPU execution though... because the `MatrixSolver` with `ILU` was not tested and that in my experience seemed always to be the fastest method

**Comment by glwagner** [comment]
These benchmarks:

https://github.com/CliMA/Oceananigans.jl/pull/2412

show a factor of 2 speed up. In principle, the FFT is faster than a matrix multiply which may explain it?

As explained on that PR, some performance is left on the table, because the fastest combination would use an FFT-based preconditioner with a matrix multiply to compute the LHS.

**Comment by simone-silvestri** [comment]
Yeah, but the `ILU` preconditioner doesn't seem to be tested, which I remember was quite good to reduce the number of iterations. So in case of a large time step that would be quite efficient even if we have to solver two triangular linear systems each iteration.

**Comment by glwagner** [comment]
Hmm, well I guess we should add that combination to

https://github.com/CliMA/Oceananigans.jl/blob/main/benchmark/benchmark_hydrostatic_model.jl

and re-run the benchmarks.

**Comment by simone-silvestri** [comment]
I think we can close this as we have the `SplitExplicitFreeSurface` as a default now
