### ISSUE TITLE
Rename `Poisson Solvers` section in Docs?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2637]
The [Poisson Solvers](https://clima.github.io/OceananigansDocumentation/stable/numerical_implementation/poisson_solvers/) in the docs doesn't only discuss poisson solvers. Perhaps we should rename it?

@glwagner I think we had some chats about this at some point but it was never made it in an issue or PR, right?

cc @elise-palethorpe

**Comment by glwagner** [comment]
I would just call it "Solvers" or "Elliptic solvers"
