### ISSUE TITLE
Is `calc_∇²!` redundant in view of `compute_∇²!`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2638]
Is there a reason that `test_matrix_poisson_solver.jl` defines its own function for computing the laplacian:

https://github.com/CliMA/Oceananigans.jl/blob/95206ae73e10460beebb2ce9d5fc9945523e5724/test/test_matrix_poisson_solver.jl#L8-L15

instead of using the one in `utils_for_runtests.jl`

https://github.com/CliMA/Oceananigans.jl/blob/95206ae73e10460beebb2ce9d5fc9945523e5724/test/utils_for_runtests.jl#L60-L77

I can only note an extra `fill_halo_regions!(ϕ)` line.

cc @simone-silvestri

**Comment by simone-silvestri** [comment]
Hmmm, you're right, looks like it's doing the same thing. Maybe it's a vestigial remaining, using just one function is better
