### ISSUE TITLE
Zero-ed initial guess to preconditioner for CG solver improves performance compared to using previous `z`

### ISSUE THREAD

**Issue by elise-palethorpe** [CliMA/Oceananigans.jl#2655]
I was having a play with preconditioning the CG solver with multigrid and found that I get considerably different results depending on whether I zero the initial guess to the preconditioner (see [here](https://github.com/CliMA/Oceananigans.jl/blob/ep/pcg-with-multigrid/validation/elliptic_solvers/testing_preconditioner.jl)). When the initial guess is all 0s the precondition! method is called ~1/3 of the number to times it is called if the given initial guess is used. My understanding is that the initial guess is not specified by the algorithm in fig 2.5 [here ](https://www.netlib.org/templates/templates.pdf)so am not sure whether this is a "correct" answer here but would like to know why the zeroing gives such a different result. Could it be because solving for a residual equation the answer should be close to all 0s so it is actually a good initial guess?

cc @navidcy

**Comment by navidcy** [comment]
Seems like zeros is a better initial guess and thus #2654 does that.
