### ISSUE TITLE
Is there a typo in Docs/Numerical implementation/Pressure decomposition in `∇p → ∇p_non + ∇ₕp_hyd`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2656]
I don't understand why

$$\nabla p \mapsto \nabla p_{\rm non} + \nabla_h p_{\rm hyd}$$

here:

https://github.com/CliMA/Oceananigans.jl/blob/caa04324bd474e8fda2eb780e7720a4c6db7165a/docs/src/numerical_implementation/pressure_decomposition.md#L35-L38

Is there something missing?

cc @elise-palethorpe

**Comment by navidcy** [comment]
Probably it should read

$$\nabla p \mapsto \nabla p_{\rm non} + \nabla_h p_{\rm hyd} - b \hat{\boldsymbol{z}}$$

?

**Comment by glwagner** [comment]
I think this is correct

**Comment by navidcy** [comment]
Can you check the Physics/Boussinesq + Numerical Implementation/Pressure decomposition in the dev version of Docs? If you disagree with what’s stated there let’s reopen the issue.
