### ISSUE TITLE
Incremental  compilation warning for `next_stream()`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2676]
I got an incremental compilation error/warning here

https://github.com/CliMA/Oceananigans.jl/blob/b6dd1fa9b1d740f7d8cb4be116a24cbba0042f86/src/Architectures.jl#L23

**Comment by simone-silvestri** [comment]
we can take out that function, we just have to test multiGPU and that part should have already been taken care of in KernelAbstraction.jl

**Comment by simone-silvestri** [comment]
nono that's removes
