### ISSUE TITLE
Question regarding a doctest that involves `rand`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2702]
How does this doctest manage to pass? It calls random numbers and then `show()` of `v` prints out statistics on the values of `v`... I'm puzzled.

https://github.com/CliMA/Oceananigans.jl/blob/67ba7f86099c9d206a20dcaa1e640bcf8da04ead/src/Fields/field.jl#L256-L264

**Comment by glwagner** [comment]
Do we set the seed?

**Comment by navidcy** [comment]
https://github.com/CliMA/Oceananigans.jl/pull/2701 does that ;)

**Comment by navidcy** [comment]
https://github.com/CliMA/Oceananigans.jl/blob/2c832b0285dde548c975db89a8d188b431c095d8/src/Fields/field.jl#L263

**Comment by navidcy** [comment]
It wasn’t! I don’t know how come it was passing!

**Comment by glwagner** [comment]
Is it set when we start Julia?

**Comment by glwagner** [comment]
Well, no:

```
(base) gregorywagner:Desktop/ $ julia -e '@show rand()'                                                                                                                                                    [10:32:47]
rand() = 0.07089964853849728
(base) gregorywagner:Desktop/ $ julia -e '@show rand()'                                                                                                                                                    [10:32:54]
rand() = 0.4810451819958207
```

**Comment by glwagner** [comment]
But it might be set in the tests

**Comment by navidcy** [comment]
Not as far as I know.

**Comment by glwagner** [comment]
It's possible the seed of the random number generator is set when julia is installed? Or, some package could be setting it (I've seen this before too).
