### ISSUE TITLE
Current implementation of `dot(::Field, ::Field)` is slow and allocates a lot

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2725]
Here's what we currently do:
https://github.com/CliMA/Oceananigans.jl/blob/b6dd1fa9b1d740f7d8cb4be116a24cbba0042f86/src/Fields/field.jl#L500

Here's a test script:

```Julia
using Oceananigans
using BenchmarkTools
using LinearAlgebra

Nx, Ny, Nz = 128, 128, 16

grid = RectilinearGrid(size=(Nx, Ny, Nz), x=(-4, 4), y=(-4, 4), z=(-4, 0), topology=(Bounded, Bounded, Bounded))

a = CenterField(grid)
b = CenterField(grid)

ε(x, y, z) = randn()

set!(a, ε)
set!(b, ε)

true_dot(a, b) = sum(interior(a) .* interior(b))

dot_current(a::Field, b::Field) = mapreduce((x, y) -> x * y, +, interior(a), interior(b))

function dot_faster(a, b)
    s = zero(eltype(a.grid))

    @inbounds @simd for I ∈ CartesianIndices(a)
        s += a[I] * b[I]
    end

    return s
end
```

I get

```julia

julia> isapprox(dot_current(a, b), true_dot(a, b))
true

julia> isapprox(dot_faster(a, b), true_dot(a, b))
true

julia> @btime true_dot($a, $b);
  149.667 μs (29 allocations: 2.00 MiB)

julia> @btime dot_current($a, $b);
  1.289 ms (34 allocations: 2.00 MiB)

julia> @btime dot_faster($a, $b);
  74.041 μs (0 allocations: 0 bytes)
```

So we can get a ~15x speedup with zero allocations.

With only this change, running a `HydrostaticFreeSurfaceModel` simulation with a PGC free surface solver gave a ~20% speedup on the CPU.

**Comment by navidcy** [comment]
Hm... I guess we can't do this on GPU because of scalar indexing.

**Comment by glwagner** [comment]
Can you benchmark compared to the (wrong, but ideal) version `dot(parent(a), parent(b))`. Ideally our implementation reaches that. That should work on GPU too.

**Comment by navidcy** [comment]
You mean compare what against what?

The same script as above but with
```julia
julia> grid = RectilinearGrid(GPU(), size=(Nx, Ny, Nz), x=(-4, 4), y=(-4, 4), z=(-4, 0), topology=(Bounded, Bounded, Bounded))
```

gives

```
julia> CUDA.@time dot_current(a, b);
  0.000156 seconds (123 CPU allocations: 7.688 KiB) (2 GPU allocations: 648 bytes, 13.04% memmgmt time)

julia> CUDA.@time dot(parent(a), parent(b));
  0.000062 seconds (2 CPU allocations: 32 bytes)
```

**Comment by navidcy** [comment]
Also I don't understand why `.dot` comes from `Statistics`? Doesn't it come from `LinearAlgebra`?

**Comment by glwagner** [comment]
They are the same

```julia
julia> import Statistics, LinearAlgebra

julia> Statistics.dot === LinearAlgebra.dot
true
```

**Comment by navidcy** [comment]
Why `dot(parent(a), parent(b))` is wrong? it includes the halos? it includes immersed boundaries?

**Comment by simone-silvestri** [comment]
also this one
https://github.com/CliMA/Oceananigans.jl/blob/b6dd1fa9b1d740f7d8cb4be116a24cbba0042f86/src/Fields/field.jl#L500

includes immersed boundaries

**Comment by simone-silvestri** [comment]
I don't think it's a huge problem if we have fields masked to zero. Also, why is `dot(interior(a), interior(b))` not correct?

**Comment by simone-silvestri** [comment]
I agree, but that is a problem with all the methods here. I was just wondering what was the difference between what we have implemented `Statistics.dot(a::Field, b::Field) = mapreduce((x, y) -> x * y, +, interior(a), interior(b)) ` and a `dot(interior(a), interior(b))`

**Comment by glwagner** [comment]
Ah, in that case I don't see a difference either!

**Comment by glwagner** [comment]
still an issue?

**Comment by navidcy** [comment]
Actually this was mostly my misinterpretation. What I thought would be an improvement is only an improvement on CPU.

It's not an "issue" really so I'm closing.
