### ISSUE TITLE
Auxiliary fields not directly available to tracer forcing functions

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#2730]
Hi all,

I think it would be useful for auxiliary fields to be available to tracer forcing functions in the same way that other tracers and the velocity fields are. I'm currently working round this by putting auxiliary fields in the parameters but this is quite cumbersome.

It would be straightforward to implement by changing the `fields` functions e.g.:

`fields(model::NonhydrostaticModel) = merge(model.velocities, model.tracers, model.auxiliary_fields)`

I'm happy to try and do this later if there's no reason not to?

**Comment by jagoosw** [comment]
Just looked and this is actually implemented in `HydrostaticFreeSurfaceModels` just not in the other too. I'll change them and modify the multiple tracer test to use an auxiliary field.

**Comment by simone-silvestri** [comment]
sounds good!
