### ISSUE TITLE
Volume integral of buoyancy variance changed between v0.71.6 and v0.72.4

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2735]
I just noticed that the Nusselt number calculation result in the horizontal convection example changed between v0.71.6 and v0.72.4. It almost doubled from around 10 at

https://clima.github.io/OceananigansDocumentation/v0.71.6/generated/horizontal_convection/#Load-saved-output,-process,-visualize

to around 20 in 

https://clima.github.io/OceananigansDocumentation/v0.72.4/generated/horizontal_convection/#Load-saved-output,-process,-visualize

The calculation is done via

```Julia
χ_diff = κ * b★^2 * π * tanh(2π * H / Lx)

for i = 1:length(t)
    b = b_timeseries[i]
    sum!(∫ⱽ_mod²_∇b, (∂x(b)^2 + ∂z(b)^2) * volume)
    Nu[i] = (κ *  ∫ⱽ_mod²_∇b[1, 1, 1]) / χ_diff
end
```

Did anything changed between these two version in the way `sum!` or `volume` works?

Here's the diff between v0.71.6 and v0.72.4: https://github.com/CliMA/Oceananigans.jl/compare/v0.71.6...v0.72.4

**Comment by glwagner** [comment]
Not that I know of, so we should maybe write a test to check that it's correct?

Also, this code should use `Integral`:

https://github.com/CliMA/Oceananigans.jl/blob/13b7f2366726b3e52303dee67bab264941088554/src/AbstractOperations/metric_field_reductions.jl#L74

**Comment by navidcy** [comment]
I was trying to use Integral and was failing...! Will try again and post the error.

**Comment by navidcy** [comment]
OK, with the help of detective @glwagner we figured this out. The change that happened between those versions is that `with_halos = false` became the default in output writers. To post process saved buoyancy to compute $|\boldsymbol{\nabla} b|^2|$ we *crucially* need the boundary conditions on $b$ to be correct in the HC example! Thus, saving output `with_halos = false` was not doing the job right...

#2734  fixes this
