### ISSUE TITLE
Strange behavior in filling halos in `GridFittedBottom` -- does it matter?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2739]
Seems like `GridFittedBottom` fills only some halos but not others? Is this a bug? Or is it because of the topology? I guess it knows how to fill periodic direction but doesn't know what to do in the bounded `y`? See this MWE:

```
using Oceananigans
using GLMakie

underlying_grid = RectilinearGrid(topology = (Periodic, Bounded, Bounded), 
                                  size = (64, 64, 24),
                                  x = (-500, 500),
                                  y = (-500, 500),
                                  z = (-1, 0),
                                  halo = (4, 4, 4))

bump(x, y) = - underlying_grid.Lz * (1 - 2 * exp(-(x^2 + y^2) / (2*100^2)))
grid = ImmersedBoundaryGrid(underlying_grid, GridFittedBottom(bump))

heatmap(parent(grid.immersed_boundary.bottom_height))
current_figure()
```

![bottom](https://user-images.githubusercontent.com/7112768/190349987-ab16ee5a-7aeb-4c9b-b2b4-3888226737f8.png)

cc @elise-palethorpe

**Comment by simone-silvestri** [comment]
This should be correct. Only the first halo is filled in case of a `Bounded` direction

**Comment by glwagner** [comment]
Isn't this true for all fields? It's not specific to `GridFittedBottom`, we just call `fill_halo_regions!`:

https://github.com/CliMA/Oceananigans.jl/blob/d08af3a04ee0e64ffdbcf824d3e6b8cbdae74a16/src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl#L71

**Comment by navidcy** [comment]
Ok, gotcha! That's actually what's happening. My bad. I'm closing this.
