### ISSUE TITLE
Error in `num_prod`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2747]
This function computes `s` and `p` but then returns `sum` and `prod` (from where?). Is there something wrong here?

https://github.com/CliMA/Oceananigans.jl/blob/c2ac8fb182a6e3ba5c6d8f891c6ca3dc90d34b39/src/Advection/reconstruction_coefficients.jl#L35-L40

@simone-silvestri

**Comment by simone-silvestri** [comment]
Good catch! That is a bug for sure

**Comment by navidcy** [comment]
What would it affect?
