### ISSUE TITLE
Is `Architectures.next_stream()` redundant?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2748]
https://github.com/CliMA/Oceananigans.jl/blob/085969cf25456d0ff456158ddaaf4e6f49c141da/src/Architectures.jl#L23-L45

I do get:

```Julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
WARNING: Method definition next_stream() in module CUDAKernels at /g/data/v45/nc3020/.julia/packages/CUDAKernels/kCOA4/src/CUDAKernels.jl:33 overwritten in module Architectures at /g/data/v45/nc3020/Oceananigans.jl/src/Architectures.jl:23.
  ** incremental compilation may be fatally broken for this module **
```

cc @simone-silvestri

**Comment by simone-silvestri** [comment]
It should have been fixed in kernel abstractions. We have to test multi GPU without it and then we can remove it

**Comment by navidcy** [comment]
This code is now removed.

@simone-silvestri, is this issue considered done?
