### ISSUE TITLE
Dynamically disable CuArray scalar operations

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#276]
https://github.com/climate-machine/Oceananigans.jl/blob/fc12f60371eb0df7ba3d088771ddc25c0f258de6/src/Oceananigans.jl#L154

@maleadt pointed out that this line might only execute when the package is precompiled so if we really want to enforce no scalar operations, we should do this in an `init.jl` file or in the `Model` constructor or something.

**Comment by glwagner** [comment]
How about adding a line to the model constructor that executes when arch=GPU(), with a flag that allows the user to permit scalar operations (maybe useful when debugging output / diagnostics)

**Comment by ali-ramadhan** [comment]
Ah yeah would be good to have the option. It could be a `kwarg` of the `Model` constructor.

**Comment by glwagner** [comment]
@ali-ramadhan do we still want to do this?

**Comment by ali-ramadhan** [comment]
Yes, although I think we want to disable scalar operations initially and @vchuravy suggested using `@allowscalar` on lines where we need scalar operations (currently just one line in each Poisson solver).
