### ISSUE TITLE
State callbacks

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#2772]
Hi all,

Following discussion with @glwagner we think it would be useful to implement a callback like construction between each sub step. This would allow users to modify tendency fields externally to normal forcing functions.

My use case for this is having Lagrangian particles which can effect tracers, for example if the particle is some organism that takes up one tracer and excretes another. We discussed a different possible implementation of this in #2724 but came to the conclusion that its much better to do it a different way but the [example](https://gist.github.com/jagoosw/213d7f2ce3707768d4ddb07f8827cdd2) I came up with there possibly explains this case better.
![Example animation](https://user-images.githubusercontent.com/26657828/188803674-9dfa61a5-2de8-4612-b8db-9c8918a9a0fb.gif)

Callbacks are implemented in `run!`:
https://github.com/CliMA/Oceananigans.jl/blob/b288527ccf34fc17ec4b31a1e9da7bd8b8d25a10/src/Simulations/run.jl#L131

And this could probably be implemented fairly easily by:
- Adding a property to `Simulation` or, probably better to the model structs since the time steppers are only passed the `model` not `sim` like `run!` is
- In the time stepper functions we can then add `[callback(sim) for callback in values(model.state_callbacks)]` either just after `calculate_tendencies!` in each substep
https://github.com/CliMA/Oceananigans.jl/blob/b288527ccf34fc17ec4b31a1e9da7bd8b8d25a10/src/TimeSteppers/runge_kutta_3.jl#L98-L115
or at the end of each `calculate_tendencies!` function
https://github.com/CliMA/Oceananigans.jl/blob/b288527ccf34fc17ec4b31a1e9da7bd8b8d25a10/src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl#L12-L36

**Comment by navidcy** [comment]
Was this closed by #2773?

**Comment by glwagner** [comment]
Yes
