### ISSUE TITLE
Updating CUDAKernels to v0.4?

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2799]
I noticed today that Oceananigans v0.78.0 uses CUDAKernels v0.3.3, which is an old version.  After a discussion on julia slack, someone suggested we try updating it to something like 0.4.x. Is this something that people have tried?  

I'm okay to keep the old version but since someone helped me and suggested I create an issue, I thought I would at least ask the question.

**Comment by navidcy** [comment]
#2782 is trying to do that!

There are some outstanding issues... I'd be delighted to get some help there. :)
