### ISSUE TITLE
Why does this package have a `Manifest.toml`?

### ISSUE THREAD

**Issue by eliascarv** [CliMA/Oceananigans.jl#2806]
It is not common for a repository of a Julia package to have Manifest.toml. Generally, Julia package repositories contain only Project.toml.
Is there a reason for this choice?

**Comment by eliascarv** [comment]
Thanks for the answer! It was quite enlightening.

**Comment by eliascarv** [comment]
Should I close this issue?

**Comment by navidcy** [comment]
If you feel satisfied then sure! :)
