### ISSUE TITLE
Saving NC files on Power9

### ISSUE THREAD

**Issue by iuryt** [CliMA/Oceananigans.jl#2840]
I often run Oceananigans on a cluster at my university that has a few nodes with IBM Power9. Since very few people use these nodes, it is a big advantage to be able to run Oceananigans there because they will almost always have the GPUs available. Almost everything seems to run as expected, but I cannot use `NetCDFOutputWriter`. I really prefer saving the output in NC files because this is more easily used by other programming languages.

```
UndefVarError: NetCDFOutputWriter not defined

Stacktrace:
 [1] top-level scope
   @ :0
 [2] eval
   @ ./boot.jl:368 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1428
```

I noticed that if I try to `using NCDatasets`, it returns

```
ERROR: InitError: UndefVarError: libnetcdf not defined
Stacktrace:
  [1] nc_inq_libvers
    @ ~/.julia/packages/NCDatasets/h1epE/src/netcdf_c.jl:242 [inlined]
  [2] netcdf_version()
    @ NCDatasets ~/.julia/packages/NCDatasets/h1epE/src/netcdf_c.jl:2157
  [3] init_certificate_authority()
    @ NCDatasets ~/.julia/packages/NCDatasets/h1epE/src/netcdf_c.jl:2170
  [4] __init__()
    @ NCDatasets ~/.julia/packages/NCDatasets/h1epE/src/NCDatasets.jl:33
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loading.jl:1039
  [7] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1315
  [8] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [9] macro expansion
    @ ./loading.jl:1180 [inlined]
 [10] macro expansion
    @ ./lock.jl:223 [inlined]
 [11] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
during initialization of module NCDatasets
```

It looks like the problem is because `NCDatasets` needs `NetCDF_jll`, which is not available for Power9.
https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl#platforms

Any way to work around this?
Maybe using `NetCDF.jl`?

**Comment by glwagner** [comment]
> It looks like the problem is because NCDatasets needs NetCDF_jll, which is not available for Power9.
https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl#platforms

You may need to raise an issue with `NetCDF_jll.jl`?

**Comment by glwagner** [comment]
I don't think we can resolve this by making changes to Oceananigans.jl though... so we may want to close this issue.

**Comment by iuryt** [comment]
As suggested by @glwagner 
I will close this issue and open a new one in NetCDF_jll
