### ISSUE TITLE
`GridFittedBottom.immersed_condition` needs to be documented

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#2905]
https://github.com/CliMA/Oceananigans.jl/blob/fc0dd6e03c4eb69a092a9b76bf1688f5d92ddfb9/src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl#L40-L44

**Comment by glwagner** [comment]
I think the purpose of this property is only to allow `GridFittedBottom` to replicated `PartialCellBottom` in a limiting case.

**Comment by navidcy** [comment]
Also needs to include an example in the docstring!

**Comment by simone-silvestri** [comment]
before documenting it let's make sure this feature is consistent with the rest of the code base (i.e. masking, immersed derivatives, implicit solvers, etc)

**Comment by simone-silvestri** [comment]
maybe adding a test for cases in which `immersed_condition = FaceImmersedCondition()`

**Comment by navidcy** [comment]
I think #3505 dealt with this issue; @glwagner?

**Comment by navidcy** [comment]
I'm closing; feel free to reopen if you think it's needed
