### ISSUE TITLE
Error interpolating on an irregularly spaced grid

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#2911]
Interpolating a field on an irregulalry spaced grid returns the wrong results. 

MWE:
```julia
julia> using Oceananigans
julia> using Oceananigans: interpolate

julia> z_faces(k) = 100 * ((k/Nz) ^ 2 - 2)
julia> grid = RectilinearGrid(topology = (Flat, Flat, Bounded), size = (Nz, ), z = z_faces)

julia> model = NonhydrostaticModel(; grid, tracers = :P)

julia> P(x, y, z) = z
julia> set!(model; P)

julia> interpolate(model.tracers.P, 0, 0, -100.0)
-118.95
```

**Comment by simone-silvestri** [comment]
Something is fishy there, but I don't think it has to do with an irregularly spaced grid, more with the fact that you have `Flat` in x and y. You have the same problem on a non-stretched grid.

```
julia> using Oceananigans
julia> using Oceananigans: interpolate

julia> z_faces(k) = 100 * ((k/Nz) ^ 2 - 2)
julia> grid = RectilinearGrid(topology = (Flat, Flat, Bounded), size = (Nz, ), z = (-100, 0))

julia> model = NonhydrostaticModel(; grid, tracers = :P)

julia> P(x, y, z) = z
julia> set!(model; P)

julia> interpolate(model.tracers.P, 0, 0, -10.0)
-20.0
```
Note that interpolation assumes that there are 3 directions available:
https://github.com/CliMA/Oceananigans.jl/blob/4940d29901d693addca7a84aea302d870031bed6/src/Fields/interpolate.jl#L105-L113

**Comment by simone-silvestri** [comment]
In this case, if I force this function to be 1D:
```
@inline _interpolate(field, ξ, η, ζ, i, j, k) =
    @inbounds (  ϕ₁(ξ, η, ζ) * field[1,   1,   k  ]
               + ϕ₂(ξ, η, ζ) * field[1,   1,   k+1])
```
I get the correct result
```
julia> interpolate(model.tracers.P, 0, 0, -10.0)
-10.0
```

**Comment by simone-silvestri** [comment]
Interestingly, the same does not apply to stretched grids, so maybe there is also, as you said, an additional problem with stretched grids. I would try debugging starting with `Periodic` topologies in x and y and once that is solved, fix the issue with `Flat` dimensions

**Comment by jagoosw** [comment]
Sorry I missed these comments. I got a similar issue when I didn't make it flat but just had size = (1, 1, Nz) but I will try with a more normal grid

**Comment by jagoosw** [comment]
I replicate this error with:
```
julia> z_faces(k) = 100 * ((k/Nz) ^ 2 - 2)
julia> grid = RectilinearGrid(size = (10, 10, Nz), x = (0, 20), y = (0, 20), z = z_faces)
julia> model = NonhydrostaticModel(; grid, tracers=:P)
julia> P(x, y, z) = z
julia> set!(model; P)
```

e.g.
```
julia> interpolate(model.tracers.P, 10.0, 10.0, -100.0)
-96.92378328741964
````
Without the fix or `-100.0` with the fix

**Comment by jagoosw** [comment]
With a `Flat` topology `fractional_indices` correctly returns `0.0` in the flat direction (if I correctly put in `grid.xᶜᵃᵃ[1]` which I think is always `1`), so only $\phi_1$ and $\phi_2$ would be non-zero so this should be correct?

**Comment by simone-silvestri** [comment]
makes sense!

**Comment by jagoosw** [comment]
Yeah this makes sense, I'll do that later

**Comment by jagoosw** [comment]
> makes sense! To prevent interpolation in Flat directions, (which is ill-defined) we could define something like
> 
> ```
> @inline fractional_x_index(x, loc,  grid::XFlatGrid) = zero(grid)
> ```

Doing this doesn't work because the grid is also still `XRegRectilinearGrid` etc. I could change the definitions of regular grids e.g. 
```julia
const XRegRectilinearGrid  = RectilinearGrid{<:Any, <:Any, <:Any, <:Any, <:Number}
```
to not include flat grids, I think the only way todo this would be to do something like:
```julia
const NotFlatTopologies = Union{Periodic, Bounded}
const XRegRectilinearGrid  = RectilinearGrid{<:Any, ::NotFlatTopologies, <:Any, <:Any, <:Number}
```
This might cause some other functions to have to change, is it worth me doing this?
