### ISSUE TITLE
Type instability in `hydrostatic_spherical_coriolis.jl`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2925]
Should this

https://github.com/CliMA/Oceananigans.jl/blob/e2841ca6dda4414fcd9177512faec557d6f12adc/src/Coriolis/hydrostatic_spherical_coriolis.jl#L60

be 

```Julia
1 - f(i, j, k, grid, args...)
```
to avoid type instability?

cc @glwagner, @simone-silvestri

**Comment by glwagner** [comment]
What does this do anyways?

**Comment by glwagner** [comment]
The answer to my question above is that `revert_peripheral_node` returns `true` when `peripheral_node` is false.
