### ISSUE TITLE
Inconsistent advection from "different" velocities

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2928]
As of now, our tracers are advected by three "different" velocities 
- Velocity
- Background velocity
- Advective forcing

to these, another additional velocity is being added in PR #2802 
All these velocities are applied differently and might have different advection schemes.

This might be a headache in terms of understanding the cause of stability problems. Imagine a situation in which a model is characterized by 3 different velocities that all advect a centered second-order reconstruction of the tracer. If we run into stability problems it might not be immediately clear what the course of action is: is the instability caused by the interaction of the tracer with velocity 1, 2, or 3?

This is not the only issue with this implementation. The implementation is _wrong_ if we use an upwinding reconstruction of the tracer for any of the velocities e.g.:

Imagine we have a Background velocity $U_b = 1$ and an advective forcing $U_a = -1$ and we upwind separately.
The tracer advective flux should be zero everywhere, but, if we upwind:
$$(U_b c) + (U_a c) = c^L - c^R$$

If we want to be able to advect with different velocities consistently we have to ensure that
- the same scheme is used
- we _sum_ the velocities and _not_ apply reconstruction separately

A way to do it could by defining
```
struct AdvectiveU{A, B, C, D}
       u        :: A
       ubkg  :: B
       ufrc   :: C
       ubgc :: D
end

Base.getindex(u::AdvectiveU, i, j, k) = u.u[i, j, k] + u.ubkg[i, j, k] + u.ubcg[i, j, k] + u.ufrc[i, j, k]
```
and passing this velocity to the tracer tendency kernel.

**Comment by simone-silvestri** [comment]
This implies that the added fields must be divergence free

**Comment by glwagner** [comment]
I wonder if we can lean on the compiler to avoid having to store objects directly, eg

```julia
struct SumOfFields{N, F}
    fields :: F
    function SumOfFields{N}(fields...) = new{N, typeof(fields)}(fields)
end

@inline getindex(s::SumOfFields{1}, i, j, k) = @inbounds s.fields[1][i, j, k]
@inline getindex(s::SumOfFields{2}, i, j, k) = @inbounds s.fields[1][i, j, k] + s.fields[2][i, j, k]
@inline getindex(s::SumOfFields{3}, i, j, k) = @inbounds s.fields[1][i, j, k] + s.fields[2][i, j, k] + s.fields[3][i, j, k]
```

then inside kernels maybe it'll be enough to write

```julia
i, j, k = @index(Global, NTuple)

U = SumOfFields{2}(velocities, background_fields.velocities)

div_Uc(i, j, k, grid, U, c)
```

**Comment by jagoosw** [comment]
Fixed

**Comment by jagoosw** [comment]
I've just realised that with `AdvectiveForcing` this is still potentially a problem. I think it should be straight forward to fix, although we may have to think about how the convenience constrictor for advective forcing works.

**Comment by glwagner** [comment]
Ah yes, we will have to change the user API so that it no longer accepts an advection scheme. We would also need a utility like `add_advective_forcing!(total_velocities, forcing)` that would add the relevant velocity field. And `SumOfArrays` needs to support 3?

https://github.com/CliMA/Oceananigans.jl/blob/fa5e280115f619d01a460f012328bd7e6d253b38/src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl#L64-L66
