### ISSUE TITLE
Bugfix in hydrostatic spherical coriolis

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2929]
https://github.com/CliMA/Oceananigans.jl/blob/c929676bcce7fc19c3f96faafd459371935a6eba/src/Coriolis/hydrostatic_spherical_coriolis.jl#L63

should be

```
neighbouring_active_nodes = @inbounds ℑxyᶠᶜᵃ(i, j, k, grid, revert_peripheral_node, Center(), Face(), Center()) 
```

(and so on for the other instances of the function)

**Comment by glwagner** [comment]
Oof!
