### ISSUE TITLE
Use of `similar` in `conditional_operations.jl`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2942]
The use of `similar` here drops the boundary conditions associated with `c.operand`. Is this dangerous?

https://github.com/CliMA/Oceananigans.jl/blob/e394bf7ef7e4341ffddd449f52f58cee84698813/src/AbstractOperations/conditional_operations.jl#L127-L131

I couldn't see any use of `concretize_condition()` anywhere though...

**Comment by glwagner** [comment]
is `concretize` the same as `regularize` and `materialize`? We probably should use just one word for that idea...

**Comment by glwagner** [comment]
I don't think it's dangerous because as mentioned elsewhere boundary conditions are _in general_ only meaningful in the context of prognostic time-stepping of a model...

**Comment by navidcy** [comment]
OK, I'm closing this. Thanks!
