### ISSUE TITLE
Running simulations with `Clock{DateTime}`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2956]
This function lives in the tests but is never used in the tests, right?

https://github.com/CliMA/Oceananigans.jl/blob/acb298b7f7447747e9f4bcb1ffbbfbe09d9f3d98/test/test_netcdf_output_writer.jl#L14-L46

In fact the whole of this file.

I remember some issues with NetCDF at some point on linux machines -- was this why this test was removed?

**Comment by glwagner** [comment]
Should we convert this to a discussion? There's no action item.

**Comment by navidcy** [comment]
Action would be either we delete it from tests or make the tests to call it.

**Comment by navidcy** [comment]
Locally on my machine these tests pass. On tartarus they pass as well.

I'll open a PR and add this file back into the CI. If we see impassable problems we'll delete it.
