### ISSUE TITLE
Heat flux sign incorrect in mixing and convection example

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#2959]
I've been running a model that I based on the ocean wind mixing and convection example and noticed that when I run it for much longer than the example it cools. I think the sign on the heat flux should be negative here:

https://github.com/CliMA/Oceananigans.jl/blob/cb6d433f75277cb289f1a2c68e9e4ec7851cc005/examples/ocean_wind_mixing_and_convection.jl#L79-L88

As it should be an inward flux right? I might be missing something but running my code again now with the sign flipped to check.

**Comment by glwagner** [comment]
Positive flux means cooling (positive means that heat is fluxed upwards, out of the ocean).

We may change the sign convention in the future.

**Comment by glwagner** [comment]
See the note here:

https://clima.github.io/OceananigansDocumentation/stable/model_setup/boundary_conditions/#.-Constant-Flux-boundary-condition

**Comment by glwagner** [comment]
Maybe we should put another note in the example similar to what's in the docs.

**Comment by jagoosw** [comment]
In this example isn't it meant to be heating not cooling to keep it stratified?

**Comment by glwagner** [comment]
It's intended to cool to cause convection (the name of the example is wind mixing and convection) but that's sort of a random choice.

Heating would be fine too and the pedagogical value of the example would be the same. The heat flux would have to be changed in that case to make it realistic. For an idealized experiment we can remove heat at the top, but typically in realistic conditions a significant component of heating is realized by solar insolation which penetrates into the interior. Heating with winds is more challenging numerically (to simulate this problem well you'd need high resolution) which I think was the original motivation to use convection.

**Comment by jagoosw** [comment]
Ah I see, perhaps we should change the comment "surface heating of 200 W m⁻²" to "surface cooling ..." or something similar to clarify then?

**Comment by glwagner** [comment]
Ha yes! I don't know how that comment got in there... it's definitely surface cooling
