### ISSUE TITLE
`UniformStokesDrift` would benefit from a `parameters` keyword

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2960]
~At the moment there's no way to run the MWE below on a GPU besides setting `Us` and `wave_vertical_scale` to be `const`ants~:

The example below fails on GPU due to `Us` and `wave_vertical_scale`:

```julia
using Oceananigans

grid = RectilinearGrid(GPU(), size=(4, 4, 4), extent = (1e3, 1e3, 120))

Us = 0.05; wave_vertical_scale = 5
∂z_uˢ(z, t) = Us * exp(z / wave_vertical_scale) / wave_vertical_scale

model = NonhydrostaticModel(; grid, stokes_drift = UniformStokesDrift(∂z_uˢ=∂z_uˢ))
time_step!(model, 10)
```

As much as using `const`ants is a valid solution, it would be nice to have the option to pass them as parameters, such as

```julia
UniformStokesDrift(∂z_uˢ=∂z_uˢ, parameters=Us=0.05, wave_vertical_scale=5)
```

which currently isn't an option.

**Comment by glwagner** [comment]
I'm up to add such a feature but to combat disinformation, we must note that it is possible to run without `const`ants:

```julia
using Oceananigans

grid = RectilinearGrid(GPU(), size=(4, 4, 4), extent = (1e3, 1e3, 120))

Base.@kwdef struct MonochromaticStokesShear
    Us :: Float64 = 0.05
    wave_vertical_scale :: Float64 = 5.0
end

@inline (mss::MonochromaticStokesShear)(z, t) = mss.Us * exp(z / mss.wave_vertical_scale) / mss.wave_vertical_scale

model = NonhydrostaticModel(; grid, stokes_drift = UniformStokesDrift(∂z_uˢ=MonochromaticStokesShear()))

time_step!(model, 10)
```

**Comment by tomchor** [comment]
> I'm up to add such a feature but to combat disinformation, we must note that it is possible to run without `const`ants:
> 
> ```julia
> using Oceananigans
> 
> grid = RectilinearGrid(GPU(), size=(4, 4, 4), extent=(1, 1, 1))
> 
> Base.@kwdef struct MonochromaticStokesShear
>     Us :: Float64 = 0.05
>     wave_vertical_scale :: Float64 = 5.0
> end
> 
> @inline (mss::MonochromaticStokesShear)(z, t) = mss.Us * exp(z / mss.wave_vertical_scale) / mss.wave_vertical_scale
> 
> model = NonhydrostaticModel(; grid, stokes_drift=UniformStokesDrift(∂z_uˢ=MonochromaticStokesShear()))
> 
> time_step!(model, 10)
> ```

Interesting, I didn't know one could use `@kwdef` to make this work so thanks for correcting me. I tried running it with a `NamedTuple` and it gave me `getindex()` errors so I assumed `const` was the only way.

**Comment by glwagner** [comment]
The key is not `@kwdef` but rather the callable 

```julia
@inline (mss::MonochromaticStokesShear)(z, t) = mss.Us * exp(z / mss.wave_vertical_scale) / mss.wave_vertical_scale
```

**Comment by glwagner** [comment]
> I tried running it with a NamedTuple and it gave me getindex() errors

What do you mean?

**Comment by glwagner** [comment]
The general point is that "parameters" can always be implemented via callable objects (functions attached to structs, where the structs can store references / data).

We provide `parameters` features purely as convenience, but they aren't strictly necessary.

**Comment by tomchor** [comment]
So [this section of the docs](https://clima.github.io/OceananigansDocumentation/stable/simulation_tips/#Global-variables-that-need-to-be-used-in-GPU-computations-need-to-be-defined-as-constants-or-passed-as-parameters) is misleading (or maybe just wrong), no? We should probably rewrite that based on information here.

**Comment by glwagner** [comment]
It's true that global variables have to be defined as `const`, but it's also true that global variables are never "required" (they just may be more convenient than defining a callable struct)

**Comment by glwagner** [comment]
Here's the relevant section of the Julia documentation:

https://docs.julialang.org/en/v1/manual/methods/#Function-like-objects
