### ISSUE TITLE
Unexpected behavior when interpolating?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2969]
I believe there is some strange behavior when interpolating, e.g., from a location L to L. This should leave the field unchanged but instead it modifies it.

```julia
julia> using Oceananigans, Oceananigans.Operators

julia> grid = RectilinearGrid(size=(3, 4, 5), extent=(3, 4, 5), halo=(1, 1, 1))
3×4×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 3.0)  regularly spaced with Δx=1.0
├── Periodic y ∈ [0.0, 4.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-5.0, 0.0] regularly spaced with Δz=1.0

julia> c = CenterField(grid); set!(c, rand(size(c)...))
3×4×5 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 3×4×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 5×6×7 OffsetArray(::Array{Float64, 3}, 0:4, 0:5, 0:6) with eltype Float64 with indices 0:4×0:5×0:6
    └── max=0.98666, min=0.00938656, mean=0.513716
```

The `c` field lives on cells' centers. Let's try interpolate it on x-faces:
```julia
julia> ℑxᶠᵃᵃ(2, 3, 1, grid, c) == (c[2, 3, 1] + c[1, 3, 1])/2
true
```

Nice. _But_ now if we try to interpolate it onto x-centers we get:

```Julia
julia> ℑxᶜᵃᵃ(2, 3, 1, grid, c) == c[2, 3, 1]
false
```

Weird. One would expect that interpolation of a field that lives on x-centers onto x-centers would leave it unchanged. Instead what happens is that the interpolant seems to be treating `c` as if it was living on x-faces, i.e.,

```Julia
julia> ℑxᶜᵃᵃ(2, 3, 1, grid, c) == (c[2, 3, 1] + c[3, 3, 1])/2
true
```

I believe we are missing some fallbacks to identity operators?

**Comment by navidcy** [comment]
cc @glwagner, @simone-silvestri

**Comment by simone-silvestri** [comment]
yeah, that interpolation operator is defined as 
```
@inline ℑxᶜᵃᵃ(i, j, k, grid::AG{FT}, u) where FT = @inbounds FT(0.5) * (u[i,   j, k] + u[i+1, j, k])
```

so it assumes that the field to be interpolated is located at `Faces`. It should not be used on Centered fields

**Comment by navidcy** [comment]
OK, I see!
User could use AbstractOperations; dev should know this. Gotcha ;)

**Comment by glwagner** [comment]
Could add a comment to explain perhaps?

To elaborate on @simone-silvestri's answer, these low-level functions are designed to operate on arrays / offset arrays on the GPU, where we don't have `Field` locations. We don't want to define special "location-aware" methods for `Field`, because this could lead to different behavior on CPU vs GPU.
