### ISSUE TITLE
`x/y/znode` returns different things for different grids

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2978]
There is an issue that `xnode` returns distances for `RectilinearGrid` but returns degrees for `LatitudeLongitudeGrid`.

We run onto this with @glwagner while working on horizontal regrading in #2881.

One suggestion is that `node()` and `nodes()` are defined for each grid and that it returns that native grid coordinates, e.g.

```julia
nodes(grid::RectilinearGrid)       = (xnodes(grid), ynodes(grid), znodes(grid))
nodes(grid::LatitudeLongitudeGrid) = (λnodes(grid), φnodes(grid), znodes(grid))
```

Then within grids we define the `xnode`, `xnodes` but also the native-coordinates-analogues, e.g., `λnode`, `λnodes`.

**Comment by glwagner** [comment]
This will further crystallize the distinction between linear distances (x, y, z) and "native coordinate systems" (Cartesian for Rectilinear, geographic for LatitudeLongitude).

We already have this partially implemented; ie `Δx` returns a linear distance. But the implementation has not extended to xnodes, ynodes, etc.

Kind of a side note but it'd be nice to figure out a cleaner / more concise way to implement the `with_halos` feature. It's hard to read the code as it is now.
