### ISSUE TITLE
Constants are sometimes defined twice

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#2981]
The grids define their own `R_Earth`.
https://github.com/CliMA/Oceananigans.jl/blob/e881faee3de5f17cb382cd61e2b43c2069cadde7/src/Grids/latitude_longitude_grid.jl#L3

The `Coriolis` module defines another one...

Perhaps we should have a module `Constants`, add everything in there and load it first? This potentially would come handy when we try to couple?

**Comment by glwagner** [comment]
We could also define this at the top level.

For coupling, we will have to set these constants in the simulation constructor (hopefully we won't be changing source code)
