### ISSUE TITLE
need to update docstring in `netcdf_output_writer.jl`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2986]
I tried running two examples in the docstring of `netcdf_output_writer.jl` and found something that I believe needs to be updated.

[Line 274](https://github.com/CliMA/Oceananigans.jl/blob/2001a7fae296977608378223045bf46e24ea2853/src/OutputWriters/netcdf_output_writer.jl#L274), defines the nodes but this didn't work for me.  I believe we should change it to the following:

`xC, yF = xnodes(Center, grid), ynodes(Face, grid)`

Also, it might helpful to add this line at the beginning, as otherwise, the example does not run,

`using Oceananigans.Grids: xnodes, ynodes, znodes`

If people agree with this I can make the changes but thought I would suggest it before creating a PR.

**Comment by navidcy** [comment]
The docstring is a doctest so how can it not work..?

Are you sure you are on the same version of Oceananigans as the docs you are pointing out?

**Comment by navidcy** [comment]
`xnodes, ynodes, znodes` are exported so users should have access to them after saying `using Oceananigans`.

**Comment by navidcy** [comment]
```Julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
[ Info: Oceananigans will use 6 threads

julia> xnodes
xnodes (generic function with 15 methods)

julia>

help?> xnodes
search: xnodes

  xnodes(grid, LX, LY, LZ, with_halos=false)


  Return the positions over the interior nodes on grid in the x-direction for the location LX, LY, LZ. For Bounded directions, Face nodes
  include the boundary points.

  See znodes for examples.
```

I believe you are not reading the docs that correspond to the version you are on?

**Comment by glwagner** [comment]
@francispoulin note if that you just paste the raw link, github will show the source code (a bit easier to read):

https://github.com/CliMA/Oceananigans.jl/blob/2001a7fae296977608378223045bf46e24ea2853/src/OutputWriters/netcdf_output_writer.jl#L274

The above is the new syntax

**Comment by francispoulin** [comment]
Sorry for my mistake @navidcy and @glwagner, and thanks for the clarification.
