### ISSUE TITLE
`Callable` tridiagonal coefficients produces catastrophic loss of performance

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3047]
Currently `BatchedTridiagonalSolver` supports `Callable` tridiagonal coefficients via

https://github.com/CliMA/Oceananigans.jl/blob/bcc34f07b3f949ea6fb34c7814f4b856d24924c2/src/Solvers/batched_tridiagonal_solver.jl#L58-L59

However, as noted on #3030 this can produce a catastrophic loss of performance. Therefore, this support should be discontinued.

cc @simone-silvestri

**Comment by navidcy** [comment]
Any idea if this affects GPU or CPU or both?

**Comment by glwagner** [comment]
It would seem just CPU
