### ISSUE TITLE
Move `ShallowWaterModel` to a different package?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3049]
Should we move `ShallowWaterModel` to its own package which would depend on Oceananigans?

There is an outstanding issue https://github.com/CliMA/Oceananigans.jl/issues/2922
We'd either need to sort it out. I believe to figure it out we need to plot/print out the tendencies from the first iteration for a version that worked and the first version that it didn't and trace back the issue. 

Perhaps it would make sense if this was a different model?

**Comment by glwagner** [comment]
I think we should delete the regression test and put a warning in the model constructor "The ShallowWaterModel has not been validated".

It's a shame we've put so much time into the regression test as it is. I think the model likely has a few bugs to be ironed out. I'm also not convinced that we have all the numerical methods (ie vanishing layers, positive preserving advection) that would be needed to advertise the model as "production-ready"). One could argue that the regression test is misleading in that it gives the false impression that the model is in a state that shouldn't change.

**Comment by glwagner** [comment]
For example, these lines multiply `h` (a field at ccc) with objects at `fcc` and `cfc` respectively

https://github.com/CliMA/Oceananigans.jl/blob/bcc34f07b3f949ea6fb34c7814f4b856d24924c2/src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl#L16-L17
