### ISSUE TITLE
Should reductions exclude `peripheral_node`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3064]
Right now reductions only exclude _immersed_ peripheral nodes:

https://github.com/CliMA/Oceananigans.jl/blob/72e2197e640ddf308fd40aa4658e7686e596bccd/src/ImmersedBoundaries/immersed_reductions.jl#L27

It recently caused me a lot of pain and confusion and time that "ordinary" peripheral nodes are included in the reduction, but immersed peripheral nodes are not.

What is the logic for treating immersed boundaries differently from ordinary boundaries? I think we should either exclude only inactive nodes or peripheral nodes, but this behavior should be consistent between immersed and not immersed grids.

This change would mean we don't need special reductions (at least for fields that are not reduced) on immersed vs not-immersed grids.

@simone-silvestri may have the answer.

**Comment by glwagner** [comment]
Simple example why this doesn't make sense: `immersed_peripheral_node` is

https://github.com/CliMA/Oceananigans.jl/blob/72e2197e640ddf308fd40aa4658e7686e596bccd/src/ImmersedBoundaries/ImmersedBoundaries.jl#L217-L218

So, for example, if the entire bottom of a grid is immersed, then it will be _included_ in the reduction, because those nodes _are_ on the periphery of the underlying grid. But this makes no sense because such nodes are way immersed.

I guess we could add another condition `inactive_node`.

I guess the question is whether we want to include the surface in reductions. And if so, then why are we not simply excluding `inactive_node` (why do we want to include "other" peripheral nodes?)

**Comment by navidcy** [comment]
cc @simone-silvestri
