### ISSUE TITLE
Continuous boundary functions don't use grids' native coordinates

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3073]
After #2979 the following is wrong since it refers to `x, y` coords and not the grid's native ones which they can be `λ, φ` for curvilinear grids.

https://github.com/CliMA/Oceananigans.jl/blob/c765c98c5880eb8a4a570a39b89824af01d75203/src/BoundaryConditions/continuous_boundary_function.jl#L105-L133

I think we should replace, e.g.,

```julia
y = ynode(i′, j, k, grid, Face(), LY(), LZ())
z = znode(i′, j, k, grid, Face(), LY(), LZ())
```

with

```julia
_, y, z = node(i′, j, k, grid, Face(), LY(), LZ())
```

**Comment by simone-silvestri** [comment]
sounds good

**Comment by glwagner** [comment]
Yes, nice catch.
