### ISSUE TITLE
Interpolation over periodic dimension returns strange result?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3114]
In an attempt to debug #3100 I ran onto this

```julia
using Oceananigans

grid = RectilinearGrid(CPU(), size=(4, 4, 4), extent=(1, 1, 1), topology=(Periodic, Periodic, Bounded))

buoyancy = SeawaterBuoyancy(gravitational_acceleration=1, equation_of_state = LinearEquationOfState(thermal_expansion=1, haline_contraction=1))

model = NonhydrostaticModel(; grid, buoyancy, tracers = (:T, :S))

set!(model.velocities.u, 1)

model.velocities.u
```

gives

```julia
4×4×4 Field{Face, Center, Center} on RectilinearGrid on CPU
├── grid: 4×4×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 10×10×10 OffsetArray(::Array{Float64, 3}, -2:7, -2:7, -2:7) with eltype Float64 with indices -2:7×-2:7×-2:7
    └── max=1.0, min=1.0, mean=1.0
```

But then, if I define a new `u` interpolated on cell centers:

```julia
new_u = @at (Center, Center, Center) u
u_new = Field(new_u)
compute!(u_new)
interior(u_new)
```

I get

```Julia
4×4×4 view(::Array{Float64, 3}, 4:7, 4:7, 4:7) with eltype Float64:
[:, :, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 0.5  0.5  0.5  0.5

[:, :, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 0.5  0.5  0.5  0.5

[:, :, 3] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 0.5  0.5  0.5  0.5

[:, :, 4] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 0.5  0.5  0.5  0.5
```

I would expect that the interpolated `u_new` still would have values 1 everywhere. No?

If I change the topology to Bounded then the interpolated `u_new` is all 1s.

(The above behaviour occurs with either Julia v1.8 or v1.9.)

**Comment by navidcy** [comment]
Thanks! I often forget this!

but then, how do you explain that this test passes without gilling the halos??  

https://github.com/CliMA/Oceananigans.jl/blob/4551a78b1f3fe4bb3b238676c128dc751be9b934/test/test_computed_field.jl#L372

**Comment by navidcy** [comment]
🙈

**Comment by glwagner** [comment]
Huh. Seems like we do need to fill the halo regions of the operand for the result of `compute!` to be correct. Should we re-open this issue?

**Comment by navidcy** [comment]
Hm... Perhaps we should! Feel free to reopen and change the title to better represent the issue?

**Comment by navidcy** [comment]
Sure! I was just doing what the test does to reproduce why CI fails... :) Let's simplify the test also!

**Comment by glwagner** [comment]
maybe the kwarg is `fill_operand_halo_regions=true`. But this requires some extensive changes to `compute!` since we have to propagate this kwarg throughout the expression tree.
