### ISSUE TITLE
`specified_times_str(::SpecifiedTimes)`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3163]
Why here we drop the last two elements?

https://github.com/CliMA/Oceananigans.jl/blob/d7d146bc59f966d65eb66a875c16679bef365130/src/Utils/schedules.jl#L177

**Comment by glwagner** [comment]
Because the string in constructed by iterating over

https://github.com/CliMA/Oceananigans.jl/blob/d7d146bc59f966d65eb66a875c16679bef365130/src/Utils/schedules.jl#L176

which includes the separators ", ". So, we want to remove the separator from the very end of the string.

**Comment by navidcy** [comment]
OK, I see! I got confused, I thought it was removing the last two specified times values!

**Comment by glwagner** [comment]
Well now I'm confused. Does it show correctly?

**Comment by glwagner** [comment]
No, it's wrong:

```julia
julia> s = SpecifiedTimes(0, 1, 2)
SpecifiedTimes([0.0, 1.0, 2.0], 0)

julia> specified_times_str(s)
"[0 seconds, ]"
```

**Comment by navidcy** [comment]
Damn! Yes! That's what I was seeing!

**Comment by glwagner** [comment]
is it a bug tho

**Comment by navidcy** [comment]
The `show` method doesn't use the `summary`, right?

(That's how I got confused after you post.)

**Comment by glwagner** [comment]
i dont think there is a custom show method for `SpecifiedTimes`

**Comment by glwagner** [comment]
It's used in `summary`:

https://github.com/CliMA/Oceananigans.jl/blob/d7d146bc59f966d65eb66a875c16679bef365130/src/Utils/schedules.jl#L262

which in turn is used to display output writers info in `Simulation`
