### ISSUE TITLE
Docs don't build for tagged releases

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3191]
See, e.g., recent v0.85.

Possibly something related with buildkite settings. E.g. for v0.84.1 the tag triggered [a buildkite run](https://buildkite.com/clima/oceananigans/builds/12019)

<img width="1215" alt="Screenshot 2023-07-18 at 1 57 24 pm" src="https://github.com/CliMA/Oceananigans.jl/assets/7112768/f0b0f59a-f909-4858-aaf1-3536ed485d91">

<img width="1234" alt="Screenshot 2023-07-18 at 1 58 19 pm" src="https://github.com/CliMA/Oceananigans.jl/assets/7112768/818d2fb1-086f-40ac-a109-52833375aa40">

@glwagner, something related to buildkite setting we were fiddling with lately?

**Comment by glwagner** [comment]
Ok so we fixed the problem with the dev docs, but created a new one?

**Comment by navidcy** [comment]
> Ok so we fixed the problem with the dev docs, but created a new one?

I think so… :(

**Comment by navidcy** [comment]
@glwagner could you try to resolve this? sorry for the burden...

**Comment by navidcy** [comment]
bumping this

**Comment by glwagner** [comment]
Huh, I have no idea what to do to solve this

**Comment by navidcy** [comment]
OK, no worries. We can always look at the `dev` version.

**Comment by navidcy** [comment]
> Huh, I have no idea what to do to solve this

It must be buildkite-related.

**Comment by glwagner** [comment]
I wonder if this is the problem:

https://github.com/CliMA/OceananigansDocumentation/actions/runs/6101820665

<img width="816" alt="image" src="https://github.com/CliMA/Oceananigans.jl/assets/15271942/26b5926b-7f8c-4889-b1c5-0f7923b74d31">

**Comment by navidcy** [comment]
I think this is an additional independent problem. I can try fix this one and we see. I think though that the stable tagged versions don’t ever trigger docs built in the first place.

**Comment by glwagner** [comment]
Something seemed to change with 0.81.1

<img width="928" alt="image" src="https://github.com/CliMA/Oceananigans.jl/assets/15271942/81cae28b-12ee-480f-b40c-1502701b97d5">

**Comment by navidcy** [comment]
Deploy of gh-pages at OceananigansDocumentation repo seems OK now. I think it was just a glitch...
https://github.com/CliMA/OceananigansDocumentation/actions/runs/6109843276

But the tags don't seem to push docs in the repo. I believe it has something to do with buildkite settings...

**Comment by navidcy** [comment]
> Something seemed to change with 0.81.1
> 
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/15271942/266183487-81cae28b-12ee-480f-b40c-1502701b97d5.png">

That's because oftentimes I had to manually clear up the repo. So the "v0.8*" is a manual commit message I put. The "build based on ..." is the automated commit message by Documenter.

**Comment by navidcy** [comment]
But something does seem to changed (in buildkite?) between v0.84.1 and v0.85.0 as I'm pointing out at the beginning of the issue.

**Comment by navidcy** [comment]
I think I managed to figure it out!

https://buildkite.com/clima/oceananigans/builds/13287

The culprit was the `Skip builds with existing commits` setting in Buildkite. This **SHOULD NOT** be ticked! The reason is, that tags are based on a commit on main, which has already triggered a build and then they tags were _not_ triggering a new build!

**Comment by navidcy** [comment]
As soon as I see `v0.90.0` in the docs I'll close the issue.

**Comment by navidcy** [comment]
https://clima.github.io/OceananigansDocumentation/v0.90.0/
