### ISSUE TITLE
Creating a method to convert Function Fields to Fields

### ISSUE THREAD

**Issue by loganpknudsen** [CliMA/Oceananigans.jl#3226]
I was working on post-processing the data from a simulation I ran in Oceananigans when I decided I wanted to access the background field data from the run and write it to a netCDF4. I had tried `output = (;u,v,w,U=(model.background_fields.velocities.u),V=(model.background_fields.velocities.v))` as seen in my minimal working example below(please let me know if you need more details)
```
u,v,w = model.velocities

output = (;u,v,w,U=(model.background_fields.velocities.u),V=(model.background_fields.velocities.v))

simulation.output_writers[:fields] = NetCDFOutputWriter(model, output;
                                                          schedule = TimeInterval(10),
                                                          filename = "test2.nc",
                                                          overwrite_existing = true)
```
but kept getting this error:
```
ERROR: LoadError: MethodError: no method matching Field(::Oceananigans.Fields.FunctionField{Face, Center, Center, Clock{Float64}, NamedTuple{(:Nₒ, :S, :γ, :ϕ, :f), Tuple{Float64, Float64, Float64, Int64, Float64}}, typeof(U_func), RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Float64}; indices::Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}})
```
Luckily I made a work around by changing the output to `output = (; u, v, w, U=(model.background_fields.velocities.u+0*u), V=(model.background_fields.velocities.v+0*v))` on a suggestion from a postdoc in my group who has much more experience using Oceananigans. I think the issue here is that the background fields are classified as function fields, so it may be worthwhile to create a method that converts function fields to fields or something similar to make outputting them easier.

**Comment by glwagner** [comment]
Hmm yes, I remember thinking about this, but reasoning that one can evaluate a `FunctionField` at any time so why would you want to compute it? I do see why that would be convenient though, especially if one is switching between concrete fields and `FunctionField` for certain things (plus potentially providing a more convenient post-processing experience to have the appropriate data saved to file rather than having to rebuild the `FunctionField`)...

**Comment by glwagner** [comment]
I'm pretty sure this is trivial to support because `FunctionField` has the same interface as `AbstractOperation`, so we can simply extend these methods:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/AbstractOperations/computed_field.jl

**Comment by glwagner** [comment]
@loganpknudsen can you see if https://github.com/CliMA/Oceananigans.jl/pull/3228 gives you what you need?
