### ISSUE TITLE
Add to the docs a better explanation about `max_change` and `min_change` of the `TimeStepWizard`

### ISSUE THREAD

**Issue by iuryt** [CliMA/Oceananigans.jl#3244]
Hi,

I have been confused about what the `max_change` and `min_change` means.
I understand from the documentation that this is to avoid the time step to change too quickly, but how is it used?

Is it in time units? e.g., taking the default `max_change` of 1.1, that means that for dated simulation it will change the time step at max in 1.1 seconds? 

Is it a multiplication? e.g., `new_time_step = 1.1*time_step` ?

I think we can try to be more clear about that in the docs.

**Comment by glwagner** [comment]
It's the latter: `max_change` is the maximum relative change of the time step and is therefore non-dimensional. Thus the new time step satisfies the criteria

```julia
new_dt <= max_change * old_dt
```

It's implemented here:

https://github.com/CliMA/Oceananigans.jl/blob/0d39f5ce93b75e7df2b896fbd8326214dbf5cea7/src/Simulations/time_step_wizard.jl#L96-L99

Improving the docs is always a good idea!

**Comment by iuryt** [comment]
I can do that to the docs.
