### ISSUE TITLE
Should `grid` be a positional argument to model constructors?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3250]
The argument `grid` is required --- of course --- in model constructors.

Our current API makes `grid` a keyword argument. Originally (and it was a long time ago now) it was argued that keyword arguments are just better and that's why we should keep it. Also, we don't dispatch on it.

However, we violate that concept in `Simulation`, where the `model` is a positional argument.

I think it's more natural to input `grid` as a positional argument in the models. It's a relatively minor thing, but it avoids anti-patterns like `grid=grid`, which appeared in many scripts before `; grid` was possible. It looks better.

This has come up because we are adding more Oceananigans-based `AbstractModel`s over in [`ClimaSeaIce`](https://github.com/CliMA/ClimaSeaIce.jl), and my first intuition there was to make `grid` a required positional argument. Ultimately though, we should strive for all models to have uniform interfaces, so either we change `Oceananigans` or we change `ClimaSeaIce`.

**Comment by navidcy** [comment]
I like kwarg because it’s more verbose. 
Is there any other reason why it should be positional?
As you said `grid=grid` can be avoided although some people like it.

**Comment by glwagner** [comment]
Hmm in that case, I can consider a `grid` keyword argument for other models too.

**Comment by glwagner** [comment]
> Is there any other reason why it should be positional?

I guess I'm just arguing that it's not consistent with most of the API, eg we write `CenterField(grid)`.

I find the position representation of required arguments to be a natural and concise interface but perhaps I shouldn't die on that hill
