### ISSUE TITLE
`node` should omit nodes from `Flat` dimensions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3285]
I think it'd be cleaner to change `node` so that `Flat` dimensions are omitted.

For example, this would mean that on a grid that is flat in `z` (two-dimensional in `x, y`, we would write initial conditions

```julia
ui(x, y) = # initial u
set!(model, u=ui)
```

Basically, grids that are `Flat` in `z` cannot depend on `z`. So it would be clearer if initial conditions also did not depend on `z`.

**Comment by navidcy** [comment]
Isn't these methods, e.g., 

https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Grids/rectilinear_grid.jl#L446-L456

supposedly there for this?

**Comment by navidcy** [comment]
Could you point me to the src code where `set!` uses `node`? I can _never_ find it!

**Comment by jagoosw** [comment]
> Could you point me to the src code where `set!` uses `node`? I can _never_ find it!

I believe `set!` creates a function field which is then copied in, which calls:
https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Fields/function_field.jl#L63-L64

**Comment by glwagner** [comment]
Right. It's here:

https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Fields/set!.jl#L17-L20

this is broadcasting. It launches `_broadcast_kernel`:

https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Fields/broadcasting_abstract_fields.jl#L74

which calls `getindex`:

https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Fields/broadcasting_abstract_fields.jl#L49-L52

**Comment by glwagner** [comment]
> Isn't these methods, e.g.,
> 
> https://github.com/CliMA/Oceananigans.jl/blob/2a7d2a1644997a6400bac41a88a7f6879d93d23d/src/Grids/rectilinear_grid.jl#L446-L456
> 
> supposedly there for this?

Those methods dispatch on location, but not the topology of the grid.

I'm proposing to add new methods that treat `Flat` dimensions as if the location were `Nothing`. In other words, the location of a field in `Flat` direction is meaningless.

**Comment by tomchor** [comment]
Is this extra simplicity in the user interface worth the extra code to maintain?

I personally think it's nice to have all IC signatures, etc., the same independently of grid topology. It makes it easy to catch newbie mistakes when reviewing code. I also think a user can easily infer that `z` in the signature can be ignored if they just defined a grid with a `Flat` z topology, so I think the added simplicity is minor.

**Comment by glwagner** [comment]
> Is this extra simplicity in the user interface worth the extra code to maintain?

Given the minor code changes required and the priority we place on user interface, I think so.

> I personally think it's nice to have all IC signatures, etc., the same independently of grid topology. It makes it easy to catch newbie mistakes when reviewing code.

Can you explain? The purpose of this PR is to catch or prevent mistakes.

> I also think a user can easily infer that z in the signature can be ignored if they just defined a grid with a Flat z topology, so I think the added user-friendliness is minor.

It's true that in our examples, `set! ` is typically invoked close to the grid definition. But such proximity is not guaranteed. In complicated applications (say for example a realistic simulation on the globe), a grid may be constructed "for" the user. One case that's come up recently is coupled ocean, sea-ice simulations. For a realistic case covering the globe, the user script may well not include the creation of the grid (which would happen within a helper function like `build_global_ocean_sea_ice_simulation`).

Even if the grid construction is immediately readable, I think it's still weird to read

```julia
initial_ice_thickness(x, y, z) = 1 # meter
```

as determining sea ice thickness --- its nonsensical for the ice thickness to depend on `z`. Ice thickness _cannot_ depend on `z`. The z topology of a slab ice model cannot be anything but `Flat`; it doesn't make sense to have a z-coordinate. That's also true for the `ShallowWaterModel`. Also there function signatures depend on `z` despite that no shallow water field can possibly depend on the third coordinate.

> (Maybe even negative since the signatures now can change based on topology(grid)?)

I think it's correct to observe that this change does not prioritize _writing_ scripts --- it prioritizes the experience of _reading_ scripts.

I think the scripts read better with this change. The purpose of "function notation" is to indicate the variables on which the function depends (usually including just dependent coordinates, like `x`, `y`, or `z`). In almost all contexts, we should not include irrelevant variables in a function signature. So I feel this change brings the experience of reading Oceananigans code into better alignment with most scientific text.

**Comment by tomchor** [comment]
> > I personally think it's nice to have all IC signatures, etc., the same independently of grid topology. It makes it easy to catch newbie mistakes when reviewing code.
> 
> I do agree that this change means that more changes are required to port a script from having a `Flat` direction to being fully three-dimensional. I'm not sure I understand the point about newbie mistakes though.

I just noticed that a lot of errors from new users that I've helped come from having the wrong function signatures, either when imposing initial or boundary conditions or forcings. With standardized "3D" function calls it makes it easier to catch. My fear is that making things less standardized (i.e. adding more possibilities), it'll be harder to spot these mistakes.

But I guess your hope is that this will decrease the number of mistakes in the first place since the signatures hopefully will become more intuitive?

> I think the scripts read better with this change.

Agreed.

**Comment by glwagner** [comment]
> But I guess your hope is that this will decrease the number of mistakes in the first place since the signatures hopefully will become more intuitive?

It will make the function signatures more specific to the problem at hand, which broadly speaking eliminates more bugs. For example, in a one dimensional problem there is only one function argument, completely eliminating the possibility of mix up between two coordinates.

**Comment by glwagner** [comment]
> My fear is that making things less standardized (i.e. adding more possibilities), it'll be harder to spot these mistakes.

It will mean that `set!` becomes more specific; ie two-dimensional set functions can only be applied to two-dimensional variables. I think there are more _possibilities_ for bugs if three-dimensional functions can be applied to two-dimensional variables. For example, you might accidentally assign the wrong initial condition to a variable. When half the variables are 2D and half are 3D, you have the possibility that a typo throws an error.

We can add some `try catch` statements to throw helpful errors within `set!` when we encounter a `MethodError`.

**Comment by tomchor** [comment]
> We can add some `try catch` statements to throw helpful errors within `set!` when we encounter a `MethodError`.

I like this idea!
