### ISSUE TITLE
Default free surface solver: `SplitExplicit` or `Implicit`

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#3289]
I noticed that the default free surface model is different than what the docstring says:
https://github.com/CliMA/Oceananigans.jl/blob/e16cdc6cfb67703df9e29368017868331f68b1c0/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L59

vs

https://github.com/CliMA/Oceananigans.jl/blob/e16cdc6cfb67703df9e29368017868331f68b1c0/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L103

I'm not sure which it is meant to be

**Comment by glwagner** [comment]
We have to debate the best choice... fate cannot decide it for us.

I think split-explicit is probably the best choice for a default --- it's performant in all contexts, and potentially also the least complicated? I believe it will also handle nonlinearity better than an implicit formulation (which we don't support now, but could support in the future). @simone-silvestri can probably best advise.

Not sure how the docstring diverged from the code.

**Comment by navidcy** [comment]
I'd like to have the SplitExplicit as the default. I'm not sure it's ready. What about #3238?

**Comment by glwagner** [comment]
True maybe we should fix the docstring first, and then have a more comphrehensive PR that fixes those issues and then changes the default.

I also wonder if we should choose the default based on the number of vertical levels.

**Comment by navidcy** [comment]
x-ref https://github.com/CliMA/Oceananigans.jl/pull/3294#issuecomment-1737819159
