### ISSUE TITLE
 NCDatasets.jl v0.13 has breaking changes

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3309]
See, e.g., at https://github.com/Alexander-Barth/NCDatasets.jl/releases/tag/v0.13.0

Does anything of the above affect us? Should we take care before upgrading?

cc @tomchor

**Comment by tomchor** [comment]
I don't have time to open a PR for this, but based on the listed breaking changes, it's very likely we'll have to modify the code in order for the upgrade to work.

**Comment by glwagner** [comment]
I opened a PR: https://github.com/CliMA/Oceananigans.jl/pull/3313

**Comment by navidcy** [comment]
NCDatasets v0.13 was taken back
https://github.com/JuliaRegistries/General/issues/92819

Closing this for now

**Comment by navidcy** [comment]
NCDatasets v0.13.1 was released
