### ISSUE TITLE
Clarification for `Face` -> `Center` interpolation operator in `Operators/README.md`

### ISSUE THREAD

**Issue by jbisits** [CliMA/Oceananigans.jl#3315]
In the `Operators/README.md` the [interpolation](https://github.com/CliMA/Oceananigans.jl/blob/82503b811a305bd7a6c4f1d3650f2b25b535c8fa/src/Operators/README.md?plain=1#L38C1-L41C4) for `Face` -> `Center` is

> Conversely, the interpolation of a quantity `u` from a face `i` to cell `i` is given by `ℑxᶠᵃᵃ(u)ᵢ = (uᵢ₊₁ + uᵢ) / 2`

Should the interpolation operator instead be `ℑxᶜᵃᵃ(u)ᵢ = (uᵢ₊₁ + uᵢ) / 2` when going from face `i` to center `i`? Very small I know but will put my mind at ease!

**Comment by glwagner** [comment]
Quite right, this is a typo!

**Comment by jbisits** [comment]
I will open a PR for this (if that suits?) soon!
