### ISSUE TITLE
Update docs to change `FieldSlicer` to `indices`

### ISSUE THREAD

**Issue by xkykai** [CliMA/Oceananigans.jl#3348]
https://github.com/CliMA/Oceananigans.jl/blob/7af4aad1eb4127c1c3c9605755ceaffaaec0668c/docs/src/model_setup/output_writers.md?plain=1#L28
I believe that `FieldSlicer` is no longer used? I think this is just a small part of the docs that missed this update.

**Comment by glwagner** [comment]
Definitely outdated! Nice find.
