### ISSUE TITLE
Documentation for latest versions does not seem to be working

### ISSUE THREAD

**Issue by xkykai** [CliMA/Oceananigans.jl#3377]
When I click on the link to the documentation/try finding the documentation on Google, it seems like the link https://clima.github.io/OceananigansDocumentation/stable automatically downloads a text file that contains the version number, and nothing more.

Here's also a screenshot of clicking on the documentation page on Google:
![Screenshot 2023-11-05 205429](https://github.com/CliMA/Oceananigans.jl/assets/50624521/ae495f16-51f8-4e9b-bd5c-a3606bc9dcbf)

But I suppose the `dev` version of the documentation works:
https://clima.github.io/OceananigansDocumentation/dev/

**Comment by glwagner** [comment]
Also noted on https://github.com/JuliaDocs/DocumenterCitations.jl/pull/25

**Comment by navidcy** [comment]
(I'll close this when we have a working version of stable docs)

**Comment by navidcy** [comment]
https://clima.github.io/OceananigansDocumentation/stable/
