### ISSUE TITLE
Explicitly time-step w instead of recomputing it from continuity?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#338]
Found out int PR #336 that we can explicitly time-step w which will be nice as it'll work for simulations without a rigid lid.

All tests passed when I made the change so should be a quick change.

**Comment by ali-ramadhan** [comment]
Few comments here:
1) I sent an email to Ali (@ali-ramadhan) and Chris (@christophernhill) on Apr 02 2019,
  and Ali opened issue #161 the same day and included a copy of my email content in it.
 So, "originally" w was stepped forward, not the other way.
2) do we currently have a good Float32 test ?
3) machine truncation error in solver when we switch to variable vertical resolution ?
4) I disagree with the last point, recomputing w from continuity is fine with free surface
 and with flow through the bottom (cf, MITgcm). In fact, it might be even more useful
 with a non-linear free-surface since, in this case, some linearization is needed when
 solving for pressure.

On Wed, Aug 07, 2019 at 05:16:43AM -0700, Gregory L. Wagner wrote:
> We originally did the recompilation of w from continuity partly because we thought this may prevent an accumulation of error that could otherwise occur, and partly because @sandreza convinced us this was more correct. But I would argue that because we haven't done model verification we aren't sure whether this is correct or not. 
> 
> Another issue, or annoyance, with recomputing w from continuity is that it is only valid in the case of rigid lids on top and bottom.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/climate-machine/Oceananigans.jl/pull/336#issuecomment-519070915

_Originally posted by @jm-c in https://github.com/climate-machine/Oceananigans.jl/pull/336#issuecomment-519120749_

**Comment by ali-ramadhan** [comment]
> do we currently have a good Float32 test ?

We have quite a few. Generally stuff works in Float32 but of course everything is less precise as expected. It might hurt us in some places. In particular, the only really bad one is tracer conservation in a channel model is much worse in Float32 than Float64 (both remain ~constant in time last time I checked).

Some results from the tests:
```
  Testing recomputing w from continuity...
[ Info: Velocity divergence after recomputing w (CPU(), Float32): min=-2.3841858e-7, max=-2.3841858e-7, sum=-4.7683716e-7, abs_sum=4.720688e-5
[ Info: Velocity divergence after recomputing w (CPU(), Float64): min=-4.440892098500626e-16, max=-4.440892098500626e-16, sum=-3.552713678800501e-15, abs_sum=1.0613732115416497e-13
[ Info: Velocity divergence after recomputing w (GPU(), Float32): min=-2.3841858e-7, max=-2.3841858e-7, sum=2.026558e-6, abs_sum=4.5895576e-5
[ Info: Velocity divergence after recomputing w (GPU(), Float64): min=-4.440892098500626e-16, max=-4.440892098500626e-16, sum=1.7763568394002505e-15, abs_sum=1.2656542480726785e-13
```

```
[ Info: Velocity divergence after 1 time steps (CPU(), Float32): min=-3.5675463e-11, max=-3.5675463e-11, sum=-2.9740932e-12, abs_sum=6.9117574e-9
[ Info: Velocity divergence after 10 time steps (CPU(), Float32): min=-3.143441e-11, max=-3.143441e-11, sum=-5.0689453e-12, abs_sum=9.463426e-9
[ Info: Velocity divergence after 100 time steps (CPU(), Float32): min=-6.3892e-11, max=-6.3892e-11, sum=-1.127638e-10, abs_sum=4.6969774e-8
[ Info: Velocity divergence after 1 time steps (CPU(), Float64): min=-7.686559298536759e-19, max=-7.686559298536759e-19, sum=-1.2421179146024245e-21, abs_sum=1.5105296988410314e-16
[ Info: Velocity divergence after 10 time steps (CPU(), Float64): min=-9.020900888258299e-19, max=-9.020900888258299e-19, sum=5.79061971704065e-22, abs_sum=1.6794563169636008e-16
[ Info: Velocity divergence after 100 time steps (CPU(), Float64): min=-8.859964628279982e-19, max=-8.859964628279982e-19, sum=2.3878439877479045e-19, abs_sum=2.3371755428721667e-16
[ Info: Velocity divergence after 1 time steps (GPU(), Float32): min=-3.5742964e-11, max=-3.5742964e-11, sum=-3.127748e-12, abs_sum=6.8964283e-9
[ Info: Velocity divergence after 10 time steps (GPU(), Float32): min=-4.984102e-11, max=-4.984102e-11, sum=-4.652792e-12, abs_sum=9.790147e-9
[ Info: Velocity divergence after 100 time steps (GPU(), Float32): min=-5.684342e-11, max=-5.684342e-11, sum=2.8093305e-11, abs_sum=4.5857547e-8
[ Info: Velocity divergence after 1 time steps (GPU(), Float64): min=-7.321110903910831e-19, max=-7.321110903910831e-19, sum=-1.805321686896983e-22, abs_sum=1.5813009122639161e-16
[ Info: Velocity divergence after 10 time steps (GPU(), Float64): min=-9.399948132154598e-19, max=-9.399948132154598e-19, sum=-2.2989927699914332e-20, abs_sum=1.8113055478312138e-16
[ Info: Velocity divergence after 100 time steps (GPU(), Float64): min=-8.080694316806025e-19, max=-8.080694316806025e-19, sum=-2.2046007346005637e-19, abs_sum=2.3631237375347637e-16
```

```
  Testing tracer conservation in channel...
[ Info: Tracer conservation after 10 time steps (CPU(), Float32): ⟨T⟩-T₀=-0.001209259 °C
[ Info: Tracer conservation after 10 time steps (CPU(), Float64): ⟨T⟩-T₀=6.750155989720952e-14 °C
[ Info: Tracer conservation after 10 time steps (GPU(), Float32): ⟨T⟩-T₀=-0.0012111664 °C
[ Info: Tracer conservation after 10 time steps (GPU(), Float64): ⟨T⟩-T₀=1.5987211554602254e-13 °C
```

**Comment by glwagner** [comment]
How can we address this? I would prefer that we time-step `w`, but I think changing the algorithm causes tests to fail. Should we open a branch to test?

**Comment by ali-ramadhan** [comment]
At some point I actually switched to time-stepping `w` and all the tests actually passed: https://github.com/climate-machine/Oceananigans.jl/pull/336#issuecomment-518876660

We originally time-stepped `w` explicitly until @jm-c suggested we recompute `w` from continuity, so might be good to check with him before making any changes. It's possible we may want to stick with this for now, in which case the issue should be closed.

**Comment by ali-ramadhan** [comment]
Bumping this issue following discussion with @glwagner and PR #666.
