### ISSUE TITLE
`compute_regionally` must be deprecated

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3386]
@simone-silvestri, what is `compute_regionally` that the docstring here is referring to?

https://github.com/CliMA/Oceananigans.jl/blob/70536571523ad2eb71fd9a2200121eca63998ac4/src/Utils/multi_region_transformation.jl#L196

Legacy/Deprecated perhaps?

**Comment by simone-silvestri** [comment]
It's here
https://github.com/CliMA/Oceananigans.jl/blob/main/src/Utils/multi_region_transformation.jl#L143

**Comment by navidcy** [comment]
oh `construct_regionally`, not `compute_regionally`. Gotcha!

**Comment by simone-silvestri** [comment]
Yeah, so I guess this docstring is deprecated. Let's change it
