### ISSUE TITLE
Three-dimensional `StokesDrift` docstring example may be misleading

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3422]
The docstring example for three-dimensional Stokes drift can be improved:

https://github.com/CliMA/Oceananigans.jl/blob/1c2a6f8752b6425bf30d856f8ba0aa681c0ab818/src/StokesDrifts.jl#L219-L226

The `v`-component (for example) is associated with a Stokes drift `vS` of the form:

```julia
vS = p.Uˢ * exp(z / p.h) * cos(p.k * x) * sin(t)
```

For this to represent a real surface wave field, then it would have to be sinusoidally oscillating in time (hard to imagine). Also, the envelope of the surface drift is modulated in space by `cos(k * x)`. Unfortunately, this is quite confusing because `k` is typically used to represent the wavelength of the _surface wave field_ (not the envelope of the surface waves). For example, for a monochromatic wave field, `h = 2k` is the vertical scale of the Stokes drift. So in this example, `k` has a different meaning (governing the wave field envelope) then it normally does (the wavenumber of the underlying wave field).

A better docstring example might represent a wavepacket that is translating at the group velocity, as done in a validation case:

https://github.com/CliMA/Oceananigans.jl/blob/1c2a6f8752b6425bf30d856f8ba0aa681c0ab818/validation/stokes_drift/surface_wave_quasi_geostrophic_flow.jl#L5-L51

**Comment by glwagner** [comment]
@navidcy @BrodiePearson @LeeAra0

**Comment by navidcy** [comment]
Fair point!
