### ISSUE TITLE
2D turbulence example missing `fontsize` keyword in `Label` call

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/Oceananigans.jl#3442]
Just as in the title the function Label calls initialize_block and gives the "no method matching initialize_block!(::label; fontsize::Int64) giving the error
got unsupported keyword argument "fontsize"
Kevin

**Comment by glwagner** [comment]
I think you're talking about this line

https://github.com/CliMA/Oceananigans.jl/blob/1c2a6f8752b6425bf30d856f8ba0aa681c0ab818/examples/two_dimensional_turbulence.jl#L148

**Comment by glwagner** [comment]
This might be a symptom of the fact that we don't have a `Project.toml` for examples... (or compat)... can you try updating `CairoMakie` to the latest version and confirm you get this error? Or let us know what version / packages you are using?

**Comment by navidcy** [comment]
[waywardpidgeon](https://github.com/waywardpidgeon), I think it's because of incompatibility of the CairoMakie version we use to build the docs (for the latest stable release that's 0.10.11

https://github.com/CliMA/Oceananigans.jl/blob/1c2a6f8752b6425bf30d856f8ba0aa681c0ab818/docs/Manifest.toml#L154-L158

and the one you are using. Which CairoMakie/GLMakie version are you using?

**Comment by waywardpidgeon** [comment]
Apologies - other urgent work and family needs have delayed me. I'm using
Julia 1.9.3
CairoMakie v0.9.4
 and have in my status report
GLMakie v0.7.4 and Makie v0.18.4

I tried to use update with the pkg manager to no effect, but see I should be using CairoMakie@0.11, which I am now installing.
This was not successful. For example the file S7LmV_3TYIX.dll would not load giving a permission denied error, but my check of the properties/security  did not reveal a deficiency.

However, the example worked fine.

Many thanks - Kevin

**Comment by navidcy** [comment]
If you start a clean project and install Oceananigans then you should be able to install GLMakie v0.9 or CairoMakie v0.11 and things should work seamlessly.

Anyway thanks. Since you mention the example works fine I'll consider this issue closed.

**Comment by glwagner** [comment]
@navidcy I think @waywardpidgeon is saying that `run!(simulation)` succeeds, but the plotting afterwards does not...

We may want to make some comment about clean environments somewhere. Or, make this process more robust

**Comment by navidcy** [comment]
I'm wondering if we can printout at the end of the documented examples the output of

```Julia
julia> using Pkg; Pkg.status()
Status `~/Oceananigans.jl/docs/Project.toml`
  [13f3f980] CairoMakie v0.11.6
  [e30172f5] Documenter v1.2.1
  [daee34ce] DocumenterCitations v1.3.2
  [033835bb] JLD2 v0.4.45
  [98b081ad] Literate v2.16.1
  [442fdcdd] Measures v0.3.2
⌅ [85f8d34a] NCDatasets v0.13.2
  [9e8cae18] Oceananigans v0.90.6 `~/Oceananigans.jl`
  [f27b6e38] Polynomials v4.0.6
  [bdfc003b] TimesDates v0.3.1
  [37e2e46d] LinearAlgebra
```

so people would know what versions of packages were used for that example.

**Comment by glwagner** [comment]
What about having an environment for the examples?

**Comment by navidcy** [comment]
Hm. It’s the environment that the docs are built with. But it’s bit cumbersome to figure out. 

If we have a separate env for the examples then we need to ensure that the docs built those examples with that environment. I’ll see if that’s possible.

**Comment by glwagner** [comment]
Yeah, plus the docs environment has many more things that aren't needed for the examples?
