### ISSUE TITLE
Question for 3D Stokes example

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3444]
https://github.com/CliMA/Oceananigans.jl/blob/8d98919ea9a6aedffc843f47e58ee67a71b7b1b2/src/StokesDrifts.jl#L211-L212

Hm.. two questions:

1. First of all it should be" "If 𝐮ˢ represents the solenoidal component..." (not "If uˢ represents the ...)
2. The statement "then ``∂_z wˢ = - ∂_x uˢ``" implies that either $vˢ = 0$ or that $∂_y vˢ = 0$. Is this true in general? Or is $vˢ = 0$ an assumption we forgot to mention here?

cc @glwagner, @BrodiePearson

**Comment by BrodiePearson** [comment]
I agree with both of these comments. Perhaps this can be clarified by

1. Changing the proceeding line: https://github.com/CliMA/Oceananigans.jl/blob/8d98919ea9a6aedffc843f47e58ee67a71b7b1b2/src/StokesDrifts.jl#L205
to say "A wavepacket moving with the group velocity in the x-direction." 

2. Adding $v^s=0$ in addition to the current $u^s$ equation
3. Changing your quoted statement to "then in this system `∂_z wˢ = - ∂_x uˢ` "

**Comment by glwagner** [comment]
> 2\. The statement "then `∂_z wˢ = - ∂_x uˢ`" implies that either ˢvˢ=0 or that ˢ∂yvˢ=0. Is this true in general? Or is ˢvˢ=0 an assumption we forgot to mention here?

It's not an assumption, it's the definition of the problem. `∂_z wˢ = - ∂_x uˢ` refers only to this example. This could be clarified by adding something like "in this case, "

**Comment by navidcy** [comment]
Well the assumption is that $v^S = 0$.
I modified the example in https://github.com/CliMA/Oceananigans.jl/pull/3430; have a look and edit to your liking.

**Comment by glwagner** [comment]
> Well the assumption is that vS=0.

The problem is defined such that vS = 0, there's no assumption

**Comment by navidcy** [comment]
Sorry, misunderstanding. I meant that previously it was never stated that $v^S=0$ so it was _assumed_. Now I stated it.

**Comment by glwagner** [comment]
It was implied by saying "the Stokes drift is X [and nothing else]", but I don't see the problem with being more explicit!

**Comment by navidcy** [comment]
If Stokes drift is X and nothing else where did $w^S \ne 0$ came about?
