### ISSUE TITLE
`restore_from_checkpoint` is deprecated?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3462]
I see it here being exported:

https://github.com/CliMA/Oceananigans.jl/blob/3b02321a350003fa9596c4f40839b031a5cc7ad1/src/OutputWriters/OutputWriters.jl#L5

but nowhere else. I believe that currently this happens via

https://github.com/CliMA/Oceananigans.jl/blob/3b02321a350003fa9596c4f40839b031a5cc7ad1/src/OutputWriters/checkpointer.jl#L201

Right?

**Comment by glwagner** [comment]
Yeah
