### ISSUE TITLE
Checkpointer required properties includes `:architecture` despite it can be inferred from `grid`

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3463]
I don't think architecture is required, despite being included here:

https://github.com/CliMA/Oceananigans.jl/blob/3b02321a350003fa9596c4f40839b031a5cc7ad1/src/OutputWriters/checkpointer.jl#L74

For example, `:architecture` property is not called within

https://github.com/CliMA/Oceananigans.jl/blob/3b02321a350003fa9596c4f40839b031a5cc7ad1/src/OutputWriters/checkpointer.jl#L201

**Comment by glwagner** [comment]
Makes sense. `Checkpointer` needs love.
