### ISSUE TITLE
@fluidnumerics-joe the CI doesn't work... something's wrong with the Manifest you pushed.

### ISSUE THREAD

**Issue by fluidnumerics-joe** [CliMA/Oceananigans.jl#3470]
@fluidnumerics-joe the CI doesn't work... something's wrong with the Manifest you pushed.

It would be easier if you somehow allow maintainers to push. There is an option "Allow edits and access to secrets by maintainers" when you open a PR. Perhaps you disabled that?

Personally if I don't see the CI working (at least starting) then I feel it's a bit futile to comment on code that might be outdate or deprecated.

_Originally posted by @navidcy in https://github.com/CliMA/Oceananigans.jl/issues/3468#issuecomment-1936950079_

What do you mean by outdated or deprecated here? Can you help me understand how this relates to the CI?

**Comment by navidcy** [comment]
Sorry I should have been more verbose. I meant that since the Manifest you pushed doesn't seem to work then I'm not sure I can reproduce the setup you run locally to test things.
