### ISSUE TITLE
`FieldTimeSeries` does not adapt correctly on GPU

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#3472]
I can't quite identify where this issue is coming from but if you load a `FieldTimeSeries` in the normal way, i.e.:
```julia
u = FieldTimeSeries("path.jld2", "u");
```
when it gets adapted the `data` and `times` are not adapted to GPU arrays if the `FieldTimeSeries` is adapted to `GPUAdaptedFieldTimeSeries` when it's passed to a model etc. If instead I specify the grid like:
```julia
u = FieldTimeSeries("path.jld2", "u"; grid);
```
then the data is correctly adapted but the `times` are still a regular vector.

I can of course manually create the adapted time series like:
```julia
u = FieldTimeSeries("path.jld2", "u"; grid);
u_adapt = GPUAdaptedFieldTimeSeries{Face, Center, Center, eltype(grid)}(arch_array(arch, u.data), arch_array(arch, u.times))
```
and also defining:
```julia
adapt_structure(to, fts::GPUAdaptedFieldTimeSeries{LX, LY, LZ, FT}) where {LX, LY, LZ, FT} = 
    GPUAdaptedFieldTimeSeries{LX, LY, LZ, FT}(adapt(to, fts.data),
                                              adapt(to, fts.times))
```
but this should probably be part of the default behaviour.

**Comment by glwagner** [comment]
If `times` is a `Vector` then it needs to be converted to `arch_array` _and_ adapted when passed to GPU.

We're doing a big overhaul on #3450 and this is one of the thing we fixed:

https://github.com/CliMA/Oceananigans.jl/blob/13dcd4ff9767c5a1e030bf4ce5765cc661b1175b/src/OutputReaders/field_time_series.jl#L235-L243

**Comment by glwagner** [comment]
Basically we'd like to support range, vector, tuple. But range is preferred for sure, so we'll try to convert to one if we can. For irregularly spaced data we'll have to make a CuArray.

**Comment by jagoosw** [comment]
Ah I see that makes sense. I didn't realise that PR was related sorry!

**Comment by glwagner** [comment]
No worries of course!
