### ISSUE TITLE
Reshape grid ranges xC, zF, etc?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#348]
Not sure if this is part of an existing issue but currently e.g. `grid.xC` is a 1D range but for broadcasting it might be nice to change it to a 3D `Nx*1*1` array?

**Comment by glwagner** [comment]
This is a tough one. An array with a shape convenient for broadcasting would be nice for many applications (and this is what dedalus does). But ranges are faster for computation, and for GPU stuff we would be forced to create CuArrays (and shared memory stuff would become more complicated).

**Comment by ali-ramadhan** [comment]
Hmmm, since the conveniently shaped arrays won't be used in performance-critical code like time-stepping, maybe it makes sense to to just add a convenience function, e.g.
```julia
xC, yC, zC = coordsC(grid)
```
that returns reshaped arrays.

**Comment by glwagner** [comment]
the function `nodes` does just that, but the argument is a `Field`. You could define a few more `nodes` functions of the form `nodes(CellField, grid)` perhaps.

The coordinate arrays may be used in time-stepping with user-defined functions and functional boundary conditions.

**Comment by glwagner** [comment]
Of course, there's no getting around arrays and ranges with stretched grids...

**Comment by ali-ramadhan** [comment]
> The function `nodes` does just that, but the argument is a `Field`.

True, this would be an easy addition.

> Of course, there's no getting around arrays with stretched grids...

True although with multiple dispatch you could still use a range whenever possible (like for x,y and sometimes z) and use an array when a range can't be used.

https://github.com/climate-machine/Oceananigans.jl/blob/2176be86be80fb4b9de2c3051c4ea09c74ed00c9/src/operators/areas_and_volumes.jl#L16-L19

**Comment by glwagner** [comment]
I just noticed this:

```julia
julia> x = range(1, stop=10, step=1.0)
1.0:1.0:10.0

julia> y = reshape(x, 10, 1, 1)
10×1×1 reshape(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, 10, 1, 1) with eltype Float64:
[:, :, 1] =
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

julia> typeof(y)
Base.ReshapedArray{Float64,3,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Tuple{}}
```

So the reshaped ranges are not arrays --- they are still ranges. I don't think there's any downside to reshape the ranges for convenience, then. This will slightly simplify the `xnodes`, etc functions as well.

**Comment by glwagner** [comment]
We've decided not to reshape the coordinate arrays.
