### ISSUE TITLE
Grid's halo size can exceed its interior

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3516]
We realized with @simone-silvestri while working on https://github.com/CliMA/Oceananigans.jl/pull/3514 that we could construct a grid whose halo size exceeds that of its interior.

```Julia
using Oceananigans

julia> grid = RectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1), halo=(2, 3, 4))
1×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×3×4 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=1.0
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=1.0
```

Here's an attempt to resolve this
https://github.com/CliMA/Oceananigans.jl/blob/aa367c705e076bfd1e6c941af9751bcd99522946/src/Grids/input_validation.jl#L67-L84

Essentially I suggest we cap the halo size by the size of the corresponding coordinate.

With the above we get:

```Julia
julia> grid = RectilinearGrid(size=(2, 1, 3), extent=(1, 1, 1))
2×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×1×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=0.5
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=0.333333

julia> grid = RectilinearGrid(size=(2, 1), extent=(1, 1), topology=(Periodic, Flat, Bounded))
2×1×1 RectilinearGrid{Float64, Periodic, Flat, Bounded} on CPU with 2×0×1 halo
├── Periodic x ∈ [0.0, 1.0)       regularly spaced with Δx=0.5
├── Flat y
└── Bounded  z ∈ [-1.0, 0.0]      regularly spaced with Δz=1.0
```

Thoughts?

**Comment by glwagner** [comment]
Won't this prevent us from doing simple stuff like creating a grid with size (1, 1, 1) that has the default halos -- (3, 3, 3)?

It's better to use `map` than broadcasting btw

**Comment by glwagner** [comment]
Oh I see, you automatically change the halo size.

**Comment by navidcy** [comment]
> Won't this prevent us from doing simple stuff like creating a grid with size (1, 1, 1) that has the default halos -- (3, 3, 3)?
> 
> It's better to use `map` than broadcasting btw

How can I use map?

**Comment by navidcy** [comment]
Oh I saw your suggestion in the PR. Nevermind.
