### ISSUE TITLE
2D turbulence example is outputting `NaNs`

### ISSUE THREAD

**Issue by jagoosw** [CliMA/Oceananigans.jl#3538]
I was just looking at the docs and noticed that the video for the 2D turbulence example goes blank, presumably because the output is `NaN`: https://clima.github.io/OceananigansDocumentation/stable/generated/two_dimensional_turbulence/.

The last version that appears to work is 0.90.9 so unless there's some change that might have cause this it might be worth setting the seed manually so that the initial conditions are always the same so it doesn't occasionally NaN?

**Comment by glwagner** [comment]
Ouch! Maybe we should fix the seed. And reduce the time step to 0.1 or something so it doens't fall exactly on the bleeding edge of possibility, depending on the whims of `rand`.
