### ISSUE TITLE
 Forcing functions that depend on internal model fields besides velocities and tracers

### ISSUE THREAD

**Issue by hdrake** [CliMA/Oceananigans.jl#3582]
@liuchihl and I are trying to implement forcing functions that depend the tracer diffusivity. It is clear how to do this for a `ScalarDiffusivity` but not for a flow-dependent closure such as `SmagorinskyLilly`.

The root of the problem seems to be that forcing functions only have access to the model `grid` and a limited tuple of `model_fields`. Since [diffusivities are also treated as `Fields` internally](https://github.com/CliMA/Oceananigans.jl/blob/main/src/TurbulenceClosures/diffusivity_fields.jl), it is not clear to me why these are not included in the `model_fields` tuple that is passed to the Forcing function:
https://github.com/CliMA/Oceananigans.jl/blob/7a4b3f04e402be70d45fcb775a4dedef087f3bb0/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl#L203-L204

Maybe what I am asking for is the same thing as suggested by this comment:
https://github.com/CliMA/Oceananigans.jl/blob/7a4b3f04e402be70d45fcb775a4dedef087f3bb0/src/Models/Models.jl#L124-L126

**Comment by glwagner** [comment]
The easiest way to add additional fields into a forcing is to create them before the forcing, eg

```julia
eddy_diffusivity = CenterField(grid)
```

Such a field can be passed into a forcing function as a parameter, for example. (It can also be captured inside a function as a global variable).

To compute this field, write a callback,

```julia
function compute_eddy_diffusivity(sim)
    νₑ = sim.model.diffusivity_fields.νₑ
    Pr = sim.model.closure.Pr
    parent(eddy_diffusivity) .= parent(νₑ) ./ Pr
    return nothing
end
```

Next add the callback to the simulation,

```julia
add_callback!(simulation, compute_eddy_diffusivity)
```

By default the callback is called every time step.

**Comment by hdrake** [comment]
Amazing! I hadn't appreciated how powerful `add_callback!` was until now!

**Comment by hdrake** [comment]
Callbacks provide a straight-forward way of implementing this, so I don't think we need to carry all of these internal fields around in `model_fields`.

**Comment by glwagner** [comment]
The disadvantage of the callback is that it requires memory allocation + computation. In the majority of cases though, this added cost is negligible (at least for only one field).

**Comment by glwagner** [comment]
Perhaps this usage should be demonstrated in the `Forcing` docs or something...

**Comment by glwagner** [comment]
> Amazing! I hadn't appreciated how powerful `add_callback!` was until now!

You can execute any code!

**Comment by hdrake** [comment]
> Perhaps this usage should be demonstrated in the `Forcing` docs or something...

Yes, I think that would be really helpful. I just checked and, across all of the examples, callbacks are only used for the timestep wizard and progress messages. Probably for this reason a lot of others users also don't realize they are more generally useful!

**Comment by glwagner** [comment]
Yes, the purpose of re-using the callback infrastructure for logging and time-step stuff was exactly to ensure that the feature was visible. But I see the point that the fact that you could do anything you want inside `progress(sim)` is potentially obscured by the fact that it appears similarly in every example... so including a case of something different than logging might be useful...

**Comment by glwagner** [comment]
It could be cool to add something to the convecting plankton example where the depth of light penetration is determined by some calculation with the plankton field, rather than just set to a constant. That would add some science + also interesting case of using a callback. And it wouldn't add another example keeping CI time constant.

**Comment by glwagner** [comment]
Hmm but I think we still need a `CumulativeIntegral` reductions feature which we don't have yet

**Comment by iuryt** [comment]
I have a version of `CumulativeIntegral` in `z` that can be used as an example.
It needs to be updated though. I was using it to estimate some initial thermal-wind currents for a baroclinic instability simulation.
https://github.com/iuryt/NorthAtlanticBloom/blob/main/src/01-model/cumulative_vertical_integration.jl

**Comment by glwagner** [comment]
Interesting that it modifies `field` in place. I think perhaps a starting point could be an implementation that puts the result in a new field, perhaps?

**Comment by iuryt** [comment]
> Interesting that it modifies `field` in place. I think perhaps a starting point could be an implementation that puts the result in a new field, perhaps?

Yes, in my case, I created a copy of the field I wanted to integrate and then applied the function.

**Comment by glwagner** [comment]
`cumsum!` is supported by CUDA now:

```julia
julia> a = CuArray(rand(3, 3))
3×3 CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}:
 0.717587   0.651834  0.292342
 0.665869   0.499985  0.0607556
 0.0594806  0.628178  0.878348

julia> b = 0a
3×3 CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> cumsum!(b, a, dims=3)
3×3 CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}:
 0.717587   0.651834  0.292342
 0.665869   0.499985  0.0607556
 0.0594806  0.628178  0.878348
```

this should be pretty easy. We just have to generalize `Reduction` because I think a cumulative sum should not be called that! Need to think of another name

**Comment by iuryt** [comment]
So the idea is to basically create a function that given a field and dimension, it will multiply by $\Delta$ in that dimension and apply `cumsum!` in whatever architecture? It doesn't seem too complicated, right?

**Comment by glwagner** [comment]
There's two challenges. One is refactoring `Reduction` to be more general. `cumsum!` has a diffeerent pattern, the dimensionality is not reduced for the output and it has a slightly different syntax. But I figured that stuff out here:

https://github.com/CliMA/Oceananigans.jl/pull/3590

The next challenge is to figure out how to integrate downwards rather than up; this is a little trickier I think because we may need an abstraction that reverses indices or something.

There is also the metric part but that's kind of trivial, its the same thing as with `Integral` or `Average`.

**Comment by glwagner** [comment]
For the metric part see `Integral` which is just a few lines:

https://github.com/CliMA/Oceananigans.jl/blob/04bcf38aba80c7915b419417390d2f89ff35f097/src/AbstractOperations/metric_field_reductions.jl#L63-L67
