### ISSUE TITLE
Huge memory use of Average associated with compilation

### ISSUE THREAD

**Issue by erin-atkinson** [CliMA/Oceananigans.jl#3621]
```jl
using Oceananigans
grid = RectilinearGrid(size=(256, 256), extent=(1, 1), topology=(Periodic, Periodic, Flat));
c = CenterField(grid);
averaged_c = Field(Average(c, dims=1))
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
```
```
[ Info: Oceananigans will use 4 threads
  1.799615 seconds (2.15 M allocations: 145.537 MiB, 2.36% gc time, 99.84% compilation time)
  0.403576 seconds (130.11 k allocations: 8.875 MiB, 99.84% compilation time)
  0.407113 seconds (130.11 k allocations: 8.875 MiB, 99.85% compilation time)
  0.404251 seconds (130.11 k allocations: 8.878 MiB, 99.85% compilation time)
  0.412207 seconds (130.11 k allocations: 8.876 MiB, 99.85% compilation time)
  0.000443 seconds (201 allocations: 40.250 KiB)
```
Note the huge memory use compared to the size of the array in c. I'm trying to do some diagnostics on fields about 50MB (post-processing). Computing an average over them uses 6GB each!
Is this the same as #2024? It does seem to go away after a couple runs. Julia 1.10.4 Oceananigans 0.91.1

**Comment by erin-atkinson** [comment]
It does appear to be exactly the same thing as #2024. As you can see I've been indecisive about whether I should just comment on that.

**Comment by glwagner** [comment]
Hmm yes it might make sense to re-open #2024 and continue discussion there.

**Comment by glwagner** [comment]
I can reproduce your results too FYI

**Comment by glwagner** [comment]
Kind of a bizarre solution but if memory allocations are slowing you down you can try something like

```julia
using Oceananigans

# Just a warm up
tiny_grid = RectilinearGrid(size=(1, 1), extent=(1, 1), topology=(Periodic, Periodic, Flat));
c = CenterField(tiny_grid)
averaged_c = Field(Average(c, dims=1))

for n = 1:5
     @time compute!(averaged_c)
end

# It's all nice and compiled now
grid = RectilinearGrid(size=(1024, 1024), extent=(1, 1), topology=(Periodic, Periodic, Flat));
c = CenterField(grid)
averaged_c = Field(Average(c, dims=1))
@time compute!(averaged_c)
```

I'm not sure what the root cause is. Some compiler heuristics which I guess are oriented towards accelerating first execution at the expense of delayed compilation or something.

**Comment by glwagner** [comment]
The above doesn't seem to work for all grids though. I though it worked for `(Periodic, Periodic, Bounded)` but it doesn't seem to work for `Periodic, Periodic, Flat` for some reason, compilation is still "sticky"

**Comment by erin-atkinson** [comment]
Yeah trying to compile it on a baby grid doesn't work for me (Bounded, Periodic, Bounded). I suppose I have to make the averaged fields manually for now.

**Comment by erin-atkinson** [comment]
Oh! This isn't actually the same as #2024 (but I guess that still stands). My high memory use is different, it happens when computing Reductions of fields that are read from a file that was saved `with_halos=false`. Fix is to just set it to true. I suppose that's what it should be if you are post-processing... The result is that #2024 still happens, but with more reasonable memory use on first compilation ~100mb.

Is it still an issue or is this something expected? If the latter, this can be closed.

**Comment by glwagner** [comment]
Not sure if this is expected. The memory usage is just during compilation, right? If so that is more out of our control (though there are some things we might try...)

The difference between `with_halos` vs not is that when halos are omitted, the resulting field is "windowed". Subsequent computations then have to take special care with indexing. So the kernels are slightly more complicated. But this shouldn't have a computation cost, it seems its just the extra complexity of doing stuff with windowed fields makes it more expensive to compile.

I would leave it open! It might be nice to have some code to work with that illustrates the issue, if you get the chance to add that here. Note that we can create windowed fields without saving files by passing `indices` explicitly to `Field` (eg something like `indices=(1:Nx, 1:Ny, 1:Nz)` might reproduce what we get with `with_halos=false`).

I think this issue has a similar underlying cause as #2024 (eg all issues with compilation are related to some degree), but it is surprising that the overhead for windowed fields is so much higher.

On a side note it remains a question whether we should switch to `with_halos=true` as default. This is a good reason to do that...

**Comment by erin-atkinson** [comment]
It seems like just making it windowed is sufficient:
```jl
using Oceananigans
grid = RectilinearGrid(size=(1000, 64, 100), extent=(1, 1, 1), topology=(Periodic, Periodic, Bounded));
c = CenterField(grid; indices=(1:grid.Nx, 1:grid.Ny, 1:grid.Nz));
averaged_c = Field(Average(c, dims=2))
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
```
```
  7.571218 seconds (148.24 M allocations: 5.525 GiB, 11.61% gc time, 20.66% compilation time)
  6.289439 seconds (147.06 M allocations: 5.446 GiB, 8.98% gc time, 9.51% compilation time)
  6.244228 seconds (147.06 M allocations: 5.446 GiB, 9.05% gc time, 9.02% compilation time)
  6.280231 seconds (147.06 M allocations: 5.446 GiB, 8.95% gc time, 9.66% compilation time)
  6.547759 seconds (147.06 M allocations: 5.446 GiB, 10.26% gc time, 8.79% compilation time)
  5.813575 seconds (146.87 M allocations: 5.433 GiB, 9.97% gc time)
```
It never stops using a lot of memory. #2024 shows up, but afterwards the memory use stays. It's probably not related to the compilation then?

Also, I tried on Julia 1.7.2 with Oceananigans 0.84.1 and the memory use happens even without a windowed field (???) Something that was fixed earlier but not for every case?

**Comment by glwagner** [comment]
Hmm. I think it's still a type instability / compiler issue but that doesn't mean we don't have some work to do to solve this. (It's very unlikely that we allocate memory accidentally in Oceananigans; for example `Field` is immutable, so we cannot change the data that it points to...)

Something interesting about this problem is that it _does_ compile when the problem size is reduced (for example to `(10, 10, 10)`.) So we are hitting some heuristic that is the combination of the problem size and the complexity of the object (which increases when we add `indices`).

**Comment by glwagner** [comment]
@simone-silvestri maybe you can help here. It looks like reductions sometimes don't get type inferred properly and suffer a huge slowdown. Here's a clue. Starting with

```julia
using Oceananigans
grid = RectilinearGrid(size=(1000, 64, 100), extent=(1, 1, 1), topology=(Periodic, Periodic, Bounded));
c = CenterField(grid; indices=(1:grid.Nx, 1:grid.Ny, 1:grid.Nz));
averaged_c = Field(Average(c, dims=2))
```

we find that

```julia
using Statistics
@time mean!(interior(averaged_c), interior(c))
```

compiles after the first execution and is fast. But

```julia
@time mean!(averaged_c, c)
```

is slow and looks like it suffers from type inference failure

**Comment by simone-silvestri** [comment]
The problem seem to be in the `sum!` reduction
```julia
julia> avgc = interior(averaged_c);

julia> @time sum!(avgc, c);
  4.943968 seconds (146.87 M allocations: 5.433 GiB, 6.24% gc time)

julia> @time sum!(avgc, interior(c));
  0.010433 seconds (1.99 k allocations: 138.898 KiB, 41.52% compilation time)
```
which seems to be a problem with the `mapreducedim!` function
```julia
julia> @time Base.mapreducedim!(identity, Base.add_sum, Base.initarray!(avgc, identity, Base.add_sum, init, c), c);
  5.202692 seconds (146.87 M allocations: 5.433 GiB, 8.23% gc time)

julia> @time Base.mapreducedim!(identity, Base.add_sum, Base.initarray!(avgc, identity, Base.add_sum, init, interior(c)), interior(c));
  0.007266 seconds (112 allocations: 3.750 KiB)
```

**Comment by simone-silvestri** [comment]
The problem stems from `axes(c)`.
If we use a non-windowed field:
```julia
julia> c2 = CenterField(grid);

julia> @time Base.mapreducedim!(identity, Base.add_sum, Base.initarray!(avgc, identity, Base.add_sum, init, interior(c)), c2);
  0.001430 seconds (57 allocations: 2.406 KiB)
```
The difference between the two is that 
```julia
julia> axes(c)
(1:1000, 1:64, 1:100)

julia> axes(c2)
(Base.OneTo(1000), Base.OneTo(64), Base.OneTo(100))
```
which is used in `mapreducedim!`. I am not sure why having a `UnitRange` axes instead of a `OneTo` axes makes this large of a difference

**Comment by glwagner** [comment]
It really just comes down to these lines:

```julia
        @inbounds for IA in CartesianIndices(indsAt)
            IR = Broadcast.newindex(IA, keep, Idefault)
            @simd for i in axes(A, 1)
                R[i,IR] = op(R[i,IR], f(A[i,IA]))
            end
        end
```

https://github.com/JuliaLang/julia/blob/7c5c724ed93015d2e9c52c7fcd8f5c4ebbefff03/base/reducedim.jl#L284

The problem could in fact be here:

https://github.com/CliMA/Oceananigans.jl/blob/d4bcc095be66c7b5c98a462106285a6f6d341fe1/src/Fields/field.jl#L404

which I think cannot be type-inferred by the compiler.

**Comment by glwagner** [comment]
I think I fixed it... PR incoming...

**Comment by glwagner** [comment]
On #3624 

```julia
using Oceananigans
grid = RectilinearGrid(size=(1000, 64, 100), extent=(1, 1, 1), topology=(Periodic, Periodic, Bounded));
c = CenterField(grid; indices=(1:grid.Nx, 1:grid.Ny, 1:grid.Nz));
averaged_c = Field(Average(c, dims=2))
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
@time compute!(averaged_c)
```

Makes


julia> @time compute!(averaged_c)
  1.576736 seconds (1.81 M allocations: 123.040 MiB, 99.63% compilation time)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0

julia> @time compute!(averaged_c)
  0.450573 seconds (150.91 k allocations: 10.220 MiB, 7.82% gc time, 99.15% compilation time)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0

julia> @time compute!(averaged_c)
  0.403323 seconds (150.90 k allocations: 10.217 MiB, 98.63% compilation time)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0

julia> @time compute!(averaged_c)
  0.404525 seconds (150.90 k allocations: 10.221 MiB, 98.74% compilation time)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0

julia> @time compute!(averaged_c)
  0.412531 seconds (150.90 k allocations: 10.219 MiB, 98.85% compilation time)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0

julia> @time compute!(averaged_c)
  0.007040 seconds (204 allocations: 44.438 KiB)
1000×1×100 Field{Center, Nothing, Center} reduced over dims = (2,) on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1000, 1, 100)
├── grid: 1000×64×100 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── operand: Average of 1000×64×100 Field{Center, Center, Center} on RectilinearGrid on CPU over dims (2,)
├── status: time=0.0
└── data: 1000×1×100 OffsetArray(::Array{Float64, 3}, 1:1000, 1:1, 1:100) with eltype Float64 with indices 1:1000×1:1×1:100
    └── max=0.0, min=0.0, mean=0.0
```

**Comment by vchuravy** [comment]
You might be able to use Tracy to investigate what is being compiled again and that might give us a hint for what we need to fix.

One explanation is that the second run exercises a part of the code that wasn't exercised on the first one.

**Comment by glwagner** [comment]
Oh nice, this package? https://github.com/topolarity/Tracy.jl

Is there a reason why 4 invocations are required to get this compiled? I think it's ok since typically we want to run things 100s of times (we can do 4) but might be helpful to understand why
