### ISSUE TITLE
Halo inflation + restriction on halo size makes it impossible to run some problems

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3622]
For example,

```julia
using Oceananigans

grid = RectilinearGrid(size = (16, 1, 16),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))

model = NonhydrostaticModel(; grid, advection = WENO(order=5))
```

errors with

```julia
julia> include("problem.jl")
┌ Warning: Inflating model grid halo size to (3, 3, 3) and recreating grid. Note that an ImmersedBoundaryGrid requires an extra halo point in all non-flat directions compared to a non-immersed boundary grid.
└ @ Oceananigans.Models.NonhydrostaticModels ~/.julia/packages/Oceananigans/OHYQj/src/Models/NonhydrostaticModels/nonhydrostatic_model.jl:223
ERROR: LoadError: ArgumentError: halo must be ≤ size for coordinate y
```

Sad, because I didn't actually ask for a halo (3, 3, 3)! Manually setting things doesn't help:

```julia
using Oceananigans

grid = RectilinearGrid(size = (16, 1, 16),
                       halo = (3, 1, 3),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))

model = NonhydrostaticModel(; grid, advection = WENO(order=5))
```

I guess the restriction on the halo size is supposed to be an optimization, but its not working in this case because I can't even set up my model. @navidcy

**Comment by navidcy** [comment]
okie -- there is definitely something wrong there

**Comment by glwagner** [comment]
bump ran into this again today

**Comment by simone-silvestri** [comment]
It is not an optimization; rather, to fill in periodic halos, a field must have a grid size larger than the halos (for other boundary conditions, only one is required). 
@navidcy, you could probably look at how the periodic halos are filled and make sure that they work also if the dimension is smaller than the number of halos. It might entail writing some ifelse in the fill periodic halo kernels.

**Comment by glwagner** [comment]
@simone-silvestri we just need to be able to write

```julia
using Oceananigans

grid = RectilinearGrid(size = (16, 1, 16),
                       halo = (3, 1, 3),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))
```

**Comment by simone-silvestri** [comment]
One option is the one above, other options that could achieve that results are:
- Limit the advection scheme order based on the grid size 
- we write something similar to `TracerAdvection` for momentum to allow different advection schemes in different directions and use `nothing` in the periodic direction with one grid point

**Comment by simone-silvestri** [comment]
I like option 3. I could open a PR to tackle this issue if there is consensus in the solution

**Comment by glwagner** [comment]
I don't completely follow. Regardless of what we do with respect to advection isn't

```julia
grid = RectilinearGrid(size = (16, 1, 16),
                       halo = (3, 1, 3),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))
```

valid?

**Comment by glwagner** [comment]
But then what would you do for 2 grid points?

**Comment by glwagner** [comment]
Why not implement both 3 _and_ 2?

**Comment by simone-silvestri** [comment]
Thinking about it again, I would prefer to stay away from 2 because it results in very implicit behavior. It is nice to be explicit about the scheme used.

**Comment by glwagner** [comment]
We already do 2 near boundaries

**Comment by glwagner** [comment]
The question is just what you want to do with things like

```julia
using Oceananigans

grid = RectilinearGrid(size = (16, 1, 16),
                       halo = (3, 1, 3),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))

model = NonhydrostaticModel(; grid, advection = WENO(order=5))
```

and

```julia
using Oceananigans

grid = RectilinearGrid(size = (16, 2, 16),
                       halo = (3, 1, 3),
                       x = (0, 1),
                       y = (0, 1),
                       z = (0, 1),
                       topology = (Periodic, Periodic, Bounded))

model = NonhydrostaticModel(; grid, advection = WENO(order=5))
```

etc

**Comment by glwagner** [comment]
I think we want to handle this automatically because for example `WENO()` has a default order. I feel this falls within our philosophy of "friendly" (not sure if @simone-silvestri agrees with this philosophy though 😆 )

**Comment by glwagner** [comment]
The risk of doing something automatic is that _in theory_ someone could think "oh, I only have 2 grid poits in the y direction, but I still expect to observe WENO advection in that direction". Will someone think that? It doesn't really make sense, with 2 grid points in a direction there won't be advection at all anyways. I don't think this is a big risk. Big risks are like, simulations are dead wrong when they present an illusion that makes them seem ok.
