### ISSUE TITLE
Outdated docs on background diffusivity/viscosity

### ISSUE THREAD

**Issue by whitleyv** [CliMA/Oceananigans.jl#3649]
Some of the docs still include the background viscosity in the description of Smagorinsky-Lilly. Maybe you're purposefully keeping the "Physics" different than the "Model," but if it's a typo, these are the two places it's the old version:

https://github.com/CliMA/Oceananigans.jl/blob/738d1724e5128502efe5579dd210fc17aacb9089/docs/src/physics/turbulence_closures.md?plain=1#L75-L81

https://github.com/CliMA/Oceananigans.jl/blob/738d1724e5128502efe5579dd210fc17aacb9089/docs/src/physics/turbulence_closures.md?plain=1#L104-L109

This description in the model setup is also a bit misleading, or, at least, unclear.

https://github.com/CliMA/Oceananigans.jl/blob/738d1724e5128502efe5579dd210fc17aacb9089/docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md?plain=1#L71-L72

**Comment by glwagner** [comment]
> Maybe you're purposefully keeping the "Physics" different than the "Model,"

I don't think so!

Previously we made the argument that the background viscosity is not part of the "eddy viscosity", conceptually. And of course as you point out that's not how its implemented currently either. So I agree this should be fixed.

> This description in the model setup is also a bit misleading, or, at least, unclear.

Totally, this is wrong, there is no background viscosity of diffusivity when using `SmagorinskyLilly` by default.
