### ISSUE TITLE
`Mem.free` is deprecated

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3664]
I see this deprecation warning

https://buildkite.com/clima/oceananigans/builds/16468#0190e24d-a041-4cf1-91bf-9753edd35bce/30-654

which seems related to 

https://github.com/CliMA/Oceananigans.jl/blob/abb66e32d333562dd9aaeb7dd2ed8fac5e781368/src/Architectures.jl#L102

Should we fix it? Does anyone has better clue from me on what's happening / why the above is needed?

cc @simone-silvestri

**Comment by simone-silvestri** [comment]
I guess the allocation of unified memory has improved quite a bit since. I can make a PR to bring this code up to speed
