### ISSUE TITLE
`cell_advection_timescale` (and CFL) does not account for `Flat` topologies

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#3679]
## Issue

This may only be an issue for models with `Flat` topologies _and_ Coriolis. If you have a 2D x-z model with no Coriolis then v is (probably) just zero so CFL is not affected. But if you have Coriolis then you'll have some non-zero v. This is a problem because if y is `Flat` then ` grid.Δyᵃᶜᵃ = 1.0` and `grid.Δyᵃᶠᵃ = 1.0` and the inverse timescale can get very large (even for small v-velocities)

https://github.com/CliMA/Oceananigans.jl/blob/bf767af3c40c049ebc9499b7553065a9ef350178/src/Advection/cell_advection_timescale.jl#L24

leading to severe time-step restrictions (even though it looks like the CFL is at the max CFL).

## Potential solution

I'm thinking a nice solution would be to turn the inverse timescale computation into a function then dispatch on the topology, e.g.

```julia
@inline _inverse_timescale(i, j, k, Δ, U, topo) = @inbounds abs(U[i, j, k]) / Δ
@inline _inverse_timescale(i, j, k, Δ, U, topo::Flat) = 0

...

inverse_timescale = _inverse_timescale(i, j, k, Δx, u, TX) + _inverse_timescale(i, j, k, Δy, v, TY) + _inverse_timescale(i, j, k, Δz, w, TZ)
```

If this sounds reasonable I'm happy to open a PR.

**Comment by simone-silvestri** [comment]
Looks like a nice solution!
