### ISSUE TITLE
Support passing keyword arguments to `jldopen` when using `FieldTimeSeries`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#3680]
I am interested in reading JLD2 files in parallel using multiple threads. This is actually now supported by JLD2.jl after https://github.com/JuliaIO/JLD2.jl/pull/477 provided you pass the `parallel_read = true` kwarg to `jldopen`.

I'm hoping to do this with `FieldTimeSeries`, but right now there's no way to pass kwargs to `jldopen` like there is with `JLD2OutputWriter`. I'm hoping to open a PR that adds support for this, but I'm just opening this issue in case there's any opposition or discussion to be had.

**Comment by glwagner** [comment]
This makes sense. The only thing to keep in mind is that we hope to eventually add support for NetCDF-backed `FieldTimeSeries`. So here's a few ideas to keep things general:

- add the ability to propagate kwargs through the constructor `FieldTimeSeries(filename, fieldname; filekwargs...)` into the `open` functions for jld2 or netcdf, or whatever else comes along
- if using `FieldTimeSeries` with other backends, would it make sense to store the kwargs in the backend?

**Comment by ali-ramadhan** [comment]
> add the ability to propagate kwargs through the constructor `FieldTimeSeries(filename, fieldname; filekwargs...)` into the `open` functions for jld2 or netcdf, or whatever else comes along

Agree this is good to future-proof.

> if using `FieldTimeSeries` with other backends, would it make sense to store the kwargs in the backend?

Good point and I think we will need to do this. There are places where `jldopen` is called not in the constructor so any kwargs passed to the constructor are not available and need to be stored in the backend object. Here are two example: 
1. https://github.com/CliMA/Oceananigans.jl/blob/b3be950ef6a1f2139c2f65e083f20f1f7958ea55/src/OutputReaders/field_time_series_indexing.jl#L78-L81
2. https://github.com/CliMA/Oceananigans.jl/blob/b3be950ef6a1f2139c2f65e083f20f1f7958ea55/src/OutputReaders/set_field_time_series.jl#L52-L54

**Comment by glwagner** [comment]
It seems logical to store the kwargs in the backend! That will also help with future proofing since we would probably implement NetCDF support by generalizing the backend concept. I think those two examples are when data is stored totally on disk or "partly" on disk (and part in memory).
