### ISSUE TITLE
Cleanup Doc Previews

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3726]
Having doc previews enable is very useful.

But...

The fill up the docs repo!
E.g., just from a week or something when we enabled them they've been adding up! See: https://github.com/CliMA/OceananigansDocumentation/tree/gh-pages/previews

Ideally we want to make a GitHub action, in the spirit of what's described at
https://documenter.juliadocs.org/stable/man/hosting/#Cleaning-up-gh-pages
that will delete the previews after PRs are merged. The workflow described in the Documenter docs will _not_ work when the docs are hosted in a different repo than the package...

_Originally posted by @navidcy in https://github.com/CliMA/Oceananigans.jl/issues/3724#issuecomment-2308562327_

**Comment by navidcy** [comment]
@Sbozzolo, do you have perhaps an idea how to make this happen?

**Comment by Sbozzolo** [comment]
One simple solution would be to host the GitHub action on the `OceananigansDocumentation` and have it so that it runs on a schedule (e.g., weekly).

**Comment by navidcy** [comment]
You mean have a GitHub action in the Docs repo and every week clear up all accumulated previews?
That's great! That would work amazingly. Do you know how to do this weekly schedule?
(Then we can also do it for ClimaOcean Docs repo, etc!)

**Comment by Sbozzolo** [comment]
> You mean have a GitHub action in the Docs repo and every week clear up all accumulated previews? That's great! That would work amazingly. Do you know how to do this weekly schedule? (Then we can also do it for ClimaOcean Docs repo, etc!)

Yes, have a look [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule) to learn how to run a GitHub action on a schedule

**Comment by glwagner** [comment]
We should set up buildkite though so we can use tartarus' GPU. I think an Oceananigans docs build via github actions would take a pretty long time. Also we should build more frequently than every week. The docs build takes about 30 min so hourly could be appropriate

**Comment by glwagner** [comment]
I don't completely understand how this enables doc previews though. Docs previews are triggered from the PR build so we wouldn't be able to clean those up?

**Comment by glwagner** [comment]
Thanks @Sbozzolo for your help on this

**Comment by navidcy** [comment]
> We should set up buildkite though so we can use tartarus' GPU. I think an Oceananigans docs build via github actions would take a pretty long time. Also we should build more frequently than every week. The docs build takes about 30 min so hourly could be appropriate

@Sbozzolo only suggests the cleaning up of the `gh-pages` branch `previews` directory to be done via GitHub Actions on some regular interval. Doing that would allow us to have that GitHub action live in the Docs repo so it would be doable. Otherwise, having the DocPreviewCleanup GitHub action in the main repo and triggering it every time a PR is merge is not doable because the GitHub action does not have permission to delete things on a different repo -- that's the issue I was hitting.
