### ISSUE TITLE
Bug with Makie extension

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3727]
The code snippet below is not working as expected. I explain.

This works fine:
```Julia
using Oceananigans, CairoMakie

underlying_grid = RectilinearGrid(size = (250, 125),
                                  x = (-1000e3, 1000e3),
                                  z = (-2e3, 0),
                                  halo = (4, 4),
                                  topology = (Periodic, Flat, Bounded))

bottom(x) = - underlying_grid.Lz + 500 * exp(-x^2 / (2*(20e3)^2))

grid = ImmersedBoundaryGrid(underlying_grid, GridFittedBottom(bottom))

lines(grid.immersed_boundary.bottom_height)
```
and gives:

![fig1](https://github.com/user-attachments/assets/79b2f1a6-be6e-43a0-80de-15ed213f38df)

which is all good! But:
```julia
x, y, z = nodes(grid.immersed_boundary.bottom_height)

lines(x, grid.immersed_boundary.bottom_height)
```
![fig2](https://github.com/user-attachments/assets/3ef1978d-871d-4121-850e-8ea64db1e207)

Perhaps this is a bit informative
```julia
lines(x/1e3, grid.immersed_boundary.bottom_height)
```
![fig3](https://github.com/user-attachments/assets/930ad10d-30d8-498f-8906-3b3294a692c6)

_Originally posted by @navidcy in https://github.com/CliMA/Oceananigans.jl/issues/3725#issuecomment-2308667545_

**Comment by glwagner** [comment]
Not sure but I'm guessing to fix this we have to overload `lines`. It seems like it computes that it's going to be making a 3D plot at some point before `convert_arguments` is called.. not sure

**Comment by glwagner** [comment]
What if you make the axis first?

**Comment by navidcy** [comment]
Actually that worked!

```Julia
using Oceananigans, CairoMakie

underlying_grid = RectilinearGrid(size = (250, 125),
                                  x = (-1000e3, 1000e3),
                                  z = (-2e3, 0),
                                  halo = (4, 4),
                                  topology = (Periodic, Flat, Bounded))

bottom(x) = - underlying_grid.Lz + 500 * exp(-x^2 / (2*(20e3)^2))

grid = ImmersedBoundaryGrid(underlying_grid, GridFittedBottom(bottom))

bottom_height = grid.immersed_boundary.bottom_height

x, y, z = nodes(bottom_height)


fig = Figure()
ax = Axis(fig[1, 1])
lines!(ax, x/1e3, bottom_height)
fig
```
![display](https://github.com/user-attachments/assets/0aedb6ec-c2f5-4873-804a-ce3ec310d00e)

OK. I suppose if you don't create the axis Makie thinks this is a 3D field and then creates Axis3 object... So it's good to point out somewhere that to visualize it's better to create axis first?

**Comment by glwagner** [comment]
Or we can dig into Makie and maybe try to fix the wrong axis assignment?

**Comment by glwagner** [comment]
I think I figured it out, basically there is a function `args_preferred_axis` that determines which Axis type to use (when it's not specified), and because `Field isa AbstractArray{3}` it ends up choosing `LScene`. So the simple fix here is just to say that `Field` does not have a preferred axis type. As a result, when the axis is not provided, it is determined later on (by the converted arguments, rather than the un-converted `Field`).

We could in the future attempt to figure out the "effective dimensionality" of a `Field` and then use that to determine whether it has a preferred axis type.
