### ISSUE TITLE
Bug in `interpolate!(target_fts::FieldTimeSeries, source_fts::FieldTimeSeries)`?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3731]
Seems that there is a bug here?

https://github.com/CliMA/Oceananigans.jl/blob/5218acd72d146f063838286e7bf61c2d26165fbf/src/OutputReaders/field_time_series_indexing.jl#L205

`target_times` is never defined but used as an arg in the kernel?

This produces the error in the ClimaOcean CI; see https://buildkite.com/clima/climaocean-ci/builds/1264#01918d21-30e8-4d9c-9ee8-a220eb16eb28/202-514

cc @simone-silvestri

**Comment by glwagner** [comment]
Shouldn't that be `target_times = target_fts.times` ?

**Comment by glwagner** [comment]
Can you run the function (produce a bug with code rather than merely by reading it)? Is there a test?

**Comment by navidcy** [comment]
[#3723](https://github.com/CliMA/Oceananigans.jl/pull/3723) seems to have deleted `target_times`

**Comment by glwagner** [comment]
Wouldn't the MWE be a one line function? We also need to test it here

**Comment by simone-silvestri** [comment]
#3733 introduces a very simple test for interpolation on field time series (testing trivial interpolation)
