### ISSUE TITLE
Should tests be run with `julia --check-bounds=yes`?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#3747]
The codebase makes extensive use of `@inbounds`, for good reason and usually pretty safely. But does it make sense to run the tests with `--check-bounds=yes` to catch any cases of out-of-bounds memory accesses?

Out of bounds accesses don't always produce an error and can silently lead to undefined behavior.

This may lead to slightly slower tests, although I doubt it would slow them down by much as most of the time is spend on compiling.

Might help with discovering certain issues sooner. Probably #3615 but maybe not #3320.

X-Ref: https://github.com/CliMA/Oceananigans.jl/pull/3682#issuecomment-2318319464

**Comment by simone-silvestri** [comment]
The tests should run with `--check-bounds=yes` automatically. I think that when calling `Pkg.test()` the testing environment should automatically activate order 0 optimization (-O0) and bounds checking `--check-bounds=yes`, but I cannot find a reference at the moment.

**Comment by ali-ramadhan** [comment]
Ah you're right! I forgot that `Pkg.test()` did that. I found the docs for it: https://pkgdocs.julialang.org/v1/api/#Pkg.test

I think the `-O0` flag is something Oceananigans.jl does on Buildkite though: https://github.com/CliMA/Oceananigans.jl/blob/main/.buildkite/pipeline.yml

**Comment by giordano** [comment]
> Ah you're right! I forgot that Pkg.test() did that. I found the docs for it: https://pkgdocs.julialang.org/v1/api/#Pkg.test

Note that [this behaviour will change in Julia v1.13](https://github.com/JuliaLang/Pkg.jl/blob/e192350baaa01afb467c6ae8986e1babd9c673d1/CHANGELOG.md?plain=1#L4).
