### ISSUE TITLE
`LagrangianParticle`s not working with `ImmersedGrid`s

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#3761]
I realize that https://github.com/CliMA/Oceananigans.jl/issues/3609 exists, but I think this is a different issue. The following MWE, which tries to advect `LagrangianParticle`s over an `ImmersedGrid` fails with this error:

```
ERROR: LoadError: MethodError: no method matching cpu__advect_particles!(::KernelAbstractions.CompilerMetadata{…}, ::StructArrays.StructVector{…}, ::Float64, ::ImmersedBoundaryGrid{…}, ::Int64, ::@NamedTuple{…})

Closest candidates are:
  cpu__advect_particles!(::Any, ::Any, ::Any, ::Oceananigans.Grids.AbstractUnderlyingGrid, ::Any, ::Any)
   @ Oceananigans none:0

Stacktrace:
  [1] __thread_run(tid::Int64, len::Int64, rem::Int64, obj::KernelAbstractions.Kernel{…}, ndrange::Nothing, iterspace::KernelAbstractions.NDIteration.NDRange{…}, args::Tuple{…}, dynamic::KernelAbstractions.NDIteration.NoDynamicCheck)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/60cqT/src/cpu.jl:144
  [2] __run(obj::KernelAbstractions.Kernel{…}, ndrange::Nothing, iterspace::KernelAbstractions.NDIteration.NDRange{…}, args::Tuple{…}, dynamic::KernelAbstractions.NDIteration.NoDynamicCheck, static_threads::Bool)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/60cqT/src/cpu.jl:111
  [3] (::KernelAbstractions.Kernel{…})(::StructArrays.StructVector{…}, ::Vararg{…}; ndrange::Nothing, workgroupsize::Nothing)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/60cqT/src/cpu.jl:46
  [4] (::KernelAbstractions.Kernel{…})(::StructArrays.StructVector{…}, ::Vararg{…})
```

This is the MWE:

```julia
using Oceananigans

grid_base = RectilinearGrid(size = (4, 4, 4), extent = (1,1,1))
GFB = GridFittedBottom((x, y) -> -1/2)
grid = ImmersedBoundaryGrid(grid_base, GFB)

n_particles = 3
x₀  = rand(n_particles)
y₀  = rand(n_particles)
z₀  = .-rand(n_particles)

lagrangian_particles = LagrangianParticles(x=x₀, y=y₀, z=z₀)

model = NonhydrostaticModel(; grid, particles=lagrangian_particles)
time_step!(model, 1)
```

I'm a bit confused, because, while the function `_advect_particles!()` doesn't seem to accept immersed grids given that it dispatches on `AbstractUnderlyingGrid`s:

https://github.com/CliMA/Oceananigans.jl/blob/3c95e7ee6772a2597e206ae35202500be1ef5b32/src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl#L152

Leading me to believe that this is just an un-implemented feature, the code in the function `advect_particle()` does take `ImmersedGrid`s into consideration:

https://github.com/CliMA/Oceananigans.jl/blob/3c95e7ee6772a2597e206ae35202500be1ef5b32/src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl#L135-L138

Is this just a typo in the `_advect_particles!()` signature, which should also work for `AbstractUnderlyingGrid`?

**Comment by simone-silvestri** [comment]
This looks very much like a bug. We have used particle tracking on immersed grids many times in the past. That kernel should work for both immersed and not-immersed grids, the fix should be simple. It looks like this feature is not tested, so
it would be nice to add a test, (something simple like a particle bouncing off a wall in a 1D domain with an immersed boundary compared to a Bounded domain).

@tomchor do you want (or have time) to tackle this?

**Comment by tomchor** [comment]
Sure! I'm open a PR soon
