### ISSUE TITLE
Why do we only build distributed `test_architectures` if `MPI.Initialized`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3879]
This seems a brittle:

https://github.com/CliMA/Oceananigans.jl/blob/9ffbee31bc5a2fa38dd93fa1594b94cddaebba8c/test/utils_for_runtests.jl#L34

some bug that caused MPI not to be initialized would cause the tests to be worthless but it might not be detected.

**Comment by simone-silvestri** [comment]
This should be fixed in #3880
