### ISSUE TITLE
The MPI we use in the distributed tests is not CUDA-aware

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#3897]
Somewhere between this commit 
https://buildkite.com/clima/oceananigans-distributed/builds/3113#01917ace-fe81-401d-ba21-467037e6aead
and main, we switched from using `libmpitrampoline.so` in the distributed tests to `libmpi.so` downloaded from the artifacts. 

Previously, the mpi trampoline was loading a CUDA-aware implementation of Open MPI, while the libmpi.so we use now is a 
MPICH implementation non CUDA-aware:
https://buildkite.com/clima/oceananigans-distributed/builds/4227#0192f70a-b947-4d38-bd1c-c2497a964de9

This makes our GPU distributed tests fail. 
I am wondering where this switch happened because I couldn't trace any changes to the code. @Sbozzolo, do you know if something changed in the `LocalPreferences.toml` in the Caltech cluster?

**Comment by glwagner** [comment]
And CUDA runtime wasn't found in that PR: https://buildkite.com/clima/oceananigans-distributed/builds/4038#0192c76f-d6ea-4e48-a7fd-f1b22df9f89f/189-1063

so we just need to look at the PR before that...

PS @Sbozzolo we realized there was a problem with the way we ran the tests that would allow the GPU tests to pass even if they didn't run on GPU

**Comment by glwagner** [comment]
Ok, I think this is the problematic PR: https://github.com/CliMA/Oceananigans.jl/pull/3783

**Comment by glwagner** [comment]
@Sbozzolo am I reading this right that ClimaAtmos does not use climacommon? 

https://github.com/CliMA/ClimaAtmos.jl/blob/a0e8612fd602ff33349e46ed34875ed8af45fd3a/.buildkite/gpu_pipeline/pipeline.yml#L4C55-L4C68

**Comment by glwagner** [comment]
There is something a little odd that we are using `2024_10_09`:

https://github.com/CliMA/Oceananigans.jl/blob/6c40d7e225c2127051b2703b9c62a8b18260e3a5/.buildkite/distributed/pipeline.yml#L4

But ClimaAtmos is on `2024_10_08` if I am reading this right

https://github.com/CliMA/ClimaAtmos.jl/blob/a0e8612fd602ff33349e46ed34875ed8af45fd3a/.buildkite/pipeline.yml#L4

**Comment by simone-silvestri** [comment]
I can try reintegrating a Manifest using julia 1.11 in #3880 to see if it makes a difference

**Comment by glwagner** [comment]
We dont' support 1.11 yet though so its not a long term solution...

**Comment by simone-silvestri** [comment]
Hmmm, ok I guess we probably have to revert to a previous version of climacommon

**Comment by Sbozzolo** [comment]
> @Sbozzolo am I reading this right that ClimaAtmos does not (always) use climacommon?
> 
> https://github.com/CliMA/ClimaAtmos.jl/blob/a0e8612fd602ff33349e46ed34875ed8af45fd3a/.buildkite/gpu_pipeline/pipeline.yml#L4C55-L4C68
> 
> EDIT I suspect these are unused in favor of https://github.com/CliMA/ClimaAtmos.jl/blob/main/.buildkite/pipeline.yml

That's a different machine.

`2024_10_09` is Julia 1.11, `2024_10_08` is Julia 1.10. Some of our repos moved to 1.11, ClimaAtmos is still on 1.10 for some issues in ClimaCore.

If you don't support 1.11, you should stay stay on _10_08.

**Comment by simone-silvestri** [comment]
I think we are also hitting this problem https://github.com/JuliaParallel/MPI.jl/issues/715
because it looks like the MPIPreferences are correctly loaded at the 
```julia
julia -O0 --project -e 'using Pkg; Pkg.instantiate()`
```
but then it loads a completely different MPI in the 
```julia
julia -O0 --project -e 'using Pkg; Pkg.test()`
```
step

**Comment by glwagner** [comment]
> I think we are also hitting this problem [JuliaParallel/MPI.jl#715](https://github.com/JuliaParallel/MPI.jl/issues/715) because it looks like the MPIPreferences are correctly loaded at the
> 
> ```julia
> julia -O0 --project -e 'using Pkg; Pkg.instantiate()`
> ```
> 
> but then it loads a completely different MPI in the
> 
> ```julia
> julia -O0 --project -e 'using Pkg; Pkg.test()`
> ```
> 
> step

Nice observation
