### ISSUE TITLE
Use default `reader_kw=nothing` to make `FieldTimeSeries` concretely typed

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3898]
The default is not a concrete type which may cause performance issues when `FieldTimeSeries` is used as boundary condition or forcing in a kernel:

https://github.com/CliMA/Oceananigans.jl/blob/6c40d7e225c2127051b2703b9c62a8b18260e3a5/src/OutputReaders/field_time_series.jl#L373

I suggest `nothing` as the default. Users can still change it if they want.

We could also use a `NamedTuple` instead of `Dict`.

@ali-ramadhan I think you maybe were not thinking that we use `FieldTimeSeries` in kernels and models now (not just for reading output)

**Comment by ali-ramadhan** [comment]
Ah good catch! Yeah `nothing` would be a good default. I can open a PR.

**Comment by glwagner** [comment]
It could be nice to support both `Dict` and `NamedTuple` --- I see uses for both. `Dict` for post processing and `NamedTuple` for forcing models. Might already work is `reader_kw` is splatted in fact.

**Comment by ali-ramadhan** [comment]
Hmmm, might have to default to `NamedTuple` as `nothing` cannot be splatted.

```julia
julia> f(x, y; kwargs...) = @show kwargs
f (generic function with 1 method)

julia> N = nothing

julia> f(1, 2; N...)
ERROR: MethodError: no method matching iterate(::Nothing)

Closest candidates are:
  iterate(::Base.AsyncGenerator, ::Base.AsyncGeneratorState)
   @ Base asyncmap.jl:362
  iterate(::Base.AsyncGenerator)
   @ Base asyncmap.jl:362
  iterate(::Core.MethodMatch, ::Int64)
   @ Base deprecated.jl:265
  ...

Stacktrace:
 [1] merge(a::@NamedTuple{}, itr::Nothing)
   @ Base ./namedtuple.jl:361
 [2] top-level scope
   @ REPL[12]:1
```

**Comment by glwagner** [comment]
> Hmmm, might have to default to `NamedTuple` as `nothing` cannot be splatted.
> 
> ```julia
> julia> f(x, y; kwargs...) = @show kwargs
> f (generic function with 1 method)
> 
> julia> N = nothing
> 
> julia> f(1, 2; N...)
> ERROR: MethodError: no method matching iterate(::Nothing)
> 
> Closest candidates are:
>   iterate(::Base.AsyncGenerator, ::Base.AsyncGeneratorState)
>    @ Base asyncmap.jl:362
>   iterate(::Base.AsyncGenerator)
>    @ Base asyncmap.jl:362
>   iterate(::Core.MethodMatch, ::Int64)
>    @ Base deprecated.jl:265
>   ...
> 
> Stacktrace:
>  [1] merge(a::@NamedTuple{}, itr::Nothing)
>    @ Base ./namedtuple.jl:361
>  [2] top-level scope
>    @ REPL[12]:1
> ```

That works
