### ISSUE TITLE
Plotting a reduced field on an `ImmersedBoundaryGrid` fills in NaNs incorrectly

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#3899]
MWE:
```julia
using Oceananigans
using GLMakie

grid = RectilinearGrid(size = (10, 10, 10), extent = (10, 10, 10))
bottom(x, y) = - rand() * 5 # Between -5 and 0
grid = ImmersedBoundaryGrid(grid, GridFittedBottom(bottom))

f1 = Field{Center, Center, Nothing}(grid)
f2 = Field{Center, Center, Nothing}(grid)
set!(f1, (x, y) -> rand())
set!(f2, (x, y) -> rand())

fig = Figure(); ax1 = Axis(fig[1, 1]); ax2 = Axis(fig[1, 2])
heatmap!(ax1, f1)
heatmap!(ax2, interior(f2, :, :, 1))
```
Produces:

<img width="1045" alt="Screenshot 2024-11-05 at 12 21 29 PM" src="https://github.com/user-attachments/assets/2840dd1b-edd2-4e74-a5f7-d0c378396e84">

It seems the field has been masked by checking the immersed condition at `k = 1`, which is not true for `Reduced` fields that need to check the whole direction to see if they are immersed. To mask the field to `NaN,` we should check that all the `k` indices at `i, j` are immersed. 

This is not a bug in the visualization but in the masking procedure that should do something different if a direction is nothing. I can create a PR for this; some computational efficiency considerations might be needed if this `mask_immersed_field!` is included in time-stepping loops.

**Comment by glwagner** [comment]
I believe there is also an issue with windowed fields but I'm not sure.
