### ISSUE TITLE
LaTeX not rendering in `boundary_conditions.md`

### ISSUE THREAD

**Issue by jbisits** [CliMA/Oceananigans.jl#3905]
The last equation in the [open](https://clima.github.io/OceananigansDocumentation/stable/numerical_implementation/boundary_conditions/#Open-boundary-conditions) boundary conditions documentation does not display. I think this is due to wrapping `begin{align} ... \end{align}` in `\begin{equation} ... \end{equation}`

https://github.com/CliMA/Oceananigans.jl/blob/6c40d7e225c2127051b2703b9c62a8b18260e3a5/docs/src/numerical_implementation/boundary_conditions.md?plain=1#L213-L221

Can either be fixed by `align` -> `aligned` or removing `\begin{equation} ... \end{equation}` (both options correctly render the equation in the markdown preview on github). I have opened a PR to make this change.

**Comment by glwagner** [comment]
thank you!
