### ISSUE TITLE
`minimum_xspacing` does not account for the immersed boundary

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#3954]
I think it's because of these definitions

https://github.com/CliMA/Oceananigans.jl/blob/504ab5da6c1cac49f0b5c364e58c117563bde0e6/src/ImmersedBoundaries/immersed_boundary_nodes.jl#L67-L69

This causes the CFL to be limited by possibly immersed nodes.
It is quite relevant on the `TripolarGrid` where nodes near the north poles are immersed with the spacings tending to zero.

I can open a PR to fix this.

**Comment by glwagner** [comment]
Nice find. @ali-ramadhan I'm not sure if this was bundled with some of the changes you made? Basically, spacings on an immersed grid are always in general different from the underlying grid. For example, with partial cells, the vertical grid spacing changes.

**Comment by glwagner** [comment]
Nice find. Also we should note that the immersed boundary grid can _change_ the spacings (in addition to the fact that we must omit immersed spacings). For example with partial cells the zspacings are different than on the underlying grid.

**Comment by glwagner** [comment]
cc @ali-ramadhan I'm not sure if this was bundled with other changes you made but a good thing to be aware of
