### ISSUE TITLE
Duplicate `ψspacing` and `Δψ`

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#3957]
At the moment we have a duplication of spacing functions: we have 
```julia
xspacing
yspacing
zspacing
```
and 
```julia
Δx
Δy
Δz
```

that appear to be doing the same thing. I think this is because the `Δ` versions are required for timestepping and the `spacing` functions are not used but defined because we have other spacings (such as `λspacing`) that we define but are not needed for timestepping.

I propose to remove all the `ψspacing` functions and keep the pointwise versions defined in the Operators module. We can add `Δλ` and `Δφ` for completeness in the Operators module if we want

**Comment by simone-silvestri** [comment]
I think these functions are defined in this way just to have the user interface allow abstract operations with metrics because we reserve the more user friendly metrics for
https://github.com/CliMA/Oceananigans.jl/blob/d289fed2d06e9530e23b60d8c421243cafb6a996/src/AbstractOperations/grid_metrics.jl#L67-L74

There is no need to define new types though. Functions themselves are unique types so we can remove completely all the `AbstractMetrics` and have the same exact behavior importing the metrics from `Operators`.

**Comment by ali-ramadhan** [comment]
Yeah I also noticed that the `*spacings` functions were defined in the `Grids` module, presumably because the `Grids` module needed to refer to them before they could properly be defined in the `Operators` module.

But the user-facing `*spacings` functions are actually defined in the `AbstractOperations` module since they rely on `KernelFunctionOperator`.

Also finding the definitions is not easy since they're generated via metaprogramming...

Is `*spacing` and `*spacings` supposed to be user-facing with `Δ*` being internal? I guess we could have exported user-facing `Δx`, etc. but maybe we didn't want to lose this very common variable name (or it would be too easy to conflict)?

**Comment by simone-silvestri** [comment]
I think the `Δ*` functions are supposed to be internal (as pointwise operations) but also allow usage in `AbstractOperations` such as:
```julia
f = CenterField(grid)
dz = f * Δz
```
In my opinion, we can remove the `*spacing` pointwise functions so as to unify the internals of the code with the user interface. However, if there is a will to keep the `*spacing` pointwise functions we can define them as 
```julia
*spacing(args...) = Δ*(args...)
```
in `Operators` module and export them.

**Comment by ali-ramadhan** [comment]
I do like the interface with `*node`, `*nodes`, `*spacing`, and `*spacings` so exporting `*spacing` might make for a more coherent user interface. Although internally it could just map to `Δ*` as you suggest.

Thinking about it a bit more, I also like that this wouldn't export `Δ*` functions so we can continue to use `Δx`, `Δy`, `Δz`, `Δλ`, and `Δφ` as variable names which is pretty common especially in scripts.

**Comment by glwagner** [comment]
This was intentional --- one is verbose the other is a mathematical symbol. We can eliminate one if you like.

**Comment by simone-silvestri** [comment]
I think we can keep both, but it is how it's implemented I think that is a bit awkward to maneuver around. 
If we use the `Δ*` versions everywhere inside the code, then export 
```julia
*spacing(args...) =  Δ*(args...)
```
it will simplify the internals leaving the user interface intact.

**Comment by glwagner** [comment]
> I guess, to be consistent, we should export xarea, yarea and zarea instead of Ax, Ay, and Az

Do users need areas for common use cases? This is entirely motivated by how we want user scripts to read.
