### ISSUE TITLE
Why are the prognostic fields deep-copied in the constructor for `HydrostaticFreeSurfaceModel`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#3967]
Doesn't this allocate unnecessary memory?

https://github.com/CliMA/Oceananigans.jl/blob/fe4123f92155f5086bce72e366843045606b4bf5/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L201

**Comment by glwagner** [comment]
@simone-silvestri

**Comment by simone-silvestri** [comment]
It is needed for the RK3 timestepper. I can move the deepcopy in the timestepper constructor to avoid the memory allocation when using an AB2

**Comment by glwagner** [comment]
Right, so its unnecessary for AB2 which is currently the default. Good also to note this is an additional downside of the RK3 scheme.
