### ISSUE TITLE
Unexpected FlatExtrapolationBoundaryCondition behaviour in validation script cylinder.jl

### ISSUE THREAD

**Issue by samlewin** [CliMA/Oceananigans.jl#3975]
I've been playing around with open outflow boundary conditions and noticed that the validation code for uniform flow past a cylinder no longer functions as intended (v0.94.3) [https://github.com/CliMA/Oceananigans.jl/blob/main/validation/open_boundaries/cylinder.jl](url).

The u boundary conditions are currently set as follows: https://github.com/CliMA/Oceananigans.jl/blame/fe4123f92155f5086bce72e366843045606b4bf5/validation/open_boundaries/cylinder.jl#L47-L48

I guess the implementation has changed since the example was written, since the initialized u velocity field is now forced to zero at the east boundary when it should be a uniform flow throughout:

![cylinderexample](https://github.com/user-attachments/assets/0f9d91cd-60aa-4d8a-ae5a-70096cd8907e)

Something similar to the oscillating cylinder flow example, like
 `u_boundaries = FieldBoundaryConditions(
                    east = FlatExtrapolationOpenBoundaryCondition(u, parameters = U, relaxation_timescale = 1),
                    west = FlatExtrapolationOpenBoundaryCondition(u, parameters = U, relaxation_timescale = 1))` 
seems to produce a reasonable looking flow. Is there still a way to implement the east boundary outflow without specifying a particular outflow profile, as was originally the case?

**Comment by jagoosw** [comment]
Hi @samlewin, 

Sorry about this! `FlatExtrapolation` is currently broken and being fixed in this PR https://github.com/CliMA/Oceananigans.jl/pull/3937 

I'll finish it up today so we can get it merged. I'm also working on a proper open boundary condition [here](https://github.com/CliMA/Oceananigans.jl/pull/3977) if you're interested.

**Comment by samlewin** [comment]
Ah, sorry I had missed that PR, thanks! Will keep an eye on the WIP you mentioned :)
