### ISSUE TITLE
Automatically adding labels to Makie's plots in Oceananigans

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#3998]
At the moment if I plot a `Field` using the Oceananigans' Makie extension I get something very minimal:

```julia
julia> grid = RectilinearGrid(size=(4, 4, 1), extent=(100, 100, 1))
4×4×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×1 halo
├── Periodic x ∈ [0.0, 100.0) regularly spaced with Δx=25.0
├── Periodic y ∈ [0.0, 100.0) regularly spaced with Δy=25.0
└── Bounded  z ∈ [-1.0, 0.0]  regularly spaced with Δz=1.0

julia> f = CenterField(grid)
4×4×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×4×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×1 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 10×10×3 OffsetArray(::Array{Float64, 3}, -2:7, -2:7, 0:2) with eltype Float64 with indices -2:7×-2:7×0:2
    └── max=0.0, min=0.0, mean=0.0

julia> heatmap(f)
```

![display](https://github.com/user-attachments/assets/0c68673d-3f6d-478d-976a-734173744f5e)

We have the information of which dimensions are being plotted, so I think we should automatically label the axes accordingly. I understand that this would need to extend the `heatmap()` function to do something that Makie's `heatmap()` doesn't do (add labels), but if the goal is to be user-friendly with this extension and take advantage of the extra information that `Field` provides us, I think this would help.

**Comment by glwagner** [comment]
`heatmap` can add labels:

```julia
heatmap(x, axis=(; xlabel="x", ylabel="y"))
```

Alternatively you can create the axis prior to plotting:

```julia
fig = Figure()
ax = Axis(fig[1, 1], xlabel="x", ylabel="y")
heatmap!(ax, f)
```

Are you proposing to automatically call the axis by their node names, eg "x, y, z" for RectilinearGrid?

**Comment by tomchor** [comment]
> Are you proposing to automatically call the axis by their node names, eg "x, y, z" for RectilinearGrid?

Yes, I should have been more clear. I also changed the issue's title for clarity. But yes, I think we should have reasonable default names. The idea is that, since we have that information from `Field`, why not use it automatically and save users some typing? Users could then overwrite this behavior by manually naming the axes like you demonstrated, of course, but I think that 99% of the time we'd be happy with the defaults.

**Comment by glwagner** [comment]
Agree this would be nice, at least for cases without units it is quick and easy. The thing we have to figure out is how to make it so the defaults do not collide with user-specific label names, since its critical that users can specify labels. I don't really agree with the 99% number, I think for cases that matter (eg papers etc) labels will be provided.

**Comment by glwagner** [comment]
So just to start investigating this a little bit, I think the key function for `heatmap(f)` is here:

https://github.com/CliMA/Oceananigans.jl/blob/87ecfedf9a045d7bb5733eb6be1dddf2f75200ec/ext/OceananigansMakieExt.jl#L28-L31

Possibly the axis labels are contained in `attributes` argument so I will look into that a little bit.

**Comment by tomchor** [comment]
Closed by https://github.com/CliMA/Oceananigans.jl/pull/4001
