### ISSUE TITLE
Use xticks to multiples of 60 or 30 for a domain that wraps around the globe in Makie extension

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#4024]
Here:

https://github.com/CliMA/Oceananigans.jl/blob/01cad9efb409f900e749bc6ea9a471dd921c73f7/ext/OceananigansMakieExt.jl#L55-L75

we could add an if statement to set the xticks to 0:60:360 if there is a domain that wraps around the globe.

How could we identify such a domain for all grids?

**Comment by glwagner** [comment]
> How could we identify such a domain for all grids?

The Makie extension only really supports `LatitudeLongitudeGrid` right now so that's all you have to worry about
