### ISSUE TITLE
Checkpointer fails if boundary condition is a CuArray

### ISSUE THREAD

**Issue by suyashbire1** [CliMA/Oceananigans.jl#420]
```julia
ERROR: LoadError: cannot write a pointer to JLD file
```

**Comment by glwagner** [comment]
Hmm... we'd have to convert this to an array, and then convert back for this to work automatically.

A simple fix to start could just be to avoid saving boundary conditions when they contain references to an array.

Is it possible to use `has_reference(CuArray, boundary_conditions)`?

**Comment by ali-ramadhan** [comment]
Closing as the `Checkpointer` no longer serializes boundary conditions as of PR #1082 so this shouldn't happen.
