### ISSUE TITLE
`HorizontalAverage` diagnostic leaves halo regions zeroed out

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#427]
Doesn't affect the model or time-stepping but the `HorizontalAverage` diagnostic zeros out halo regions prior to computing horizontal averages.

This could be a problem because currently output writers run after diagnostics so if post-processing scripts rely on the halo regions being there to e.g. calculate fluxes, then they won't be there.

**Comment by glwagner** [comment]
Are you suggesting that we refill the halo regions after computing the horizontal average?

**Comment by glwagner** [comment]
I see two ways to address this:

1. Allow `field_boundary_conditions` to be optionally specified to the `HorizontalAverage` constructor. In that case, we can call `fill_halo_regions` in `run_diagnostic(model, havg::HorizontalAverage)`.

2. Add boundary conditions to the `Field` type.

2 is hard may be ill-advised. 1 is annoying and requires more user input, but may be our only option at the moment.

One idea to facilitate using averages should we decide to do 1 is to create a constructor for `HorizontalAverage` in which the *name* of the field to be averaged is specified, along with `model`. In that case, we can extract both the correct field and its corresponding boundary conditions.

**Comment by ali-ramadhan** [comment]
Hmmm, I think in the long term we don't want to do any halo filling for computing averages. What we have is probably fine for now.

I think a permanent solution may be possible with the abstract operators from PR #463.

I guess I output the fields first before I compute and output horizontal averages, so this would only be an issue if I did horizontal averages first.

A slightly separate issue is that we zero out the vertical halos when doing horizontal averages, whereas you might be interested in these halo points. This has to be done in the horizontal for periodic halos.

**Comment by glwagner** [comment]
This was resolved by #1081
