### ISSUE TITLE
Implement Vreman SGS closure

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#440]
We should implement the Vreman subgrid closure described in

http://www.vremanresearch.nl/Vreman-PF2004-subgridmodel.pdf

cc @tapios

**Comment by tapios** [comment]
It's implemented here: https://github.com/climate-machine/CLIMA/blob/master/src/Atmos/Model/turbulence.jl

We should move this out of the 'Atmos' tree into some space for shared numerics for atmosphere, ocean, etc. @asraero @simonbyrne ?

**Comment by simonbyrne** [comment]
At the moment it is somewhat coupled to the AtmodModel, but we could try to unify them once the Ocean part is in place.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
