### ISSUE TITLE
Shared memory for GPU kernels

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#442]
At the GPU hackathon way back in June we learned that the `calculate_interior_source_terms` kernel was a bottleneck as each thread required a lot of registers. It could benefit greatly from shared memory to reduce register pressure and allow more threads to run at a time.

Some preliminary work has been done in PR https://github.com/climate-machine/Oceananigans.jl/pull/293

@vchuravy has an `@stencil` abstraction in development at https://github.com/vchuravy/GPUifyLoops.jl/pull/81

But would be good to implement plain shared memory without an abstraction and see how much of a performance boost we get, especially with LES closures.

**Comment by vchuravy** [comment]
> without an abstraction

The memory management and reuse for shared memory to be efficient without an abstraction is going to be hard. I based the stencil abstraction on this work: https://www.sciencedirect.com/science/article/pii/S016781911300094X?via%3Dihub

https://superfri.org/superfri/article/view/276 and https://onlinelibrary.wiley.com/doi/full/10.1002/cpe.4929 might provide up-to-date guidance.

**Comment by ali-ramadhan** [comment]
Thanks for the link!

Hmmm, maybe the better approach without be to try using the `@stencil` abstraction on a smaller problem like a Laplacian kernel and once that works efficiently, try the Oceananigans kernels again.

**Comment by vchuravy** [comment]
> abstraction on a smaller problem like a Laplacian kernel and once that works efficiently, try the Oceananigans kernels again.

Happy yo have a pair-programming session on that next week.

**Comment by sandreza** [comment]
I will close this issue for now

**Comment by glwagner** [comment]
@simone-silvestri might be interested in this
