### ISSUE TITLE
Example or test: advection of a square or Gaussian

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#481]
If anyone is interested in setting up an example or test for advection: you set up a 2D model with a square or Gaussian initial condition for temperature and a constant background velocity that advects the square around the domain.

We can use it to test our numerical methods and any advection schemes we implement in the future.

It would be something like this: https://www.youtube.com/watch?v=NkSVHpZV-xU

**Comment by johncmarshall54** [comment]
Suggest that we look in the mitgcm tutorials section that describes some
advection scheme tests.

**Comment by ali-ramadhan** [comment]
That's a good idea. I think these are the relevant sections from the MITgcm manual:
* [2.17 Linear advection schemes](http://mitgcm.org/public/r2_manual/latest/online_documents/node72.html)
* [2.17.4 Multi-dimensional advection](http://mitgcm.org/sealion/online_documents/node80.html)

Doing some 1D advection might also be good.

I opened this issue in case anyone is intersted in making a useful contribution as part of Hacktoberfest.

**Comment by glwagner** [comment]
Could make sense to close this due to #767

**Comment by ali-ramadhan** [comment]
I agree. We have an advection convergence test so this could be closed.

Producing some movies to show the behavior of different advection schemes would be cool and educational but already exists in many places and isn't within the scope of this issue.
