### ISSUE TITLE
Doctests

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#493]
We should test our docs:

https://juliadocs.github.io/Documenter.jl/stable/man/doctests/index.html

**Comment by ali-ramadhan** [comment]
True. Yeah I added a couple during PRs #410 and #474 but found it hard to test as most of our functions do not produce simple output, they usually modify the internal state of model.

For example, a `jldoctest` for the `RegularCartesianGrid` examples only really ends up testing that the `show(::RegularCartesianGrid)` function produces the expected output.

There are probably a few docstrings that will benefit from doctests, but the vast majority might not.

If we just don't want the docstring examples to go out of date we should probably use `@example` block that Documenter provides: https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@example-block-1

**Comment by glwagner** [comment]
It's still a good idea to test that the docs have recorded the behavior of `show` correctly, however. Developers may change `show` in the future but forget to / incorrectly update the docstring.

The `AbstractOperations` module adds a ton of functionality that can benefit from `REPL`-based experimentation.

We could experiment with returning a bit more information from functions to make `Oceananigans` more REPL friendly. For example, the `push!` operator defined in julia base returns the array that it modified --- even though unnecessary, this triggers `show` for that array at the REPL and shows the user that their array has a new element.

**Comment by glwagner** [comment]
Fixed by a number of PRs; I think most notably #799
