### ISSUE TITLE
Differing syntax for output writers

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#500]
The `JLD2OutputWriter` and the `Checkpointer` use the keyword `force=true` to indicate if existing files should be overwritten, while the `NetCDFOutputWriter` uses `clobber=true`.

`force=true` was chosen because this is used by the julia intrinsics `rm` and `mv`.

`overwrite_existing_files` could be clearer.

**Comment by suyashbire1** [comment]
`clobber` is quite common in the netcdf community and comes from its base C library (I think). `NCDatasets.jl` uses it but I am fine with `overwrite_existing_files`.

**Comment by glwagner** [comment]
It's probably ok if the syntax is slightly different.
