### ISSUE TITLE
Abstraction / Diagnostic for moving averages

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#501]
We need an abstraction for calculating moving averages. We could call this `TimeAverage`, `MovingTimeAverage`, or maybe `AveragedTimeSeries` --- or something else sensible. (Also, should `Timeseries` actually be `TimeSeries`?)

To do this I think we should build something that shares a lot of syntax with `TimeSeries`, which is defined via

```julia
struct TimeSeries{D, Ω, I, T, TT} <: AbstractDiagnostic
    diagnostic :: D
     frequency :: Ω
      interval :: I
          data :: T
          time :: Vector{TT}
end
```

The main challenge is designing syntax that isn't confusing. In `TimeSeries`, the `frequency` field refers to the frequency at which the time series is recorded. However, an `AveragedTimeSeries` diagnostic has two frequencies --- the frequency with which the raw data is acquired, and the frequency / interval at which the time-average is calculated.

Thus we want something more like

```julia
mutable struct AveragedTimeseries{D, Ω, I, X, T, TT} <: AbstractDiagnostic
    diagnostic :: D
    timeseries_frequency :: Ω # good name?
    averaging_interval :: I
    # other needed fields
    integrand :: X # something to store accumulated timeseries output
    data :: T # an "averaged timeseries", or a timeseries with moving average applied     
    time :: Vector{TT}
end
```

The reason the user might want to change the `timeseries_frequency` is if the object they are averaging is expensive to compute. 

Thoughts?

A related issue is how to output time series that are collected via diagnostics (obviously they can be saved brute force, but it'd be nice to have an interface). I'll open another issue to address this.

**Comment by glwagner** [comment]
I am now thinking that we want an abstraction for "windowed" averaging. In other words, there are two frequencies and one window size:

1. `sample_frequency`: the "fast" frequency of the raw field being averaged.
2. `diagnostic_frequency`: the "slow" frequency at which statistics are output / stored.
3. `averaging_window`: The size of the window over which statistics are collected and averaged.

Comments are extremely welcome on this feature and my proposed semantics. This feature is complex but crucial. A well-designed API is paramount. We probably needed this yesterday for the robust computation of turbulent fluxes and higher-order turbulence statistics, which are often noisy enough that we need more averaging than just a horizontal average at fixed times to compute robustly.

**Comment by ali-ramadhan** [comment]
`TimeAverage` suggests a single output to me, a time averaged scalar or vector, etc. kinda analogous to `HorizontalAverage`.

`MovingTimeAverage` suggests multiple outputs to me, i.e. that the output is also a time series but it has been smoothed. So maybe naming it e.g. `MovingAverageTimeSeries` would make it more analogous to `TimeSeries`?

I like the names you proposed in your second post: `sample_frequency` and `diagnostic_frequency`.

To be consistent with existing terminology, these are frequencies as in number of iterations, right? Will there also be `sample_interval` and `diagnostic_interval`? Those could be trickier to get completely right as the time step might not always coincide with a sampling or diagnostic interval unless you detect that you're going to overshoot a sampling interval and change the time step appropriately (I think OceanTurb.jl does this for time-stepping).

**Comment by glwagner** [comment]
Right, I see. I wonder if we could use a `MovingTimeAverage` that wraps around an `OutputWriter`. I think we probably want to avoid the complexity of weaving together objects in `.diagnostics` and objects in `.output_writers`.

**Comment by ali-ramadhan** [comment]
Hmmm, to avoid weaving together diagnostics and output writers maybe we can add a `Simulation` property called `align_diagnostics` or `align_output` that ensures that diagnostics and output writers are called at exact intervals, rather than when the model clock time exceeds an interval.

Then we can define a function like
```julia
time_to_next_action(time, diag) = diag.previous + diag.interval - time
...
if simulation.align_diagnostics
	for diag in simulation.diagnostics
	    Δτ = time_to_next_action(simulation.model.clock.time, diag)
	    Δτ < Δt && (Δt = Δτ)
	end
end
```
for diagnostics and output writers. That way no diagnostic or output writer will miss its target.

**Comment by glwagner** [comment]
Not even sure we need a boolean for switching it off. I think it makes sense to simply implement this. If its important to some user that the time step isn't changed, they will be using a constant time-step anyways and can calculate the `frequency` rather than using an interval. Eh?

**Comment by glwagner** [comment]
@BrodiePearson might be interested in this issue!

**Comment by glwagner** [comment]
Here's my latest thought.

I think the basic implementation of this feature, at least using the current abstraction system we have, will require both a diagnostic and an output writer.

The diagnostic will calculate a windowed time-average. The type could look something like

```julia
mutable struct WindowedTimeAverage{RT, FT, A, B} <: Diagnostic
    time_window :: FT
    time_interval :: FT
    window_start_time :: FT
    previous_interval_stop_time :: FT
    collecting :: Bool
    kernel :: A
    result :: B
    return_type :: RT
end
```

`time_to_run` would look like

```julia
function time_to_run(clock, wta::WindowedTimeAverage)
    if clock.time >= wta.previous_interval_stop_time + wta.time_interval - wta.time_window
        return true
    else
        return false
    end
end
```

Thus until `previous_interval_stop_time` is updated, `time_to_run` will return true within a time window.

Calling `run_diagnostic(windowed_time_average, model)` will accumulate the average. Here's an example using trapezoidal accumulation of the average:

```julia
get_kernel(kernel::Field, model) = data(field)

function get_kernel(kernel::AbstractAverage, model)
    run_diagnostic(kernel, model)
    return kernel.result
end

function run_diagnostic(windowed_time_average, model)

     current_window = model.clock.time - windowed_time_average.window_start_time

    # Manage beginning and ending averaging window
    if !(windowed_time_average.collecting)
         # Start averaging period by zeroing out result and accumulating the first data point in the timeseries
        windowed_time_average.result = get_kernel(wta.kernel, model) / 2
        windowed_time_average.collecting = true
        windowed_time_average.window_start_time = model.clock.time

    elseif current_window > windowed_time_average.time_window
        # Averaging period is complete. Accumulate final time point
        windowed_time_average.result .+= get_kernel(wta.kernel, model) / 2
        windowed_time_average.result ./= current_window

        # This will stop run_diagnostic from being called in the future
        wta.previous_interval_stop_time = model.clock.time - rem(model.clock.time, wta.time_interval)

        windowed_time_average.collecting = false
        
    else # Accumulate time series 
        windowed_time_average.result .+= get_kernel(wta.kernel, model)

    end

    return nothing        
end
```

With this algorithm, `collecting  == false` indicates that `result` represents an average (rather than an integral over `kernel` as it does when `collecting == true`). We can further define a callable object that can finalize averaging collection if currently occuring, or return the result if needed:

```julia
convert_result(wta) = wta.return_type(wta.result)
convert_result(wta::WindowedTimeAverage{<:Nothing) = wta.result

function (wta::WindowedTimeAverage)(model)
    if wta.collecting
        # throw error?
    else
        return convert_result(wta)
    end
end
```

To obtain output, the user would have to add both `WindowedTimeAverage` to the list of diagnostics, as well as an output writer that extracts output from `WindowedTimeAverage`.

Example usage is something like

```julia
U = HorizontalAverage(model.velocities.u)
V = HorizontalAverage(model.velocities.v)

Uavg = WindowedTimeAverage(U, time_interval=1hour, time_window=5minute)
Vavg = WindowedTimeAverage(V, time_interval=1hour, time_window=5minute)

push!(simulation.diagnostics, Uavg, Vavg)
simulation.output_writers[:time_and_horizontal_averages] = JLD2OutputWriter(model, (U=Uavg, V=Vavg), time_interval=1hour)
```

(Note, this is not current syntax for `JLD2OutputWriter` because #672 is not resolved yet.)

A few notes:

- We can also implement behavior such that an average is always returned when `wta(model)` is called, even if the `time_window` is not complete. However, this might be undesirable in that the output would not represent an average over the expected `time_window`.

- Because adding both a diagnostic and an output writer is a bit of a burden on users, we should think about how to streamline this process. One possibility is to introduce an API for adding output writers, such as a function `add_output_writer!(simulation, output_writer)` and ask users to call that, instead of manually adding the output writer to a dictionary. With such a function, we can ensure that the correct diagnostics are added to `simulation` when it is called for.

- The constructor for `WindowedTimeAverage` is also slightly non-trivial.

- There's the possibility of adding a `stride` so that the `kernel` being accumulated is evaluated less often during a time-window. This could be desirable if the kernel is expensive, and if it changes slowly across single time-steps for some reason.

**Comment by glwagner** [comment]
Hmm, rather than changing current API by requiring something like `add_output_writers!` we could infact overload `set_index!` for `OrderedDict(Symbol, AbstractOutputWriter)`. Then we can check whether the output writer includes a `WindowedTimeAverage` and, if so, add it as a diagnostic to `simulations.diagnostics`.

**Comment by ali-ramadhan** [comment]
This seems like a pretty nice design. I'm just concerned about mixing diagnostics with output writers.

I think we kinda agreed to merge diagnostics and output writers. Would doing so simplify the `WindowedTimeAverage`?

**Comment by glwagner** [comment]
Something we might need is a wrapper around output writers, along the lines of

```julia
struct TimeAveragedOutputWriter{O, WTA}
    output_writer :: O
    windowed_time_averages :: WTA
end

function TimeAveragedOutputWriter(OutputWriterName, model, kernels; time_window, return_type=Array, output_writer_kwargs...)
    # construct NamedTuple of WindowedTimeAverage s
    OutputWriter = Symbol(OutputWriterName, :OutputWriter)
    output_writer = OutputWriter(model, windowed_time_averages; output_writer_kwargs...)
    return TimeAveragedOutputWriter(output_writer, windowed_time_averages)
end
```

Then users will write

```julia
U = HorizontalAverage(model.velocities.u)
V = HorizontalAverage(model.velocities.v)

averages_writer = TimeAveragedOutputWriter(JLD2, model, (U=U, V=V), time_interval=1hour)
```

A WIP sketch of how we might manage "diagnostic dependencies" is by putting a line at the top of `run!(simulation)`:

```julia
function run!(sim)
    model = sim.model
    clock = model.clock

    [add_dependencies!(sim, out) for out in values(sim.output_writers)]
    
    # the rest of the code in run! 
  
    return nothing
end
```

where `add_dependencies!` is something like

```julia
add_dependencies!(sim, out) = nothing

get_dependency(output) = nothing
get_dependency(output::WindowedTimeAverage) = output

function add_dependencies!(sim, writer)
    for output in writer.outputs
        dependency = get_dependency(output)
        if !isnothing(dependency) && dependency !∈ sim.diagnostics.vals
            push!(sim.diagnostics, dependency) 
        end 
    end 

    return nothing
end
```

**Comment by glwagner** [comment]
As discussed elsewhere, it might be most convenient for users if an interface to applying moving averages is provided within the constructor for an output writer, rather than creating a wrapper object like `TimeAveragedOutputWriter`. An example of this would be

```julia
U = HorizontalAverage(model.velocities.u)
V = HorizontalAverage(model.velocities.v)

statistics_writer = JLD2OutputWriter(model, (U=U, V=V), time_interval=1hour, time_averaging_window=1minute)
```

The advantage of this syntax is that deciding to time-average output is as simple as adding a keyword argument to an existing output writer. This may be easier to user than previously proposed interfaces.
