### ISSUE TITLE
Method / abstraction for outputting timeseries

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#502]
We currently have a `Timeseries` diagnostic which accumulates the output of `some_function(model)` in a vector `data`. 

It'd be nice to have a simple way to save a timeseries to file. The problem is that we don't want to duplicate data; eg we want to periodically append data to an array that was previously saved in a file. 

Note that it is not possible to, for example, delete data within a `JLD2` file and replace it with something else:

https://github.com/JuliaIO/JLD2.jl/issues/38

@ali-ramadhan @suyashbire1 is this possible in NetCDF / `NCDatasets.jl`?

There are two other possibilities. One is to "unspool" the time series into a `group` within a `JLD2` file and write the data from each time stamp individually in the file. This allows new data to be appended to the group easily. I'm not sure how performant this would be, but perhaps its fine.

The second is to simply delete the old file and replace it with a new one with the updated time series. This is the hack that I've been using so far. The downside is that we have to save each timeseries in their own file.

Curious to hear if there are any other ideas for solving this problem.

**Comment by glwagner** [comment]
There seems to be very little downside to unspooling data when writing to a JLD2 file:

```julia
julia> a = rand(10^3);

julia> file = jldopen("test.jld2", "a+")
JLDFile /Users/gregorywagner/Projects/ColumnModelOptimizationProject.jl/les/test.jld2 (read/write)
  (no datasets)

julia> @time file["timeseries/a/1"] = a[1]
  0.000130 seconds (53 allocations: 3.656 KiB)
0.2596016305757207

julia> @time for i in 2:length(a); file["timeseries/a/$i"] = a[i]; end
  0.004707 seconds (31.48 k allocations: 1.754 MiB)

julia> file
JLDFile /Users/gregorywagner/Projects/ColumnModelOptimizationProject.jl/les/test.jld2 (read/write)
 └─📂 timeseries
    └─📂 a
       ├─🔢 1
       ├─🔢 2
       ├─🔢 3
       ├─🔢 4
       ├─🔢 5
       ├─🔢 6
       ├─🔢 7
       ├─🔢 8
       ├─🔢 9
       ├─🔢 10
       ├─🔢 11
       ├─🔢 12
       ├─🔢 13
       ├─🔢 14
       ├─🔢 15
       ├─🔢 16
       ├─🔢 17
       ├─🔢 18
       ├─🔢 19
       ├─🔢 20
       ├─🔢 21
       ├─🔢 22
       ├─🔢 23
       ├─🔢 24
       ├─🔢 25
       ├─🔢 26
       ├─🔢 27
       ├─🔢 28
[...]
```

**Comment by suyashbire1** [comment]
> @ali-ramadhan @suyashbire1 is this possible in NetCDF / NCDatasets.jl?

Yes, if I understand the issue correctly, this is what the NetCDFOutputwriter does currently. The file stays open and data is appended to it at each output iteration.

**Comment by glwagner** [comment]
When I say “timeseries”, I actually mean Timeseries, aka, Oceananigans.Diagnostics.Timeseries. Timeseries collects high frequency statistics and accumulates the result in an array rather than writing to disk at high frequency. 

But you’re right that there are other solutions to this problem, namely doing IO every time step. I think doing a lot of IO every time step could slow a simulation down unacceptably, however, so we will need this functionality eventually. But This is not an urgent issue.

**Comment by glwagner** [comment]
It's probably not worth implementing a special time-serises output type since it's cheap to write small data to disk often.
