### ISSUE TITLE
Forward Euler + 3rd order Runge-Kutta time-stepping (or integration with DifferentialEquations.jl)

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#506]
We need to implement a forward Euler time-stepping scheme, which is useful for testing if for nothing else.

We need also better and more stable time-steppers. One option is to implement by hand a 3rd-order low storage Runge Kutta scheme.

Another interesting avenue is to figure out how to integrate with `DifferentialEquations.jl`, which would give us access to a large number of new time-steppers (issue #391). However, we are unsure how this would couple with the our incoming GPU tridiagonal solvers for implicit time-stepping.

**Comment by johncmarshall54** [comment]
Greg, is this something to be be done now? Let's get what we have now
completed and out to the community, get feedback etc. Development will
continue but we need to engage users. John

**Comment by glwagner** [comment]
I’m having trouble time stepping some problems stably (mostly larger-scale problems I’ve experimented with recently) and our low-order time stepper may be the problem. New time steppers are easy, so a small amount of investment now could save us a lot of failed / slow simulations in the near future. Of course, this issue is just to spark discussion; I haven’t done any work yet. But I did not raise this issue because of an academic interest in time stepping. I suspect (but cannot prove) it may be having a tangible impact on our work right now.

**Comment by johncmarshall54** [comment]
Greg, are your large scale applications baroclinically unstable channels?
John

**Comment by glwagner** [comment]
I tried two problems in horizontally-periodic domains: a problem with circular wind stress (Beaufort-like) and an idealized Eady problem. 

These problems are also nominally hydrostatic and I'd also like to understand differences in numerical stability (if they exist) between non-hydrostatic and hydrostatic algorithms. This is also an easy modification to the code (though off topic for this issue). 

Perhaps we can discuss more offline and outline an efficient but also forward-looking strategy to achieve fast time-to-solution for these problems?
