### ISSUE TITLE
Lagrangian particle trajectories

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#511]
@johncmarshall54 suggested that it might be good to add support for simulating Lagrangian particle trajectories as the model time steps (online simulation) within the next few weeks.

We might want to output a time series of `(x, y, z, C...)` for each particle where `C...` represents additional properties we might want to track like temperature. So maybe we can attach a bunch of `Union{Field, AbstractOperation}` to the list of particle properties to save.

Perhaps we just need to keep track of particle location and advect them around, and the `TimeSeries` diagnostic can do the rest.

@gaelforget has done some (offline?) Lagrangian particle advection with [IndividualDisplacements.jl](https://github.com/gaelforget/IndividualDisplacements.jl) so maybe it makes sense to take some inspiration from there or rely on it?

cc @suyashbire1

**Comment by glwagner** [comment]
What parallelism strategy makes sense? One particle per thread? Do we use linear interpolation between velocity nodes or assume a constant velocity within each cell (nearest neighbor interpolation)?

Presumably `TimeSeries` makes sense for simple diagnosed particle "properties" and is the place to start.

Obtaining prognostic quantities within particles (like reacting chemical species with reaction rates that depend on ambient temperature) may be challenging and probably requires a careful design, especially because our time stepping is not very abstracted yet. If we are integrated with DifferentialEquations this job might get a bit easier...

**Comment by ali-ramadhan** [comment]
> What parallelism strategy makes sense? One particle per thread?

I think that makes sense, and we just queue up a huge amount of blocks like we already do with 3D kernels. Although if we use DifferentialEquations.jl then maybe we won't have to worry about parallelism here?

> Do we use linear interpolation between velocity nodes or assume a constant velocity within each cell (nearest neighbor interpolation)?

Yeah I'm not super sure what's a good approach here. We're on a regular Cartesian grid right now so maybe the difference isn't huge?

The [Parcels v2.0 paper by Delandmeter & van Sebille (2019)](https://www.geosci-model-dev.net/12/3571/2019/) discusses interpolation schemes for curvilinear C-grids using mostly Lagrange polynomials. But on a rectilinear grid like ours, it seems that it just reduces down to linear interpolation [see Eq. (3)].

Maybe a good question for @jm-c.

> Obtaining prognostic quantities within particles (like reacting chemical species with reaction rates that depend on ambient temperature) may be challenging and probably requires a careful design

Agreed. It may not even be clear what a good solution is. Apparently DARWIN has a similar problem I think where many plankton species may be uptaking nutrients so the question of what to do when a nutrient are depleted is hard to solve, especially as having nutrients go below zero can be bad for the model.

**Comment by glwagner** [comment]
> Agreed. It may not even be clear what a good solution is. Apparently DARWIN has a similar problem I think where many plankton species may be uptaking nutrients so the question of what to do when a nutrient are depleted is hard to solve, especially as having nutrients go below zero can be bad for the model.

Even more than details associated with particular challenging ODEs is the more fundamental software challenge of designing a flexible and useful system for user-specification of ODEs (special fields defined on sets of particles, each associated with an independent ODE that is coupled to the model solution) to be solved on particle trajectories. If we were integrated with DifferentialEquations.jl, this might not be all that hard, however.

**Comment by glwagner** [comment]
A few more thoughts:

1) It's probably simplest to use a native time-stepping schemes to advance particle trajectories. The third-order Runge-Kutta scheme seems like a fine choice.

2) I think it makes sense to launch one kernel to compute particle trajectories. "One kernel per thread" is a simple paradigm. Up to "one particle per grid point", we know this method will work well.

3) A few challenges that I see are: i) writing functions that linearly interpolate the velocity field to the particle location, and ii) dealing with boundaries. Enforcing boundary conditions, presumably, requries launching an additional kernel after a time-step is complete that checks the location of each particle and adjusts it if the particle location lies outside the domain. Enforcing periodic conditions presumably requires a cyclic shift of the particle location. I'm less sure how to deal with solid boundaries: perhaps reflecting the particle position (an elastic collision?) is a good model?

4) I think tackling the problem of determining particle trajectories is a big enough challenge for now. I think once we have the ability to interpolate fields to the particle location, it may not be difficult to introduce "auxiliary fields" for each particle, with user-specified RHS that depend on local tracer and velocity fields at the particle position.
