### ISSUE TITLE
Utilities for calculating buoyancy and density offline

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#516]
We need utilities for calculating buoyancy and density offline in a manner identical to the internal implementation.

cc @xiaozhour

**Comment by ali-ramadhan** [comment]
@glwagner Should we close this issue since PR #952 added a `BuoyancyField`?

Oceananigans.jl solves the Boussinesq equations so density is constant though.

**Comment by glwagner** [comment]
Oh ya. This is solved for sure by `BuoyancyField`.

Strictly speaking density is not constant. The Boussinesq equations are an asymptotic expansion around a constant density, in which only the first effect of variable density is retained (the gravitational acceleration such variations impart) and other effects are ignored.

Due to this reduction of the equations of motion, however, the density cannot always be reconstructed. More over it is linearly related to buoyancy via

```
density = reference_density (1 - b / g)
```

where `b = BuoyancyField(model)` and `g = buoyancy.gravitational_acceleration` when `buoyancy::SeawaterBuoyancy`.

I am fine to require users to use this formula, rather than providing an implementation of `DensityField` on top of `BuoyancyField`.
