### ISSUE TITLE
Each turbulence closure should probably have its own submodule

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#521]
They are complicated enough, and the TurbulenceClosures submodule huge enough, that namespace cleanliness and more orderly code would likely be quite helpful to code readability and interpretability.

When in doubt, *more modules*...

**Comment by ali-ramadhan** [comment]
Hmmm, seems like taking an approach like Documenter.jl where everything is a module makes sense for us. In which case, each turbulence closure will become its own submodule.

It could be part of a larger code refactoring to turn everything into a submodule.

**Comment by glwagner** [comment]
I think the `Documenter.jl` approach is appropriate for large codes. Requiring lots of modules makes the code clearer, protects namespaces, and enforces local import statements. Plus all the JuliaDocs packages are just really neat and useful.

PS: are there other nice julia codes that we might turn to for inspiration?

**Comment by navidcy** [comment]
Is this still ongoing?

**Comment by glwagner** [comment]
For sure --- `Oceananigans.TurbulenceClosures` is giant.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
