### ISSUE TITLE
`ReducedField` type

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#525]
We need a generic type that represents a reduction operation over a field that can be used both by the user to compute arbitrary reductions on the fly, and also for integration into `AbstractOperations`.

One way to accomplish this is to define a new field that looks something like

```julia
struct ReducedField{X, Y, Z, A, G, O, D, I} <: AbstractLocatedField{X, Y, Z, G}
    data :: A
    grid :: G
    reduction! :: O
    dims :: D
    input :: I
end
```

here `data` and `grid` are an array and grid similar to an ordinary `Field`, except that `data` is reduced along the tuple of dimensions in `dims`. The `input` is the 3D field / OffsetArray on which the reduction is performed. The function `reduction` performs the reduction; eg

```julia
U = ReducedField(mean, model.velocities.u, dims=(1, 2))
```

Returns an object `U` that represents the average of `model.velocities.u` over dims `(1, 2)` (x and y). We can also write wrappers / translators that allow dimensions to be referenced by name rather than number (integration with DimensionalData.jl would help in this respect). 

Computing a reduction would look something like

```julia
function compute!(reduced)
    zero_halo_regions!(parent(reduced.data), model.grid)
    reduced.reduction!(parent(reduced.data), parent(reduced.input), dims=reduced.dims)
    return nothing
end
```

Note that `mean` requires a special implementation since we have to use `sum!` followed by normalization. But this is not too onerous; we can dispatch on that scenario, and other scenarios that require special implementation not covered by the generic version above.

We can then integrate `ReducedField`s into abstract operations so we can calculate things like

```julia
u, v, w = model.velocities

U = ReducedField(mean, u, dims=(1, 2))
V = ReducedField(mean, v, dims=(1, 2))

turbulent_kinetic_energy = @at (Cell, Cell, Cell) ( (u - U)^2 + (v - V)^2 + w^2 ) / 2
```

This is a little tricky and requires the analysis of an operation tree to deduce which operations must be pre-computed. But this can be done in the constructor for `Computation` and is probably not too difficult (also, the topic of another issue).

**Comment by glwagner** [comment]
Another way to construct a reduced field could be

```julia
u, v, w = model.velocities

U = mean(u, dims=(1,))
```

**Comment by glwagner** [comment]
Picking up some of the discussion in #858 , we may want to adopt a more hierarchical approach to `ReducedField`s than suggested by the above comments. A more bare-bones implementation of a `ReducedField` would be

```julia
struct ReducedField{X, Y, Z, A, G, D} <: AbstractLocatedField{X, Y, Z, G}
    data :: A
    grid :: G
    dims :: D
end

@propagate_inbounds getindex(r::ReducedField{Nothing, Y, Z}, i, j, k) where {Y, Z} = r.data[j, k]
@propagate_inbounds getindex(r::ReducedField{X, Nothing, Z}, i, j, k) where {X, Z} = r.data[i, k]
@propagate_inbounds getindex(r::ReducedField{X, Y, Nothing}, i, j, k) where {X, Y} = r.data[i, j]

@propagate_inbounds getindex(r::ReducedField{X, Nothing, Nothing}, i, j, k) where X = r.data[i]
@propagate_inbounds getindex(r::ReducedField{Nothing, Y, Nothing}, i, j, k) where Y = r.data[j]
@propagate_inbounds getindex(r::ReducedField{Nothing, Nothing, Z}, i, j, k) where Z = r.data[k]
```

We can then provide further wrappers around `ReducedField` that specify the computation that generates `ReducedField.data`. We only support one of these right now (an average), so we'd only need something like `AveragedField`.

**Comment by ali-ramadhan** [comment]
Would `ReducedField` be part of the `AbstractOperations` module?

I think the bare-bones implementation makes a lot of sense for reduced averaged fields needed for computations like 
```julia
TKE = @at (Cell, Cell, Cell) ( (u - U)^2 + (v - V)^2 + w^2 ) / 2
```
which can then be built up as we encounter new things we want to compute (or reduce?).

I'm guessing you're suggesting the bare-bones implementation for something like `ReducedField(::Average, ...)`.

**Comment by glwagner** [comment]
I think it should be part of the `Fields` submodule.

`Average` would be a wrapper around `ReducedField`. It would have similar behavior, but with the added complication that it requires evaluation to be correct.
