### ISSUE TITLE
Equation numbering in docs broken

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#528]
<img width="833" alt="Screen Shot 2019-11-08 at 7 21 15 AM" src="https://user-images.githubusercontent.com/7112768/68426948-5608ea80-01fd-11ea-8ad5-ca959013d4df.png">

**Comment by johncmarshall54** [comment]
The Boussinesq approximation and the incompressibility assumption are not related to one-another i.e. the latter is not a consequence of the former. Two different things. One can have a non-Boussinesq, incompressible model, for example.
I suggest that the momentum equations be presented first without the complications of surface wave effects. We can deal with that later on in the documentation.
I will print out the documentation and make more detailed suggestions. Best not done here.

**Comment by navidcy** [comment]
> I suggest that the momentum equations be presented first without the complications of surface wave effects.

I'd also agree with this.

**Comment by ali-ramadhan** [comment]
Thanks for pointing this out @navidcy!

Indeed I think Documenter v0.24 defaults to KaTeX for the LaTeX backend which apparently does not support equation numbering yet (https://github.com/KaTeX/KaTeX/issues/350). We can switch back to the MathJax backend but then might lose other features (KaTeX is mostly faster but some of the rendering comes out weird). Worth thinking about...

**Comment by navidcy** [comment]
I'm resurfacing this ongoing issue...
