### ISSUE TITLE
Floating point equality checking in 2D Leith

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#535]
I noticed that `leith_enstrophy_diffusivity.jl` does a lot of floating point comparisons with zero when computing the components of the Redi tensor, e.g.
```julia
@inline function Redi_tensor_xz_fcc(i, j, k, grid::AbstractGrid{FT}, buoyancy, C) where FT
    bx = ∂x_b(i, j, k, grid, buoyancy, C)
    bz = ℑxzᶠᵃᶜ(i, j, k, grid, ∂z_b, buoyancy, C)
    return ifelse(bx == 0 && bz == 0, zero(FT), - bx / bz)
end
```

but if `bx` and `bz` are floats then might be a bad idea to check for `== 0` as they could be very small but not trigger the true branch. Even worse as we're dividing by `bz`.

Not sure if this is an issue but noticed it while refactoring for PR #529.

**Comment by ali-ramadhan** [comment]
@glwagner Is this a relevant issue or should we close it?

**Comment by glwagner** [comment]
Let's close. Comparison to 0 is potentially problematic for _physical_ reasons, but it is not a mathematical / floating point issue (the topic of this PR) since the operator `==` does the right thing.
