### ISSUE TITLE
Comments in pressure solvers are incorrect

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#593]
This line:

https://github.com/climate-machine/Oceananigans.jl/blob/72f1f5a770f3939c8bb16f29926f0bd776dc3756/src/Solvers/horizontally_periodic_pressure_solver.jl#L49

claims that we solve the Poisson equation using "Fourier coefficients", but this is incorrect. The wavenumbers used in the subsequent line are the eigenvalues of the discrete Poisson equation. The discrete analog of Fourier space is not used to solve the Poisson equation and the coefficients are not Fourier coefficients.

**Comment by ali-ramadhan** [comment]
True, I've been blindly copy-pasting ancient comments. It should be corrected and updated to match the description in the documentation.
