### ISSUE TITLE
Update README and fix broken links

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#608]
> The link to benchmarks.jl in the README.md file is broken.
>
> _Originally posted by @funsim in https://github.com/openjournals/joss-reviews/issues/2018#issuecomment-580286479_

**Comment by glwagner** [comment]
I think this is resolved?

**Comment by ali-ramadhan** [comment]
Haha so the link is dead again since we don't have a `benchmarks.jl` file. It should link to the documentation page on performance benchmarks.

I will open a PR.
