### ISSUE TITLE
Taylor-Green vortex verification experiment and convergence test

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#611]
> It seems that you have not performed a convergence test of your numerical model (based on analytical known solutions or manufactured solutions). I suggest that you add this (for instance based on the Taylor Green example)
>
> _Originally posted by @funsim in https://github.com/openjournals/joss-reviews/issues/2018#issuecomment-580286479_

**Comment by glwagner** [comment]
This was resolved by #767
