### ISSUE TITLE
Sugary syntax for boundary conditions

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#637]
> Thought: we provide the sugary syntax `.top` and `.bottom` for boundary conditions in `z`. Should we also provide east, west, south, and north, and avoid using `.left` and `.right` in the code for full clarity?
> 
> _Originally posted by @glwagner in https://github.com/climate-machine/Oceananigans.jl/pull/631#pullrequestreview-362963583_

**Comment by ali-ramadhan** [comment]
Sounds like a good idea. I think `setbc!` and `getbc` aren't fully tested so also worth adding some simple tests there.

Hmmm, so right now aliases like `top` and `bottom` are defined on coordinate boundary conditions but maybe we want to define them on field boundary conditions?

```julia
getbc(fbc::FieldBoundaryConditions, ::Val{:south}) = getfield(fbc.y, :left)
getbc(fbc::FieldBoundaryConditions, ::Val{:top})   = getfield(fbc.z, :right)
```

So accessing boundary conditions of a field `u` would look like
```julia
u.boundary_conditions.south  # Instead of u.boundary_conditions.y.south
u.boundary_conditions.top    # Instead of u.boundary_conditions.z.top
```

**Comment by glwagner** [comment]
@ali-ramadhan that's a cool idea. I hadn't thought of bypassing the individual coordinates altogether, but certainly that makes sense if we have unique names for all 6 boundaries.
