### ISSUE TITLE
Functions common to many submodules should be defined at top-level

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#641]
Just encountered this line:

https://github.com/climate-machine/Oceananigans.jl/blob/7b5cc97c18c8cd7dcc7a866312630df511735189/src/Fields/show_fields.jl#L2

I think we want to define `short_show` at the top, eg

```julia
function short_show end
```

somewhere in `Oceananigans.jl`.

We can then import into appropriate submodules from the top-level module.

**Comment by ali-ramadhan** [comment]
That's a good idea. Off the top of my head, I think `with_tracers` might be another candidate.

**Comment by ali-ramadhan** [comment]
Closing as I think we do this now but feel free to reopen if needed.

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/Oceananigans.jl#L135-L142
