### ISSUE TITLE
Don't require `simulation.progress` to subtype `Function`

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#642]
Ah interesting yeah a callable object would have worked as well. We should change
https://github.com/climate-machine/Oceananigans.jl/blob/7b5cc97c18c8cd7dcc7a866312630df511735189/src/Simulations.jl#L158
to 
```julia
iscallable(f) = !isempty(methods(f))
...
iscallable(sim.progress) && sim.progress(sim) 
```
See: https://discourse.julialang.org/t/how-to-determine-if-an-object-is-callable/2897

Although to have a callable object with parameters you'd have to define an new type right? (As in https://docs.julialang.org/en/v1/manual/methods/#Function-like-objects-1)

Either way, would be good to move the discussion to an issue on getting rid of `model.parameters`.

_Originally posted by @ali-ramadhan in https://github.com/climate-machine/Oceananigans.jl/pull/639#issuecomment-590149784_

**Comment by glwagner** [comment]
My question: what are we defending against with this check? If we only want to ensure that we don't throw an error is `progress===nothing`, we can simply check for that case and otherwise call `progress(sim)`.

**Comment by ali-ramadhan** [comment]
Yeah I guess we want to be able to call `progress(sim)`, doesn't matter what the type of `progress` is although most likely it'll be a `Function` or callable object. So I think we just want to blacklist anything we cannot call.

So I think your suggestion makes sense, something like:
```julia
iscallable(sim.progress) && sim.progress(sim) 
```
which will work if `progress = nothing` as
```julia
julia> iscallable(nothing)
false
```
and if the function signature is wrong a reasonable error will be thrown.

**Comment by glwagner** [comment]
Maybe just run `sim.progress(sim)` without any checking? If the user provided some `progress` object that can't be called, the line will error and provide a nice stack trace so that the user can figure out what went wrong.

**Comment by ali-ramadhan** [comment]
Sounds like a good idea. We'll just have to change the default from nothing to a function like `default_progress(args...) = nothing` or `nothingfunk(args...) = nothing`.
