### ISSUE TITLE
Outputting abstract operation computations to NetCDF (or disk) is cumbersome

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#653]
Working with @arnscheidt to output vorticity to NetCDF the code below is what we came up with but it feels quite cumbersome and required us to define some boilerplate `get_vorticity` function so it can all be accessed on demand by the `NetCDFOutputWriter`.

I wonder if we can improve the interface to allow users to easily pipe the output of abstract operations to disk. One approach might be to add explicit support for abstract operations to output writers. `NetCDFOutputWriter` already knows what to do if you give it a field or a function. We can tell it to do all this in the background if given an abstract operation like `vorticity_operation = ∂x(v) - ∂y(u)`.

```julia
u, v, w = model.velocities
vorticity_operation = ∂x(v) - ∂y(u)
ω = Field(Face, Face, Cell, model.architecture, model.grid, TracerBoundaryConditions(grid))
vorticity_computation = Computation(vorticity_operation, ω)

function get_vorticity(model)
    compute!(vorticity_computation)
    return Array(interior(ω))
end

fields = Dict(..., "vorticity" => get_vorticity)
```

**Comment by glwagner** [comment]
I believe the computation can be called, eg: vorticity_operation(model) does what get_vorticity does.

**Comment by glwagner** [comment]
This means you can pass the computation directly to the output writer, it will do the right thing.

**Comment by glwagner** [comment]
You can design convenience for the abstract operation too if you don’t care whether the user explicitly creates scratch space.

For convenience for large numbers of computations, I suggest a wrapper similar to FieldOutputs.

**Comment by glwagner** [comment]
Here's the function. It's usage should be documented!

https://github.com/climate-machine/Oceananigans.jl/blob/042f8cf12928b53b36cfa2a61a6b6a8ec7dc71bc/src/AbstractOperations/computations.jl#L53

**Comment by glwagner** [comment]
I think we can do this now @ali-ramadhan ?

**Comment by ali-ramadhan** [comment]
Ah yes! We can just pass `ComputedField` to any output writer now which is nice. Some extra boilerplate is needed if you want all the right metadata (output attributes) but perhaps this is unavoidable.
