### ISSUE TITLE
Value and gradient boundary conditions cannot be set with a stretched grid

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#667]
This line:

https://github.com/climate-machine/Oceananigans.jl/blob/3a8e4bf8f71873e8938474eda3ae1b86fbc77bfe/src/BoundaryConditions/apply_value_gradient_bcs.jl#L46

Assumes the grid is uniform, for example.

**Comment by glwagner** [comment]
What is the correct syntax? It looks like we have `ΔzF` and `ΔzC` but only `Δx` and `Δy`.

**Comment by ali-ramadhan** [comment]
Yeah pretty sure I fixed this in the (increasingly stale) `ar/integrate-vs-grid` branch but should double check what I did there.

**Comment by ali-ramadhan** [comment]
Closing as we now use functions so it should work on a stretched grid (but the dynamics might not be rigorously tested).

E.g. https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/BoundaryConditions/fill_halo_regions_value_gradient.jl#L87
