### ISSUE TITLE
Clearer names for `frequency` and `interval` for diagnostics

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#672]
> Hmmm, we're the ones that came up with this naming convention so maybe this suggests we should rename `frequency` and `interval` to `frequency_interval` and `time_interval` respectively?
> 
> If it confuses us, then maybe it'll massively confuse users.
> 
> _Originally posted by @ali-ramadhan in https://github.com/climate-machine/Oceananigans.jl/issues/661#issuecomment-592955701_

**Comment by glwagner** [comment]
I quite agree! Also agree they are both intervals. `iteration_interval` could be an alternative to `frequency_interval`. I like `time_interval`.

**Comment by glwagner** [comment]
@ali-ramadhan: votes on

* `iteration_interval`
* `time_interval`

?

**Comment by ali-ramadhan** [comment]
Yeah I'd vote for `iteration_interval` and `time_interval` as it matches the clock's property names.

**Comment by glwagner** [comment]
The same issues applies to `Simulation.progress_frequency`:

https://github.com/CliMA/Oceananigans.jl/blob/3f491e7444d06e1eada7f6a5f4e424affc2690c7/src/Simulations/simulation.jl#L57
