### ISSUE TITLE
Mixing plotting + animations + simulations produces bad examples

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#676]
Since PR #621 introduced simulations, the examples have actually started looking worse as plotting + animation + simulations are all mixed together.

Simplest example from https://climate-machine.github.io/Oceananigans.jl/stable/generated/one_dimensional_diffusion/
```julia
anim = @animate for i=1:100
    simulation.stop_iteration += 100
    run!(simulation)

    plot(interior(T)[1, 1, :], zC, linewidth=2, title=tracer_label(model),
         label="", xlabel="Tracer concentration", ylabel="z", xlims=(0, 1))
end

mp4(anim, "1d_diffusion.mp4", fps = 15) # hide
```

I don't think that's a clean use of the simulation class. I think we should add an output writer, run the simulation, then have a separate loop that reads the output and plots/animates it.

**Comment by glwagner** [comment]
Yeah, live-plotting was always a bit of a suspect strategy in general. I think adding an output writer is a great idea. 

Would be pretty neat also to have the ability to export snapshots from the interior of a running `Simulation`, somehow (basically, more descriptive simulation logging) --- some kind of callback function? In theory I suppose such a function could be integrated with `progress`.

**Comment by EavenW** [comment]
This would help greatly, as the process for generating the output files has altered a lot in the last few updates.

**Comment by glwagner** [comment]
Looks like this issue is partially resolved (`langmuir_turbulence.jl`, `one_dimensional_diffusion.jl`, and `two_dimensional_turbulence.jl` all use post-processing to create animations). 

We still need to bring `internal_wave.jl`, `ocean_convection_with_plankton.jl`, `ocean_wind_mixing_and_convection.jl`, and `eady_turbulence.jl` into the second half of 2020.
