### ISSUE TITLE
Support for a full equation of state for seawater (TEOS-10?)

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#692]
@johncmarshall54 has suggested we switch to a full equation of state for seawater for LESbrary simulations as temperature and salinity profiles from state estimates may not be statically stable in Oceananigans when using a linear equation of state. The Roquet et al. (2015a) idealized nonlinear equation of state should be better. Ideally we would use the same equation of state as ECCO/SOSE I think, but TEOS-10 should be what we aim for I suppose.

I think we have a couple of options:
1. There's a Julia wrapper for the TEOS-10 C library but this probably won't work on the GPU: https://github.com/ax1ine/GSW.jl
2. A 6+52-term polynomial approximation to TEOS-10, accurate to ~0.1% and suitable for Boussinesq models, from Roquet et al. (2015b). We can code up a pure Julia version as there already exist Python, MATLAB, and Fortran implementations here: https://github.com/fabien-roquet/polyTEOS (Thank you @fabien-roquet!)

In implementing a pure Julia TEOS-10 equation of state we should make sure it can be shared between Oceananigans and CliMA Ocean (cc @blallen).

cc @jm-c @christophernhill @glwagner @rafferrari who might have suggestions or comments.

@leios Do you think evaluating a 52-term polynomial at every grid point will be problematic on the GPU? I imagine GPUs should be fast at evaluating polynomials but maybe we have to be smart about storing the coefficients in memory?

References:
1. Roquet et al. (2015a), "Defining a Simplified Yet “Realistic” Equation of State for Seawater", DOI: https://doi.org/10.1175/JPO-D-15-0080.1
2. Roquet et al. (2015b), "Accurate polynomial expressions for the density and specific volume of seawater using the TEOS-10 standard", DOI: https://doi.org/10.1016/j.ocemod.2015.04.002

**Comment by glwagner** [comment]
I also think it’s a good idea to use a full equation of state for all simulations sooner rather than later. It’s simpler: we won’t have to report constants of linearization everywhere. And setting up simulations will be easier.

I’ll defer to the modelers for whether Roquet’s approximation is an acceptable model for TEOS-10.

This package is relevant and we should consider contributing to it rather than implementing an equation of state somewhere in the Clima ecosystem:

https://github.com/gher-ulg/PhysOcean.jl

**Comment by blallen** [comment]
> In implementing a pure Julia TEOS-10 equation of state we should make sure it can be shared between Oceananigans and CliMA Ocean (cc @blallen).

:100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: :100: 

> This package is relevant and we should consider contributing to it rather than implementing an equation of state somewhere in the Clima ecosystem:
> 
> https://github.com/gher-ulg/PhysOcean.jl

:sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: :sunglasses: 

Whatever we do should be shared between Oceananigans and Clima. Either a custom implementation or using the `PhysOcean.jl` package is fine by me.

**Comment by rafferrari** [comment]
The  Roquet’s approximation is perfectly sufficient for Oceananigans, because it will never be used for global calculations where local approximations are an issue. However I agree with everybody else that it would be best to use the same EOS in Ocenanigans and Climate_Ocean. in that case we should adopt TEOS-10. Be warned that it is quite inefficient through. So we may be hit performance-wise. Hard to tell without trying.

Raffaele

**Comment by johncmarshall54** [comment]
What does J-M think?
John

**Comment by ali-ramadhan** [comment]
> What does J-M think?

Talked to @jm-c earlier today who agreed that the Roquet et al. (2015b) 52-term polynomial approximation to TEOS-10 is a good choice.

Although he did point out that ECCO and SOSE are probably using an older pre-TEOS-10 equation of state (from 1995 or 2003 based on the EOS-80 but for potential temperature I think?).

**Comment by ali-ramadhan** [comment]
> The  Roquet’s approximation is perfectly sufficient for Oceananigans, because it will never be used for global calculations where local approximations are an issue. However I agree with everybody else that it would be best to use the same EOS in Ocenanigans and Climate_Ocean. in that case we should adopt TEOS-10. Be warned that it is quite inefficient through. So we may be hit performance-wise. Hard to tell without trying.

Thanks for the feedback @rafferrari. I talked to @leios earlier today and we think it shouldn't be a problem on the GPU. It's just straight up number crunching so it might benefit from being run on a GPU. But we can make sure by doing a quick benchmark.

**Comment by jm-c** [comment]
Ali,

This is a correct transcript of what I said earlier.

Cheers,
Jean-Michel

**Comment by glwagner** [comment]
This is resolved as of v0.30.0!
