### ISSUE TITLE
Documentation of vertically-stretched grid notation

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#696]
I think the definitions of `ΔzF` and `ΔzC` should be documented and commented on in the code in `src/Operators/areas_and_volumes.jl` and `src/Grids/vertically_stretched_cartesian_grid.jl`, and probably also mentioned in the docstring for the vertically stretched grid.

In particular, I am not sure if `ΔzF` yields the delta *between* cell faces, or is *defined* at cell faces (and therefore gives the delta between cell centers) --- or some subtle permutation thereupon.

**Comment by glwagner** [comment]
Ok, this function:

https://github.com/climate-machine/Oceananigans.jl/blob/4ad7e93f6ea9e715ca89ae2c1129f258430df656/src/Grids/grid_utils.jl#L97

Makes clear that `ΔzF` is the delta between faces. Let's document this.

**Comment by ali-ramadhan** [comment]
Good catch. This should be made very clear as it has confused us in the past...

I'll make sure to address this issue on the (increasingly stale =/) `ar/integrate-vs-grid` branch...

**Comment by ali-ramadhan** [comment]
Closing as this notation is old and this issue has perhaps been superseded by #1471.
