### ISSUE TITLE
Simulation does not stop at stop_iteration, in general

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#702]
This only works, in general, if `progress_frequency=1`. `Simulation` should always stop at the specified iteration or time, regardless of `progress_frequency`.

**Comment by ali-ramadhan** [comment]
Yeah... I'll put in a quick PR.

**Comment by ali-ramadhan** [comment]
Not sure when this was resolved by definitely by or before PR #1213.
