### ISSUE TITLE
Tests for 'show' methods

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#705]
Hmmm, yeah one issue is that we don't actually test `show` methods. Perhaps it would be good to add a bunch of `show` tests which would also increase code coverage.

_Originally posted by @ali-ramadhan in https://github.com/climate-machine/Oceananigans.jl/issues/700#issuecomment-599480673_

**Comment by navidcy** [comment]
I believe there are some tests for `show()` overloads now.

**Comment by glwagner** [comment]
Let's close --- this is open-ended.
