### ISSUE TITLE
CPU status in README banner does not print results of tests on master

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#712]
The CPU status in the README currently states that a build is erroring: 

<img width="995" alt="image" src="https://user-images.githubusercontent.com/15271942/77115376-96c30c80-6a04-11ea-95dc-c94f17dd09d7.png">

However, [clicking on the banner](https://travis-ci.com/climate-machine/Oceananigans.jl) shows that this result does not correspond to `master`:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/15271942/77115429-ae01fa00-6a04-11ea-82fd-855fe9534062.png">

but instead to the branch `glw/forced-flow-verification`. Is this what is intended?

**Comment by navidcy** [comment]
after updating the URLs (#761), I see the status of the master branch on travis-ci.com

**Comment by glwagner** [comment]
Thanks for catching this @navidcy !
