### ISSUE TITLE
Abstract operations `compute_kinetic_energy` test fails with CUDA error

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#732]
In PR #715 (commit https://github.com/climate-machine/Oceananigans.jl/pull/715/commits/df22124af635970f9f46e9706c6b8694fcc921da) I skipped the kinetic energy multiary test as it was giving some weird CUDA error:

```
 Multiary computations [Float64, GPU]: Error During Test at /builds/JuliaGPU/Oceananigans-jl/test/test_abstract_operations.jl:399
  Test threw exception
  Expression: compute_kinetic_energy(model)
  CUDA error: device kernel image is invalid (code 200, ERROR_INVALID_IMAGE)
```

We should revisit this issue when we can. It's weird because the test used to work...

Build log for more information: https://gitlab.com/JuliaGPU/Oceananigans-jl/-/jobs/510398403

**Comment by glwagner** [comment]
Are we still skipping this test?

**Comment by ali-ramadhan** [comment]
It's currently an operational test so I will close this issue: https://github.com/CliMA/Oceananigans.jl/blob/c7a729012d89509f446f609a992f50ee03642a86/test/test_abstract_operations.jl#L399

`git blame` shows that it was enabled and fixed by PR https://github.com/CliMA/Oceananigans.jl/pull/757.
