### ISSUE TITLE
Advection schemes: a model property or field property?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#77]
We want to be able to switch between 2nd and 4th order tracer advection schemes.

**Comment by glwagner** [comment]
Advection scheme be handled with multiple dispatch once higher abstractions are allowed in kernels (once the `isbitstype` problem is solved)? For example, the advection scheme could be a type parameter of `Model`.

**Comment by ali-ramadhan** [comment]
Reviving this ancient issue to propose we make the `advection_scheme` a property of the field as we may want different advection schemes for different tracers, or different schemes for momentum and tracers.

Storing all the advection schemes in some `model.advection_schemes` will probably be messy and bring us back to a situation like PR #631.

Agreed that advection schemes should be simple types that we dispatch on.

@glwagner What do you think?

**Comment by glwagner** [comment]
Well, let's discuss. I'm going to argue that `advection_scheme` doesn't belong in `Field`. Many fields are not advected; plus I think conceptually you can apply different advection schemes to the same field. This thought experiment implies that `advection` is orthogonal to `field`. 

Other field specific properties are not stored in `Field` --- for example, `.forcing` and the closure diffusivities, so `advection` wouldn't be the first field-specific property to exist outside of `Field`. I don't think all field-specific items belong in `Field`.

Eventually we'd also want to consider swappable differencing schemes for other terms in the equations, like diffusion, hyper-diffusion, etc... (?) Collecting these differencing schemes in `Field` might get unwieldy and harder to maintain / update.

**Comment by ali-ramadhan** [comment]
Hmmm, based on your comment [https://github.com/climate-machine/Oceananigans.jl/issues/695#issuecomment-597398151] I agree that not all fields are advected and that the advection scheme is part of the numerical methods.

I see that it could get messy if the advection scheme becomes a field property, because for a lot of fields (anything that's not a velocity or tracer) should really get the `Nothing` advection scheme.

I guess I would advocate for putting the advection scheme wherever it makes the code cleaner. `model.advection_scheme` seems to be the best choice for that. Perhaps it won't be as bad as `model.boundary_conditions` as advection schemes are (probably mostly) singleton types.

**Comment by glwagner** [comment]
I think if you want a more field-democratic design then we should think about having a more hierarchical API. For example, you could define an Equation type that stores equation info for each field. Then there is a closure for each field independently, a forcing for each field independently, etc. the equation for a model is then constructed from a tuple of equations for each field.

**Comment by glwagner** [comment]
Resolved by #815
