### ISSUE TITLE
[Documentation] Why use bit.ly link in documenation?

### ISSUE THREAD

**Issue by freemin7** [CliMA/Oceananigans.jl#773]
I wouldn't call the link it points to ugly and i generally distrust link shorteners.

**Comment by glwagner** [comment]
I think the link shortener was created to share the documentation link in other contexts where brevity matters. I agree its less useful here. Why should we distrust link shorteners?

**Comment by ali-ramadhan** [comment]
I think link shorteners are frequently used to hide malicious links but I wouldn't expect to encounter one on GitHub.

@freemin7 Would something like http://bit.ly/OceananigansDocumentation look more trustworthy?

I don't mind going back to the original link (https://clima.github.io/Oceananigans.jl/stable/ so it's a bit shorter now) although it's too long for GitHub so they add dots (...) and you can't see the full URL but you do see a link to github.io which is trustworthy.

Another potential reason to use bitly is you can track number of clicks as a function of time and location, but we don't really need that info, it's more out of curiosity.

**Comment by ali-ramadhan** [comment]
Just changed it back to the actual URL: https://clima.github.io/Oceananigans.jl/stable/

**Comment by freemin7** [comment]
Link shortener are commercial entities which can either go under any time, can maliciously tamper with the link or make money by tracking people who click the link.

```When You Interact With a Bitly Link
Bitly automatically collects personal information about the interaction (such as clicks or views) with every Bitly Link created through the Services (either our bit.ly links or one of our branded domains) on a third-party website. This information includes, but is not limited to: (i) the IP address and location derived from the IP address; (ii) the referring websites or services; (iii) the time and date of each access; (iv) device settings, such as browser type, operating system, and language; (v) cookies, as described below, and mobile advertising identifiers and (v) information about sharing of the Bitly Link on Third Party Services such as Twitter and Facebook (collectively, “Bitly Link Metrics”).  As described in this policy, we use Bitly Link Metrics to provide the Services, to understand and analyze how our Services are used and to identify trends, and to detect, deter and prevent malicious, fraudulent or unlawful activity. Please see the “Information We May Share” section of this Privacy Policy for a description of how we may share information we collect when you create, view or interact with Bitly Links.```

**Comment by ali-ramadhan** [comment]
Thanks for bringing this up @freemin7. Certainly it's not good if our links collect data for bitly.

I think we only used the bitly link in one place which we changed back to the actual URL so I'm going to close this issue now.
