### ISSUE TITLE
Validation test: Abernathey et al 2011

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#774]
A nice validation test for channels might be Abernathey et al 2011:

https://journals.ametsoc.org/jpo/article/41/12/2261/11254/The-Dependence-of-Southern-Ocean-Meridional

**Comment by glwagner** [comment]
@sandreza how close are we to having this?

**Comment by sandreza** [comment]
I think it's just a few modifications of the existing script in https://github.com/sandreza/Mesoscale/blob/master/oceananigans_scripts/hybrid.jl

In particular, the northern wall relaxation needs to change, the sponge layer, and a few of the model constants

**Comment by sandreza** [comment]
Oh and the surface forcing

**Comment by glwagner** [comment]
We have this now.
