### ISSUE TITLE
Return of the multiple of 16 bug

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#780]
@sandreza and I found that you still need `grid.Nx` and `grid.Ny` to be multiple of 16 on a GPU otherwise GPU kernels miss the last 0-15 grid points. Was so sure we fixed this quite a while back but can't find the PR right now.

**Comment by glwagner** [comment]
I don't think it was fixed:

https://github.com/CliMA/Oceananigans.jl/blob/f18daed6d6a1c7ad424a9774081d852100f012d2/src/TimeSteppers/time_stepping_kernels.jl#L20

However, support was added for 2D models on the GPU...

**Comment by ali-ramadhan** [comment]
Right I think the problem was that we were computing the blocks with `floor`: https://github.com/CliMA/Oceananigans.jl/blob/f18daed6d6a1c7ad424a9774081d852100f012d2/src/TimeSteppers/time_stepping_kernels.jl#L21

So I think this issue has been fixed in PR #805 but I'll update one of the time stepping tests to act on a grid of size `(13, 17, 19)` just to make sure.
