### ISSUE TITLE
Need to update `ParameterizedForcing` constructor

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#785]
https://github.com/CliMA/Oceananigans.jl/blob/8e3c27504be68ca06bacc7502cd6095ae390f8c6/src/Forcing/parameterized_forcing.jl#L16

Docstring example doesn't work as `parameters` isn't an accepted kwarg.

**Comment by glwagner** [comment]
Fixed by https://github.com/CliMA/Oceananigans.jl/commit/8a3793554c52a18d4fe9d388370fba9ddee06191
