### ISSUE TITLE
Movie missing in Langmuir turbulence example in docs

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#791]
I don't see the movie in [this example](https://clima.github.io/Oceananigans.jl/latest/generated/langmuir_turbulence/).

**Comment by ali-ramadhan** [comment]
Ah, thanks for catching this!

**Comment by ali-ramadhan** [comment]
Looks like the movie is up now: https://clima.github.io/Oceananigans.jl/latest/generated/langmuir_turbulence/

Thanks again @navidcy!
