### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package CuArrays

### ISSUE THREAD

**Issue by raphaelouillon** [CliMA/Oceananigans.jl#796]
Hi all, I recently switched from using v0.30.0 to using the latest version of the master branch, and I am now unable to add the CuArrays package, as it seems to clash with some of the packages used by Oceananigans. Has anyone else experienced this? I was able to reproduce this issue on two computers. When reverting back to v0.30.0, I have no such problem and can add CuArrays without packages clashing. Thanks for letting me know if you get the same issue!

Full error message suggest that Adapt, GPUArrays, CUDA and NNlib are clashing with CuArrays but I am a beginner at Julia so not sure I interpret the error correctly. I tried removing Oceananigans and all dependencies, installing CuArrays first and then adding Oceananigans, but I get the same problem doing things in that order.

```
ERROR: Unsatisfiable requirements detected for package CuArrays [3a865a2d]:
 CuArrays [3a865a2d] log:
 ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2]
 ├─restricted by compatibility requirements with Adapt [79e6a3ab] to versions: [0.2.1, 0.3.0] or uninstalled, leaving only versions: [0.2.1, 0.3.0]
 │ └─Adapt [79e6a3ab] log:
 │   ├─possible versions are: [0.3.0-0.3.1, 0.4.0-0.4.2, 1.0.0-1.0.1, 1.1.0, 2.0.0-2.0.2] or uninstalled
 │   └─restricted to versions 2 by Oceananigans [9e8cae18], leaving only versions 2.0.0-2.0.2
 │     └─Oceananigans [9e8cae18] log:
 │       ├─possible versions are: 0.30.0 or uninstalled
 │       └─Oceananigans [9e8cae18] is fixed to version 0.30.0
 ├─restricted by compatibility requirements with GPUArrays [0c68f7d7] to versions: 0.2.1 or uninstalled, leaving only versions: 0.2.1
 │ └─GPUArrays [0c68f7d7] log:
 │   ├─possible versions are: [0.3.0-0.3.4, 0.4.0-0.4.2, 0.5.0, 0.6.0-0.6.1, 0.7.0-0.7.2, 1.0.0-1.0.4, 2.0.0-2.0.1, 3.0.0-3.0.1, 3.1.0, 3.2.0, 3.3.0, 3.4.0-3.4.1, 4.0.0] or uninstalled
 │   └─restricted by compatibility requirements with CUDA [052768ef] to versions: 4.0.0
 │     └─CUDA [052768ef] log:
 │       ├─possible versions are: [0.1.0, 1.0.0-1.0.2, 1.1.0] or uninstalled
 │       └─restricted to versions 1 by Oceananigans [9e8cae18], leaving only versions [1.0.0-1.0.2, 1.1.0]
 │         └─Oceananigans [9e8cae18] log: see above
 └─restricted by compatibility requirements with NNlib [872c559c] to versions: [1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled — no versions left
   └─NNlib [872c559c] log:
     ├─possible versions are: [0.3.2, 0.4.0-0.4.3, 0.5.0, 0.6.0-0.6.6, 0.7.0-0.7.3] or uninstalled
     └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.6.5-0.6.6, 0.7.0-0.7.3]
       └─CUDA [052768ef] log: see above
```

**Comment by ali-ramadhan** [comment]
Thanks for opening this @raphaelouillon! Yeah it's a little confusing. So Oceananigans v0.30.0 (latest release) depends on the old packages CUDAnative.jl, CuArrays.jl, etc. but the master branch depends on CUDA.jl.

With CUDA.jl the other packages are all deprecated and can't be used as all CUDA functionality comes from CUDA.jl. The older repositories like CuArrays.jl now have deprecation warnings: https://github.com/JuliaGPU/CuArrays.jl

So I guess any functionality you need from CuArrays.jl should be available through CUDA.jl.

Let us know if you hit any issues with CUDA.jl though and if you need help figuring anything out.

**Comment by raphaelouillon** [comment]
Thanks a lot @ali-ramadhan. When using CUDA with the master branch am running into what I believe the be the same issue as @sandreza (https://github.com/CliMA/Oceananigans.jl/issues/784). I was able to run on GPU with v0.30.0 however.

**Comment by glwagner** [comment]
@raphaelouillon, resolving that issue requires switching over to `KernelAbstractions.jl` as a backend rather than `GPUifyLoops.jl`. It's not trivial but is our main priority right now. Once that is done, we'll release 0.31.0.

**Comment by glwagner** [comment]
@raphaelouillon we are about to release 0.32.0 which may resolve this issue. Can you let us know if it does?

**Comment by raphaelouillon** [comment]
@glwagner thanks very much, just tested with 0.32.0 and the issue is resolved.
