### ISSUE TITLE
Travis can't deploy docs

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#808]
Seems like there is some issue with SSH deploy keys and travis can't deploy the docs to [OceananigansDocumentation](https://github.com/CliMA/OceananigansDocumentation). See:
https://travis-ci.com/github/CliMA/Oceananigans.jl/jobs/362580712#L1729

**Comment by ali-ramadhan** [comment]
Ah thanks for pointing this out @navidcy! Yeah I think I dropped the ball on the docs migration last week. I think I just need to generate a new SSH key for the OceananigansDocumentation repo and tell Travis CI about it. Will try rebuilding and see if that works.

**Comment by ali-ramadhan** [comment]
Looks like deploying docs to https://github.com/CliMA/OceananigansDocumentation is successful now! There was a commit on the `OceananigansDocumentation#gh-pages` branch but nothing on `Oceananigans#gh-pages`.

We can probably nuke the `Oceananigans#gh-pages` branch now and massively reduce the repo size.

**Comment by navidcy** [comment]
Note that `v0.30` doesn't seem to appear in https://github.com/CliMA/OceananigansDocumentation/tree/gh-pages though...

**Comment by ali-ramadhan** [comment]
Yeah I tried rerunning that doc build a few times but it doesn't seem to grab the correct `TRAVIS_REPO_SLUG` and deploy since the repo name technically changed I think (from `climate-machine/Oceananigans.jl` to `CliMA/Oceananigans.jl`): 

https://travis-ci.com/github/CliMA/Oceananigans.jl/jobs/339867352#L1783-L1789:
```
┌ Info: Deployment criteria for deploying release build from Travis:
│ - ✘ ENV["TRAVIS_REPO_SLUG"]="CliMA/Oceananigans.jl" occurs in repo="github.com/climate-machine/Oceananigans.jl.git"
│ - ✔ ENV["TRAVIS_PULL_REQUEST"]="false" is "false"
│ - ✔ ENV["TRAVIS_TAG"] contains a valid VersionNumber
│ - ✔ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="push" is not "cron"
└ Deploying: ✘
```

I'm gonna try manually setting the `TRAVIS_REPO_SLUG` environment variable in the Travis CI settings and see if this hack does the trick haha.

**Comment by navidcy** [comment]
I think I had the same issue for GeophysicalFlows.jl and somebody in the Julia Slack in the #documentation channel helped me out. But now my message is long deleted and I don't recall what was the issue..

**Comment by ali-ramadhan** [comment]
Haha :( Another argument for Julia Zulip over Slack...

**Comment by ali-ramadhan** [comment]
So manually specifying `TRAVIS_REPO_SLUG` worked but it's still trying to `git push` to climate-machine/Oceananigans.jl as we didn't update the call to `deploydocs` before releasing v0.30.0: https://github.com/CliMA/Oceananigans.jl/blob/dd764fe726b2bc5a61136144b4976cd3de498c04/docs/make.jl#L147

Hmmm, I wonder if there's a way to fix this retroactively...

**Comment by ali-ramadhan** [comment]
If we can't fix it I'm happy to leave the v0.30.0 docs as "missing" since v0.30.0 didn't include any updated docs and it isn't really a usable version anyways.

What do you guys think?

**Comment by navidcy** [comment]
I think there is a way to fix retroactively... I did this for GeophysicalFlows.jl...
But I'd ask in the slack for help (or Zulip;))

**Comment by glwagner** [comment]
I would not object if v0.30.0 becomes "the lost version"... the stuff of legends and myths...

**Comment by glwagner** [comment]
Fixed?

**Comment by ali-ramadhan** [comment]
I guess yes so I will close.

We can open a separate issue for v0.30.0 docs. Easiest way to get them in might be to manually build them and push them which can be done at any time.

**Comment by navidcy** [comment]
@ali-ramadhan, note that if you push manually you have to update [`versions.js`](https://github.com/CliMA/OceananigansDocumentation/blob/gh-pages/versions.js). And Documenter will automatically update `versions.js` every time it pushes so somehow you have to inform it that `v0.30.0` should be included.

**Comment by ali-ramadhan** [comment]
Ah thanks for the tip @navidcy! Didn't know about `versions.js`.
