### ISSUE TITLE
Translate `fill_halo_regions` kernels to `KernelAbstractions` kernel language

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#811]
These kernels:

https://github.com/CliMA/Oceananigans.jl/blob/1dbe86c49e1d4e013c5ea595f837b4c226b1561e/src/BoundaryConditions/fill_halo_regions.jl#L51-L66

use broadcasting and are thus executed on the default CUDA stream.

We should rewrite these kernels using the `KernelAbstractions.jl` kernel language so that we can control when they are executed.

In particular, kernel filling for periodic directions must be filled after non-periodic directions to ensure that corner points are set properly.

We can potentially solve this problem by asking *only* the west, east halo-filling routines to fill corner points. This ensures the corner points will be filled if _at least_ one direction is periodic. In the case that no directions are periodic, the corner points do not need to be filled.

**Comment by glwagner** [comment]
>  In the case that no directions are periodic, the corner points do not need to be filled.

Hmm... I'm wondering --- perhaps corner points need to be filled by both `Periodic` and `NormalFlow`?

Some care is needed if we do convert these kernels. Also, we may have an issue running with non-zero `NormalFlow` and fully enclosed domains with Coriolis. We should probably put together a test or validation test for this case.

**Comment by ali-ramadhan** [comment]
Halo filling for flux BCs is now done with `@kernel`s: https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/BoundaryConditions/fill_halo_regions_flux.jl

But not periodic BCs: https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/BoundaryConditions/fill_halo_regions_periodic.jl

Should we close this issue?
