### ISSUE TITLE
Race condition leading to NaNs with KernelAbstractions.jl on v0.31.0?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#816]
@sandreza and Adeline have a script that explodes into NaNs almost immediately at 128³ but takes many thousands of iterations to produce a NaN at 32³.

Reverting to Oceananigans v0.27.0 the script runs fine.

@sandreza suggested that it might be a race condition between kernels since KernelAbstractions.jl allows for multiple streams. Race conditions get much more (exponentially?) frequent as the number of threads increase I guess.

I'm trying to reproduce this issue with a minimal working example.

**Comment by ali-ramadhan** [comment]
Here's a minimal working example (static ocean wouldn't NaN so I just used a minimal free convection setup):

```julia
using Statistics
using Oceananigans

N, L = 256, 1
grid = RegularCartesianGrid(size=(N, N, N), extent=(L, L, L))


ρ₀ = 1027  # Density of seawater [kg/m³]
cₚ = 4000  # Specific heat capacity of seawater at constant pressure [J/(kg·K)]
Q  = 100
Fθ = -Q / (ρ₀*cₚ)
∂T∂z = 0.01
T_bcs = TracerBoundaryConditions(grid, top=FluxBoundaryCondition(Fθ), bottom=GradientBoundaryCondition(∂T∂z))

model = IncompressibleModel(architecture=GPU(), grid=grid, boundary_conditions=(T=T_bcs,))

ε(μ) = μ * randn() # Gaussian noise with zero mean and standard deviation μ.
T₀(x, y, z) = 20 + ∂T∂z * z + ε(1e-10) * exp(z/25)
set!(model, T=T₀)

for i in 1:100
    time_step!(model, 1)
    T̄ = mean(model.tracers.T.data.parent)
    @show i, T̄
    isnan(T̄) && break
end
```

It seems to blow up pretty consistently after 10 time steps:

```
julia> include("race_condition.jl")
(i, T̄) = (1, 19.993841303184755)
(i, T̄) = (2, 19.995100916481185)
(i, T̄) = (3, 19.995148630057237)
(i, T̄) = (4, 19.995196213849784)
(i, T̄) = (5, 19.995243581693437)
(i, T̄) = (6, 19.99529110652786)
(i, T̄) = (7, 19.995331683398174)
(i, T̄) = (8, 20.305035875325455)
(i, T̄) = (9, -72074.69106889727)
(i, T̄) = (10, 3.754242711999504e12)
(i, T̄) = (11, -2.991870092582959e39)
(i, T̄) = (12, -5.826058008552174e99)
(i, T̄) = (13, 2.76189480501013e220)
(i, T̄) = (14, NaN)

julia> include("race_condition.jl")
(i, T̄) = (1, 19.99384130318475)
(i, T̄) = (2, 19.995100916481178)
(i, T̄) = (3, 19.995148630076905)
(i, T̄) = (4, 19.995196213858108)
(i, T̄) = (5, 19.995244222889166)
(i, T̄) = (6, 19.995208325105533)
(i, T̄) = (7, 18.419038290730448)
(i, T̄) = (8, -471865.1158281428)
(i, T̄) = (9, 7.518975065552512e13)
(i, T̄) = (10, 2.1416640335873834e48)
(i, T̄) = (11, 2.1471745708787494e116)
(i, T̄) = (12, 1.3286236056288004e256)
(i, T̄) = (13, NaN)

julia> include("race_condition.jl")
(i, T̄) = (1, 19.99384130318474)
(i, T̄) = (2, 19.995100916481164)
(i, T̄) = (3, 19.995148630054146)
(i, T̄) = (4, 19.995196213838604)
(i, T̄) = (5, 19.995243713504674)
(i, T̄) = (6, 19.995207999545425)
(i, T̄) = (7, 18.398598647756994)
(i, T̄) = (8, -475471.5695771488)
(i, T̄) = (9, 7.304147206536727e13)
(i, T̄) = (10, 2.2309000349868576e47)
(i, T̄) = (11, -1.513209249837606e116)
(i, T̄) = (12, 1.977442051085017e253)
(i, T̄) = (13, NaN)
```

**Comment by glwagner** [comment]
Flux and gradient conditions are treated differently --- should test which one is causing the problem.

Hopefully it doesn't depend on the initial condition, or the magnitude of the flux. You could just try setting both the flux and gradient to 0.0.

**Comment by ali-ramadhan** [comment]
Going down to 128³ it still produced NaNs after ~10 iterations. Going down to 32³ it always seems to make it to 100 iterations. So race condition seems to make sense as they occur when the GPU is saturated I think.

@glwagner Ah good point. I'll try again with just the `FluxBoundaryCondition` and then with just the `GradientBoundaryCondition`.

**Comment by ali-ramadhan** [comment]
It still NaNs with `FluxBoundaryCondition` as the only non-default BC. Same if I run with `GradientBoundaryCondition` as the only non-default BC.

Also happens with `FluxBoundaryCondition(0.0)` and `GradientBoundaryCondition(0.0)`.

Running with default boundary conditions actually produces NaNs too.

Commenting out the call to `set!` I don't get NaNs anymore, but at this point it's just a static ocean model with nothing happening.

Actually running with the non-default boundary conditions but without `set!` still no NaNs.

So it doesn't seem like the boundary conditions or halo regions are directly at fault? It might have more to do with large numbers (the example above set T to values of ~20)?

**Comment by vchuravy** [comment]
See https://github.com/CliMA/Oceananigans.jl/pull/805#pullrequestreview-454050354

**Comment by ali-ramadhan** [comment]
Thanks for having a look and the review @vchuravy! Looks like we missed quite a few top events...
