### ISSUE TITLE
Missing pages in documentation v0.31

### ISSUE THREAD

**Issue by mancellin** [CliMA/Oceananigans.jl#818]
In version 0.31.0 of the documentation, the pages of the 'Example' section seem to have been replaced by the pages of the 'Model setup' section. It is fine in version 0.29.0.
Maybe a side effect of #808?

**Comment by glwagner** [comment]
Nice catch! Looks like a copy paste error in #799 perhaps?

These lines

https://github.com/CliMA/Oceananigans.jl/blob/847d446516a61fe8b7cc522dd18f71d48e80a8fb/docs/make.jl#L53-L69

are in correct and should be something more like

https://github.com/CliMA/Oceananigans.jl/blob/dd764fe726b2bc5a61136144b4976cd3de498c04/docs/make.jl#L74-L80
