### ISSUE TITLE
Use `FFTW.set_num_threads`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#867]
By default FFTW only uses 1 thread even if `Threads.nthreads() > 1`. We should use `FFTW.set_num_threads()` to speed up CPU models, especially now that we support multithreading.

**Comment by glwagner** [comment]
Perhaps when the pressure solver is initialized, we can invoke `FFTW.set_num_threads(Threads.nthreads())`?
