### ISSUE TITLE
Run convergence tests as part of the verification testset

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#873]
Otherwise they might go out of date. Also good to keep checking convergence I suppose.

X-Ref: https://github.com/openjournals/joss-reviews/issues/2018

**Comment by glwagner** [comment]
Agree this is a necessity. Some tests are cheap enough to verify convergence continuously. Some of them are expensive so I think we should just ensure that they continue to execute (like we do for the other verification tests).
