### ISSUE TITLE
`total_size(grid::AbstractGrid)` seems wrong

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#883]
https://github.com/CliMA/Oceananigans.jl/blob/5b8813da360921c66c2f3ee77021db91bedda1f7/src/Grids/Grids.jl#L81

Shouldn't the size of the `x`-direction, for example, be `Nx + 2 * Hx`? Perhaps we should simply delete this function if it isn't being used. It doesn't exactly make sense since the size of a _field_ depends on its location, and the topology of the grid.

**Comment by ali-ramadhan** [comment]
Haha good catch. Don't think `total_size(::AbstractGrid)` is used anywhere but `total_size(loc, grid)`
https://github.com/CliMA/Oceananigans.jl/blob/b2c5393bdf4fd1fa94f58ab8ae9351c4c49af41e/src/Fields/field.jl#L197-L206
is used in a couple of places, e.g. `Diagnostics/averages.jl`.

It's more a function of the grid though so maybe it makes sense to move `total_size` to `Grids.jl` and then `total_size(f::Field) = total_size(f.grid)`?

**Comment by glwagner** [comment]
Agree with moving `total_size(loc, grid)` to the `Grids` module. Just a minor correction on the last point: it should be `total_size(f::Field) = total_size(location(f), f.grid)`.
