### ISSUE TITLE
Inconsistency in output writers interface

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#884]
The `NetCDFOutputWriter` requires the keyword argument `filename`:

https://github.com/CliMA/Oceananigans.jl/blob/ed73ad36c99b61f24c37c73e4a2d26a12c7601d9/src/OutputWriters/netcdf_output_writer.jl#L147-L163

while `JLD2OutputWriter` requires `prefix` (which is optional, even though the default `prefix=""` would produce a file called `.jld2`:

https://github.com/CliMA/Oceananigans.jl/blob/fbbb5f81b851bb838c8796efba36a3021cb89f0e/src/OutputWriters/jld2_output_writer.jl#L56-L60

There are also some minor differences: `filename` is used for the NetCDF writer, while `filepath` is used for the JLD2 writer.

We should probably even out these differences:

* I think `filename` is more descriptive than `prefix`
* I also think its redundant to require the user to specify the file suffix (`.jld2` or `.nc`) in addition to specifying `JLD2` or `NetCDF` in the output writer name. So we need to weigh the two above considerations in coming to a decision. 
* `filepath` may be a better name for the struct member if we are also going to allow the keyword argument `dir` (this is not part of `NetCDFOutputWriter` either)

In general I think we should strive to make all the keywords as identical as possible so that users can switch between the writers by changing `NetCDF` to `JLD2` and vice versa.

**Comment by ali-ramadhan** [comment]
Yeah definitely agree the two should have a consistent interface. I'm also in favour of a single `filepath` keyword argument that encompasses both `filename` and `dir`.

**Comment by glwagner** [comment]
@tomchor let's discuss here, we could use a refresh...

I think the main issue is to figure out how to merge the interface. JLD2 supports file "splitting" which is why a `prefix` and `dir` makes more sense than specifying the whole filepath. We could try to infer `prefix` and `dir` from a `filepath` too, just need to decide if we are ok that users write `filepath` but then the files end up in different places (because of the file splitting).

Changing `force` to `mode` seems totally fine.

**Comment by tomchor** [comment]
> Changing `force` to `mode` seems totally fine.

Agreed.


> I think the main issue is to figure out how to merge the interface. JLD2 supports file "splitting" which is why a `prefix` and `dir` makes more sense than specifying the whole filepath. We could try to infer `prefix` and `dir` from a `filepath` too, just need to decide if we are ok that users write `filepath` but then the files end up in different places (because of the file splitting). Personally I think it probably makes more sense to change `NetCDF` to take the file `prefix` and `dir` separately than the whole `filepath`.

I also think using `dir` and `prefix` is easier than asking for `filepath` and then trying to split it behind the scenes for the JLD2 writer. Here's what I would do as a unified interface:

- `dir`
- `filename`. I think we should use `filename` and not `prefix` since it's more descriptive. Also it gives the opportunity for user to use different extensions which they might want.
- `mode`

**Comment by glwagner** [comment]
If we use `filename`, we do have to calculate a "prefix", because the splitting creates multiple files with different names.

Is there an application for allowing different extensions than `.nc` and `.jld2`?

**Comment by tomchor** [comment]
> If we use `filename`, we do have to calculate a "prefix", because the splitting creates multiple files with different names.
> 
> Is there an application for allowing different extensions than `.nc` and `.jld2`?

Sorry but I didn't understand both comment here. Do you mind elaborating?

**Comment by glwagner** [comment]
Right now if you specify `prefix = cool_data` then you get a file `cool_data.jld2` before splitting.

But then when you reach `max_filesize` you get `cool_data_part1.jld2`, `cool_data_part2.jld2`, etc.

If we use filename with arbitrary extensions, then we need to "infer" the extension. We can do that by looking for the first `.` that appears in the string. It's just a bit of code that might be better avoided if we can just ask for the `prefix` / `name`, rather than name + extension.

**Comment by tomchor** [comment]
> Right now if you specify `prefix = cool_data` then you get a file `cool_data.jld2` before splitting.
> 
> But then when you reach `max_filesize` you get `cool_data_part1.jld2`, `cool_data_part2.jld2`, etc.
> 
> If we use filename with arbitrary extensions, then we need to "infer" the extension. We can do that by looking for the first `.` that appears in the string. But life is a bit simpler if we can just ask for the `prefix` / `name`, rather than name + extension.

Ah, I wasn't aware that JLD2 writer split the output if the file got too big. In that case I agree with you that using `prefix` is simpler than `filename`.

**Comment by glwagner** [comment]
It's a feature: 

https://github.com/CliMA/Oceananigans.jl/blob/d857f777f0ed300c3b989e70179e220e713084f3/src/OutputWriters/jld2_output_writer.jl#L82-L84

though I don't know how often its used.

**Comment by glwagner** [comment]
I also didn't realize that we never implemented schedules for `NetCDFOutputWriter` 😨

**Comment by glwagner** [comment]
Note that the NetCDF data mode "a" corresponds to JLD2's "a+" and the NetCDF data mode "c" corresponds to JLD2's "w".

I'm thinking we should change both keyword arguments since they are both a bit inscrutable. `clobber = true` or `overwrite_existing = true` might be better. Then `overwrite_existing=true` means JLD2 "w" and NetCDF mode "c", otherwise we are "a+" and "a" respectively.
