### ISSUE TITLE
`NetCDFOutputWriter` constructor fails if attributes or dimensions are not specified

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#885]
It's not possible to build a `NetCDFOutputWriter` object with output that is not a field without specifying an "attribute", because this line

https://github.com/CliMA/Oceananigans.jl/blob/fbbb5f81b851bb838c8796efba36a3021cb89f0e/src/OutputWriters/netcdf_output_writer.jl#L192

throws an error. The error is a `KeyError`, eg:

```
KeyError: key :time_average not found
  Stacktrace:
   [1] getindex at ./dict.jl:477 [inlined]
   [2] NetCDFOutputWriter(::IncompressibleModel{Oceananigans.TimeSteppers.AdamsBashforthTimeStepper{Float64,NamedTuple{(:u, :v, :w, :T, :S)
...
```

which occurs because, in this case, `:time_average` is not one of the defaults provided:

https://github.com/CliMA/Oceananigans.jl/blob/fbbb5f81b851bb838c8796efba36a3021cb89f0e/src/OutputWriters/netcdf_output_writer.jl#L13-L20

There are really two issues:

1. Should we really require users to specify "output attributes" with their output? While this does seem like good practice, I don't think we want to strictly police this behavior. Sometimes its nice to be able to play around with output, with no intention of sharing / using the data in the future. For example, we could throw a `try`-block around the above attempt to find "default" attributes, so that its possible to build an output writer with non-default output without specifying output attributes.

2. If we do intend to require "output attributes", we should probably throw an error that says something like "output attributes must be specified for x".

**Comment by glwagner** [comment]
Note that a similar problem applied to `dimensions`: if `dimensions` are not specified, and output is non-default, the user receives a `KeyError`.

**Comment by glwagner** [comment]
As a side note, if we resolve #884, we can advocate the philosophy that `JLD2` output writer is for "experimenting" / "personal use", while `NetCDF` is what you should use if you intend to share your data. If it's easy to switch between the two, and we can make this concept clear, we can have a strict / hard-to-use NetCDF writer that ensures shareable, interpretable output, and a looser but easier-to-use JLD2 output writer.

**Comment by ali-ramadhan** [comment]
Output attributes and dimensions are now inferred from the field and aren't mandatory anymore (can't remember which PR though) so I'm going to close this.

Feel free to reopen though if you think this needs more work!

> This may be more serious because NetCDF does actually require "dimensions"? Is there any way to have "unspecified" dimensions in NetCDF?

I think so actually. We could default to just using Cartesian indices, e.g. `1:N`, when the dimensions cannot be inferred. But not sure how to do this right now...
