### ISSUE TITLE
Check for 'invalid' boundary conditions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#890]
Incorrect behavior results if, for example, a `NormalFlow` boundary condition is applied to a tracer or non-wall-normal velocity component. Conversely, only the `NormalFlow` boundary condition type is correct for a wall-normal velocity component.

We may want to validate the boundary condition types in the constructors for `XFaceField`, `YFaceField`, `ZFaceField`, and `CellField`. I think this might save some users a bit of pain.

**Comment by ali-ramadhan** [comment]
> I think this might save some users a bit of pain.

Would have saved me some pain last week when I overwrote some no-normal flow BCs with value BCs haha.

So definitely +1 to this.

**Comment by glwagner** [comment]
We can add some validation to the inner constructor for `Field`:

https://github.com/CliMA/Oceananigans.jl/blob/e808a821d78949b0482b8372533e992cabb5d65f/src/Fields/field.jl#L13-L15

I think three lines along the lines

```julia
validate_boundary_conditions(X, topology(grid, 1), bcs.x)
validate_boundary_conditions(Y, topology(grid, 2), bcs.y)
validate_boundary_conditions(Z, topology(grid, 3), bcs.z)
```

might work. Then we can write a couple methods for `validate_boundary_conditions

```julia
function validate_boundary_conditions(loc, topo, bcs, dir)
    validate_boundary_condition(loc, topo, bcs.left, dir, :left)
    validate_boundary_condition(loc, topo, bcs.right, dir, :right)
    return nothing
end

function validate_boundary_condition(loc, ::Periodic, bc::BoundaryCondition{C}, dir, side) where C
    C === BoundaryConditions.Periodic ||
    error("$side boundary condition type $C in $dir at location $loc is invalid; must be Periodic")
    return nothing
end

function validate_boundary_condition(::Face, ::Bounded, bc::BoundaryCondition{C}, dir, side) where C
    C === NormalFlow || error("$side boundary condition type $C in $dir at location Face is invalid; must be NormalFlow")
    return nothing
end

function validate_boundary_condition(::Cell, ::Bounded, bc::BoundaryCondition{<:NormalFlow}, dir, side) =
    error("$side boundary condition in $dir at location Cell cannot be NormalFlow.")
```

**Comment by glwagner** [comment]
Another case where boundary conditions are invalid, [as pointed out by @jkozdon](https://github.com/CliMA/ClimateMachine.jl/issues/1755) is if you try to specify value/gradient boundary conditions but have `closure=nothing`. In this case the boundary conditions will not be respected, because there are no diffusive fluxes across boundaries.
