### ISSUE TITLE
"Field-dependent" boundary condition functions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#897]
We have the need for continuous (not discrete) boundary condition functions that depend on the field to which the boundary condition is applied. For example, in the `ocean_convection_and_wind_mixing.jl`, the prescribed salinity flux depends on the salinity adjacent to the boundary:

https://github.com/CliMA/Oceananigans.jl/blob/f13a0a26df78cd1c1495d56ef5e7ea2fbbbfb23c/examples/ocean_wind_mixing_and_convection.jl#L73

The linear drag boundary condition implemented in `eady_turbulence.jl` is similar:

https://github.com/CliMA/Oceananigans.jl/blob/f13a0a26df78cd1c1495d56ef5e7ea2fbbbfb23c/examples/eady_turbulence.jl#L60

A slightly simpler interface would allow users to implement the salinity flux (for example) with

```julia
Qˢ(x, y, t, S, evaporation) = - evaporation * S
```

For this to work, a number of changes must be made in `BoundaryFunction`, `BoundaryCondition`, `FieldBoundaryConditions`, and the `TracerFields` constructor:

- `BoundaryFunction` must record whether or not the function is `field_dependent`, as well as the "`side`" of the boundary condition (left or right, so that the wall-normal index may be inferred), the `field_name`, and the `field_container` in which the field lives (`model.velocities` or `model.tracers`).

- `BoundaryCondition` must provide the option `field_dependent=true`.

- `FieldBoundaryConditions` must supply the `side` at which the boundary condition is applied (`Left()` for west, south, bottom and `Right()` for east, north, and top)

- `TracerFields` must supply the tracer name.

New methods for field-dependent `BoundaryFunction`s are also required. For `z`-boundaries, for example, we need

```julia
@inline function (bc::BoundaryFunction{:z, X, Y, true})(j, k, grid, clock, state) where {X, Y}
    k = wall_adjacent_index(bc.side, grid.Nz)
    container = getproperty(state, bc.field_container)
    field = getproperty(container, bc.field_name)
    
    return @inbounds call_boundary_function(bc.func, xnode(X, i, grid), ynode(Y, j, grid), clock.time, field[i, j, k], bc.parameters)
end
```

**Comment by glwagner** [comment]
We can modify `FieldBoundaryConditions` to

```julia
repackage_function_boundary_condition(bc, args...) = bc # fallback

function repackage_function_boundary_condition(bc::BoundaryCondition{C, <:BoundaryFunction}, boundary, loc1, loc2, side, field_name) where C
    condition = BoundaryFunction{boundary, loc1, loc2}(bc.condition.func; parameters=bc.condition.parameters, field_dependent=bc.condition.field_dependent, side=side, field_name=field_name)
    return BoundaryCondition(C, condition)
end

"""
function FieldBoundaryConditions(grid, loc, field_name=:u;
      east = DefaultBoundaryCondition(topology(grid)[1], loc[1]),
      west = DefaultBoundaryCondition(topology(grid)[1], loc[1]),
     south = DefaultBoundaryCondition(topology(grid)[2], loc[2]),
     north = DefaultBoundaryCondition(topology(grid)[2], loc[2]),
    bottom = DefaultBoundaryCondition(topology(grid)[3], loc[3]),
       top = DefaultBoundaryCondition(topology(grid)[3], loc[3]))

    west = relocate_function_boundary_condition(west, :x, loc[2], loc[3], Left(), field_name)
    east = relocate_function_boundary_condition(east, :x, loc[2], loc[3], Right(), field_name)
    south = relocate_function_boundary_condition(south, :y, loc[1], loc[3], Left(), field_name)
    north = relocate_function_boundary_condition(north, :y, loc[1], loc[3], Right(), field_name)
    bottom = relocate_function_boundary_condition(bottom, :z, loc[1], loc[2], Left(), field_name)
    top = relocate_function_boundary_condition(top, :z, loc[1], loc[2], Right(), field_name)

    TX, TY, TZ = topology(grid)
    x_default_bc = DefaultBoundaryCondition(topology(grid)[1], loc[1])
    y_default_bc = DefaultBoundaryCondition(topology(grid)[2], loc[2])
    z_default_bc = DefaultBoundaryCondition(topology(grid)[3], loc[3])

    validate_bcs(TX, west,   east, x_default_bc, :west,   :east, :x)
    validate_bcs(TY, south, north, y_default_bc, :south, :north, :y)
    validate_bcs(TZ, bottom,  top, z_default_bc, :bottom,  :top, :z)

    x = CoordinateBoundaryConditions(west, east)
    y = CoordinateBoundaryConditions(south, north)
    z = CoordinateBoundaryConditions(bottom, top)

    return FieldBoundaryConditions(x, y, z)
end
```

Then the velocity field boundary condition constructors become, for example

```julia
UVelocityBoundaryConditions(grid; user_defined_bcs...) = FieldBoundaryConditions(grid, (Face, Cell, Cell), :u; user_defined_bcs...)
```

Further changes are required in `TracerFields` to ensure that the tracer field boundary conditions are correct.

**Comment by glwagner** [comment]
Finally, we need to modify `TracerBoundaryConditions`:

```julia
TracerBoundaryConditions(grid, tracer_name=:c; user_defined_bcs...) = FieldBoundaryConditions(grid, (Cell, Cell, Cell), tracer_name; user_defined_bcs...)
```

 and `TracerFields`:

```julia
with_name(name, grid, bcs) = TracerBoundaryConditions(grid, name,
    east=bcs.x.east, west=bcs.x.west, north=bcs.y.north, south=bcs.y.south, top=bcs.z.top, bottom=bcs.z.bottom)

function TracerFields(arch, grid, names, bcs)
    tracer_names = tracernames(names) # filter `names` if it contains velocity fields
    tracer_fields =
        Tuple(c ∈ keys(bcs) ?
              CellField(arch, grid, with_name(c, grid, bcs[c])) :
              CellField(arch, grid, TracerBoundaryConditions(grid, c))
              for c in tracer_names)
    return NamedTuple{tracer_names}(tracer_fields)
end
```

**Comment by glwagner** [comment]
Instead of `field_dependent`, we could have a more general abstraction with the keyword `depends_on`. For example:

```julia
Qˢ(x, y, t, S, evaporation) = - evaporation * S

bc = BoundaryCondition(Flux, Qˢ, depends_on=:S)
```

or

```julia
drag(x, y, t, u, v, Cd) = - Cd * u^3 / sqrt(u^2 + v^2)

bc = BoundaryCondition(Flux, drag, depends_on=(:u, :v), parameters=Cd)
```

We can also use this concept in `SimpleForcing`.

**Comment by ali-ramadhan** [comment]
I guess we talked on Slack but yeah the `depends_on` keyword argument idea does seem nicer and more general than just a `field_in_signature` or `field_dependent` kwarg.

I guess to avoid interpolation issues we could just not interpolate for now which would still work for a large number of common boundary condition functions, e.g.
```julia
Qˢ(x, y, t, S, evaporation) = - evaporation * S
τ₁₃_linear_drag(x, y, t, u, p) = p.μ * p.H * u
```

Maybe interpolating these fields tangentially at the boundary would become easy once we have something like a lazy field or `ReducedField` implementation (#525)?

Are you thinking of resolving this issue as part of PR #894?

**Comment by glwagner** [comment]
No, I think this should be resolved in a future PR.

Interpolation is possible if we infer field location from names and further use the information passed to `FieldBoundaryConditions` to obtain the location at which the boundary condition is applied. We could use the `interpolation_operator` function from `AbstractOperations`:

https://github.com/CliMA/Oceananigans.jl/blob/57031aeeabb9342715511f3cbff147142cf93782/src/AbstractOperations/interpolation_utils.jl#L29-L36

food for thought.

**Comment by glwagner** [comment]
@ali-ramadhan what do you think about the name `depends_on` for the kwarg?

**Comment by ali-ramadhan** [comment]
I think it sounds good to me! It matches what you would say in real life, e.g. "the relaxation just depends on temperature".

**Comment by glwagner** [comment]
Let's implement this after resolving #896 .

**Comment by glwagner** [comment]
After starting work on forcing functions in #896, I am thinking that field_dependencies is a better name than depends_on. Feedback welcome on this change.

**Comment by glwagner** [comment]
Hmm, so after working on `ContinuousForcing` a bit, I think this discussion needs to be updated:

1. The keyword we'll provide is `field_dependencies`, as in `field_dependencies=(:u, :v, :T)`.
2. We'll have to put a function `regularize_boundary_conditions` inside the constructor for `IncompressibleModel`, since fundamentally this function needs to know what the `model_fields` are.
3. Since `regularize_boundary_conditions` goes inside `IncompressibleModel`, we don't need to modify `FieldBoundaryConditions`. Instead, the boundary conditions can be "regularized" prior to being passed to the various field tuples. This may simplify `FieldBoundaryConditions`.
4. The implementation within `BoundaryFunction` can basically follow what was done for `ContinuousForcing`; the only difference being that, as mentioned above, the `side` at which the boundary function is applied needs to be known for correct indexing.
