### ISSUE TITLE
Keyword `array_type` in JLD2OutputWriter (and perhaps NetCDFOutputWriter)

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#901]
Currently many objects used for output with the `JLD2OutputWriter` have a field `return_type`, which converts an array from its native type (typically something on the GPU) to something else (typically a CPU `Array`). For example: `FieldOutput`, `Average`, and `Computation`.

This "local" method of type conversion has two disadvantages. First, it litters and complicates the code; second, if a user wants to specify conversion of all objects to, for example, `Array{Float32}`, they'd have to specify this for every output individually.

It's probably a better design to let the output writers handle the conversion of output to a desired type. For this we can add a field and keyword argument `array_type` whose default value is `Array` or `Array{Float32}`. All output that's some kind of array will then be converted to `array_type` before being saved to disk.

**Comment by ali-ramadhan** [comment]
Yeah this sounds like a good idea, since you probably want to make sure all outputs end up with the same float type. And it would simplify diagnostics.

**Comment by glwagner** [comment]
This was resolved by #927 .
