### ISSUE TITLE
Eliding differences, interpolation, and `fill_halo_regions` for `Flat` dimensions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#902]
The topology of a dimension can be labeled `Flat`. However, this doesn't produce any special behavior. To fully take advantage of this abstraction, we need differences across `Flat` dimensions to return 0:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Operators/difference_operators.jl#L5-L25

eg

```julia
 @inline δxᶜᵃᵃ(i, j, k, grid::RegularCartesianGrid{FT, Flat}, args...) where FT = zero(FT)
```

etc.

In addition, interpolation should have no effect:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Operators/interpolation_operators.jl#L12-L32

I think we should probably use `nothing` for boundary conditions in `Flat` dimensions:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/BoundaryConditions/field_boundary_conditions.jl#L17

which will make it easy to elide `fill_halo_regions!`, since we can dispatch on `nothing`.

Finally, we should set halo size to 0 in the grid constructor:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Grids/regular_cartesian_grid.jl#L117-L126

**Comment by glwagner** [comment]
Anything I'm missing? We can convert a few examples to use `Flat`. We can also add a few unit tests.

**Comment by ali-ramadhan** [comment]
Ah #35, our second oldest open issue.

I used to think it would be hard to implement but yeah if we just dispatch on `Flat` then it might be pretty easy!

Setting halo size to 0 along `Flat` dimensions should ensure we don't allocate more memory than needed.

Would be interesting to benchmark 1D and 2D models before and after.

Can't think of anything you missed... Don't think the pressure solver needs to change but might hit a problem there.

There are plenty of 0D, 1D, and 2D tests that could be converted to use `Flat` dimensions and act as tests for eliding operations. Unit tests are always useful too.

**Comment by glwagner** [comment]
See also #1001 for an important issue about user input to `RegularCartesianGrid` when dimensions are flat.

Are there other topology-dependent inputs that we need to think about?
