### ISSUE TITLE
Docs for 0.35.0 seem to be missing

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#917]

**Comment by ali-ramadhan** [comment]
Thanks for reporting this @navidcy! Hmmm, can't seem to find the Travis build for v0.35.0 so maybe this was an unintended consequence of me trying to only build pushes to master while only building merge commits on PRs: https://github.com/CliMA/Oceananigans.jl/blob/4e25982c19e89664eb6ad1c800610454fa2e9bdf/.travis.yml#L17-L21

I'll try to `deploydocs` for v0.35.0 manually from my laptop and probably try removing those lines from `.travis.yml`.

**Comment by navidcy** [comment]
It won't matter if you release v0.36.0 and docs for that version are pushed.

**Comment by ali-ramadhan** [comment]
True. I'll try removing those lines from Travis for v0.36.0 and see if that helps.

**Comment by ali-ramadhan** [comment]
Yup looks like this was fixed by https://github.com/CliMA/Oceananigans.jl/commit/5260346ed1407be28eb2b3bdfcb43e150071f367
