### ISSUE TITLE
Stop simulation when output is NaN

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#938]
I was wondering whether it's a good idea to stop the simulation if the output is NaN. This can be the default and could be turned of by the user if needed (although I can't think of any situation that one wants the simulation to continue running producing NaNs...). This is useful when running simulations on HPCs. For example, when the `TimeStepWizard` checks the velocity values to recompute the time-step, if it gets a `Δt=NaN` then it should save the current state and exit the simulation?

**Comment by glwagner** [comment]
There is a diagnostic called a `NaNChecker` which has this behavior:

https://clima.github.io/OceananigansDocumentation/stable/library/#Oceananigans.Diagnostics.NaNChecker

However, there are no "default" diagnostics. I agree that it might make sense to include some, like this one.

**Comment by glwagner** [comment]
It might actually be more appropriate to add `NaN`-checking as a default stop criteria to `Simulations`. This seems a bit more clear.

Also, we don't need to check every single grid point like the current `NaNChecker` does. It's sufficient to check just one point; perhaps checking pressure is most appropriate.
