### ISSUE TITLE
Model constructor should check that halos are big enough for chosen advection scheme and turbulence closure

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#941]
Model constructor could emit a warning (error would be more suitable). Could re-create the grid but maybe that's not as good as getting the user to specify the right halo size.

New users shouldn't have to interact with halos and getting `NaN`s because you didn't know to change the halo size can be frustrating.

**Comment by glwagner** [comment]
I think we should rebuild the grid.

You don't get NaNs if the halos aren't big enough -- you get a segfault and Julia crashes.

One solution is to design a function that queries every model struct that specifies the "equation" (eg required_halo_size). We then rebuild the grid with the required halos if the current halos are too small (grid = with_halos(args...)).

The grid keyword argument is only needed then if a user specifies forcing that needs the halos.

Agree that some features requiring non-default halos are going to lose "experimental" status imminently...

**Comment by glwagner** [comment]
Note that halos of size 2 are also needed for biharmonic diffusivity.

**Comment by glwagner** [comment]
For now we might assume halos are symmetric. Then we can put something like

```julia
halo = minimum_halo_size # 1
halo = max(halo, required_halo_size(advection))
halo = max(halo, required_halo_size(closure))
grid = with_halo(grid, halo)
```

in the constructor for `IncompressibleModel`. 

Note that we also have to change the keyword arguments that depend on `grid`:

https://github.com/CliMA/Oceananigans.jl/blob/e808a821d78949b0482b8372533e992cabb5d65f/src/Models/incompressible_model.jl#L71-L91

We can convert `boundary_conditions` to an empty `NamedTuple` with no penalty. However, for `velocities`, `pressures`, `diffusivities`, and `pressure_solver`, we will have to use `nothing` defaults and conditionally construct them on `grid` if they aren't provided. We may also want to check that, if they are provided, that the grid they are associated with matches the grid being build (this is not currently done).
