### ISSUE TITLE
Improving tracer budget tests

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#942]
In `test_dynamics.jl` we test budgets for tracers and momentum variables:

https://github.com/CliMA/Oceananigans.jl/blob/0807552c94b87ec009564bf228ab85517e31dde0/test/test_dynamics.jl#L25-L41

However, the test is imperfect because 1) it does not test velocity components in non-periodic directions and 2) it uses a too-loose tolerance.

~~We can improve this test by tapering the initial condition for the field in question to zero for velocity fields in bounded directions.~~

EDIT: a little thought goes a long way: in `Bounded` directions, momentum is not conserved in general unless pressure at the boundaries is zero. Perhaps we should be happy just to test momentum conservation in periodic directions. This is still an important test that ensures the no flux condition is correctly implemented.

Also, we can make the tolerance more strict. Finally, once this test works well, we can get rid of the `tracer_conserved_in_channel` test in `test_time_stepping.jl`.

**Comment by glwagner** [comment]
We probably should run these tests with different advection schemes in addition to different diffusion schemes.

cc @navidcy

**Comment by ali-ramadhan** [comment]
@glwagner Does your still-open PR #1486 resolve this issue?

**Comment by glwagner** [comment]
I don't think it should because the issue here is whether we conserve tracers when we have explicit diffusion. The tests on PR #1486 test whether fluxes across boundaries are correctly prescribed (and uses `closure=nothing`).

The tests are pretty similar though and resolving this issue is a priority now. We also need to extend the tests mentioned in this issue to other models and grids.
