### ISSUE TITLE
Animations in Docs don't show up on Safari Mac OS X

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#944]
<img width="1154" alt="Screen Shot 2020-09-15 at 6 12 13 am" src="https://user-images.githubusercontent.com/7112768/93133392-7b6a5d00-f71a-11ea-9b91-c2ab5a1c9bf6.png">

I've confirmed this with others. I had a brief [chat](https://julialang.slack.com/archives/C6E4SU1D3/p1599886434109500) at Slack but haven't found this `crf` setting in Plots.jl anywhere.

**Comment by glwagner** [comment]
Thanks @navidcy. I can confirm this happens to me on Safari too.

**Comment by ali-ramadhan** [comment]
Yeah I think it's a browser-specific issue. Of course it works under our Chrome overlords. The `ffmpeg -crt` setting might be to blame but in the mean time we could probably try switching from `mp4` to `gif` (which would look worse and take up more file size but would probably work everywhere).

**Comment by navidcy** [comment]
gifs work everywhere
I disagree that they look worse...
But they **do** take up much more space!

**Comment by jklymak** [comment]
The animation at https://clima.github.io/OceananigansDocumentation/stable/generated/internal_wave/ shows on my version of Safari (14.0)

**Comment by navidcy** [comment]
Oh yeah. We fixed this by converting all animations from mp4 to gif. I’m closing the issue.

**Comment by navidcy** [comment]
This https://github.com/JuliaPlots/Plots.jl/pull/3209 is relevant btw in case one wants to generate mp4 files that work well on Safari.

**Comment by navidcy** [comment]
Should we go back to mp4?

**Comment by ali-ramadhan** [comment]
I'd be on board with switching back to mp4. Thanks for looking into this!

We could test that animations work with different browsers in the PR doc build before merging.

**Comment by navidcy** [comment]
I’ve changed it in FourierFlows.jl/Geophysical Flows.jl docs. Can you check that animations work well in those Docs? I’ll do a PR shortly for Oceananigans.jl.

**Comment by ali-ramadhan** [comment]
Yup, works for me on Firefox 84 on Windows and Firefox 80 on Linux!
