### ISSUE TITLE
PrescribedVelocities type for tracer advection problems

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#958]
It would be relatively simple to create a new type called `PrescribedVelocities` for the purpose of solving tracer advection problems with prescribed fluid motion. The velocity fields would be specified as functions of `x, y, z, t`, wrapped in a [`FunctionField`](https://github.com/CliMA/Oceananigans.jl/blob/master/src/Fields/function_field.jl) at the appropriate locations, and stored in `PrescribedVelocities`:

```julia
struct PrescribedVelocities{U, V, W}
    u :: U
    v :: V
    w :: W
end
```

The next part of this implementation is overloading halo filling, time stepping, pressure corrections, and other functions that act on `model.velocities` with a bypass for `PrescribedVelocities`. This would be tedious but straightforward. We can also avoid allocating memory for pressure fields.

**Comment by Mikejmnez** [comment]
@glwagner, do you know if somebody is already looking into this? I am doing some idealized modeling of the sorts, and wouldn't mind stepping up.

**Comment by ali-ramadhan** [comment]
Hi @Mikejmnez that would be awesome!

I think background/prescribed velocities might have already been implemented in PR #1014 and maybe this issue wasn't closed though?

Two examples use `BackgroundFields`:
* Internal wave: https://clima.github.io/OceananigansDocumentation/stable/generated/internal_wave/
* Eady turbulence: https://clima.github.io/OceananigansDocumentation/stable/generated/eady_turbulence/

**Comment by Mikejmnez** [comment]
Great, even better. I'll take a look at those examples.

**Comment by ali-ramadhan** [comment]
@Mikejmnez I accidently disabled the examples in v0.46.0 lol so the above links are incomplete/unbuilt Markdown.

Until this is fixed in v0.46.1 later today, the examples should be at these links:
* https://clima.github.io/OceananigansDocumentation/v0.45.2/generated/internal_wave/
* https://clima.github.io/OceananigansDocumentation/v0.45.2/generated/eady_turbulence/

**Comment by Mikejmnez** [comment]
That explains it. Although the `eady_turbulence` example is working...

**Comment by glwagner** [comment]
@Mikejmnez @ali-ramadhan `BackgroundField` is not the same as `PrescribedVelocities`! We could maybe come up with a better name.

The purpose of `PrescribedVelocities` is for tracer advection-diffusion problems with prescribed dynamics. If the velocity field is prescribed we can save a lot of compute time and memory.

@Mikejmnez nobody is looking into it, feel free to open a PR! We can also discuss the design on this issue. I think there are a few puzzles; we have to set `model.pressures = nothing` (and dispatch on this case in the time-stepping methods), and we have to make sure we can construct the time-stepper tendencies correctly. I think all of the code should probably belong in its own module `PrescribedVelocities`.

**Comment by francispoulin** [comment]
Ah, I think I see.  If we turned off advection, pressure solve, buoyancy, Coriolis and all other forces, then the velocity would be fixed.  In this case the `BackgroundField` would be identical to `PrescribedVelocties`, in that the tracers would evolve with the velocity but the velocity would not be changed.  Very good to know!

**Comment by Mikejmnez** [comment]
@glwagner Yeah, what I am interesting is in evolving, say the 2D advection diffusion equation, with a prescribed (constant) shera flow. No need to evolve the velocity field, it is just defined by the used (e.g. a cellular flow, a jet, etc).

**Comment by ali-ramadhan** [comment]
Oceananigans already supports `advection = nothing`, `buoyancy = nothing` and `coriolis = nothing`.

So if support for `pressure = nothing` (or `pressure_solver = nothing`) is added, would `BackgroundField` effectively work as a prescribed unchanging velocity?

I guess Oceananigans would reduce to solving the advection-diffusion equation. So it would have to be `advection = nothing` for momentum only (keeping tracer advection).

**Comment by glwagner** [comment]
> So if support for `pressure = nothing` (or `pressure_solver = nothing`) is added, would `BackgroundField` effectively work as a prescribed unchanging velocity?

Yes, something like this is an alternative design. But do we think that setting `pressure=nothing` might be too roundabout of a way to avoid launching kernels that calculate the velocity tendencies and to avoid allocating memory for the velocity fields?

The design I'm suggesting would have users write `velocities = PrescribedVelocities(...)` in the constructor for `IncompressibleModel` as the interface; so there's just a single keyword arg to set.

We don't want `advection=nothing` since this turns off all advection, including advection by `BackgroundField`s.

**Comment by francispoulin** [comment]
@Mikejmnez , could you maybe say a bit more of what you are hoping to do?  If you initialize your flow to have a constant shear, for example, then there is a velocity associated with that shear and it will evolve because of the mometnum equations.  

If you wanted a simple toy problem, we might be able to do something with `ShallowWaterModel`.  It might be simple enough for your purposes, depending on what you wanted to learn, but that would be orthogonal to this issue.

**Comment by francispoulin** [comment]
Good point @glwagner .  

This is a different topic, but I do wonder whether we might want to allow for different advection schemes for momentum and tracers?

**Comment by glwagner** [comment]
> would BackgroundField effectively work as a prescribed unchanging velocity?

Just to clarify: I think we should design `PrescribedVelocities` to accept functions of `x, y, z, t`. This includes a constant velocity field as a special case. `BackgroundField`s are also functions of `x, y, z, t`.

**Comment by glwagner** [comment]
> This is a different topic, but I do wonder whether we might want to allow for different advection schemes for momentum and tracers?

See #1015

**Comment by Mikejmnez** [comment]
> @Mikejmnez , could you maybe say a bit more of what you are hoping to do? If you initialize your flow to have a constant shear, for example, then there is a velocity associated with that shear and it will evolve because of the momentum equations.
> 
> If you wanted a simple toy problem, we might be able to do something with `ShallowWaterModel`. It might be simple enough for your purposes, depending on what you wanted to learn, but that would be orthogonal to this issue.

@francispoulin I am interested deriving/testing closures in the 2D Adv-Diff equation in the (general) case of periodic shear flows. A constant shear flow won't do it. More like a velocity field that can be decomposed into a shear flow u(y) (e.g. a cosine in y or sum of cosines) plus a cellular flow (square waves).  I am still a newbie over here, so I am open to trying different models.

**Comment by francispoulin** [comment]
Thanks @Mikejmnez , that is helpful.  Any model can do this but I suspect that using `IncompressibleModel` in 2D is probably the best place to start.  It is essentially equal to the 2D vorticity equation and does allow for variable shear flow. 

I'm guessing you want to start off with a sinusoidal shear and add on a perturbation and see how things evolve?  If the flow is supercritical then you will get a shear instability and that will give rise to all sorts of interesting dynamics.

Sounds like a fun project and very interested to see what you find!

**Comment by Mikejmnez** [comment]
Thanks! It would be nice though, if the flow field doesn't evolve so that it doesn't get unstable. That way I can look at the effective diffusivities without the 'eddy' perturbation growth. This is a classic approach when deriving effective diffusivities that are purely kinematic within homogenization theory (e.g. Majda and Kramer, 1999). I can prob code this myself, but from this issue it seemed like people were interested...

**Comment by francispoulin** [comment]
That's for the refrence.  I glanced at it but it's 337 pages so I might have missed a thing, or two, or three.

If you want to look at the diffusion of a tracer with a fixed velocity, a snapshot in time if you will, then that makes sense to me.  As for how best to do that, @glwagner had a suggestion at the beginning of this issue, which would do the trick.  I'm not sure if there is a better way than that.

**Comment by glwagner** [comment]
> I can prob code this myself, but from this issue it seemed like people were interested...

I think this would be a great feature to have in Oceananigans!

I'd be happy to pair program with you @Mikejmnez to help you get started if you like. Feel free to message me on the julia slack (Oceananigans channel is at https://julialang.slack.com/archives/C01D24C0CAH).
