### ISSUE TITLE
Bugs in fourth order advection in bounded directions

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#965]
In tracers in `y`:

https://github.com/CliMA/Oceananigans.jl/blob/b444acfe7d0c038d83fbcf50e72aaf2a747599fd/src/Advection/centered_fourth_order.jl#L145

and `z`:

https://github.com/CliMA/Oceananigans.jl/blob/b444acfe7d0c038d83fbcf50e72aaf2a747599fd/src/Advection/centered_fourth_order.jl#L153

and momentum:

https://github.com/CliMA/Oceananigans.jl/blob/b444acfe7d0c038d83fbcf50e72aaf2a747599fd/src/Advection/centered_fourth_order.jl#L118

**Comment by glwagner** [comment]
I think we should run the `forced_flow_fixed_slip.jl` test with all the advection schemes. Unfortunately since one of the directions needs to be periodic, we cannot test `x` boundaries (since we don't have a pressure solver that is bounded in `x` but periodic in another direction). Naturally, there was no bug in that part of the anyways :-D

**Comment by navidcy** [comment]
You can run then again the `forced_flow_fixed_slip.jl` with y being periodic. The solution should be the same as the first case with x->y, y->x, no? Then you'll test all directions.

**Comment by glwagner** [comment]
Ah, you mean transpose `u` and `v`. Hmm, that might work.
