### ISSUE TITLE
Unneeded `arch` argument to fill_halo_regions?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#969]
https://github.com/CliMA/Oceananigans.jl/blob/c3f6ce0b52a4bb519d1a2efe87c755a9113d6851/src/BoundaryConditions/fill_halo_regions.jl#L13

`arch` can be inferred from `field`.

**Comment by glwagner** [comment]
Ah, this may be a legacy from when `fill_halo_regions` was called directly on arrays. Still, in that case we would not have needed `arch` because it could be inferred from the type of the array. Mysterious.

**Comment by ali-ramadhan** [comment]
I agree. Seems like technical debt uncovered haha.

**Comment by glwagner** [comment]
This is resolved! Finally.
