### ISSUE TITLE
Halo regions for fields cannot be filled without references to other model fields

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#971]
Currently it is not generically possible to call

```julia
fill_halo_regions!(field)
```

Part of this is trivial as noted in #969.

But another part is that boundary conditions on fields can depend on other _other_ fields, to which `field` contains no reference. We allow field boundary conditions to depend on anything in `state(model)`, which includes the model velocity fields, tracer fields, pressure fields, and diffusivities.

Because references to `state(model)` are required to fill halo regions in general, we are unable to fill halo regions prior to computing an `AveragedField` (for example).

We may not _want_ to solve this problem because it require too-invasive changes. For example, we certainly want to support the concept of fields that are independent of other fields. General support for interdependent fields may be too difficult.

Some possible solutions:

* an "optional" `state` property of `Field` which is set to `nothing` by default. We can ensure that `state` is properly determined in the constructor for `IncompressibleModel` for the model fields.

* an "optional" `state` or `fields` property within each individual boundary condition (with a similar function as the optional property above). This property could be activated only for boundary conditions that need it (currently, only discrete form boundary conditions, though this could be extended to continuous form boundary conditions in the future via #897)

Solving this will simplify time-stepping code a bit and permit simpler halo region filling via `fill_halo_regions!(field)` with no additional arguments.

**Comment by ali-ramadhan** [comment]
Hmmm, right so if a boundary condition uses the `discrete_form=true` then it might require access to `state(model)` to fill halos, and if it `depends_on` other fields, then it needs access to them.

I agree that we don't want to make invasive changes where fields depend on other fields and fields have extra properties that link to other big objects... It would make the code less modular I think. I think the current field abstraction is pretty lean so it might be nice to avoid bloating it.

Would it make sense to add these dependencies in the boundary condition or `BoundaryFunction`? Then filling halos just calls the boundary condition which has immediate access to the state/fields it needs?

**Comment by glwagner** [comment]
Hmm... we could definitely introduce a wrapper for discrete form boundary condition functions. Then we can store boundary condition dependencies in either `ContinuousBoundaryFunction` or `DiscreteBoundaryFunction`. This is definitely doable.

**Comment by glwagner** [comment]
The solution is not too difficult, except for one annoying detail: if boundary conditions contain references to model fields, this means that `field.boundary_conditions` contains a circular reference. I guess we can work around this by giving boundary conditions a reference to field data, rather than the field itself. This preserves existing functionality and so its fine. We will, however, have to rewrite `VelocityFields` and `TracerFields` to a single `VelocityAndTracerFields` constructor, and perform the requisite gymnastics there.

There are also challenges if users want to create `VelocityFields` and pass them to the model. I suppose we'll have to re-wrap the user-created data for that.

**Comment by glwagner** [comment]
We've decide that a better solution is to leave halo regions untouched when possible, rather than creating an intricate web of dependencies between different fields.
