### ISSUE TITLE
Maintain a list of publications using Oceananigans in the docs?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#973]
Might be a pretty good idea, other models do it too. I can think of three so far: @sandreza's KPP paper, @glwagner's momentum + energy transfer paper, and [Bhamidipati et al. (2020)](https://doi.org/10.1016/j.ocemod.2020.101615).

**Comment by glwagner** [comment]
I don't think Bhamidipati et al. (2020) uses Oceananigans. @sandreza can confirm.

**Comment by ali-ramadhan** [comment]
I think they use Oceananigans to do the 3D vs. 2D comparison in figure 8. It's not as central as it is to the other papers, but still a cool use (and pretty sweet that it agrees so well with the 2D dedalus simulations).

**Comment by glwagner** [comment]
Ah, I missed that! We should add a section to the README that asks for a citation, and also ask that authors mention "Oceananigans" in addition to providing a citation to the JOSS paper.

**Comment by sandreza** [comment]
I can confirm what Ali said. I used Oceananigans (3D) to compare to Dedalus (2D) output in "identical" configurations. It's the first publication that uses Oceananigans!

**Comment by sandreza** [comment]
Perhaps more precisely I should say that I sent the data to Neeraja and she did the comparison!
