### ISSUE TITLE
Can we inline source term calculation to save memory?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#98]
Hmmm, I wonder if we can inline the previous lines calculating `Gu`, `Gv`, etc. into here so we'd only have to store the source term from one time step. That would free up so much memory!
```julia
Gu[i, j, k] = (1.5 + χ)*(inlined stuff) - (0.5 + χ)*Gu[i,j,k]
```

_Originally posted by @ali-ramadhan in https://github.com/ali-ramadhan/Oceananigans.jl/pull/97_

**Comment by glwagner** [comment]
This issue is probably stale since we have a new RK3 time-stepper...

**Comment by ali-ramadhan** [comment]
True.
